### ISSUE TITLE
If I rename a prompt the assets should use the custom name

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3476] opened 2020-06-23 20:37 UTC
## Describe the bug

When I start with a prompt and don't give it a name it auto generates intent and LG templates that have something really generic like **#TextInput_Prompt_KtxJeV**.  The problem is that as my project grows, that template becomes extremely hard to understand what is.  If I give that prompt a unique name **AskForUserFeedback**, then I would expect the template to be changed to **#AskForUserFeedback_Prompt** without the KtxJeV goo.

Same thing with intents.

## Version

1.0.1
![image](https://user-images.githubusercontent.com/17789481/85459129-b5322a00-b556-11ea-9b2d-73fb53edca53.png)

![image](https://user-images.githubusercontent.com/17789481/85459069-a77ca480-b556-11ea-8831-dbd1ac5728ef.png)
![image](https://user-images.githubusercontent.com/17789481/85459096-ae0b1c00-b556-11ea-9326-f79731549ff0.png)

**Comment by a-b-r-o-w-n** [comment] 2020-06-25 16:40
Duplicate of #2884

**Closed by a-b-r-o-w-n** 2020-06-25 16:40 UTC
