### ISSUE TITLE
[visual editor] Add enable and disable to the actions menu

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#3950] opened 2020-08-31 20:58 UTC
## Is your feature request related to a problem? Please describe.
Currently, to disable actions in the visual editor, user's have to focus on the actions they want to disable and then click the disable button in the editor menu. We should consider adding the enable and disable options to the node's menu options.

## Screenshot

![image](https://user-images.githubusercontent.com/17039790/91767403-cbbcb900-eb77-11ea-9095-8ac6d8f761de.png)

**Comment by cwhitten** [comment] 2020-09-01 16:43
Currently "by design", adding Design team for visibility

**Comment by mewa1024** [comment] 2021-07-02 23:03
Copied this feedback into #4103. Closing this issue.

**Closed by mewa1024** 2021-07-02 23:03 UTC
Labels: Area: Visual editor, Composer Controls, UX Design, feature-request
