### ISSUE TITLE
ProvisionComposer.Js infinitely loops after outputting the information for publishing.

### ISSUE THREAD

**Issue by Bracciata** [microsoft/BotFramework-Composer#6289] opened 2021-03-06 18:28 UTC
## Describe the bug

ProvisionComposer.Js infinitely loops after outputting the information for publishing. I get the following then my apps information "Your Azure hosting environment has been created! Copy paste the following configuration into a new profile in Composer's Publishing tab." then the spinning wheel goes on forerver. This is with a fresh bot.

## Version

Release: 1.3.1

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to home
2. Click on create a new bot
3.Open the bot in vs code and follow the directions in the readme to run provisionComposer.js

## Expected behavior

It would end and I would be able to run my application in the testing. Also even if it were to infinitely loop I would be able to test it.

**Comment by carlosscastro** [comment] 2021-03-22 18:19
@benbrown could you take a look at this item? @hatpick I see you removed the needs-triage label - was this issue assigned to a release?

**Comment by benbrown** [comment] 2021-03-24 16:58
@Bracciata The spinning wheel you saw was inside the terminal?  

Did the command line tool return control to the terminal after the publishing profile was displayed?

**Comment by Bracciata** [comment] 2021-03-24 17:35
No it did not. I left it running 15 or so minutes before cancelling the
command.

**Comment by msomanathan** [comment] 2021-03-29 19:20
@benbrown is there any updates to this issue?

**Comment by benbrown** [comment] 2021-03-31 17:48
I am working on determining the cause of this issue.  I am not currently able to reproduce this condition.

**Comment by Bracciata** [comment] 2021-03-31 17:49
I can try to upload a video and recreation script this evening.

**Comment by Bracciata** [comment] 2021-04-02 16:44
I have not forgotten about this but I have gotten extremely busy due to classes.

**Comment by lauren-mills** [comment] 2021-04-13 17:33
@benbrown - would updating to the latest nightly or 1.4.0 help with this issue you think?

**Closed** 2021-11-23 15:41 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, ExemptFromDailyDRIReport
