### ISSUE TITLE
Publishing profile for CoreAssistant includes LUIS - why is it indicated as optional?

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7548] opened 2021-05-01 21:51 UTC
The 'Core Assistant' template includes a series of pre-created components which require LUIS to work properly.
The rocket menu makes 'create LUIS keys' a required step - which is correct.

When creating a publishing profile, several of the resources required for a Core Assistant bot template are indicated as 'optional resources' in the screen below. This would allow me to unselect these resources **and break my bot/bot template** before i've even started...

Expected: LUIS (note: why are there 2 LUIS registrations needed???) and QnA should be in the 'Required resources' section. When deselecting these, we should indicate that pre-created component of the Core Assistant template will not work.

<img width="1179" alt="Screen Shot 2021-05-01 at 2 44 44 PM" src="https://user-images.githubusercontent.com/48503434/116795832-9a8ce380-aa8c-11eb-896f-6bdd7ec8ad23.png">
<img width="1296" alt="Screen Shot 2021-05-01 at 2 44 52 PM" src="https://user-images.githubusercontent.com/48503434/116795836-9c56a700-aa8c-11eb-9d77-f2051b9cfbd1.png">

**Comment by benbrown** [comment] 2021-05-25 17:00
This is a dupe of #6775 - it is our plan to have the resources that are actually required appear as required!

**Closed by benbrown** 2021-05-25 17:00 UTC
Labels: Area: Publish, Type: Bug
