### ISSUE TITLE
lg editing wrong behaviors

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2398] opened 2020-03-27 10:19 UTC
## Describe the bug
when add [Activity] at the beginning of lg, the content under [Activity] will disappear.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. add a send activity component
2. input some text in lg editor
3. add
```
[Activity
]
```
before the text
![image](https://user-images.githubusercontent.com/19773357/77745934-1aa97400-7057-11ea-99e3-c04ec18f38d7.png)
4. click other components to save the lg
5. click and check the send activity, the text is missing. but it still in lg file
![image](https://user-images.githubusercontent.com/19773357/77746147-73790c80-7057-11ea-98c3-041f6dcad27a.png)
![image](https://user-images.githubusercontent.com/19773357/77746079-5c3a1f00-7057-11ea-9ae8-366f44690868.png)

**Comment by hibrenda** [comment] 2020-03-27 11:03
Reproduced this issues . please reference following format generated in lg file.  
- editing in sendactivity with following content
```
[Activity]
-hi
```
- then nothing showed for sendactivity and lg file with wrong format.
![image](https://user-images.githubusercontent.com/43408889/77749447-01a3c180-705d-11ea-9fc0-f66dc2fb2a6f.png)
![image](https://user-images.githubusercontent.com/43408889/77749776-90184300-705d-11ea-9c5b-0ca17f6255f7.png)

**Comment by a-b-r-o-w-n** [comment] 2020-03-27 16:03
@zhixzhan I think this is a LG lsp error, not a problem with the form component itself. Feel free to assign to me if you find otherwise.

**Comment by cosmicshuai** [comment] 2020-03-27 16:09
> @zhixzhan I think this is a LG lsp error, not a problem with the form component itself. Feel free to assign to me if you find otherwise.

I think the problem is from my last commit which LG LSP do the suggestion in the inline editor. The suggestion of cards are OK but the content is not correctly updated in the managed resources. So it cannot be saved correctly. I suggest disable inline LG suggestion of cards first. And I will figure out how to do the things in inline mode correctly on Monday.

**Comment by zhixzhan** [comment] 2020-03-30 03:24
It's a lg parser issue，content after [activity] after parse not be included in current template body. it cause re-render lose content.

But it seems to be a design bug, we allow save everything in this field, but some content in this field after parse will not be include in this field. it causes an inconsistency experience. @hibrenda @boydc2014 @a-b-r-o-w-n @cwhitten do you guys have any ideas ?

**Comment by zhixzhan** [comment] 2020-03-30 03:30
> @zhixzhan I think this is a LG lsp error, not a problem with the form component itself. Feel free to assign to me if you find otherwise.

@a-b-r-o-w-n Sure, by the way I found some previous 'passing diagnostics' changes in 'LgEditorWidget.tsx/LgField.tsx' has been reverted by the form refactor pr, I will fix it later

**Comment by boydc2014** [comment] 2020-03-30 07:07
@zhixzhan looks like there are two issues here, 

parsing issue, and a "append instead of upate" issue, please make sure they all get covered.

**Comment by zhixzhan** [comment] 2020-03-30 08:49
> @zhixzhan looks like there are two issues here,
> 
> parsing issue, and a "append instead of upate" issue, please make sure they all get covered.
> 
> maybe you can sync with @hibrenda for repro the 2nd issue

@boydc2014 2nd issue comes from the same parse bug, when the file ends with 
`
# bfd
[a]
\n
`
parse templates would be empty, the updateTemplate target not found, so composer do an addTemplate. that caused the duplicate appends.

**Comment by cwhitten** [comment] 2020-04-07 19:00
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2373

**Closed by cwhitten** 2020-04-07 19:00 UTC
Labels: R9, Type: Bug, skill-reported
