### ISSUE TITLE
"New Bot" requires Node Installation - should have been chain installed

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6961] opened 2021-04-14 20:26 UTC
## Describe the bug

Click the "New Bot" button on the getting started screen. 
I'm immediately presented "Node.js is required". 

NodeJS should have been chain-installed at installation time. Why am I doing this now?

## Version

Nightly Build. 
![image](https://user-images.githubusercontent.com/1165321/114774065-a6567700-9d24-11eb-98ae-dbc347fc2115.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer (new computer)
2. Click on "New Bot"
3. See "Node.js required" screen. 
4. Wonder why this wasn't chain-installed already? 

## Expected behavior

Clicking "New Bot" allows me to create a new bot. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114773980-8f178980-9d24-11eb-9dcb-3f3c3d5db37a.png)

**Comment by srinaath** [comment] 2021-04-15 17:00
This is on our backlog @cleemullins. Unfortunately, we couldn't prioritize it for BUILD but we would do the chain installation in a future release.

**Comment by mewa1024** [comment] 2021-07-01 02:33
Dupe of #6967?

**Closed** 2021-11-23 15:42 UTC
Labels: Type: Bug, UX Design, P1, Backlog, Team: Platform, ExemptFromDailyDRIReport, R13 Bugbash
