### ISSUE TITLE
"Show code" identifies problems incorrectly

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#5910] opened 2021-02-23 22:00 UTC
## Describe the bug

When viewing the code for a dialog in Composer, there seems to be a code analyzer that validates the JSON schema incorrectly.

## Version

1.3.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a dialog with a `SendActivity` and a `TelemetryTrackEventAction`
2. Click on 'Show code'
3. Scroll down to the actions
4. Change `Microsoft.SendActivity` to `asdf`
5. Observe that the tooltip for `TelemetryTrackEventAction` says Value must be "Microsoft.CancelAllDialogs" and the tooltip for `asdf` says Value must be "Microsoft.SkillDialog".

## Expected behavior

1. `"Microsoft.TelemetryTrackEventAction"` should not be underlined in yellow, since it's a valid action.
2. When values are underlined in yellow, the message should be correct. Rather than saying the value "must be" something that's not actually the only option, it should either provide a complete list of possible values or not give any list and just say the current value is invalid.

## Screenshots

![image](https://user-images.githubusercontent.com/41968495/108913334-a9fc3600-75de-11eb-876c-96c4ac2cc4e5.png)

## Additional context

I discovered this while implementing Lu Han's `TelemetryTrackEventAction` workaround [here](https://github.com/microsoft/BotFramework-Composer/issues/4305#issuecomment-706510033). It's likely that there are more problems with the code analyzer than just the two I saw, so this should be treated as a general problem rather than specific.

**Comment by srinaath** [comment] 2021-02-25 17:48
@v-kydela What happens if you copy the entire Show Code section into VSCode JSON file. Does it show the same warnings?

@luhan2017 I see you had updated the typo in the schema name here [Update the TelemetryTrackEvent name by luhan2017 · Pull Request #4820 · microsoft/botbuilder-dotnet (github.com)](https://github.com/microsoft/botbuilder-dotnet/pull/4820). Could you check on this ticket.

**Comment by a-b-r-o-w-n** [comment] 2021-02-25 18:51
@v-kydela This is a product of the implementation of the sdk schema. @chrimc62 @tomlm may have some suggestions on how to surface errors like this better, but I'm concerned about the change that would be required to the schema.

Per @luhan2017 suggestion about the workaround, the schema does not specify `Microsoft.TrackTelemetryEventAction` but rather, `Microsoft.TrackTelemetryEvent`. The workaround will not address the dialog validation because the schema is incorrect. That issue should be addressed when we update the version of the sdk packages Composer uses.

**Comment by v-kydela** [comment] 2021-02-25 19:47
@srinaath - Yes, the same warnings are in VS Code. It seems the problems are in the schema itself rather than Composer.

@a-b-r-o-w-n - To be clear, the distinction between `TelemetryTrackEvent` and `TelemetryTrackEventAction` is irrelevant in this case because the same error will show up in both cases. The schema doesn't seem to recognize either of them as valid.

**Comment by tonyanziano** [comment] 2021-07-22 18:16
I cannot reproduce this anymore. Closing as fixed

**Closed by tonyanziano** 2021-07-22 18:16 UTC
