### ISSUE TITLE
Composer prereq docs should point at .Net Core SDK 3.1 *Hosting Bundle*

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#3745] opened 2020-07-29 22:36 UTC
__Minimum__: Ensure docs point to exact prerequisites.
__Better__: detect when cannot launch web server and display error with corrective action recommendation in the GUI.

### References 
* ..."The [.NET Core SDK 3.1](https://dotnet.microsoft.com/download/dotnet-core) and above."...
* https://docs.microsoft.com/en-us/composer/setup-yarn
* https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by zxyanliu** [comment] 2020-07-30 00:06
@scheyal thanks for the feedback! 
I will update the [doc](https://docs.microsoft.com/en-us/composer/setup-yarn). Thanks!

**Comment by zxyanliu** [comment] 2020-07-30 00:51
Closing since the issue is resolved.
@scheyal Thanks again for your feedback. The content is merged and will go live soon.

**Closed by zxyanliu** 2020-07-30 00:51 UTC
Labels: Status: In PR, Type: Enhancement, topic: docs
