### ISSUE TITLE
OAuth Login null reference exception

### ISSUE THREAD

**Issue by fathorMB** [microsoft/BotFramework-Composer#2260] opened 2020-03-12 17:18 UTC
When using the OAuth login component in the Composer, i get an exception with the following message: 

> "Object reference not set to an instance of an object."

![image](https://user-images.githubusercontent.com/13238241/76547493-8acbcd80-648d-11ea-8f97-9b6a58138528.png)

I'm using the OAuth component exaclty as i was using it with the previous release and it was working perfectly.

## Version

![image](https://user-images.githubusercontent.com/13238241/76547609-c5356a80-648d-11ea-9ba6-35472dc44f00.png)

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by zxyanliu** [comment] 2020-03-12 17:37
FYI. I had the same issue and was about to report. Thanks for reporting. 

![oauth-issue](https://user-images.githubusercontent.com/32497439/76549356-82ec3900-644d-11ea-8136-3040c2e6dcc7.jpg)

**Comment by fathorMB** [comment] 2020-03-13 07:59
I just tried to switch to the master branch to check if it was working but i get the same error, but i think on a different component. The error i obtain is exactly at the beginning of the Greeting dialog. Here's a screenshot of what my project looks like.

![image](https://user-images.githubusercontent.com/13238241/76601295-e8e9c680-6508-11ea-85ad-0492f40ef9a2.png)

![image](https://user-images.githubusercontent.com/13238241/76601318-f606b580-6508-11ea-98e8-dd1e603c8033.png)

**Comment by zxyanliu** [comment] 2020-03-13 19:36
FYI. I think OAuth works now.

**Comment by zxyanliu** [comment] 2020-03-18 03:09
@fathorMB Did you have a chance to try again? I think the OAuth issue has been addressed.
Here is a [doc](https://docs.microsoft.com/en-us/composer/how-to-use-oauth) for your reference.

**Comment by fathorMB** [comment] 2020-03-18 10:19
@zxyanliu OAuth is now working. Thanks!

**Comment by zxyanliu** [comment] 2020-03-18 16:02
Closing because the issue is addressed.

**Closed by zxyanliu** 2020-03-18 16:02 UTC
Labels: Needs investigation
