### ISSUE TITLE
User Input section doesn't have ability to define a new intent.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3473] opened 2020-06-23 19:39 UTC
## Describe the bug

There is no way to define LU resources from the UI without dropping into "editor" mode.

## Version

1.01

## To Reproduce

1. Go to User Input.  There is no way to add a intent definition.

## Expected behavior
an Add button which lets me define a new intent.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/85451182-74361780-b54e-11ea-96b1-5c8c0eb535f7.png)

**Comment by cwhitten** [comment] 2020-06-24 18:14
This is by design. Adding @sangwoohaan for comment.

**Comment by sangwoohaan** [comment] 2020-06-24 21:46
Currently, even if you define a new intent, there's no way for you to hook it up with triggers and prompts unless you directly modify the code. We are currently working on the overall improvement on this side of UX.

**Comment by cwhitten** [comment] 2021-02-11 22:46
Closing as "by design"

**Closed by cwhitten** 2021-02-11 22:46 UTC
Labels: UX Design, feature-request
