### ISSUE TITLE
Auth prompt by Composer after creating an empty bot template

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7591] opened 2021-05-04 13:09 UTC
## Describe the bug

When creating an empty bot (no azure resource dependencies) Composer prompts for authentication. 

Also note that when clicking Cancel, it prompts again? Cancelling the 2nd prompt enables you to continue.

## Version

2.0.0-nightly.242275

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Empty Bot
2. Observe Auth prompt after creation

## Expected behavior

No auth prompt

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/117008121-4d09b400-ace2-11eb-9e8a-c64e1291dba1.png)

**Comment by benbrown** [comment] 2021-05-04 14:08
I believe this is due to the auth being called when the ManagerService components mount as part of the getstarted component.

https://github.com/microsoft/BotFramework-Composer/blame/4fd58c86e6038ac1c33432814839dac4754cfb4b/Composer/packages/client/src/components/ManageService/ManageService.tsx#L162

**Comment by sgellock** [comment] 2021-05-04 15:02
Shiproom - this is a regression, P0.  approved.

**Comment by benbrown** [comment] 2021-05-04 23:17
fixed by #7623

**Closed by benbrown** 2021-05-04 23:17 UTC
Labels: P0, ShipRoom-Approved, Type: Bug, topic: creation
