### ISSUE TITLE
Can't publish bot to Azure with version 1.3.0

### ISSUE THREAD

**Issue by franctum5** [microsoft/BotFramework-Composer#5377] opened 2020-12-17 14:40 UTC
## Describe the bug

After updating to 1.3.0 the publish to Azure Web App functionality keeps on spinning on the UI but the bot is never published to Azure. 

Opening the developer tools I can see that the request to api/publish ends with a 431 (Request header fields too large) and all the following requests to get the status end with a 404.

## Version

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish and select a bot
2. Click on "publish selected bots"
3. The bot is never published

## Expected behavior

The bot should be published to the Azure Web App

**Comment by zxyanliu** [comment] 2020-12-17 17:24
This is a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/5335

**Closed** 2020-12-17 17:38 UTC
Labels: Type: Bug, duplicate
