### ISSUE TITLE
Publish Error JSON SyntaxError v1.3

### ISSUE THREAD

**Issue by lucasdodgson** [microsoft/BotFramework-Composer#5344] opened 2020-12-15 15:21 UTC
Hi, 
Just updated to v1.3 and tried to publish with the same profile as I had used in v1.2. 
Running locally works, although when publishing I get the following error: 
SyntaxError - Unexpected token o in JSON at position 1

Below is the log: 

> "Assigning to luis app id: _removed_"
> ---
> 
> ---
> "{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:110568)\\n    at F.callback (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:109411)\\n    at F.e.callback.t.callback [as _callback] (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:108459)\\n    at F.t._callback.t.callback.t.callback (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:4015)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:16712)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:15544)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
> ---
> 
> ---
> "{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:114757)\\n    at E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:111883\\n    at Object.throw (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:111988)\\n    at s (E:\\\\Program Files\\\\BotFrameWorkComposer\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:110753)\",\"message\":\"Unexpected token o in JSON at position 1\"}"
> ---
> 
> ---
> "SyntaxError - Unexpected token o in JSON at position 1"
> ---
>

**Comment by a-b-r-o-w-n** [comment] 2020-12-15 18:01
@luhan2017 can you investigate this issue?

**Comment by luhan2017** [comment] 2020-12-16 02:30
@lucasdodgson，could you share your profile? I can't reproduce this issue on my side.

**Comment by a-b-r-o-w-n** [comment] 2020-12-16 17:08
@sriget @lucasdodgson Can you provide your appsettings.json file (with secrets redacted)?

**Comment by sriget** [comment] 2020-12-16 18:10
> @sriget @lucasdodgson Can you provide your appsettings.json file (with secrets redacted)?

This is my app settings json from bot. After i click publish, i see luis keys and pwds are cleared out of json file. Hope that is expected.

[appsettings_issue.txt](https://github.com/microsoft/BotFramework-Composer/files/5704632/appsettings_issue.txt)

**Comment by lucasdodgson** [comment] 2020-12-16 21:30
Attached is mine as well. 

[appsetting_issue.txt](https://github.com/microsoft/BotFramework-Composer/files/5705585/appsetting_issue.txt)

**Comment by luhan2017** [comment] 2020-12-17 01:48
@lucasdodgson , is your luis resource provisioned through composer? you may need to add luisResource in your publish profile. Please refer to the details here. 
https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-747150353

**Comment by lucasdodgson** [comment] 2020-12-17 10:02
@luhan2017 The lines are present in the publish profile. 

Trying to play around though I have observe two things, maybe they are helpful.
1. I believe I am not loging into the directoy in which my azure subscription is in (as Composer login is not prompting me to enter my 2FA). Is there any way of specifying this?

2.  If I try to provision a publish profile through composer, it just says loading forever. This happens after having logged in, so might be related to 1.

**Comment by cameroncharles** [comment] 2020-12-24 01:22
I am also getting this error, i had to create a new profile in 1.3 but it looks very similar to the one for another bot that was created in 1.2, said bot also publishes just fine in 1.3 the only difference between the 2 is LUIS

i have the hostname and luisResource values set and the json for both the profile and the settings is valid, but i still get this error

**Comment by Rekeyea** [comment] 2020-12-29 15:49
Same issue here. Both the inability to publish from composer due to something with luis and the composer never finishing loading when trying to provision a profile with resources created from composer.

**Comment by sshaque1** [comment] 2021-01-08 15:55
Hello experts, any solution to this yet? TIA.

**Comment by sshaque1** [comment] 2021-01-09 01:53
Just managed to publish successfully my test bot from Bot Framework Composer to my Azure account using using version 1.3.0.

I resolved the "SyntaxError - Unexpected token o in JSON at position 1" error by **logging into my Work/School account** from the **composer** as oppose to _Personal account_.  

So, all the resource information i used with **"node provisionComposer.js"** command referred to my Work/School account's **subscription**.

The solution actually triggered when I read this post:  #5393 - Impossible to sign in to personal account to create a publish profile.

**Comment by nitroin** [comment] 2021-01-21 13:54
Exact same problem here.

**Comment by sshaque1** [comment] 2021-01-21 19:11
> 
> 
> Exact same problem here.

@nitroin: are you using work/school account or personal account?

**Comment by Pajani** [comment] 2021-01-24 11:19
@sshaque1 , I am facing the same issue, i could not publish my bot into azure. 


> Just managed to publish successfully my test bot from Bot Framework Composer to my Azure account using using version 1.3.0.
> 
> I resolved the "SyntaxError - Unexpected token o in JSON at position 1" error by **logging into my Work/School account** from the **composer** as oppose to _Personal account_.
> 
> So, all the resource information i used with **"node provisionComposer.js"** command referred to my Work/School account's **subscription**.
> 
> The solution actually triggered when I read this post: #5393 - Impossible to sign in to personal account to create a publish profile.

i am also facing the issue, could not publish my bot into azure.  i am using luis and bot composer v1.3. Getting error "" we could not find a work or school account with the email address""

i am using personal account.

**Comment by DavidStrickland0** [comment] 2021-01-27 21:36
Any updates on this? 
I took an Unaltered Echobot and published it and did not receive this error (Got a different one [#5628 ])
Added a Trigger to the one dialog in the Echobot and got "Unexpected token o in JSON at position"
Definitely seems LUIS related. I have Luis Authoring and Endpoints created and the Intent publishes when I run it locally. But something blows a fuse when I try to Publish explicitly.

Not certain if its related but the instance I'm using for just about everything are Free or Free tier... Unfortunately can't switch to standard to test but thought it might be worth pointing out in case its one of those hidden Azure Pay Wall "features".

**Comment by VanyLaw** [comment] 2021-01-28 07:09
@DavidStrickland0 is your luis resource provisioned through composer? you may need to add luisResource in your publish profile. Please refer to the details here.
#5354 (comment)

**Comment by cameroncharles** [comment] 2021-01-28 07:13
to put an update here, still getting the error when attempting to publish to existing azure resources, however in 1.3 there is the option to have bot framework composer provision you a set of resources to then publish too, we did this and it publishes perfectly fine, besides the different names and keys there were no major differences in the publish profile to point out though.

**Comment by DavidStrickland0** [comment] 2021-01-28 14:22
@VanyLaw The Bug your referencing is closed as a duplicate of this one then @luhan2017 's answer was added after the fact.. Should we continue this conversation about that response here or there?

**Comment by luhan2017** [comment] 2021-01-29 08:30
@VanyLaw  Let's update the error message, we should say: Failed to bind luis prediciton resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile.

**Comment by cameroncharles** [comment] 2021-02-01 06:41
for the record, adding "luisResource" did not help me when i originally encountered this issue, i think there was another github issue that mentioned it as a possible solution, that and hostname, futhermore as mentioned above, my now fully working profile is near identical to the one that doesnt work

**Comment by compulim** [comment] 2021-02-17 19:22
@luhan2017 I am DRI this week.

Is this a bug on the error message we put in Composer? Or is this a confusion while we are discussing about this issue?

**Comment by cwhitten** [comment] 2021-02-18 17:41
@luhan2017 can you please update this thread or drive it to closure? thank you

**Closed** 2021-02-22 12:01 UTC
Labels: Area: Publish, Bot Services, Team: Runtime & Publishing, Type: Bug, customer-replied-to, customer-reported

**Comment by danielgoldszmit** [comment] 2021-04-01 18:51
> Moving a short version of @luhan2017 's work around here.
> 
> In short it appears there are two missing properties in the publication Profile. That can cause an error. The Json parsing one can be caused by a missing "luisResource" property.
> 
> > {
> > "name": "Luhan0603AF",
> > "environment": "dev",
> > "hostname": "Luhan0603AF-dev",   ------------------> This is the name of your webapp.
> > "luisResource": "Luhan0603AF-dev-luis",   ----------------> This is the name of your luis prediction service.

Adding the luisResource fix the issue using V1.4
