### ISSUE TITLE
Inconsistent line references between diagnostic section and sidebar

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6139] opened 2021-03-03 20:42 UTC
## Describe the bug

The line numbering in the bottom panel is incorrect.

## Version

1.3.1-nightly.219396.61c944a

## To Reproduce

1. Introduce an LG error in a dialog somewhere
2. Open the bottom panel
3. Note the inconsistent line numbers

## Expected behavior

Line numbers should be the same when pointing to the same error.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/109869019-3a5cfb00-7c1d-11eb-921b-a0f1cba4c541.png)

**Comment by boydc2014** [comment] 2021-05-26 13:19
This is actually by design, because the inline error is trying to point to the "relative offset" and the global diagnostic bar is trying to show the "absolute offset" in the file. 

Close this for now, free feel to re-open if you think this is still an issue.

**Closed by boydc2014** 2021-05-26 13:19 UTC
Labels: R12 Bugbash, Team: Platform, Type: Bug
