### ISSUE TITLE
[R11 Bugbash] We shouldn't have an Edit->Undo menu if it isn't universally applicable throughout the app

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5156] opened 2020-12-04 22:27 UTC
## Describe the bug

There is an "Edit" -> "Undo" in the top level menu. However that only applies whatever that was entered into the text box last. It doesn't undo anything else in the UI around the WSYIWYG editor for the dialogs, etc. I assume undo also works in the "Show Code" mode since it is essentially a multi-line text box.

Should we even expose that if Undo is not universally supported throughout the app?

## Version
                Bot Framework Composer

                Version:  1.2.1-nightly.191674.827857c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/101221566-c8384280-363c-11eb-9fd4-1a2b6f3f3386.png)

**Comment by mrtank** [comment] 2021-05-07 12:12
It does undo delete/cut multiple flow control elements at once, but looses the content of it... I suggest to implement the [Memento design pattern](https://en.wikipedia.org/wiki/Memento_pattern)

**Comment by mewa1024** [comment] 2021-07-02 18:18
closing as a duplicate of #8115

**Closed by mewa1024** 2021-07-02 18:18 UTC
Labels: ExemptFromDailyDRIReport, R11 Bugbash, UX Design
