### ISSUE TITLE
Composer doesn't stop the previous runtime when switching projects.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3658] opened 2020-07-18 20:37 UTC
## Describe the bug
Composer leaves the runtimes running when switching between projects. This can be problematic when you're doing skill development because you can't guarantee which runtime will process postbacks from a skill your testing.   

I was making a change to a skill which I published to Azure after testing in the emulator. I then switched to my Assistant project and started up ngrok and the assistant runtime. Calling my skill from the emulator resulted in 500 errors from the skill. Looking at the ngrok window that was because my runtime was returning 401 errors. After attaching a debugger to my runtime I couldn't get any breakpoints on the callback side of things to hit. It was at that point that I realized the callbacks were going to the skills runtime I had just been testing. Killing both processes and re-starting my assistants runtime resolved the issue.

## Version
1.0.2

**Comment by cwhitten** [comment] 2020-07-18 23:17
Taking this in R10

**Comment by boydc2014** [comment] 2020-07-21 00:19
@Stevenic it's by design today to not closing previous bot when you switching project, so that user can create and start multi bots and\or skills, they are supposed to run in different local port, starting from 3979, 3980, etc. We didn't take ngrok into consideration on this, if your old ngrok still pointing to the previous one, it might have issues. 

The issue to me is that this management is all behind the scene, and leave user no control on this. So @srinaath was working on a feature that give user explicitly control on the multiple bots that were being started and support user to close certain runtime, so i think this issue could be solved by the time we have that feature.

**Comment by cwhitten** [comment] 2020-07-21 21:02
@Stevenic we inclined to consider this more of a feature than a bug, and as @boydc2014 the team will be introducing more fine-grained control over running servers/ports in a future release. We confirmed that closing Composer does clean up processes it started, including bot processes.

So, working as intended with the knowledge that you may need to restart your tunnel with an updated port based on what bots you have running in a session.

**Comment by bradrlaw** [comment] 2020-07-24 07:20
On OS X it is not cleaning up the processes.  I started up several bots and talking to them in the emulator in different windows.  The bots are still running even if the composer application is quit.  Do you want this as a separate bug? @cwhitten

**Comment by cwhitten** [comment] 2020-09-12 04:15
Closing as being unable to reproduce on 1.1.1. Please ping this issue if you are still experiencing this on latest stable. Thanks!

**Closed by cwhitten** 2020-09-12 04:15 UTC
Labels: Area: Shell, R11, Team: Platform, Type: Bug

**Comment by shermanmccoy** [comment] 2020-11-13 19:03
I have the same problem as bradrlaw. In MacOS, a lot of dotnet process keep alive after closing the composer. Even if I make a portscan on localhost, the bots remain listening.

I am using 1.1.1
