### ISSUE TITLE
Create new resources content has formatting issues

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6780] opened 2021-04-08 17:19 UTC
## Describe the bug
When creating a new publishing profile, the "Create new resources" content has formatting issues when describing what's required. specifically, the azure subscription requirement.

## Version
Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. create a new, or open an existing bot with Composer
2. Nav to the publish your bots page
3. Click the Add new link to invoke the Add a publishing profile flow
4. Name your profile, select the Azure publishing target
5. Log into azure if prompted
6. From the resource selection modal, select the "Create new resources"
7. Review the "Create New Resources" text.  Notice the formatting/layout issue with the second sentence.  see screenshot below.

## Expected behavior
Proper formatting of the second sentence

## Screenshots

<img width="987" alt="Screen_Shot_2021-04-08_at_10_11_53_AM" src="https://user-images.githubusercontent.com/733559/114068894-40b14900-9853-11eb-8a4d-379399658180.png">

**Comment by Dewain27** [comment] 2021-04-09 16:27
I believe duplicate of #6825

**Closed** 2021-04-09 21:08 UTC
Labels: Type: Bug, topic: creation
