### ISSUE TITLE
Electron app: Add file menu options

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3513] opened 2020-06-28 16:24 UTC
## Minor UX improvements for the Electron app

- Currently the buttons _New_, _Open_ and _Save As_ are **only** available from the Home screen. 
- The _Save As_ button on the Home page is grayed out when no bot is opened (logically), and gets enabled when a bot project is loaded. With the current design of the Home page, it is not intuitive for a user to come back to Home to find the _Save As_ action after making changes to a bot project, as most of the actions on the Home page are related to the creation of a new bot (from scratch or via samples).

**Suggestion:** 
- Add the actions _New_, _Open_ and _Save As_ to the _File_ menu in the Electron app, so they can be accessed from anywhere.
- Maybe the _Export_ actions (as .zip & as skill) can be added under the _File_ menu as well?

**Comment by hibrenda** [comment] 2020-06-29 05:37
@sangwoohaan @mareekuh may take a look

**Comment by tdurnford** [comment] 2020-09-22 16:49
@sangwoohaan Can you weigh in?

**Comment by sangwoohaan** [comment] 2020-09-25 18:27
This is a great suggestion. We will take a look into it

**Comment by mewa1024** [comment] 2021-07-02 23:35
Closing as dupe of
- #6959

**Closed by mewa1024** 2021-07-02 23:35 UTC
Labels: Bot Services, Composer Controls, ExemptFromDailyDRIReport, UX Design, customer-replied-to, customer-reported, feature-request
