### ISSUE TITLE
"Sign In code was not found or expired"

### ISSUE THREAD

**Issue by bobokids** [microsoft/BotFramework-Composer#8926] opened 2022-01-21 07:32 UTC
## Describe the bug

Copied the bug from https://github.com/microsoft/BotFramework-Services/issues/329
![image](https://user-images.githubusercontent.com/19182479/150485231-1ad0de35-200e-4df3-8158-ab6dbc5ea84e.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by ramfattah** [comment] 2022-01-26 03:29
Hi @rodriguesnich -- This behavior is expected. For more on Bot composer OAuth refresh token, please check out this [oauth prompt logic issue](https://github.com/microsoft/BotFramework-Composer/issues/3629#:~:text=The%20logic%20of,there%20is%20any.). 

Closing this as it is not a bug, feel free to reopen this issue if you come across any bugs.
Hi @user, let us know if @user's suggestion worked, I am closing this one for now, feel free to re-open if you are still having issues.

**Closed by ramfattah** 2022-01-26 03:29 UTC
Labels: Type: Bug, Needs-triage
