### ISSUE TITLE
Dotnet function bots spin indefinitely while trying to start

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7489] opened 2021-04-29 17:11 UTC
## Describe the bug
When I try to start a dotnet function bot it's just spins indefinitely trying to start the bot. If you look at the screenshot below it appears it's stuck in an infinite loop. A new record comes in every ~1 second.

## Version
Version:  2.0.0-nightly.240913.4390cd8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a dotnet function bot
2. Click start bot

## Expected behavior
It should start.

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116590728-f449ae00-a8d2-11eb-89c7-e74fead74c08.png)

**Comment by srinaath** [comment] 2021-04-29 17:12
Closing as its a dupe of [Composer nightly build won't start bots · Issue #7483 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/issues/7483)

**Closed by srinaath** 2021-04-29 17:12 UTC
Labels: Needs-triage, P0, Type: Bug
