### ISSUE TITLE
'Something went wrong' when navigating triggers or editing language generation

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3242] opened 2020-05-31 11:52 UTC
## Describe the bug

When navigating "Intent recognized" triggers, or typing in the "Language Generation" field, an error message pops up "Something went wrong". The issue does not produce all the time, it's intermittent, but very frequently. It seems to produce mostly on "Intent recognized" triggers using Luis. It's almost impossible to complete any simple bot logic without triggering this error message. 

The issue can be experienced on out of the box samples with no changes to the bot conversations. 

## Version

![image](https://user-images.githubusercontent.com/23324404/83351535-17778080-a345-11ea-91dd-63d60ca8dd96.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Scenario 1: 
1. Create a new bot based on the ToDoBotWithLuis template from the samples.
2. Click over the different intents on the left (for example 'add', 'delete', 'view' in the screenshot), until dialog "something went wrong" pops up. 

Scenario 2:
1. Create a new bot based on the empty bot template. 
2. Add an unknown intent trigger. 
3. Add a bot response, and start typing in the language generation field. The error pops up after typing a few characters. 

## Screenshots

Scenario 1: 
![image](https://user-images.githubusercontent.com/23324404/83351494-c49dc900-a344-11ea-93fc-a851a4a9a926.png)

Scenario 2: 
![image](https://user-images.githubusercontent.com/23324404/83357791-d72cf800-a36e-11ea-8faf-9cb4bae75ba5.png)

**Comment by cwhitten** [comment] 2020-05-31 20:19
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3167

**Closed by cwhitten** 2020-05-31 20:19 UTC
Labels: Needs investigation, Type: Bug
