### ISSUE TITLE
Updates to GUI not taking effect after generating a new custom runtime

### ISSUE THREAD

**Issue by alfenne** [microsoft/BotFramework-Composer#6588] opened 2021-03-29 18:18 UTC
## Describe the bug

After creating a new copy of the runtime, edits in the GUI are not taking effect in the bot. @garypretty 

## Version
1.4.0-nightly.228398.1bfe853

## Browser

- [ ] Electron distribution

## OS

- [ ] Windows

## To Reproduce

1. Create a new empty bot project
2. Add a prompt to the default dialog after the WelcomeUser() prompt
3. On the "Project Settings" side tab, click the "Get a new copy of the runtime code" button, then select "C#".
4. Make any edits to the default dialog (add new prompt, edit existing prompt)
5. When testing the bot, in both the Emulator and Web Chat, the edits made after generating a new copy of the runtime code are not applied.

## Expected behavior

After generating a new copy of the runtime code, subsequent edits to the bot project should be applied to the bots behavior

## Screenshots
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/64445981/112881195-61caaa80-9099-11eb-8405-1a236a2935d0.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64445981/112881294-7c9d1f00-9099-11eb-8839-1a32411954dc.png)

**Comment by msomanathan** [comment] 2021-03-31 18:06
@dmvtech could you please update on this issue, Thanks!

**Comment by dmvtech** [comment] 2021-04-02 17:17
I'm not able to reproduce this issue.

@alfenne Are you running the bot a first time before generating new runtime and making changes? i.e. In between steps 2 and 3.


I'm running:
Version:  1.4.0-nightly.230410.31d4ca5
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Let me know if I need to alter my steps at all.

**Comment by alfenne** [comment] 2021-04-02 17:19
Yes @dmvtech, I did run the bot for a first time before generating a new runtime. Sorry for not making that clear.

**Comment by dmvtech** [comment] 2021-04-06 00:11
Thanks @alfenne. I am _still_ not able to reproduce. Just wanted to confirm this reproduces for you consistently. i.e. You can create new bots with the same steps above and it reproduces each time?

**Comment by dmvtech** [comment] 2021-04-12 16:39
@alfenne 

I just tried again with the following:
```
Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

And still cannot reproduce. Are you able to test with the newest nightly and confirm you can still reproduce?

**Comment by alfenne** [comment] 2021-04-12 16:42
Hi @dmvtech,

I have upgraded Bot Composer to the newest nightly build and I am no longer able to reproduce this. 

Thinking it was fixed in the latest release?

**Comment by dmvtech** [comment] 2021-04-13 22:01
hi @alfenne Apparently so. Hard to say since I was never able to reproduce. I'm going to close this, but please comment if this happens to pop back up.

**Closed by dmvtech** 2021-04-13 22:01 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
