### ISSUE TITLE
Publish the BOT Framework Composer gives status code 202 for long time, wait almost 2 hrs still getting the same status code

### ISSUE THREAD

**Issue by MayankKT** [microsoft/BotFramework-Composer#3602] opened 2020-07-09 05:08 UTC
## Version
BotFramework-Composer-master 

     "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-transform-runtime": "^7.9.6",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "^7.9.4",
    "@babel/preset-typescript": "^7.9.0",
    "@bfc/eslint-plugin-bfcomposer": "*",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@testing-library/cypress": "^6.0.0",
    "@typescript-eslint/eslint-plugin": "2.34.0",
    "@typescript-eslint/parser": "2.34.0",
    "chalk": "^4.0.0",
    "concurrently": "^4.1.0",
    "coveralls": "^3.1.0",
    "cypress": "^4.5.0",
    "cypress-plugin-tab": "^1.0.5",
    "eslint": "7.0.0",
    "eslint-config-prettier": "6.11.0",
    "eslint-plugin-cypress": "2.10.3",
    "eslint-plugin-emotion": "10.0.27",
    "eslint-plugin-format-message": "6.2.3",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-lodash": "7.1.0",
    "eslint-plugin-notice": "0.9.10",
    "eslint-plugin-prettier": "3.1.3",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.2",
    "eslint-plugin-security": "1.4.0",
    "get-port": "^5.1.1",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.0",
    "prettier": "2.0.5",
    "rimraf": "^2.6.3",
    "ts-loader": "7.0.4",
    "typescript": "3.9.2",
    "wsrun": "^5.2.0"

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots

![botcompoesrissue](https://user-images.githubusercontent.com/28943234/86999462-48629500-c1d0-11ea-98bb-8a2af4b48db0.png)

## Additional context

Need to create the skill bot.

**Comment by VanyLaw** [comment] 2020-07-09 07:24
Yeah @MayankKT, Because the azure deploy need to copy files, build project, publish luis, zip folder and upload it, it's a very time-consuming process. If we don't response 202 which means still processing, the http call will easily timeout.

**Comment by MayankKT** [comment] 2020-07-09 07:45
Yes, I understood but it takes almost 4 hrs but still showing the same status code.

**Comment by cwhitten** [comment] 2020-07-09 16:44
Hi @MayankKT - it is unlikely that this process requires the time you're experiencing, and an error has occurred. Can you restart Composer and try again? Also, because you are self-hosting Composer you may see some of this information in stdout of the terminal running the application processes. To give you additional telemtry, run the application with the following:

`DEBUG=composer* yarn start`

**Comment by zxyanliu** [comment] 2020-07-21 00:16
Hi @MayankKT I just tested using the latest [main branch](https://github.com/microsoft/BotFramework-Composer) and I was unable to reproduce the error you mentioned. 
Could you please try again and follow the [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot).?

**Comment by zxyanliu** [comment] 2020-07-22 20:39
@MayankKT any updates?

**Comment by MayankKT** [comment] 2020-07-23 04:21
@zxyanliu I will try again with latest main branch and will update you accordingly . thanks

**Comment by zxyanliu** [comment] 2020-07-27 19:04
@MayankKT did you have a chance to try again?

**Comment by MayankKT** [comment] 2020-07-29 04:03
Hi @zxyanliu ,No I am outside, will try and update you soon.

**Comment by zxyanliu** [comment] 2020-07-31 21:44
I am closing this issue at this point because we were unable to reproduce your error. 
Please feel free to reopen it after you have a chance to try again and still had the same issue. 
Thanks a lot!

**Closed by zxyanliu** 2020-07-31 21:44 UTC
Labels: Type: Question, topic: publish
