### ISSUE TITLE
Bot Framework Composer, error when creating new bot - command failed

### ISSUE THREAD

**Issue by ajonesbb7** [microsoft/BotFramework-Composer#8706] opened 2021-09-28 15:06 UTC
I installed the Bot Framework Composer , with all the tools required as prerequisite. On creating a new bot I am getting error.

![image](https://user-images.githubusercontent.com/91552539/135114271-bbe200df-8a78-4145-8146-c5e1744a70b1.png)

**Comment by tonyanziano** [comment] 2021-09-28 16:44
Closing this issue as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/8703. Please follow that issue for any updates.

**Closed by tonyanziano** 2021-09-28 16:44 UTC
Labels: Needs-triage
