### ISSUE TITLE
Add custom actions through runtime in Bot Composer 2.xx Missing

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7830] opened 2021-05-14 09:49 UTC
## Describe the bug

Have a need to create a custom action which could be achieved through Custom Action (solution) present in runtime is missing

## Version

![image](https://user-images.githubusercontent.com/26645750/118252937-da929400-b498-11eb-895f-86e1e599da8d.png)

## Browser

- [ ] Chrome

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

![image](https://user-images.githubusercontent.com/26645750/118253331-57257280-b499-11eb-8a42-24f7734bc1a1.png)
![image](https://user-images.githubusercontent.com/26645750/118253537-918f0f80-b499-11eb-8f40-d29ef627d4ca.png)

Runtime folder -> Custom Action folder is missing and don't find a option to generate
## Expected behavior

is there a way we can create custom actions in this version?

**Comment by dmvtech** [comment] 2021-05-14 14:52
Looks like duplicate of #7829

**Comment by tdurnford** [comment] 2021-05-14 16:29
Closing as duplicate of #7829

**Closed by tdurnford** 2021-05-14 16:29 UTC
Labels: Bot Services, Needs-triage, Type: Bug, customer-reported

**Comment by dmvtech** [comment] 2021-05-14 23:08
@aparnaji Please see my info/findings/steps in [this comment](https://github.com/microsoft/BotFramework-Composer/issues/7829#issuecomment-841543388).
