### ISSUE TITLE
Getting error prompt when displaying adaptive card with media using link to SharePoint in Bot Framework Composer

### ISSUE THREAD

**Issue by mukeshOps** [microsoft/BotFramework-Composer#8073] opened 2021-06-14 14:49 UTC
## Describe the bug

Getting error prompt when using adaptive card with media using link to SharePoint for video and same link in button in Bot Framework Composer. The output is displayed fine in PVA. But for some reason when I test the bot in emulator it keeps giving me error "Something went wrong..." not sure if there is something failing or just something I need to avoid by pressing ok.
## V2.0.0

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Add Adaptive card with this code :
```md
- ```{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
    "body": [
        {
            "type": "Media",
            "poster": "https://sites.ey.com/sites***.png",
            "sources": [
                {
                    "mimeType": "video/mp4",
                    "url": "https://sites.ey.com/sites/***.mp4"
                }
            ],
            "horizontalAlignment": "Center",
            "spacing": "Small"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Open in Internet Explorer",
                    "url": "https://sites.ey.com/sites/***.mp4",
                    "style": "positive"
                }
            ],
            "horizontalAlignment": "Center",
            "spacing": "Small"
        }
    ],
    "backgroundImage": {
        "horizontalAlignment": "Center"
    }
}```
```

## Expected behavior

Expecting a video as we do in any normal video adaptive card.

## Screenshots

![image](https://user-images.githubusercontent.com/59365172/121911809-b4893980-cd4d-11eb-81eb-bb15d31af6c9.png)
![image](https://user-images.githubusercontent.com/59365172/121911904-c2d75580-cd4d-11eb-96ba-6ddae07504d8.png)

## Additional context

please let me know in case of any more details needed.

**Comment by dmvtech** [comment] 2021-06-15 17:19
Hi @mukeshOps I'm assuming this is due to the issue specified here: https://github.com/microsoft/BotFramework-Composer/issues/6128

I'm also assuming that the video file url does not need/use any sort of authentication, correct?

I'll do some further testing and see if I can confirm the above for that linked bug.

**Comment by dmvtech** [comment] 2021-06-16 00:21
Can confirm I can can reproduce. Will share when I have more information.

**Comment by mukeshOps** [comment] 2021-06-16 00:48
Thx. I think I have one more issue to report but more of problem inside PVA. I will raise separately. Thank You for looking into it.

**Comment by srinaath** [comment] 2021-06-16 16:44
@garypretty Another issue related to codec support in the electron flavor we are using.

**Comment by dmvtech** [comment] 2021-06-16 17:04
Further clarification; I tested in Webchat/TestinWebchat and that works. So, it is for sure the electron flavor.

**Comment by dmvtech** [comment] 2021-06-18 18:41
Closing as the issue is being tracked in #6128.

This is a known issue for Emulator and Composer WebChat. You can use WebChat or other channels (assuming specific channel supports video in cards).

**Closed by dmvtech** 2021-06-18 18:41 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
