### ISSUE TITLE
Need ability to delete a publishing profile in Composer

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#5892] opened 2021-02-23 15:13 UTC
## Describe the feature

Currently in Composer, you can't delete a publishing profile.  We need to be able to give a user the ability to easily delete a publishing profile.

## Describe the solution you'd like

We should put a delete button next to the edit option in Composer.  This delete function should only delete the profile, not the Azure resources.  We need to clearly communicate that this is what is happening.
![image](https://user-images.githubusercontent.com/18688053/108863759-29760f00-75b7-11eb-8d44-4ca9f223a7c9.png)

**Comment by cwhitten** [comment] 2021-03-22 19:20
Closing as a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/5642

**Closed by cwhitten** 2021-03-22 19:20 UTC
Labels: Team: Runtime & Publishing, feature-request, topic: publish
