### ISSUE TITLE
Webex Adapter AttachementAction Response Unusable

### ISSUE THREAD

**Issue by mocalv** [microsoft/BotFramework-Composer#8997] opened 2022-02-15 14:37 UTC
## Describe the bug

When using adaptive cards with buttons, the response data (turn.activity.value = Webex [AttachementAction](https://developer.webex.com/docs/api/guides/cards)) is formatted as a dictionary and therefore not unusable for the composer. 

## Version

![image](https://user-images.githubusercontent.com/30929452/154037415-1e266287-2a5f-472c-81f6-1437fb3b2724.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Bot Composer
2. Create new empty bot
3. Create "Ask a question"->"Text" Action for "unknown intent" Trigger
4. Add text and an adaptive card with buttons as attachment to the action
5. Install Webex adapter under "package manager" and configure it
6. Install and Configure ngrok to debug locally
7. debug

## Expected behavior

Useable response data when using Webex with adaptive cards and buttons

## Screenshots

![image](https://user-images.githubusercontent.com/30929452/154034546-8d242b7b-210c-439c-987b-f1b221dbe610.png)

**Comment by anishprasad01** [comment] 2022-02-16 23:37
Thank you for the report. I will investigate.

**Comment by anishprasad01** [comment] 2022-02-18 22:32
Hi @mocalv,

Could you provide me with a screenshot of your Webex configuration in Composer? Please make sure to cover up or remove your secret and token.

**Comment by anishprasad01** [comment] 2022-02-22 20:20
Could you by any chance also provide a sample of how you have set up adaptive cards on Composer for Webex? To be perfectly honest, I am having some trouble following your reproduction steps.

**Comment by mocalv** [comment] 2022-02-23 08:57
Sure, here step three and four with more details:

3. Create "Ask a question"->"Text" Action for "unknown intent" Trigger
![grafik](https://user-images.githubusercontent.com/30929452/155275273-628f17bd-2fdf-4cbf-865b-8019f17ee7da.png)

4. Add text and an adaptive card with buttons as attachment to the action
![grafik](https://user-images.githubusercontent.com/30929452/155275555-63ff7d6a-3843-44ea-84a7-7e402551886a.png)
![grafik](https://user-images.githubusercontent.com/30929452/155275427-c78c5f92-d2a2-4593-86d1-92b2576f26be.png)

As mentioned earlyer, for a adaptive card on Comper for Webex you have to use a  "dopple json structure". You can use this:
```
- ```
{
  "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
  "body":[
    {
      "type":"TextBlock",
      "text":"So let's get started."
    },
    {
      "type":"TextBlock",
      "text":"Currently I am able to help you with the following topics"
    }
  ],
  "actions":[
    {
      "type":"Action.Submit",
      "title":"Encryption",
      "data":{
        "action":"encryption"
      }
    },
    {
      "type":"Action.Submit",
      "title":"Document Classification",
      "data":{
        "action":"classification"
      }
    },
    {
      "type":"Action.Submit",
      "title":"Tools for experts",
      "data":{
        "action":"tools"
      }
    }
  ],
  "type":"AdaptiveCard",
  "version":"1.0",
  "contentType":"application/vnd.microsoft.card.adaptive",
  "content":{
    "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
    "body":[
      {
        "type":"TextBlock",
        "text":"So let's get started."
      },
      {
        "type":"TextBlock",
        "text":"Currently I am able to help you with the following topics"
      }
    ],
    "actions":[
      {
        "type":"Action.Submit",
        "title":"Encryption",
        "data":{
          "value":{
            "value":"encryption"
          }
        }
      },
      {
        "type":"Action.Submit",
        "title":"Document Classification",
        "data":{
          "value":{
            "value":"classification"
          }
        }
      },
      {
        "type":"Action.Submit",
        "title":"Tools for experts",
        "data":{
          "value":{
            "value":"tools"
          }
        }
      }
    ],
    "type":"AdaptiveCard",
    "version":"1.0"
  }
}```
```

The created webhooks should look like this:
![grafik](https://user-images.githubusercontent.com/30929452/155279170-994aa5ab-8d39-49f2-a001-8a8eb14d3f28.png)

**Comment by anishprasad01** [comment] 2022-02-25 21:40
It looks like the issue is located in the Webex adapter. Unfortunately, adapters previously integrated with the SDK, like Webex, have been deprecated as of **February 7th, 2022**. Their ownership has been transferred to the [BotBuilder-Community](https://github.com/BotBuilderCommunity/) for continued support. You may wish to open a new issue in the appropriate community repository for additional support.

**Closed by anishprasad01** 2022-02-25 21:40 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
