### ISSUE TITLE
Multi language responses not showing up in certain languages

### ISSUE THREAD

**Issue by jelleDK** [microsoft/BotFramework-Composer#9269] opened 2022-06-29 08:57 UTC
## Describe the bug
I'm currently developing a chatbot that is available in 4 languages. I started by adding all the responses in English (default language), now when I wanted to add the translation for the other languages (being Dutch, Spanish and Chinese). I noticed some of the responses that were used in English disappeared when trying to add the dutch translation.

## Version
Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create a new blank project
Add 4 languages (English default, Dutch, Spanish, Chinese simplified)
Create new dialog
Add response in new dialog
Try to add translation in another language in responses
Text disappears

## Expected behavior

Text should show in English to input the translated text

## Screenshots
![image](https://user-images.githubusercontent.com/57387033/176395860-c06b3919-d95d-4cad-94d8-0eb9bf6f98ea.png)
![image](https://user-images.githubusercontent.com/57387033/176395987-ccf01e6d-e0e2-4c17-afd4-2de6f72bd8bd.png)
![image](https://user-images.githubusercontent.com/57387033/176396066-0e354d81-54ec-4e08-863b-2407dcb33afc.png)
![image](https://user-images.githubusercontent.com/57387033/176396134-94e569fe-933e-4029-96f0-657b05c1ff09.png)

**Comment by stevkan** [comment] 2022-07-06 17:37
Duplicate of #9227. Closing and redirecting to that issue.

**Closed** 2022-07-06 17:41 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Needs-triage

**Comment by kcs-amityadav** [comment] 2022-07-07 11:27
I have same issue. I create bot using bot framework composer (selecting core both with Language) with two different languages (Hindi and English). But I can only run one language at a time selecting any one language from top of left corner.

![1](https://user-images.githubusercontent.com/79498615/177762660-7dffdb6b-eba3-417b-81f7-2f82707fe3ba.PNG)

I also need two working with MS team with multi language bot. Kindly find any solution with proper steps.
