### ISSUE TITLE
Tooltips for sidebar tabs

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3054] opened 2020-05-14 17:35 UTC
When you hover over the tabs in the left sidebar there's no tooltip so you have to click on each tab to see what it is. Minor nit but tooltips would be nice.

**Comment by cwhitten** [comment] 2020-05-24 23:18
This is addressed via the pull request here: https://github.com/microsoft/BotFramework-Composer/pull/2691

Closing as a dupe of an existing a11y ticket.

**Closed by cwhitten** 2020-05-24 23:18 UTC
Labels: Needs-triage, Type: Enhancement
