### ISSUE TITLE
[3/29 bugbash] Composer: create a bot project; dead end when trying to edit directory

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6601] opened 2021-03-30 19:54 UTC
Originally created in ADO by Jonathan Fingold
https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58573/

1. Create resource in Azure and click Open in Composer.
2. Create a bot in Composer from scratch.
3. In Create a bot project dialog, start to edit the location and attempt to use TAB to auto complete the path.
4. Error: end up at a dead end. See attached image.

![image](https://user-images.githubusercontent.com/17152540/113048095-fe9f4d80-9156-11eb-860c-c0d0d1ed73e4.png)

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by liweitian** [comment] 2021-04-07 06:55
Hi @Andrea-Orimoto, I cannot reproduce this on my side. And we do not have the functionality "use tab to auto complete the path". Did you see your hard disk file directory information in the create a bot project modal before you run into the bug?

**Comment by CharingJC** [comment] 2021-04-09 07:18
Hello issue owner, 

Please check the solution provided by #5454
Found a solution: in %userprofile%\AppData\Roaming\BotFrameworkComposer\data.json, inspect the storageConnections section. Both path and defaultPath must point to an exiting folder.
In my case, path pointed to a full pathname of a botproj file (maybe a bug in an older composer version). Deleting that line solved the problem.

https://github.com/microsoft/BotFramework-Composer/issues/5454

**Comment by liweitian** [comment] 2021-04-12 09:30
When user inputs a file path rather than a directory path, it may causes the above issue. Maybe this is the reason .It is fixed in #6733. 
To fix your problem @Andrea-Orimoto, like @CharingJC said,  change the data.json manually can solve the issue.

**Comment by liweitian** [comment] 2021-07-15 07:27
Already fixed in #6733

**Closed by liweitian** 2021-07-15 07:27 UTC
Labels: ABS Handoff, P1, Type: Bug
