### ISSUE TITLE
Unable to publish Azure bot though 'Import existing resources' alternative

### ISSUE THREAD

**Issue by amitabhuddi** [microsoft/BotFramework-Composer#8856] opened 2021-12-14 16:33 UTC
## Describe the bug
I am attempting to use existing resources and you are encountering the ENOTFOUND error while attempting to publish to a newly created Azure Bot. MS support has tried to help but it is a bug that needs to be investigated further than support team. 

## Version
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Chrome
- [x] Edge

## OS
- [x] Windows

## To Reproduce
1. Created an Azure Bot in the Azure Portal, along with the QnAMaker and LUIS services.
2. Opened the project in composer by clicking 'Open with Composer' 
3. Publish > Logged in through the cloud account 
4. Adding the profile in the alternate 'Import existing resources'
5. Added the script (copied below, added dummy names to some parameters to show which ones are same/added)
6. Click on 'Publish selected bots'
7. Error as shown in image below

## Expected behavior
After the publish, the both should be deployed to the environment and accessible through Azure portal

## Screenshots
1. ERROR - 
![image](https://user-images.githubusercontent.com/7301750/146045792-5864bf1f-0d3a-46ae-ba52-6b5a45f0c9b6.png)

2. SCRIPT - 
![image](https://user-images.githubusercontent.com/7301750/146039359-7c96d888-c0a5-4488-866f-f3d458fe619c.png)

(hostname and botName is same, & scmHostDomain is empty)

**Comment by dmvtech** [comment] 2021-12-20 17:09
hi @amitabhuddi A few questions:

- What is the OS of the App Service Plan that was created as part of the provisioning?
- What language is the bot (Dotnet/C# or Javascript/Node)?
- Is the account you are using part of more than one subscription and/or more than one tenant?

**Comment by amitabhuddi** [comment] 2021-12-22 15:19
hi @dmvtech, please see below - 
- What is the OS of the App Service Plan that was created as part of the provisioning?
Microsoft
- What language is the bot (Dotnet/C# or Javascript/Node)?
Dotnet/C#
- Is the account you are using part of more than one subscription and/or more than one tenant?
We have multiple subscriptions under one tenant.

**Comment by dmvtech** [comment] 2021-12-30 21:14
Thank you @amitabhuddi.

When you created the Azure Bot, did you create the type of app as `Multi Tenant` or `Single Tenant`/`User-Assigned Managed Identity`? You should be able to find this from the bot Configuration blade.

**Comment by dmvtech** [comment] 2021-12-30 21:50
Also:

> We have multiple subscriptions under one tenant.

Are all the LUIS and QnA resources in the same subscription as the Azure Bot?

**Comment by amitabhuddi** [comment] 2022-01-06 12:07
Hi @dmvtech,

- When you created the Azure Bot, did you create the type of app as Multi Tenant or Single Tenant/User-Assigned Managed Identity? = Multitenant (also this is something i cannot change in the configuration so i am assuming it is created by default)
- Are all the LUIS and QnA resources in the same subscription as the Azure Bot? = Yes that's correct

**Comment by carlosscastro** [comment] 2022-01-24 18:54
@dmvtech could you please follow up on this issue?

**Comment by amitabhuddi** [comment] 2022-01-27 12:17
Hi Dana, @dmvtech, could you please help me give update on progress of this issue? If there is any other info needed from my end or we need to book a call to try the solution, I am happy to do that. Thanks

**Comment by amitabhuddi** [comment] 2022-01-27 17:19
> Also:
> 
> > We have multiple subscriptions under one tenant.
> 
> Are all the LUIS and QnA resources in the same subscription as the Azure Bot?

Yes they are

**Comment by dmvtech** [comment] 2022-01-28 18:48
I'm investigating. I will update later today. I'll let you know if I need anything further. Thank you for the offer.

**Comment by dmvtech** [comment] 2022-01-28 23:22
@amitabhuddi I am unable to reproduce this. There are some deploy zip issues, but those only happen on Linux runtime hosts. 

Can you please share the full publishing log? You can find it by expainding the publish status line and then clicking `View log`. 
![image](https://user-images.githubusercontent.com/43397658/151634855-ee60736b-999c-46b5-bfff-f3cd7e9819ea.png)


Please remove/sanitize all personal and sensitive info (IDs, etc) before adding here.

**Comment by amitabhuddi** [comment] 2022-01-29 20:55
hi @dmvtech, please see the below screenhot, i do not have any option to expand the publish status line, all i see is the following in the message column.

![image](https://user-images.githubusercontent.com/7301750/151677239-5eec0c8d-9589-415c-8878-5ff6a72cbcbc.png)

**Comment by dmvtech** [comment] 2022-01-31 17:55
@amitabhuddi You cannot scroll further to the right?

**Comment by amitabhuddi** [comment] 2022-01-31 18:13
> 

no @dmvtech, that's all I see on my screen, cannot double-click or right-click. I am using 2.1.1 version of the composer if that helps, in the latest version of the composer - I cannot log in to my company azure account thus I needed to switch back to 2.1.1 version. 

![image](https://user-images.githubusercontent.com/7301750/151849316-62248b6b-1abc-437d-98e7-49bc98d51183.png)

**Comment by dmvtech** [comment] 2022-02-01 23:54
You may have to maximize the window before you see it. Can you please try that?

**Comment by dmvtech** [comment] 2022-02-07 23:10
hi @amitabhuddi Were you able to find the full log by maximizing the Composer window?

If not, can you please run Composer in debug mode using the following directions, then do the publish again to reproduce the failure. Then send the output of the debugging console window.



- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

**Comment by amitabhuddi** [comment] 2022-02-09 17:53
Hi @dmvtech, please see below -,
---
"Accepted for publishing..."
---
---
"Abs settings incomplete, skip linking bot with webapp ..."
---
---
"appPasswordHint incomplete, return ..."
---
---
"Building the bot app..."
---
---
"Build succeeded!"
---
---
"Creating build artifact..."
---
---
"Build artifact ready!"
---
---
"Publishing to Azure ..."
---
---
"Uploading zip file... to ABC-azure-bot"
---
---
"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: getaddrinfo ENOTFOUND ABC-azure-bot.scm.azurewebsites.net\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\\\",\\\"message\\\":\\\"getaddrinfo ENOTFOUND ABC-azure-bot.scm.azurewebsites.net\\\",\\\"code\\\":\\\"ENOTFOUND\\\",\\\"config\\\":{}}\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\XYZ\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269072:25)\\n    at createCustomizeError (C:\\\\Users\\\\ XYZ \\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269077:10)\\n    at BotProjectDeploy.deployZip (C:\\\\Users\\\\ XYZ \\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269593:13)\"}"
---
---
"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). {\"stack\":\"Error: getaddrinfo ENOTFOUND ABC-azure-bot.scm.azurewebsites.net\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\",\"message\":\"getaddrinfo ENOTFOUND ABC-azure-bot.scm.azurewebsites.net\",\"code\":\"ENOTFOUND\",\"config\":{}}"
---

**Comment by dmvtech** [comment] 2022-03-03 23:40
@amitabhuddi This looks exactly like the issue [here](https://github.com/microsoft/BotFramework-Composer/issues/8890).

Can you please confirm the following:

- In your Azure portal for the resource group that contains this bot; find the resource of type `App Service Plan` that was created by Composer.
- Go into the overview blade and verify that it says `Operating System : Windows` and **_not_** Linux:
![image](https://user-images.githubusercontent.com/43397658/156671454-81da014f-e11b-401c-a036-c77d47d5f579.png)

**Comment by amitabhuddi** [comment] 2022-03-07 20:24
@dmvtech, I confirm that the `App Service Plan` is 'windows' as OS. 

Just a clarification - I created the `App Service Plan` manually in the Azure Portal and then used it in the composer script (also, that was the whole point with this issue that it is not allowing me to publish the bot using Composer with the resources created through Azure Portal and then trying to publish through the script option). Script option is using 'Publishing profile' through 'Import existing resources' and using the script format that I have added at the beginning of the issue. 

Please let me know if you have more questions or clarifications.

**Comment by dmvtech** [comment] 2022-03-16 23:53
Hi @amitabhuddi Can you please follow the steps here and send the logs from the console output:

- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

Reproduce the error and send the output from that console window. You will know that it has been activated correctly once you start to see messages in the log that are prefixed with `composer:`.

**Comment by amitabhuddi** [comment] 2022-03-25 12:43
Hi @dmvtech,

Please see the attached file for the log. 
Apologies for the delay. Thanks

[LogGithub.docx](https://github.com/microsoft/BotFramework-Composer/files/8350584/LogGithub.docx)

**Comment by dmvtech** [comment] 2022-04-01 21:06
hi @amitabhuddi Do you have any sort of firewall or antivirus that could be causing an issue? There was another issue where customer running Netskope caused a similar problem (`/api/auth/getTenants 500 `).

**Comment by dmvtech** [comment] 2022-04-14 18:45
Hi @amitabhuddi Can you please confirm/deny if you are using any sort of firewall or antivirus? If so, are you able to test without those for troubleshooting purposes?

**Comment by amitabhuddi** [comment] 2022-04-20 15:44
Hi @dmvtech, I have to be behind the firewall through VPN so I don't have the option there in order to use the Azure services to publish the bot through Composer. Antivirus should not be a problem. Apologies for the late response, we were trying some options for this problem internally.

**Comment by dmvtech** [comment] 2022-05-03 23:41
Hi @amitabhuddi My own apologies for the delay. Are you able to look at firewall/VPN logs to see what might be blocking it? It appears that the address isn't found or accessible. Not sure we can do anything from this end.

**Comment by amitabhuddi** [comment] 2022-05-10 10:19
Hi @dmvtech - the IT chain for allowing me to take a look at logs for the firewall is not very bright. Please suggest if we can do something else. 
@LuwkasLima - thanks for sharing, regarding "... if I can deploy a composer bot using AZ CLI ("az webapp deployment source config-zip...")" - Our company policy blocked me to perform this action but if that's not an issue for u (i.e. personal account), try that. 

If it helps - I used the Direct Line App Service extension to publish the bot as a workaround for not using Composer for now (given that the resources are created in Azure Portal beforehand and all the config parameters are set as per guide).

**Comment by LuwkasLima** [comment] 2022-05-10 12:48
Hi folks,

If you follow my debug steps above, you will notice that the issue is clearly not related to the 403 forbidden response in the debug logs. The error message stated is a DNS resolving issue.

@amitabhuddi thanks for sharing the Direct Line suggestion. I actually found out by debugging the deployment process that the zip build package is actually created, so I just deployed the zip file using AZ CLI, and it's now working.

**Comment by dmvtech** [comment] 2022-05-12 23:10
Glad you got it working via cli @LuwkasLima. As you have found, that is a valid workaround/approach. 

@amitabhuddi I'm glad you have a workaround as well. I'll continue investigation to see if there is anything further we can do to troubleshoot.

**Comment by dmvtech** [comment] 2022-06-02 17:28
Hi @amitabhuddi 

Can you confirm the issue still happens if you enable the nightly build (Early Adopters setting)?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/43397658/171688739-753c7473-f73a-49a5-8867-2bd06814c3fe.png)

**Comment by dmvtech** [comment] 2022-06-13 21:42
Closing due to lack of response. If you are still experiencing this issue, please comment and we reopen.

**Closed by dmvtech** 2022-06-13 21:42 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to

**Comment by Tarun7898** [comment] 2023-02-23 04:23
hi guys, i am facing this same issue while publishing my code and uploading zip file though composer @dmvtech please help on this same issue @amitabhuddi let me know how you have fix this issue rest all the details are same except i am using node js.

1. What is the OS of the App Service Plan that was created as part of the provisioning?
	Microsoft
2. What language is the bot (Dotnet/C# or Javascript/Node)?
	NodeJs
3. Is the account you are using part of more than one subscription and/or more than one tenant?
	We have multiple subscriptions under one tenant.
4. Operating System : Windows
5. type of app as Multi Tenant

<img width="181" alt="image" src="https://user-images.githubusercontent.com/49971161/220820845-e6e2cfbc-c990-4b48-b44b-da0682d02985.png">

**Comment by ramfattah** [comment] 2023-08-23 01:27
Thanks reaching out @Tarun7898, 

I was not able to reproduce this issue when trying to publish both C# and NodeJS Composer bots using the "Import existing resources" options to Azure App Service (Windows OS).

Here is what I manually provided for my publishing configuration in Composer:
```json
{
  "name": "myAzureSubscriptionName",
  "environment": "dev",
  "tenantId": "e73*****-**e7-4**e-****-ece*****70*9",
  "hostname": "ramcomposernodepublish",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "RamLabRG",
  "botName": "RamSDKBot",
  "subscriptionId": "634*****-****-****-****-********f302",
  "region": "East US",
  "appServiceOperatingSystem": "windows",
  "scmHostDomain": "",
  "luisResource": "",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "",
      "connectionString": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "",
      "endpoint": ""
    },
    "MicrosoftAppId": "********-8f18-41e0-*****-*******",
    "MicrosoftAppPassword": "qij8Q~Lxtr**********Hcdus"
  }
}

```


Properties I added values:
* name (azure subscription name)
* tenantId
* hostname (App service name)
* resourceGroup
* botName
* subscriptionId
* region (resource group region)
* MicrosoftAppId
* MicrosoftAppPassword

![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/cc2123b6-ca42-4093-a2ca-90ea787e681e)
