### ISSUE TITLE
Bot Framework Composer not updating properties until end of dialog (to prevent Adaptive Card double submits)

### ISSUE THREAD

**Issue by filcole** [microsoft/BotFramework-Composer#7832] opened 2021-05-14 15:30 UTC
## Describe the bug

1. Properties are not updated until a trigger has been completed.  

Example:

1. Set 'conversation.selectionMade' = false
2. Adaptive card is shown to the user. They chose the option to get a "Random Word"
2. The adaptive card button press fires a 'Message activity received' trigger
3. We set check if 'conversation.selectionMade' = false, if so
      a. set 'conversation.selectionMade' = true
      b. Call slow HTTP API call to fetch a random word
      c. Display random word to user
  else
      a. Display 'You've already had a random word' to the user

## Version

1.4.1

## Browser

n/a - Testing in BFC and Bot Framework Emulator

## OS

- [X ] Windows

## To Reproduce

Steps to reproduce the behaviour:

1. Download and unzip the attached Bot 'AdaptiveCardSinglePress.zip' and open in Bot Framework Composer
2. Start bot, start bot framework emulator
3. Select "Get Random Word" in adaptive card dropdown, and press 'Submit'
4. Press 'Submit' a couple more times quickly in succession
5. You will incorrectly multiple Random Words
6. Wait 10 seconds, for all API calls to resolve
7. Press 'Submit'
8. You will correctly get 'You’ve already got a random word'

## Expected behavior

I expected using 'Set Properties' or 'Set Property' action to update the variable immediately and be accessible by other triggers.

## Screenshots

![image](https://user-images.githubusercontent.com/6078398/118293470-9a033c80-b4d1-11eb-94c4-a8a63f62221b.png)

## Additional context

[AdaptiveCardSinglePress.zip](https://github.com/microsoft/BotFramework-Composer/files/6479726/AdaptiveCardSinglePress.zip)

**Comment by filcole** [comment] 2021-05-14 15:31
[AdaptiveCardSinglePress.zip](https://github.com/microsoft/BotFramework-Composer/files/6479724/AdaptiveCardSinglePress.zip)

**Comment by ninggao** [comment] 2021-05-17 18:13
@cwhitten Could you please take a look at this issue?

**Comment by srinaath** [comment] 2021-05-18 18:56
@filcole 
This is by design. Essentially, while the previous dialog is processing, any variables that are set are persisted only after the dialog is completed processing. A couple of solutions thanks to @EricDahlvang but unfortunately a bit more work

1. https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp. Leveraging cosmos db for storage in your bot. This would mean the key values you write can be leveraged immediately.

2. In Composer 2.0, we have moved to the package model https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Components.Storage. You could persist this value in a storage and read from it by leveraging this package.

@Stevenic Any other ideas to approach this ticket?

**Comment by ninggao** [comment] 2021-05-19 18:15
@cleemullins @srinaath needs help on SDK side for this issue. Could you please take a look at this issue, and let me know who can better help him? I add you to the assignees for now to keep track of it.

**Comment by srinaath** [comment] 2021-05-19 18:38
Just an update on this ticket. I tried using the Storage package from community repo. I keep facing an error. https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/403

**Comment by stevkan** [comment] 2021-06-03 00:37
@srinaath, I am also getting the same error when attempting to use the Storage package. I have tried previous versions, including preview, but with no luck.

As for option #1, I am able to pass the state values into Cosmos however, at this moment, it doesn't appear to be making a difference in functionality or flow. @dmvtech and I are testing an idea or two around this. I will update this thread when I know more.

**Comment by stevkan** [comment] 2021-06-03 20:12
@filcole, which client is it that you intend to use? If you are using Web Chat, an idea that was floated is to disable the adaptive card button after it has been pressed. This is an option in Web Chat thru the client. If Teams (or any other channel that supports UpdateActivity) then the activity can be modified to disable the button.

I'm a little less confident about the latter UpdateActivity option as it is dependent on the bot receiving the initial click event and issuing an update. Where multiple clicks are occurring back-to-back, this may not mitigate the issue.

Another option is to create a [custom action ](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) in the exported runtime and insert that in between the parent and child dialog to save state. The idea being the property will then save mid-conversation. In this case, the property check in the trigger could be moved to a separate dialog that is called from the trigger. The `conversation.selectionMade` value would save just before the new dialog would run. If the value is false, then the new dialog would call HttpRequest. If it is true, then it would end the turn.

**Comment by filcole** [comment] 2021-06-04 07:57
@stevkan, thanks for the suggestions.  I'm using WebChat provided by the CDN here: https://cdn.botframework.com/botframework-webchat/latest/webchat.js.

I like the idea of disabling the adaptive card buttons since it provides user feedback.  I haven't seen any examples of how to do that whilst using the CDN provided WebChat, only the ideas floated here: https://github.com/microsoft/BotFramework-WebChat/issues/1427 especially this example: https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/05.custom-components/l.disable-adaptive-cards/index.html

Do you think it is possible using the CDN webchat?

**Comment by stevkan** [comment] 2021-06-14 17:47
Hi @filcole, please accept my apologies. I know I had typed up a response but it looks like I never hit the 'comment' button. Yes, it is absolutely possible to to do the above using Web Chat's CDN. I have it set up in my test instance of Web Chat and I have yet to have an issue with it that I can recall.

As you can see in the image, the unselected buttons are grayed out after an action occurs.

![image](https://user-images.githubusercontent.com/18403946/121935861-cd69fe80-ccfd-11eb-8b97-912bcd8dadaa.png)

**Comment by stevkan** [comment] 2021-06-22 21:31
Closing issue as resolved.

**Closed by stevkan** 2021-06-22 21:31 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported
