### ISSUE TITLE
Need to do a pass at toolbar menus and buttons: consistent, context sensitive

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3356] opened 2020-06-08 23:14 UTC
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment] 2020-06-25 16:43
Duplicate of #3494

**Closed** 2020-06-25 16:44 UTC
Labels: UX Design
