### ISSUE TITLE
App create failed after 3 retries. Error: Request failed with status code 403

### ISSUE THREAD

**Issue by zaheedk** [microsoft/BotFramework-Composer#8633] opened 2021-09-05 00:14 UTC
Hi,

I am trying to publish my bot from the composer using the option Create New Resources. I have selected my subscription, resource group, and chose Windows as target operating system. When I click on next to proceed, it fails with the error message **App create failed.**

The accoun that I am using to log into Azure is administrator with all privileges. I am able to create resources manually in Azure through the portal. 

I was able to create resource one time. After that it is failing for all projects.

Can you please advise what the issue is.
```
{
  "profileName": "Publish",
  "jobId": "800d3e2b-a1ac-407d-b00f-c8dfbe3cf2ec",
  "projectId": "72401.44671572401",
  "time": "2021-09-05T00:08:54.145Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: XXXXX at centralus",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed after 3 retries. Error: Request failed with status code 403",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269071:25)\\n    at createCustomizeError (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269076:10)\\n    at BotProjectProvision.createApp (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:270566:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269071:25)\\n    at createCustomizeError (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269076:10)\\n    at BotProjectProvision.createApp (C:\\\\Users\\\\OEM\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:270566:17)\"}. See provision.Publish.log in your bot folder"
  ]
}
```

**Comment by dmvtech** [comment] 2021-09-06 17:59
This appears to be a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/8283

Please follow and comment on that thread for resolution.

**Comment by zaheedk** [comment] 2021-09-07 07:38
Hi Dana,

Issue #8283 refers to assigning application administrator and application developer roles to the user that is publishingthe app, which I have already done and inspite of that it did not solve the issue. This issue is still happening when I am trying to a create a new publish profile.

Plesae advise on next steps.

Thanks
Zaheed

**Comment by dmvtech** [comment] 2021-09-09 16:45
HI @zaheedk 

After checking internally, it does appear that these are most likely the same issue/root cause.  I will be closing this again as a duplicate, with the assumption that it is. Please monitor the other issue for progress. Once a solution/fix is discovered, please determine if it is applicable to your situation as well.

In the meantime, if you can answer these questions, it might help us in our discovery:

- Does this happen every time you provision?
- What type of account are you using? Is it a work, school, or Microsoft account?
- What is your "role" for the subscription you are using? You can find this by looking up your subscriptions in the Azure Portal.
- Are you creating a new resource group or updating an existing one?
- When the provision fails, what is the result in Azure Portal? What resources were successfully created?
- If the App Registration is successfully created, navigate to it in the Azure Portal. In the left side panel of the App Registration, select Authentication. Check if there are any restrictions under "Supported Account Types".

@natalgar @GeoffCoxMSFT @cwhitten

**Closed by dmvtech** 2021-09-09 16:45 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
