### ISSUE TITLE
example CI/CD pipeline for azure devops/github actions

### ISSUE THREAD

**Issue by sowsan** [microsoft/BotFramework-Composer#5581] opened 2021-01-21 22:16 UTC
Is there an example for CI/D pipeline..?

https://github.com/microsoft/BotFramework-Composer/tree/main/runtime/dotnet/azurewebapp/Scripts

Reading the above readme says we can readily use the script but in our case we have to use a CI pipeline to just build the web project and publish the artifacts. In the CD use that published zip file to Azure web app. Provided script is baked with everything in it also it has a dependency with the entire source code folder structure. 

A working sample for reference would be very helpful. Thanks!

![image](https://user-images.githubusercontent.com/11544153/105419544-e36f0980-5c0c-11eb-9573-43316c6cf505.png)

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-cicd-chatbot

**Comment by cwhitten** [comment] 2021-01-27 16:59
Hello @sowsan - i'll close this issue as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3339

See https://github.com/microsoft/BotFramework-Composer/issues/3339#issuecomment-754234795 for the latest updates, and we'll use that ticket to track and report updated progress.

**Closed by cwhitten** 2021-01-27 16:59 UTC
