### ISSUE TITLE
Building bots with LUIS and Qna fails

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4970] opened 2020-11-24 20:53 UTC
## Describe the bug
- Create a bot from the Todo LUIS template
- Add a Qna kb action using "Add new knowledge base" context menu to the main dialog
- Start the bot

![Screen Shot 2020-11-24 at 12 46 36 PM](https://user-images.githubusercontent.com/13004779/100150066-f0ad8900-2e53-11eb-9ae8-cbbee2dfbed2.png)

@boydc2014 who is the right person to take this task?

**Comment by srinaath** [comment] 2020-11-24 21:06
@zhixzhan i think you might know whats going on here

**Comment by zhixzhan** [comment] 2020-11-25 03:45
@srinaath I have try the latest feature/botprojects and main branch, both can't repro this error. Did you modify the lu content after create from `Todo Luis Template` bot.

**Comment by luhan2017** [comment] 2020-11-25 06:31
Synced with Srinaath, we've successfully reproduced this issue. The issue is a corner case which is because there is an special qna question in the qna file. 
```
What does const [thing, setThing] = useState() mean?
```
If we enable both luis and qna, it will crosstrain the content and the question above will be listed under DefertoQnA intent.

And our lu cli failed to parse this utterance, assigning to Fei to investigate whether we can fix it in the cli side.

**Comment by feich-ms** [comment] 2020-11-25 06:56
Tried this special utterance and actually it is not permitted by luis. The optional fix is to remove all patterns in crosstrained results when doing cross-training. Created a ticket in cli https://github.com/microsoft/botframework-cli/issues/1064 to track it. Since this is a very special corner case, so the fix in cli will target R12.
![image](https://user-images.githubusercontent.com/43032123/100192434-e8754c80-2f2c-11eb-8eac-6b61c8ccc349.png)

**Comment by luhan2017** [comment] 2020-11-25 10:42
@cwhitten @srinaath , this is not a composer issue, should we remove 1.3 label on this?

**Comment by srinaath** [comment] 2020-11-25 16:49
@feich-ms @luhan2017  yep let's close the ticket. Great catch to find an issue with the kb content.

**Closed** 2020-11-30 02:20 UTC
Labels: 1.3, BotProjects, Type: Bug
