### ISSUE TITLE
QNA Subscription key - Sorry, something went wrong with publishing. Try again or exit out of this task.

### ISSUE THREAD

**Issue by saiteja21** [microsoft/BotFramework-Composer#4814] opened 2020-11-14 10:01 UTC
Sorry, something went wrong with publishing. Try again or exit out of this task.

Qnamaker build failed: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource. 

By default the region value is set to "westus" - may be that's the reason why I am not able to use the QNA Subscription Key, **_how to change this default region value?_**

![image](https://user-images.githubusercontent.com/11377131/99144685-d397df80-2635-11eb-89ba-48f3eaca4bc4.png)

Also, I tried creating a QNA maker resource in westus, but I do get the option to create the QNA resource in **westus**, so I created in **australiaeast**. 

![image](https://user-images.githubusercontent.com/11377131/99144704-148ff400-2636-11eb-84dc-2b0a2e2f1339.png)

**Comment by saiteja21** [comment] 2020-11-14 10:15
Though I have changed the region value in setting... 

![image](https://user-images.githubusercontent.com/11377131/99144927-2ffbfe80-2638-11eb-883b-c6b1367c7d8e.png)


But nothing changed... I am still getting the same error and below value does not change 

![image](https://user-images.githubusercontent.com/11377131/99144949-65a0e780-2638-11eb-987a-a742080479ac.png)

**Comment by hibrenda** [comment] 2020-11-16 13:31
Thanks to report the issue. Yes. This is by design so far. we only support west-us.  We will support other region later.

**Comment by mrivera-ms** [comment] 2020-11-16 19:08
@hibrenda do we know when additional regional support will be available?

**Comment by saiteja21** [comment] 2020-11-17 12:14
@hibrenda If I do not have access to create a QNA maker service in westus what should I do? [I have a region restriction on my subscription]

funny thing is, it shows these options :/ 
![image](https://user-images.githubusercontent.com/11377131/99388897-3ee6e900-28a4-11eb-9620-a70adeb700b5.png)

Hope we get a quick resolution!

**Comment by hibrenda** [comment] 2020-11-23 03:01
@saiteja21 As the region support for QnA is in preview version, so no quick workaround in short term. we will evaluate the solution both from features and quality. Stay tuned.

**Comment by hcyang** [comment] 2020-12-06 19:12
Hi @hibrenda, any update on backlogging or a planned fix? Please take an action and drive to close this issue. Thanks.

**Comment by hibrenda** [comment] 2020-12-08 07:23
We plan to support new region authoring for QnA in R12.

**Closed** 2021-11-23 15:34 UTC
Labels: customer-reported, Bot Services, customer-replied-to, feature-request
