### ISSUE TITLE
Can't use personal Azure subscription?

### ISSUE THREAD

**Issue by GraemeMalcolm** [microsoft/BotFramework-Composer#9103] opened 2022-04-06 23:22 UTC
Not sure if this is a bug or by design, but I can't seem to deploy a bot to Azure by signing in with a _personal_ Azure subscription - I'm prompted to use a school or work account. Same thing happens if I follow the tutorial instructions to create an Azure Bot in the portal and then open it in Composer (I can create the bot resource, but get prompted to sign in when opening a new composer project for it, and using a personal Azure subscription fails) 
![image](https://user-images.githubusercontent.com/11771134/162089598-b565ed4d-0d09-4990-b8f2-939afe41f6bd.png)

**Comment by dmvtech** [comment] 2022-04-08 21:07
Hi @GraemeMalcolm 

I'm not quite sure, but it _might_ be due to the permission that a personal account has on the subscription/tenant, more than the fact that it *is* a personal account. I myself use a personal account with a (MSDN) subscription. I'm not aware of a **_personal_** subscription. Do you mean `pay-as-you-go`?
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/switch-azure-offer

- What permissions does that account has on both the tenant & subscription? 
- Are you able to roll back to v`2.1.1` and verify that it occurs there as well? (there are some other publishing bugs in 2.1.2 that are yet to be fixed and I want to rule those out)

**Comment by GraemeMalcolm** [comment] 2022-04-08 21:15
This also an MSDN subscription, for which my login is the admin. The error is specifically indicating that I can't sign in with a personal account - it must be a school or work account.
I got the same error in previous versions of the Bot Composer, going back to 1.x.
I'll try spinning up a new trial subscription and see if that works.

**Comment by GraemeMalcolm** [comment] 2022-04-08 21:48
Just tried with a totally different outlook.com account, signing into an Azure sub for which the account is a global admin - same result.

**Comment by dmvtech** [comment] 2022-04-20 23:23
Thanks @GraemeMalcolm We have identified a bug which might be the cause of this issue as well. Stay tuned.

**Comment by dmvtech** [comment] 2022-05-06 21:00
Update: We've identified patterns though which we can reproduce this; engineering is working to identify a workaround or product improvement that would mitigate this issue. We don't yet have an ETA.

**Comment by dmvtech** [comment] 2022-05-23 23:47
Still investigating. Thank you for your patience.

**Comment by dmvtech** [comment] 2022-06-13 23:14
Hi @GraemeMalcolm 

Apologies for the delay. The aforementioned bug is likely not related. Can you please grab extended logging and then reproducing the error:

- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

Send the output from the terminal.

**Comment by dmvtech** [comment] 2022-06-24 21:46
Closing as unable to reproduce and we do not have additional logging to troubleshoot. If you still need assistance, please supply the requested logging information and we can reopen.

**Closed by dmvtech** 2022-06-24 21:46 UTC
Labels: customer-reported, Bot Services, customer-replied-to
