### ISSUE TITLE
[Accessibility][Keyboard - Open]: Navigation within table is not performed using up/down arrow keys.

### ISSUE THREAD

**Issue by ShellySoni** [microsoft/BotFramework-Composer#2067] opened 2020-02-24 11:14 UTC
**User Experience:**
For keyboard users it is difficult to perform the task if any control does not perform its functionality.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. "Bot Framework Composer" homepage will gets opened.
3. Navigate to "Open" button and activate it.
4. 'Select a Bot' dialog gets opened.
5. Navigate within the table using up/down arrow keys and observe the issue.

**Actual Result:**
Navigation within table is not performed using up/down arrow keys. When user press down arrow key to navigate to next row, then either the table gets refreshed & focus shifts to another control or new page gets opened.

**Note:**
1. Same issue is repro within: Save >Define conversation objective table.
2. Select 'Notification' from left navigation bar, when focus reach on table 1st column & press down arrow key, the new page gets open, which is incorrect and when user press 'Enter' key on error, then also nothing is happened. (Refer: Attachment: Functional_Notfication_error)
3. Sorting is also not performed.

**Expected Result:**
Navigation within table is not performed using up/down arrow keys. When user press down arrow key to navigate to next row, focus should land to next row rather than refreshing the table and new page to open.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%202.1.1%20%E2%80%93%20Keyboard.docx?d=w1f29acf9a3e7414fbd8d7e3598d877bb&csf=1&e=LSJeSF

**Attachment:**
[MAS2.1.1_ Table.zip](https://github.com/microsoft/BotFramework-Composer/files/4244259/Functional_.Table.zip)
[MAS2.1.1_Notfication_error.zip](https://github.com/microsoft/BotFramework-Composer/files/4265748/Functional_Notfication_error.zip)

**Comment by corinagum** [comment] 2020-02-25 18:00
Can we also add the severity label to this issue?

**Comment by beyackle** [comment] 2020-04-08 23:02
Double-checked this, and this is both repro-able and highly annoying. Our FileSelector code needs some work, so I'll take this on next.

**Comment by corinagum** [comment] 2020-04-09 22:47
![image](https://user-images.githubusercontent.com/14900841/78947101-54c43e00-7a79-11ea-843a-bc2aff9aca5d.png)

Since selecting is now a double click (thank you thank you), I think the modal will also need a 'next' button for an intuitive UX.

**Comment by corinagum** [comment] 2020-04-09 22:52
Hm actually that raises up a bunch of other UX issues. I'm going to file a new one, unrelated to a11y. Thoughts?

**Comment by corinagum** [comment] 2020-04-09 23:59
File here: https://github.com/microsoft/BotFramework-Composer/issues/2594

**Comment by ashish315** [comment] 2020-05-01 04:57
As checked the issue is resolved, so closing the bug.

**Closed by ashish315** 2020-05-01 04:57 UTC
Labels: A11yCT, A11yMAS, A11yMediumImpact, Accessibility, Fixed, HCL- BotFrameworkComposer, MAS2.1.1, Severity3
