### ISSUE TITLE
Templates and NPM packages not working from enterprise network

### ISSUE THREAD

**Issue by Dan-Bai** [microsoft/BotFramework-Composer#8188] opened 2021-06-24 14:33 UTC
To start off, I am build Bots with Bot Composer from within my company's network. We have a jfrog artifactory with a mirror of NPM packages.

When starting a new bot with bot composer, only the "Core Bot with QnA Maker" template is available for both C# and Node.

With a node project, when accessing package manager I am getting an error "Could not load feed from URL" which is expected since the url is blocked by company firewall. However, adding a new feed with the internal NPM registry, the browse section shows up as blank.

**Comment by benbrown** [comment] 2021-06-29 17:29
@Dan-Bai - When you add your feed, did you specify any sort of filter on it? By default, Composer will only show packages tagged "msbot-component" 

Are you using an npm *search endpoint*, or a static feed url?

**Comment by jmyers82** [comment] 2021-06-29 18:25
I am seeing the same result in terms of what templates I see from inside an enterprise network. no filter applied.

**Comment by benbrown** [comment] 2021-06-29 20:13
@jmyers82 so do you mean you are not experiencing the same problem as @Dan-Bai?

**Comment by jmyers82** [comment] 2021-06-30 19:06
I AM experiencing the same issue.  I only see 1 template when starting the bot from inside an enterprise network. my GUESS is that there is a directory in a repo somewhere that it will pull these templates from and our proxy or firewall is blocking it?

**Comment by benbrown** [comment] 2021-06-30 19:22
@jmyers82  - The templates and packages are pulled in from NPM and Nuget via feeds.  Do you have access to npm from inside our firewall?

**Comment by jmyers82** [comment] 2021-06-30 19:28
okay thats good to know. do we know all of the packages that are required?  so we can have those opened up on our end.  Thanks.

**Comment by benbrown** [comment] 2021-06-30 19:35
Templates are pulled from NPM using a feed URL like this:
https://registry.npmjs.org/-/v1/search?text=generator+keywords:bf-template+scope:microsoft

It then pulls down the appropriate generator based on your selection and creates the project.

For components in package manager, we use similar feeds.  For C# components, we use the Nuget search API:
https://api.nuget.org/v3/index.json

And for JS, we use NPM:
https://registry.npmjs.org/-/v1/search

Allowing access to these URLs would be a start - that would at least allow composer to load the content. You may need to open additional access for the component packages to be downloaded from those package repos. Please let me know!

**Comment by jmyers82** [comment] 2021-06-30 19:51
Perfect.. I will get our folks working on that. To be clear... there is no way in bot framework composer yet to tell it which repository to point to right?  e.g. we have our own artifactory where we could get packages from, but bfc (bot framework composer) by default looks at nuget.  we can't control that yet?

**Comment by benbrown** [comment] 2021-07-07 16:03
@jmyers82 you can specify alternate feed sources for the *package manager* inside Composer, but not yet for the *new bot templates* that appear during the creation flow.

**Comment by Brent-Higgins** [comment] 2021-07-13 17:07
@benbrown in using our internal artifactory npm mirror I have run into an issue.
![image](https://user-images.githubusercontent.com/87079486/125494963-ab630908-deaf-4160-836b-cd9105de6be0.png)
It looks to be tied to the fact that the search result from artifactory does not contain the links field which is not null checked.
https://github.com/microsoft/BotFramework-Composer/blob/2.0.0/extensions/packageManager/src/node/feeds/npm/npmFeed.ts#L69
When I took the json from the npm search add added dummy link sections and hosted the json locally I was able to get composer to install packages.

**Comment by taicchoumsft** [comment] 2021-07-26 18:17
Closing due to resolution.

**Comment by benbrown** [comment] 2021-07-27 15:32
Thanks for identifying the root cause, @Brent-Higgins. I will open a PR including this fix.

**Comment by pavolum** [comment] 2021-08-05 00:04
@Brent-Higgins @jmyers82  @Dan-Bai 



Couple questions for you 
- Can your Jfrog aritifactory be indexed similar to how the npm registry can be indexed  (i.e. [sample registry api call](https://registry.npmjs.org/-/v1/search?text=generator+keywords:bf-template+scope:microsoft))
  - @Brent-Higgins your screen shot above seems to indicate this is the case with the url `http://repo1.uhc.com/artifactory/api/npm/nvirtual/-/v1/search`
- What happens if you are working on a node project that has other node dependencies and you run `npm install`? will this also fail if the dependency is not in your Jfrog artifactory as well?
- What happens if you are working on a dotnet project that has nuget dependencies and you run `dotnet restore`? will this fail if the nuget dependency is not in your jFrog artifactory? 

Please check out this [issue](https://github.com/microsoft/BotFramework-Composer/issues/8525) where I have outlined a potential workaround to unblock users between now and when the patch release with the solution is shipped.

**Comment by Dan-Bai** [comment] 2021-08-05 16:36
@pavolum 

* It is indexed in a similar fashion. When we search, the response doesn't contain "links" property but otherwise it looks similar to your sample api call.
* If he dependency is not in our Jfrog artifactory then it will fetch from public. However, we can only talk to the Jfrog artifactory.
* I believe dotnet is the same, however we don't have any dotnet projects on the team so I can't speak from experience.

**Comment by benbrown** [comment] 2021-08-16 20:52
The ability to specify an alternate feed URL for templates will be introduced when this PR is merged: #8553 

This should resolve the problem regarding sourcing templates directly from NPM.

**Closed** 2021-08-18 19:43 UTC
Labels: customer-reported, Bot Services, customer-replied-to
