### ISSUE TITLE
No runtime version available when ejecting bot runtime

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3443] opened 2020-06-20 14:24 UTC
## Describe the bug

When trying to eject the bot runtime, no runtime version is available to select. The runtime versions field is empty.
Since the selection is not available, the runtime cannot be ejected, which blocks (amongst others) creating custom actions.

## Version

![image](https://user-images.githubusercontent.com/23324404/85203962-6f385480-b311-11ea-986c-b52fe8e20455.png)

The issue is producing in a nightly build version.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Make a new bot based on the sample Echobot.
2. Navigate to the **Settings** page and select **Runtime Config**.
3. Toggle **Use custom runtime** in the Bot runtime settings field and select **Get a new copy of the runtime code**.
4. The dialog box which appears has no runtime versions listed.

## Expected behavior

There should be the option in the dialog box to select **C#** and click **OK**, after which the ejected runtime directory should show in the Runtime code location field.

## Screenshots

![image](https://user-images.githubusercontent.com/23324404/85204110-6bf19880-b312-11ea-856c-8a95c55b32fa.png)

**Comment by hibrenda** [comment] 2020-06-22 03:08
@VanyLaw for more investigation

**Comment by VanyLaw** [comment] 2020-06-22 08:34
Hi @tonyanziano, It seems like the electron load plugins folder error. I tested in local and found the plugins our nightly-build version loaded was previously.
FYI. 
For example, the azure function plugin name was changed to @bfc/plugin-azure-functions-publish.
![image](https://user-images.githubusercontent.com/21174180/85264905-02a18f00-b4a4-11ea-8989-31aaa6f446d7.png) 

I try to build electron locally by `yarn dist:full`, but it fail to load plugins folder either. I try to run `yarn start:electron` locally and find the `pluginsDir` is `[Composer folder]\Composer\packages\electron-server`, but the path need to be `[Composer folder]\Composer\packages\electron-server\dist\win-unpacked\resources\app.asar.unpacked`.

I am not sure how to debug in electron, could you help to take a look? Thanks!

**Comment by tonyanziano** [comment] 2020-06-22 20:22
I've taken a look and the problem is that since #3322, plugins are now inside of the yarn workspace (`/packages/plugins/`), and the plugins have their dependencies hoisted.

This means that they are not independently functional, and do not contain all of their own dependencies when not inside of workspace.

When we packaged the Electron app, we need a plugin directory to point the plugin loader to, so we copy all the plugins from source into the unpacked ASAR before building the installer. However, now, since the plugins have their deps hoisted, they no longer are self-contained and break when in production because of missing deps.

This will require some sort of change to the build logic that handles & packs plugins.

**Comment by manashty** [comment] 2020-06-23 20:34
I temporarily fixed this issue by Uninstalling the composer from C:\Users<user>\AppData\Local\Programs\Bot Framework Composer and running the installer of version 1.0.0.1093 and installing it for local user. Similar to @ #3444

**Comment by VanyLaw** [comment] 2020-06-28 02:11
Fixed in https://github.com/microsoft/BotFramework-Composer/pull/3479

**Closed by VanyLaw** 2020-06-28 02:11 UTC
Labels: P0, R10, Type: Bug
