### ISSUE TITLE
"The parent is missing." error when sending HTTP request with string body

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/BotFramework-Composer#3412] opened 2020-06-14 14:37 UTC
## Describe the bug

"The parent is missing." error when performing HTTP request with string body (required for `x-www-form-urlencoded`)

## Version

1.0.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new HTTP request
1. Set method: "POST"
1. Set a url
1. Set the body as string and write something. For example, "this is the body"
1. Run the bot
1. When the bot will try to run this action, the bot will write "The parent is missing." in the chat

## Expected behavior

Run the HTTP Request

## Screenshots

![image](https://user-images.githubusercontent.com/66222191/84596324-a7e5b300-ae65-11ea-9502-80c1ccfb8ed0.png)

![image](https://user-images.githubusercontent.com/66222191/84596334-bcc24680-ae65-11ea-93ac-32c2f6757402.png)

**Comment by cwhitten** [comment] 2020-06-14 19:40
hello @hraz-msft - we will investigate this today. thank you!

**Comment by luhan2017** [comment] 2020-06-15 03:16
@hraz-msft could you try to use GET? I've checked in the msgraph doc, we should use GET instead of POST for this API. https://docs.microsoft.com/en-us/graph/api/user-get

**Comment by rhalaly** [comment] 2020-06-15 07:27
@luhan2017 Yes, you are correct. This URL is for the screenshot, it is not the actual URL that I use.

The issue is that sending POST request with string code (no matter to which URL or Body) the request fails

**Comment by triciasinclair** [comment] 2020-06-15 07:32
I also have this experience when trying to get an Auth token for D365CE... using both get and post.

**Comment by luhan2017** [comment] 2020-06-15 09:00
@hraz-msft @rhalaly @triciasinclair Thanks for reporting this issue. I've got what you mean. This is a bug in the botbuilder-dotnet httprequest body handling logic. @zidaneymar will help to prepare a fix on this, and we will keep you posted.

**Comment by zidaneymar** [comment] 2020-06-15 10:06
Fixed in PR:https://github.com/microsoft/botbuilder-dotnet/pull/4064

**Comment by zidaneymar** [comment] 2020-06-18 06:43
Closed in PR:https://github.com/microsoft/botbuilder-dotnet/pull/4064

**Closed by zidaneymar** 2020-06-18 06:43 UTC
Labels: Area: SDK, R10, Type: Bug

**Comment by hraz-msft** [comment] 2020-06-18 07:41
@zidaneymar I still didn't see it's working nightly build of 6/16 still has this issue

**Comment by luhan2017** [comment] 2020-06-19 02:07
@hraz-msft , could you please try the nightly build of 6/17 or 6/18, it should be included there.

**Comment by samaroj** [comment] 2020-06-30 06:22
hi, i encountered an error "The parent is missing" when i try to make a POST http method. My aim is to get the token but its not working. Please refer to the link.

https://docs.microsoft.com/en-us/graph/auth-v2-user


Current Bot Framework Composer Version (Please see image ref. below): 
![image](https://user-images.githubusercontent.com/25364986/86090214-4451bb80-badc-11ea-8d49-4ae4eb96850e.png)

**Comment by luhan2017** [comment] 2020-06-30 07:07
@samaroj We didn't include the sdk fix in the composer electron app for now. could you try to do the following steps to migrate this issue?

1. go the runtime config page -> Use Custom Runtime
2. go the runtime folder under your bot update the sdk packages (replace 4.9.3 with 4.10.0-preview-200627-141514 in every csproj file)
And try to start your bot again. 

Please let me know if it still not works.

**Comment by samaroj** [comment] 2020-06-30 07:09
> 
> 
> @samaroj We didn't include the sdk fix in the composer electron app for now. could you try to do the following steps to migrate this issue?
> 
>     1. go the runtime config page -> Use Custom Runtime
> 
>     2. go the runtime folder under your bot update the sdk packages (replace 4.9.3 with 4.10.0-preview-200627-141514 in every csproj file)
>        And try to start your bot again.
> 
> 
> Please let me know if it still not works.

Thank you, @luhan2017. I'm trying this now.

**Comment by samaroj** [comment] 2020-06-30 08:07
> 
> 
> @samaroj We didn't include the sdk fix in the composer electron app for now. could you try to do the following steps to migrate this issue?
> 
>     1. go the runtime config page -> Use Custom Runtime
> 
>     2. go the runtime folder under your bot update the sdk packages (replace 4.9.3 with 4.10.0-preview-200627-141514 in every csproj file)
>        And try to start your bot again.
> 
> 
> Please let me know if it still not works.

Hi @luhan2017 it works. I only update the packages on the .WebApp csproj file.

**Comment by samaroj** [comment] 2020-06-30 08:26
i'm not sure if this is issue i'm gonna share is related to this thread. Already fixed the "The parent is missing" error by updating the preview packages. Then i have now this issue. Please refer to the link:

Bot Framework Emulator Output: https://ibb.co/qdrjXWG
Bot Framework Composer Output: https://ibb.co/mb9sxSj

based on the error i don't have "grant_type in the request body" but I already have it on my HTTP request body on the Composer.

**Comment by triciasinclair** [comment] 2020-06-30 08:28
It now works for me as well. Thanks all!

**Comment by triciasinclair** [comment] 2020-06-30 08:29
@samaroj do you have grant_type as a parameter in the body?

**Comment by samaroj** [comment] 2020-06-30 08:30
> 
> 
> @samaroj do you have grant_type as a parameter in the body?

yup. but it gets an error

**Comment by triciasinclair** [comment] 2020-06-30 09:03
i can see the initial values but not grant_type. I ask because I have the below value and it works. 
client_id=[clientid]&username=[userid] &password=[password]&grant_type=password&resource=[resource]&client_secret=[clientsecret]

**Comment by samaroj** [comment] 2020-06-30 09:55
> 
> 
> i can see the initial values but not grant_type. I ask because I have the below value and it works.
> client_id=[clientid]&username=[userid] &password=[password]&grant_type=password&resource=[resource]&client_secret=[clientsecret]

i see you use delegated permission. i'm using application permission.

**Comment by samaroj** [comment] 2020-06-30 14:32
IT WORKS! and still using the application permission. What i did is instead of adding the "Content-Type": "application/x-www-form-urlencoded" to the Headers, i put the **application/x-www-form-urlencoded** to the Content type textbox.

![image](https://user-images.githubusercontent.com/25364986/86138820-85b88a00-bb21-11ea-9ae6-4aa72418c082.png)

**Comment by samaroj** [comment] 2020-06-30 14:36
upon checking the JSON output from the Bot Framework Emulator, if you don't indicate you content type on the textbox, the Content-type is set automatically to "application/json"

![image](https://user-images.githubusercontent.com/25364986/86139147-f8c20080-bb21-11ea-9520-7d70172fc462.png)

If you indicate it, this will look like this,

![image](https://user-images.githubusercontent.com/25364986/86139302-20b16400-bb22-11ea-9d73-69cf9867f5a6.png)
