### ISSUE TITLE
update-schema.ps1 does not work

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7031] opened 2021-04-16 00:52 UTC
## Describe the bug
Created a project using Blank Bot template, update-schema.ps1 does not work.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create project using "Blank Bot"
2. go to schemas folder
3. run ```powershell .\update-schema.ps1"
```
C:\scratch\empty4\empty4\schemas>powershell .\update-schema.ps1
Running schema merge.
Finding component files
Error multiple definitions of empty4.en-us.lu in
  C:\scratch\empty4\empty4\generated\interruption\empty4.en-us.lu
  C:\scratch\empty4\empty4\language-understanding\en-us\empty4.en-us.lu
Error multiple definitions of empty4.en-us.qna in
  C:\scratch\empty4\empty4\generated\interruption\empty4.en-us.qna
  C:\scratch\empty4\empty4\knowledge-base\en-us\empty4.en-us.qna
Parsing component .schema files
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: connect ETIMEDOUT 40.83.182.206:443
``` 

## Expected behavior

update-schema to work.

**Comment by clearab** [comment] 2021-04-16 01:09
Potential duplicate of: https://github.com/microsoft/botframework-components/issues/900

**Comment by cwhitten** [comment] 2021-04-16 01:45
Closing as the issue exists with the new runtime and is tracked at https://github.com/microsoft/botframework-components/issues/900

**Closed by cwhitten** 2021-04-16 01:45 UTC
Labels: Needs-triage, Type: Bug
