### ISSUE TITLE
unable to create bot using `yarn start:dev`

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1612] opened 2019-11-20 18:26 UTC
## Describe the bug
When starting the app using `yarn start:dev`, I am unable to create a bot.

## Version
ec382b29cf3d53e08cfea1fe17c9fed775b4cf42

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to home page
2. Click on 'Empty Bot' template
3. See error "Can not connect the storage."

## Expected behavior
Should show me contents of my default storage path

## Screenshots
https://p274.p4.n0.cdn.getcloudapp.com/items/WnuAggee/Screen+Recording+2019-11-20+at+10.21+AM.gif?v=4f55302e1e7d9c72984db600cd0c25ec

**Comment by hibrenda** [comment] 2019-12-02 06:12
root cause is #1610 . If see it again, please open it.

**Comment by a-b-r-o-w-n** [comment] 2019-12-02 17:28
This has not been fixed as of 9bfd9278aeeed2d76f04f481e5474ef715635508

**Comment by cwhitten** [comment] 2019-12-03 23:57
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1696

**Closed by cwhitten** 2019-12-03 23:57 UTC
Labels: Type: Bug
