### ISSUE TITLE
LUIS recognizer score condition with QnA Maker enabled doesn't work

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1640] opened 2019-11-22 19:12 UTC
##  Describe the bug
When I use the "Luis & QnA Maker" template as it is and just insert my LUIS IDs and keys as well as my QnA Maker IDs and keys in the settings, it seems that QnA Maker is always winning.
The prebuilt BuySurface LUIS intent is getting added to my LUIS app but if I ask "how can i buy a surface pro?" in the emulator, I get "Sorry, I did not find an answer." which is coming from QnA Maker.
The strange thing I found out, is that the emulator trace shows first the LUIS trace and then the QnA trace:

![image](https://user-images.githubusercontent.com/29750798/69453331-00d3e980-0d64-11ea-910a-5307e11ae938.png)

and the LUIS trace results in a 0.9x confidence score: 
![image](https://user-images.githubusercontent.com/29750798/69453377-134e2300-0d64-11ea-8aee-be9909950561.png)

within my Composer I have defined that the BuySurface score should be above 0.6:
![image](https://user-images.githubusercontent.com/29750798/69453426-2bbe3d80-0d64-11ea-91bb-dd507d73fb98.png)

If I remove the condition on the LUIS recognizer however, I get back the correct result coming from LUIS...

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

test

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment] 2019-11-25 06:04
@stephanbisser Thanks for reporting the issue. I set up the LUIS&QNA template and defined the BuySurface score for 0.6 as well but I could not reproduce the issues. Could you share more detail for any specific changes you made ?
![image](https://user-images.githubusercontent.com/43408889/69515950-2db61580-0f8b-11ea-9796-3f08dd0c22a7.png)

**Comment by stephanbisser** [comment] 2019-11-25 09:50
I now created a brand new bot with the QnA and Luis template and just started the bot without modifying anything and get the same result:

![image](https://user-images.githubusercontent.com/29750798/69529885-62b56e80-0f71-11ea-91e7-273a1d39c57e.png)

How to solve that issue?

**Comment by hibrenda** [comment] 2019-11-25 14:06
If you don't mind , could you please share your ComposerDialogs so we can further debug the issues.

**Comment by stephanbisser** [comment] 2019-11-30 09:47
[ComposerDialogs.zip](https://github.com/microsoft/BotFramework-Composer/files/3906978/ComposerDialogs.zip)

Here you go...

**Comment by hibrenda** [comment] 2019-12-04 15:47
I tried out and find out the root cause. Wrong luis score set to "BuySurface" intent. 
So every time you say "buy surface pro", you indeed get the top intent score with "BuySurface" but #help.score always < 0.8, so this trigger never been cached and then UnknownIntent will be triggered, that's the reason why QnA step will be called.
![image](https://user-images.githubusercontent.com/43408889/70156958-acc7ee00-16ef-11ea-8c75-108760267ec2.png)
t cause.

**Comment by stephanbisser** [comment] 2019-12-05 10:53
Sorry I provided you with the wrong ComposerDialogs. here are the correct ones:
[ComposerDialogs.zip](https://github.com/microsoft/BotFramework-Composer/files/3926456/ComposerDialogs.zip)

**Comment by hibrenda** [comment] 2019-12-05 12:10
could not reproduce the issue with your attached dialog resource. 
![image](https://user-images.githubusercontent.com/43408889/70234227-2832a980-179b-11ea-89c6-4d181cf09eeb.png)

![image](https://user-images.githubusercontent.com/43408889/70234275-48626880-179b-11ea-8215-6ed9d3d67afe.png)

**Comment by stephanbisser** [comment] 2019-12-05 13:28
I guess I now found the error (which is a big problem) I have an English OS but I have set the locale to German. Therefore the OS translates a dot (".") to a comma (",") instead of keeping the dot. So this intent condition will never be fulfilled as it is always 0,5 instead of 0.5

That's a bit of a problem for everyone not using the English locale

**Comment by hibrenda** [comment] 2019-12-05 15:37
@stephanbisser much appreciate your finding and reporting. I will also address your issue within the team as well.

**Comment by hibrenda** [comment] 2019-12-11 04:41
close this as it has been root caused and no code change needed so far

**Comment by stephanbisser** [comment] 2019-12-11 06:49
@hibrenda what is the solution to this issue now? Everyone in the non-English speaking market will get errors using the conditions within Composer?!

**Comment by hibrenda** [comment] 2019-12-12 01:07
This is nothing about the composer, we will evaluate whether runtime can solve it.

**Comment by cwhitten** [comment] 2020-01-25 16:44
@stephanbisser this is a valid issue we're discussion solutions to right now. Thanks for your patience

**Comment by vishwacsena** [comment] 2020-01-28 06:24
@stephanbisser I just tried to repro this on my English Win 10 machine and could not. Can you share crisp repro steps? What exactly do you mean by locale set to german? Do you mean Regional format set to 'English (Germany)' or Country or region set to 'Germany'? Also, I presume you were able to confirm that composer serializes down '0.9' as '0,9'? Thanks!

**Comment by stephanbisser** [comment] 2020-02-05 13:08
I would like to but after I updated the Composer I get this errror whenever I start a bot:

**Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-bin/Debug/netcoreapp2.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.**

Are you aware of that?

**Comment by stephanbisser** [comment] 2020-02-06 17:10
I solved the issue with the execution now, but no I'm facing another error: Whenever I try to start a bot which has LUIS enabled I always get this in the emulator and I'm not able to communicate with the bot:
![image](https://user-images.githubusercontent.com/29750798/73960899-f6110580-490b-11ea-9d2b-c16a1c5999b5.png)

As soon as I remove the intent triggers from the bot I can chat with the bot. What's the issue here?

**Comment by stephanbisser** [comment] 2020-02-06 19:09
Created a separate issue for that problem I'm facing currently: https://github.com/microsoft/BotFramework-Composer/issues/1965 if that's solved I can repro the steps for you @vishwacsena but in general I have had set everything to German (region, regional format and country - so the Windows display language was English but the rest was German and therefore "." got translated to "," as this is the common character for a comma in the German speaking area)

**Comment by vishwacsena** [comment] 2020-03-20 21:03
@stephanbisser we've been unable to reproduce this issue on our end. @boydc2014  tried this on a brand new VM as well and was unable to repro. 

![config](https://user-images.githubusercontent.com/20918136/77206067-61292c80-6ab3-11ea-8354-bc627419fe0c.png)

Please reactivate with accurate repro steps to help us reproduce the issue on our end. 

Note: This is probably related but we are planning to make the expression runtime be locale invariant. This has nothing to do with composer serializing content incorrectly though which is what I understand this issue to be. https://github.com/microsoft/botbuilder-dotnet/issues/3598

**Closed by vishwacsena** 2020-03-20 21:03 UTC
Labels: Bot Services, Needs investigation, R9, customer-replied-to, customer-reported

**Comment by dfvr1994** [comment] 2020-04-07 23:27
Hey guys, 

I encountered the same issue. I followed this tutorial [https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis](url) , and I wasn't able to get the "help" and "cancel" triggers to work unless I removed the `#Help.Score >= 0.5` and `#Cancel.Score >= 0.8` conditions.  

Spanish (not working): 
![image](https://user-images.githubusercontent.com/45764991/78727699-0a1cb780-78fb-11ea-9e46-f1c38a21e3ce.png)

Changed the settings to decimal ( . ) and thousands ( , ) separations: 
![image](https://user-images.githubusercontent.com/45764991/78728007-d68e5d00-78fb-11ea-99fa-1ba5ddcedf01.png)

English (working): 
![image](https://user-images.githubusercontent.com/45764991/78728150-371d9a00-78fc-11ea-84c0-e5deb0d52cc8.png)

Spanish (working):
![image](https://user-images.githubusercontent.com/45764991/78728269-849a0700-78fc-11ea-8aca-f2767abf7620.png)

So I guess is a matter of setting the decimal separator to point, right?

**Comment by Sbardo93** [comment] 2020-04-20 18:11
Hi all,
I've found the trick.. simply change this trigger condition "#Intent.Score > 0.7" to "#Intent.Score*100 > 70".
I have set the locale to Italian and the trigger works!

**Comment by peterbozso** [comment] 2020-05-07 13:53
@dfvr1994 Yes, that's it. I guess it's a couple of missing [CultureInfo.InvariantCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=netcore-3.1) references here and there in the code of the generated chatbot.
I assume. I don't know the codebase enough (yet) to verify it myself. :)
