### ISSUE TITLE
Home Page MRU list has confusing sort order visuals and behavior

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#7110] opened 2021-04-19 19:25 UTC
## Describe the bug
The sort order for the MRU list of previously opened bots has misleading UI.  See screenshot for visuals.  

I'm not exactly sure what drives the MRU list sort order.  It's not recently opened.  Which is should be.  This list should be sorted by most recently opened.  This is the way office products work.  This is the way Visual Studio works.

also, there are headers for this list that indicate the list can be sorted by other columns.  This isn't the case.  

Lastly, the Name column has a sort icon displayed, and this isn't accurate, as the list isn't sorted by name. 

## Version
Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. launch Composer
2. Note the MRU header indicates that list is sorted by name.  It actually isn't.
3. Click on the headers of the MRU list, note they indicate they should be sortable, though they are not.
4. Open a previous bot project that is not the first project in the list. 
5. Click the Home icon in the left hand nav to return to the home page.  Note the bot project you opened is not at the top of the MRU list, though is is the Most Recently Used project

## Expected behavior
I would expect the MRU list to behave as other Microsoft MRU lists, e.g. Word, Visual Studio, etc.

I would also expect the headers to not be sortable, and therefore not clickable

I would expect the up arrow icon for the Name column to go away, as we don't sort by Name.

## Screenshots

<img width="1001" alt="Screen Shot 2021-04-19 at 12 25 28 PM" src="https://user-images.githubusercontent.com/733559/115292051-57388980-a10a-11eb-9de4-349b9ca9d1b9.png">

**Comment by mewa1024** [comment] 2021-04-19 20:45
Agree with the 3 expected behaviors above. 
(Adding @xiyangdesign as fyi)

**Comment by zhixzhan** [comment] 2021-04-20 06:53
Hi @mewa1024,  I found it's because recent bot list did not render again. it should be fixed by #7140.

**Closed** 2021-04-21 16:05 UTC
Labels: R13 Bugbash, Team: Authoring, Type: Bug
