### ISSUE TITLE
New creation restriction with special characters

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6130] opened 2021-03-03 20:04 UTC
See image:
* Folder name is valid FS name, but restricted in Composer (used to have one)

![image](https://user-images.githubusercontent.com/8867670/109864835-2e226f00-7c18-11eb-9d97-3fd97d4a8f1a.png)

**Comment by a-b-r-o-w-n** [comment] 2021-03-03 20:46
I'm not sure why this restriction exists, but I do know it was deliberate. @boydc2014 do you recall?

**Comment by a-b-r-o-w-n** [comment] 2021-03-03 20:55
duplicate of #6070

**Closed by a-b-r-o-w-n** 2021-03-03 20:55 UTC
Labels: Needs-triage, R12 Bugbash, UX Design, feature-request, topic: creation
