### ISSUE TITLE
Not to publish my bot through bot framework composer.

### ISSUE THREAD

**Issue by shubham8886** [microsoft/BotFramework-Composer#6594] opened 2021-03-30 05:00 UTC
when i am trying to publish my bot through bot framework composer, i am getting below error in my logs.
LOG:
[Bot-doc01.docx](https://github.com/microsoft/BotFramework-Composer/files/6226253/Bot-doc01.docx)

---
"Accepted for publishing..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"Creating build artifact..."
---

---
"Build artifact ready!"
---

---
"Publishing to Azure ..."
---

---
"Uploading zip file..."
---

---
"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"RequestError - Error: getaddrinfo ENOTFOUND botcr-9401-dev.scm.azurewebsites.net\",\"stack\":\"Error\\n    at new n (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:18:97996)\\n    at Object.t.createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:18:98326)\\n    at e.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:28742)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:25368\\n    at Object.throw (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:25473)\\n    at s (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:24238)\"}"
---

---
"DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND botcr-9401-dev.scm.azurewebsites.net"
---

My Web App Bot is already provisioned.

**Comment by cwhitten** [comment] 2021-03-30 16:39
@shubham8886 is it possible that the hostname used is incorrect?

> RequestError - Error: getaddrinfo ENOTFOUND botcr-9401-dev.scm.azurewebsites.net"

**Comment by shubham8886** [comment] 2021-03-31 06:07
@cwhitten My messaging endpoint is "https://botcr-9401-dev.ase2-dev-paas.p.azurewebsites.net/api/messages"

and my bot framework composer is trying to publish at botcr-9401-dev.scm.azurewebsites.net, 
con you help me to change the configuration of bot framework composer so that it will route me to https://botcr-9401-dev.ase2-dev-paas.p.azurewebsites.net/

For more detail please refer attachment: doc02
[doc02.docx](https://github.com/microsoft/BotFramework-Composer/files/6234134/doc02.docx)

**Comment by shubham8886** [comment] 2021-03-31 06:08
@cwhitten i am currently using bot framework composer (v1.3.1)

**Comment by dmvtech** [comment] 2021-03-31 16:24
@shubham8886 Can you clean up all publishing profiles (and any orphaned resources) and then update to v1.4.0 and try again please?

**Comment by shubham8886** [comment] 2021-03-31 16:32
@dmvtech I have only ne profile to publish. why my bot is publishing to  "botcr-9401-dev.scm.azurewebsites.net" instead of scm i need to configure it to "ase2-dev-paas.p" is it possible? what is the issue here?

**Comment by shubham8886** [comment] 2021-03-31 16:42
"name": "botcr-9401",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "<name of your resource group>",
  "botName": "<name of your bot channel registration>"


Question: what is the difference between name and botName?

**Comment by shubham8886** [comment] 2021-03-31 17:00
---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"hostname incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"Creating build artifact..."
---

---
"Build artifact ready!"
---

---
"Publishing to Azure ..."
---

---
"Uploading zip file..."
---

---
"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"The hostname is invalid, please check if hostname/name-environment matches your target resource(webapp/function) name\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\ads.ssaurav\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:183482:25)\\n    at createCustomizeError (C:\\\\Users\\\\ads.ssaurav\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:183487:10)\\n    at BotProjectDeploy.deployZip (C:\\\\Users\\\\ads.ssaurav\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:183913:15)\"}"
---

---
"DEPLOY_ZIP_ERROR - The hostname is invalid, please check if hostname/name-environment matches your target resource(webapp/function) name"
---


where i need to provide these setting, please find below my setting values.

{
  "name": "botcr-9401-dev",
  "environment": "ase2-dev-paas",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "rg_9401_PAAS_dev1",
  "botName": "BOTCR-9401-Dev",
  "subscriptionId": "******************",
  "region": "East US",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "<subscription key>",
      "endpoint": "<endpoint>"
    },
    "MicrosoftAppId": "f45f3179-bc00-459c-acf7-26e465b22552",
    "MicrosoftAppPassword": "********************"
  }
}



Please guide me to fill these values.

**Comment by shubham8886** [comment] 2021-04-07 11:02
any update?

**Comment by pavolum** [comment] 2021-04-22 18:08
May be a duplicate of #6406

**Comment by stevkan** [comment] 2021-04-27 17:51
@shubham8886, I can see above in the discussion history that it was suggested you try the most recent version, 1.4.0. Were you able to do so? If not, can you try and see if the issue persists? You can also try the nightly version by selecting "Early adopters" in Composer's settings page to get the most recent unpublished version.

**Comment by stevkan** [comment] 2021-05-04 17:15
Closing due to lack of response.

**Closed by stevkan** 2021-05-04 17:15 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
