### ISSUE TITLE
Nodejs "Empty Bot" provisioned to Azure does not respond

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7685] opened 2021-05-06 20:48 UTC
## Describe the bug

Creating a new bot with Composer using Empty Bot (nodejs) runs locally.  Provisioning and deploying this bot using composer succeeds.  However, once deployed, the bot does not respond.

## Version

Version:  2.0.0-nightly.243098.1eefb2e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer.
2. Select nodejs
3. Select Empty Bot template.
4. Locally, start the bot and "Open in Web Chat".
5. The bot will respond with "Welcome to your bot".  
6. If you type something, the bot will respond with "Sorry, I didn't get that.".
7. Publish and deploy to Azure.
8. In portal.azure.com, navigate to your deployed bot.
9. Click "Test in WebChat".
10. The bot does not respond (even after several minutes).

**Comment by sgellock** [comment] 2021-05-07 14:49
Shiproom - I and Darren can repro this.  First play to look is app settings between a bot provisioned by composer and the ibiza portal

**Comment by darrenj** [comment] 2021-05-07 14:49
![image](https://user-images.githubusercontent.com/33519520/117467628-c48e4c00-af4b-11eb-8c08-4c9dc001a8c6.png)

**Comment by darrenj** [comment] 2021-05-07 14:54
Creating a new publish profile doesn't automatically publish so there is nothing on the disk (checked with kudu). Manually publishing makes test in webchat work but super confusing to an end user that this isn't done. 

FWIW Making a bot a skill flow creates a publishing profile **and** publishes

**Comment by sgellock** [comment] 2021-05-07 19:39
Shiproom - creating a pub profile provisions but doesn't deploy.  this is why the bot isn't working.  if you deploy, the bot will work.  as much as we'd like to make an improvement in this experience, we don't have enough time to make an structural changes in R13.   moving out to R14

**Comment by benbrown** [comment] 2021-05-24 16:20
Closing this as a dupe of #6827

**Closed by benbrown** 2021-05-24 16:20 UTC
Labels: P0, Type: Bug
