### ISSUE TITLE
Integrity check failed for "lubuild" 

### ISSUE THREAD

**Issue by shefalikuk** [microsoft/BotFramework-Composer#1609] opened 2019-11-20 13:48 UTC
Unable to install dependencies
Steps followed: 

$ cd Composer
$ yarn install
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://botbuilder.myget.org/F/botbuilder-declarative/npm/lubuild/-/1.0.3-preview.tgz: Integrity check failed for "lubuild" (computed integrity doesn't match our records, got "sha512-PHBy7+Szk2+6ZpKP4p++YEgi7HKu5EHBKaXhJ3yWEBraD2FZbol68it2F9VXj9ahSv/+KlHcEFzl77jndtWT0Q== sha1-DT/hG3IjHhIb8llqw4l46BvpkNg=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by christopheranderson** [comment] 2019-11-20 17:42
This was caused by a mutation of a package in our private feed. PR #1606 fixes this. Sorry about that.

**Comment by cwhitten** [comment] 2019-11-20 17:59
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1606

**Closed by cwhitten** 2019-11-20 17:59 UTC
Labels: Type: Bug, customer-replied-to, customer-reported, known issue
