### ISSUE TITLE
Toolbar redesign

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1912] opened 2020-01-28 00:27 UTC
The current toolbar needs a redesign since it has a scope issue. Currently,
- Undo/Redo works globally.
- Cut/Copy/Paste only works for action nodes on the visual canvas.

This will be a small design tweak.

Related issues:
https://github.com/microsoft/BotFramework-Composer/issues/1860, https://github.com/microsoft/BotFramework-Composer/issues/1415

**Comment by a-b-r-o-w-n** [comment] 2020-06-25 16:42
Duplicate of #3494

**Closed by a-b-r-o-w-n** 2020-06-25 16:42 UTC
Labels: UX Design
