### ISSUE TITLE
Impossible to create non english bots

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#3035] opened 2020-05-13 21:04 UTC
## Describe the bug

New bots get created with a default locale of "en-us" and there's no possibility to change it.
Also LUIS model are locked to "en-us" locale.

## Version

v0.0.3

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] Electron

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Need to be able to create a bot with a different locale (e.g.: "it-it") both in the dialogs and LUIS model.

**Comment by VanyLaw** [comment] 2020-05-14 06:53
Fix in https://github.com/microsoft/BotFramework-Composer/pull/3029
you can choose the location to create reources in provision script, like` --location westeurope`
then after provision, you can copy the result into add profile dialog and set your own language for luis build, like 
```
{
        accessToken: **,
        name: name,
        environment: environment,
        hostname: ***,
        luisResource: ***,
        language: "en-us",
        settings: createResult,
}
```
but please make sure the language is valid in your reources location. (According to luis specification)

**Comment by hibrenda** [comment] 2020-05-14 08:32
@EPinci Multi-lang support is on the roadmap. However you can publish luis to different region.
![image](https://user-images.githubusercontent.com/43408889/81911510-00742700-9600-11ea-9fb1-e28392aab3f8.png)
For local host bot, you can specify "westeurope" and "australiaeast" in settings. As @VanyLaw mentioned above, you need to specify the location as well if you will deploy and publish the bot to azure.

**Comment by EPinci** [comment] 2020-05-14 08:37
Ehm, apologies, I must have mixed thigs up in here.

In this bug I'm talking about "dialog locale". Language generation creates "en-us" resources only and I cannot change this. Once I deploy my bot in a non english locale, I get an error like "language generator not found".

How do I change the locale of the dialog resources?

Thank you.

**Comment by hibrenda** [comment] 2020-05-14 08:54
So far this can not be done automatically. this is on the roadmap. we will support it later.

**Comment by EPinci** [comment] 2020-05-14 08:59
I see, thank you.

In the runtime, you explicitly set defaultLocale to "en-us", that impacts dates and decimals processing.
If I set it to something else, is there a way to tell bot framework to serve "en-us" regardless of the requested locale? (Assuming this makes any sense...)

**Comment by hibrenda** [comment] 2020-05-14 09:05
@boydc2014  do you have more comments ?

**Comment by EPinci** [comment] 2020-05-14 09:08
WRT LUIS publishing: If I manually change the authoringRegion, I can see that Composer publishes the model fine but when I test the bot with composer and emulator, the model doesn't work (aka: emulator hangs in there for a while).

**Comment by hibrenda** [comment] 2020-05-14 09:58
which authoringRegion ? supported region listed in https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions

**Comment by EPinci** [comment] 2020-05-14 10:02
westeurope

Authoring/publishing appears to works fine.
Using it... not so much.

**Comment by hibrenda** [comment] 2020-05-14 10:05
I could not reproduce as I test it in westeurope.

**Comment by goergenj** [comment] 2020-05-15 16:57
I have "defaultLanguage": "de-de" in the appsettings and "language": "de-de" in the publish profile.
LUIS Apps are still always created with "en-us". This needs to be fixed urgently.
Also there is not way to specifiy the Bot language or change it asfaik. It is always "en-us". Can this be changed? Is this realted to the LUIS Apps always being created as "en-us"?

**Comment by EPinci** [comment] 2020-05-16 18:46
> I could not reproduce as I test it in westeurope.

A version upgrade and a few restarts later, I was able to have LUIS work in westeurope.

The inability to create a locale specific model, however, is blocking me to use Composer: as much as I can temporarily workaround the bot locale, with LUIS the scoring is different and the language specific entities (dates, etc...) are useless.

Is there a tentative ETA to have international locale support or, at least LUIS created with the right model?

**Comment by cwhitten** [comment] 2020-05-17 16:46
this is tracked here: https://github.com/microsoft/BotFramework-Composer/issues/1726

closing as a duplicate.

**Closed by cwhitten** 2020-05-17 16:46 UTC
Labels: Type: Enhancement
