### ISSUE TITLE
Publish skill with QnA KB in parent fails

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5843] opened 2021-02-19 16:52 UTC
## Describe the bug
I have a multibot with root and skill bot. Tried to publish just the skill for the first time, creating all Azure resources.
Only the parent has QnA KB; however the error seems to suggest resource creation conflict with QnA.

## Version
1.3.1

## To Reproduce

(see description above)

![image](https://user-images.githubusercontent.com/8867670/108535024-b192a680-728f-11eb-8671-556158a9307c.png)

**Comment by cwhitten** [comment] 2021-02-23 17:40
@scheyal have you looked into the portal to look into the resources that already exist and where they may have come from?

**Comment by luhan2017** [comment] 2021-02-24 02:41
@scheyal，the error is because there is already a Qna resource named SchoolNavigatorComplexRG, could you please either give it another name or just uncheck the QnA service when you do the provision? Seems you don't even need a QnA service in your child bot.

**Comment by scheyal** [comment] 2021-02-25 20:00
My understanding is that this is normal flow.
Create QnA kb in composer and publish (or connect and publish).
The bot is running as expected in composer. It shouldn't fail the publish.

I think we have a primary scenario that's failing.

**Comment by luhan2017** [comment] 2021-03-01 01:21
@scheyal, according to your screenshot, it did not fail at the publish step, it failed at the provision step, and I think the root cause is that the qna name is already used, so you can not create a qna service with the same name. I think you don't need to provision qna service for your child bot. if you want to use qna in your child bot, just fill the parent qna configuration in your child profile. We can sync offline if you are still confused :)

**Comment by luhan2017** [comment] 2021-03-31 02:14
Offline synced with Eyal, the issue is due to name conflict and is resolved by giving another name to the qna service.

**Closed by luhan2017** 2021-03-31 02:14 UTC
Labels: Team: Runtime & Publishing, Type: Bug
