### ISSUE TITLE
Missing line across pages

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7656] opened 2021-05-05 21:04 UTC
There used to be a silver line under the title on each page which seems to have disappeared in the nightly. Patrick and noticed it on the project settings page when doing fit and finish issues yesterday ("silver" line) and didn't realize it was more than one page. Latest nightly it's missing on all pages.

![image](https://user-images.githubusercontent.com/55601267/117208809-670ec980-adaa-11eb-911d-c7c76e66c25b.png)
![image](https://user-images.githubusercontent.com/55601267/117208822-6d04aa80-adaa-11eb-8fe8-f26987d26c91.png)
![image](https://user-images.githubusercontent.com/55601267/117208837-71c95e80-adaa-11eb-8604-bc0c7319c18c.png)
![image](https://user-images.githubusercontent.com/55601267/117208849-768e1280-adaa-11eb-9922-6ed3f3ce48b8.png)
etc

It should be perpendicular to the vertical line on the bot selection menu, right under the title.

![image](https://user-images.githubusercontent.com/55601267/117209029-ae955580-adaa-11eb-8cd2-5f307534dd01.png)

cc @mareekuh @vivekkshankar

**Comment by sgellock** [comment] 2021-05-05 21:15
Shiproom - the window for F&F issues is now closed.  moving this to R14

**Comment by mewa1024** [comment] 2021-05-05 21:44
The divider line only disappeared in today's nightly. Could this be a regression/new issue introduced by another change? (We are concerned.)

**Comment by emivers8** [comment] 2021-05-05 21:53
Yeah, I saw this when Patrick and I went through f+f issues yesterday but only on the configure page (and it does seem to be fixed there now), not any of the other pages. So I wonder if that created a regression. It looks pretty sloppy.

**Comment by sgellock** [comment] 2021-05-05 22:32
we tool a lot of F&F issues yesterday, which are in today's bits.  I'm sure somewhere in one of those PRs there's the cause.

it's unfortunate, but at this point in the cycle, it doesn't electrocute the user, there's not data lost, and it doesn't cause a crash.  so we'll have to live with it until we push a post R13 release out.

**Comment by mareekuh** [comment] 2021-05-06 14:32
I need to respectfully disagree. This regression is a must fix.  It's a glaring bug that every single user will see and notice. 
It's like having some buttons missing in your beautiful pressed wedding shirt... and it'll show up in every single wedding picture for the next many years to be ridiculed... (congrats to getting married @a-b-r-o-w-n ).

But seriously - this is visible on pretty much all pages of the product and even those not sensitive to visuals will notice this bug. We want our bloggers or demoers on stage or demoing the product and having to apologize 'oh never mind that glitch... please focus on the rest of our amazing product - it really is solid everywhere else'.. 

Given that it's persistent (not just every once in a while or just some page) It'll show up in the many screenshots that are taken by our docwriters that will have to be re-done. Our product is better than this - let's not let this one slip based on principle.

**Comment by sgellock** [comment] 2021-05-06 15:19
Shiproom - @beyackle can you assess a fix and then let's discuss

**Comment by sgellock** [comment] 2021-05-07 15:13
Shiproom - approved.  @beyackle can you merge today please?  thanks Ben

**Closed** 2021-05-07 16:12 UTC
Labels: P0, ShipRoom-Approved, Type: Bug
