### ISSUE TITLE
Publish to WebApp Bot with LUIS fails with error - "Failed to parse azure account information object object"

### ISSUE THREAD

**Issue by sriget** [microsoft/BotFramework-Composer#5354] opened 2020-12-16 08:04 UTC
Tried many options to deploy my Bot through Bot composer publish feature. Getting below error in publish log.
  Bot is configured with LUIS and works locally. Trying to deploy with publish script as per new bot composer update i received.
 Not sure where its going wrong tried using new way of MS login option in during publish and tried using az token json format also. Same errorr. Cross checked all keys and all in same region and under same resource group.

**Errors:**
 - "Failed to parse azure account information object object"
 - "SyntaxError - Unexpected token o in JSON at position 1"
 
 Screenshots:
Error:
![image](https://user-images.githubusercontent.com/35751420/102321048-c0cd3f00-3f42-11eb-86a8-c64a6210ad7c.png)

Publish profile:
![image](https://user-images.githubusercontent.com/35751420/102321061-c460c600-3f42-11eb-873e-ae91e111d2d9.png)

**Comment by a-b-r-o-w-n** [comment] 2020-12-16 16:52
duplicate of #5344

**Closed by a-b-r-o-w-n** 2020-12-16 16:52 UTC
Labels: Needs-triage, Type: Bug

**Comment by luhan2017** [comment] 2020-12-17 01:46
@sriget, If you didn't provision your luis resources through composer,  you need to add a luisResource to point to you luis prediction resource. 

Here is an example: 
```
{
  "name": "Luhan0603AF",
  "environment": "dev",
  "hostname": "Luhan0603AF-dev",   ------------------> This is the name of your webapp.
  "luisResource": "Luhan0603AF-dev-luis",   ----------------> This is the name of your luis prediction service. 
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "26c2cebc-cb5e-4732-af5b-e816f7c0ef79"
    },
    "luis": {
      "endpointKey": ""
      "authoringKey": "",
      "region": "westus"
    },
    "MicrosoftAppId": "9de821a0-f856-4655-a9ac-3fb9a39c293f",
    "MicrosoftAppPassword": "qwert12345!@#$%^"
  }
}
```

![image](https://user-images.githubusercontent.com/32191031/102427631-b26b4a00-404c-11eb-8032-139407414888.png)

**Comment by sriget** [comment] 2020-12-17 18:00
Thanks @luhan2017 . it works fine now !!!

**Comment by goergenj** [comment] 2021-02-25 17:22
@luhan2017 Can you make sure to update the template in the Publishing Profile create to incl. this setting? Current nightly does not have this properly set:

{
  "name": "<unique name in your subscription>",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<Instrumentation Key>"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<endpoint url>",
      "authKey": "<auth key>",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "<connection string>",
      "container": "<container>"
    },
    "luis": {
      "authoringKey": "<authoring key>",
      "authoringEndpoint": "",
      "endpointKey": "<endpoint key>",
      "endpoint": "",
      "region": "westus"
    },
    "MicrosoftAppId": "<app id from Bot Framework registration>",
    "MicrosoftAppPassword": "<app password from Bot Framework registration>"
  }
}

**Comment by luhan2017** [comment] 2021-03-01 09:55
sure, will follow up in the next release.

**Comment by danielallen73** [comment] 2021-03-02 11:01
Please can I get some urgent assistance.
Since moving to v1.3.1 of Composer I get the following issue when trying to publish.

"Error  - Required field accessToken is missing from publishing profile"

My redacted publishing profile as follows:
{
  "name": "REDACTED",
  "environment": "composer",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "REDACTED",
      "authoringEndpoint": "https://westeurope.api.cognitive.microsoft.com/",
      "endpointKey": "REDACTED",
      "endpoint": "https://westeurope.api.cognitive.microsoft.com/",
      "region": "westeurope"
    },
    "MicrosoftAppId": "REDACTED",
    "MicrosoftAppPassword": "REDACTED"
  },
  "accessToken": "REDACTED",
  "qna": {
    "endpoint": "REDACTED",
    "subscriptionKey": "REDACTED"
  },
  "hostname": "REDACTED",
  "luisResource": "REDACTED"
}

**Comment by danielallen73** [comment] 2021-03-02 11:43
Apologies but I have since raised the above as #6081

**Comment by Jenny0932** [comment] 2021-03-04 10:09
Hi I am getting the same issue here. It's working fine previously and just today, I got this error. I added the luisResource to both settings and publish profile, still the same error. Is that something related to LUIS portal? I found the LUIS server is not stable.

**Comment by JohnRobertGreen** [comment] 2021-03-04 21:28
I have the same experience . Worked fine one day, failed the next. Admittedly a lot of changes to dialog in between but no changes to the settings or publish settings. I can prove that the LUIS model is updated (eg a new intent is added) but the bot does not get published.

**Comment by danielallen73** [comment] 2021-03-05 01:22
I am reporting the same issue. Have followed all of the advice in all the threads. I'm on 1.3.1. Was working the other day after working around it, now I can get past the dreaded "SyntaxError - Unexpected token o in JSON at position 1"

All resources created in westus.
Using a work account.

Publish Profile as follows:
{
  "name": "REDACTED",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "REDACTED"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "REDACTED",
      "authKey": "REDACTED",
      "databaseId": "botstate-db",
      "containerId": "botstate-container",
      "collectionId": "botstate-collection"
    },
    "blobStorage": {
      "connectionString": "REDACTED",
      "container": "transcripts"
    },
    "luis": {
      "authoringKey": "REDACTED",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "REDACTED",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "MicrosoftAppId": "REDACTED",
    "MicrosoftAppPassword": "REDACTED",
    "qna": {
      "endpoint": "https://REDACTED-qnahost.azurewebsites.net",
      "subscriptionKey": "REDACTED"
    }
  },
  "accessToken": "REDACTED",
  "hostname": "REDACTED",
  "luisResource": "REDACTED"
}


Debug...
2021-03-05T01:19:07.665Z composer:extensions:azurePublish { status: 'DEPLOY_INFO', message: 'Build succeeded!' }
2021-03-05T01:19:07.704Z composer:extensions:azurePublish { status: 'DEPLOY_INFO', message: 'start publish luis' }
2021-03-05T01:19:09.041Z composer:extensions:azurePublish {
  status: 'DEPLOY_INFO',
  message: 'Assigning to luis app id: a3171f17-a364-4e5a-b7b9-9d9809d0519f'
}
2021-03-05T01:19:10.473Z composer:extensions:azurePublish {
  status: 'LUIS_PUBLISH_ERROR',
  message: '{"name":"StatusCodeError","statusCode":400,"message":"400 - {\\"error\\":{\\"code\\":\\"BadArgument\\",\\"message\\":\\"Failed to parse azure account information object object.\\"}}","error":{"error":{"message":"Failed to parse azure account information object object."}},"options":{},"response":{"statusCode":400},"stack":"StatusCodeError: 400 - {\\"error\\":{\\"code\\":\\"BadArgument\\",\\"message\\":\\"Failed to parse azure account information object object.\\"}}\\n    at new i (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:110597)\\n    at F.callback (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:109440)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:108488)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:4017)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:16714)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:15546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}'
}
2021-03-05T01:19:11.684Z composer:extensions:azurePublish {
  status: 'DEPLOY_ERROR',
  message: '{"stack":"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:115579)\\n    at C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112703\\n    at Object.throw (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112808)\\n    at s (C:\\\\Users\\\\dtall\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:111573)","message":"Unexpected token o in JSON at position 1"}'
}
2021-03-05T01:19:11.687Z composer:extensions:azurePublish SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:115579)
    at C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:112703
    at Object.throw (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:112808)
    at s (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:111573)
2021-03-05T01:19:12.863Z composer:bot-project No schemas directory found.
GET /api/publish/56237.44182596713/status/Test4 500 1794.387 ms - -

**Comment by Jenny0932** [comment] 2021-03-06 05:51
By the way, contacted with the microsoft support team and turns out it's LUIS portal UI issue. Now it's all working as it before.

**Comment by danielallen73** [comment] 2021-03-08 13:19
Hi Jenny, please can you elaborate on your comment. Do you have an example redacted publishing profile you can share please? Thank you

**Comment by Jenny0932** [comment] 2021-03-10 02:36
Hi Daniel,
I did not change anything in my publishing profile. It's an server issue of the LUIS portal in Australia region. It's not allowed to attach prediction resource to LUIS app. In that case, the LUIS publish is not be able to complete. After the LUIS team fixed the web server bug, everything goes back to normal.

**Comment by shawnzhangmicrosoft** [comment] 2021-03-25 08:43
@Jenny0932 is this issue resolved or not? I got the same error. The region is westus.

**Comment by praful-dhone** [comment] 2021-04-07 12:39
I am getting this error: 
Error - Failed to bind luis prediction resource to luis applications.
Please check if your luisResource is set to luis prediction service name in your publish profile.
<img width="796" alt="ComposerError" src="https://user-images.githubusercontent.com/37966893/113867604-5fb8c800-97cc-11eb-98c0-b9e234556b49.PNG">

Can someone help me or give some pointer here?

**Comment by luhan2017** [comment] 2021-04-09 01:51
@praful-dhone @damlaalkan see my comments here: https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-747150353

**Comment by praful-dhone** [comment] 2021-04-09 04:50
@luhan2017 

![image](https://user-images.githubusercontent.com/37966893/114129802-ec729b80-991c-11eb-882b-0f3e7dff3ba7.png)

I have added those keys in the json. You can see it in attachment, still getting same error.

![image](https://user-images.githubusercontent.com/37966893/114129861-09a76a00-991d-11eb-851e-a897cd5e1932.png)

Is there anything that I am missing here? Also MicrosoftAppId and Password is compulsory to pass here in JSON?

**Comment by praful-dhone** [comment] 2021-04-09 04:53
@luhan2017 

I have added those keys in JSON 
![image](https://user-images.githubusercontent.com/37966893/114130063-699e1080-991d-11eb-819f-4adc9ab60f71.png)

Still getting the same error. 

![image](https://user-images.githubusercontent.com/37966893/114130122-889ca280-991d-11eb-9e2b-e3a57b11820d.png)

Is it compulsory to pass MicrosoftAppId and MicrosoftAppPassword in the JSON? How do I get it?

**Comment by damlaalkan** [comment] 2021-04-09 09:03
> @luhan2017
> 
> I have added those keys in JSON
> ![image](https://user-images.githubusercontent.com/37966893/114130063-699e1080-991d-11eb-819f-4adc9ab60f71.png)
> 
> Still getting the same error.
> 
> ![image](https://user-images.githubusercontent.com/37966893/114130122-889ca280-991d-11eb-9e2b-e3a57b11820d.png)
> 
> Is it compulsory to pass MicrosoftAppId and MicrosoftAppPassword in the JSON? How do I get it?

Hello @luhan2017 I have connected the LUIS in bot composer and when I start publish with "Create new resources" not "Import existing resources" how can we integrate the existing luis model?

**Comment by luhan2017** [comment] 2021-04-20 01:55
@damlaalkan @praful-dhone sorry for the late responses, are you OK to have a live debug session with me?

**Comment by damlaalkan** [comment] 2021-04-20 15:24
> @damlaalkan @praful-dhone sorry for the late responses, are you OK to have a live debug session with me?

Hello Luhan, in nightly version the problem has solved for me thank you!

**Comment by vimalnar** [comment] 2021-04-26 20:13
Hi @luhan2017  - I am having the same issue, even after following your tips above ensuring that the hostname, luisResource, etc are correct.  I would love a live session to help solve the issue if thats at all possible?

**Comment by luhan2017** [comment] 2021-04-29 02:20
Sure, are you OK to have a live session with me today? I am in Beijing UTC+8. I will be on vacation from 4/30 to 5/5. Or we can talk after I am back.

**Comment by vboluarte** [comment] 2021-05-12 12:16
You have this in extensions.js/Line 183600 ( more or less):
async function publishLuisToPrediction(name, environment, accessToken, luisSettings, luisResource, path4, logger, runtime)
{
...
...
...
const response = await rp.post(getAccountUri, options)
...
...
...
}
you have to change post to get :

const response = await rp.get(getAccountUri, options)

**Comment by vimalnar** [comment] 2021-05-12 21:09
Hi All, sorry i did fix this in the end.  I did the following actions:

- Ensured i was not going through my companies Proxy (direct internet connection)
- Updated the Bot Composer to the latest (nightly - 2.0+) build
- I also deleted the Luis.AI apps (to allow the Bot composer to recreate them), which probably wasnt required because of the below action
- Created a new publishing profile in Bot Framework, which created an entirely new set of Azure resources

After these actions I've been having ZERO issues with additional changes.

ALSO...

I later found out not to modify/train the bot in Luis.AI directly... this causes issues with additional play/publish from the Bot Composer. This causes an issue "Error: Cannot read property 'utterances' of undefined".  To fix this I deleted the Luis.AI apps (to allow the Bot composer to recreate them) in the next play/publish

**Comment by victorlamana** [comment] 2021-07-02 16:42
I don't understand, if we need LUIS.AI to help training the bot, why after using it the Bot stops working on Framework Composer? This needs to be fixed, I've just ran into this problem and it's sad to hear that I'll have to lose all my work LUIS to this point..

**Comment by VyasK17** [comment] 2023-06-29 12:34
> Thanks @luhan2017 . it works fine now !!!

I am having an issue when publishing a profile from the Bot composer
Issue: unexpected token u in JSON at position 0 

one more thing I want to ask:
What is the authoring key and endpoint key, where to get these keys in Azure?
Luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
please help me I'm stuck at this point...Thanks
