### ISSUE TITLE
Bot Feamework Composer - Luis build failed: The model name { boolean } are reserved error when using form dialog feature

### ISSUE THREAD

**Issue by PrajwalNaik2027** [microsoft/BotFramework-Composer#9123] opened 2022-04-19 06:02 UTC
## Describe the bug
Unable to start bot. Getting Luis build failed: The model name { boolean } are reserved error when trying to use form dialog feature in Bot Framework Composer(v2.1.2)

## Version
v2.1.2

## Screenshots
![image](https://user-images.githubusercontent.com/103985127/163936098-57dc1122-56de-422d-a0f3-e11549d4e484.png)

**Comment by anishprasad01** [comment] 2022-04-19 18:18
Hi @PrajwalNaik2027,

What actually is your model's name? It's not `boolean` is it? That would be a reserved name. Additionally, is this a C# or JS bot, and are you following any specific pieces of documentation when implementing this feature? Reproduction steps would also be helpful.

**Comment by PrajwalNaik2027** [comment] 2022-04-20 06:59
Hi @anishprasad01 My model name is forms, it is a C# bot.

I am following this documentation:-
https://www.arafattehsin.com/generate-dialogs-automatically-using-form-dialogs-for-bot-framework-composer/

**Comment by anishprasad01** [comment] 2022-04-20 16:33
`forms` might also be a restricted name. Out of curiosity, have you tried any others?

**Comment by PrajwalNaik2027** [comment] 2022-04-21 03:32
No @anishprasad01 I haven't tried any other name, will try something else and check

**Comment by PrajwalNaik2027** [comment] 2022-04-21 04:36
@anishprasad01 I tried another name other than forms and still getting the same error

![image](https://user-images.githubusercontent.com/103985127/164372973-f68b872b-f1d2-47d7-b256-0ebab9e7a3c5.png)

**Comment by anishprasad01** [comment] 2022-04-21 20:19
@PrajwalNaik2027

I was able to reproduce this, however the issue seems to be specific to Composer. If you open the solution file in Visual Studio or build and run it in the command line, the bot runs properly and you can trigger the form.

We will investigate the cause of this issue further. In the meantime, it's important to remember that this feature is in preview.

For the time being, developing your bot in Composer, and running it outside Composer is a viable workaround.

**Comment by PrajwalNaik2027** [comment] 2022-04-22 04:10
Thank you @anishprasad01

**Comment by anishprasad01** [comment] 2022-04-22 14:47
Since we have identified a workaround, I am going to go ahead and close this issue. If you need further help with this, feel free to comment and we can reopen the issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-04-22 14:47 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to

**Comment by PrajwalNaik2027** [comment] 2022-04-26 05:54
Hi @anishprasad01 

The Bot is running in vs code but getting ""is not a valid LUIS application ID error, even thought I have updated the LUIS details in the bot via composer, and even in the appsettings file

![image](https://user-images.githubusercontent.com/103985127/165231187-21866c4f-fb55-4e9d-b17f-df42d7b86edc.png)

**Comment by anishprasad01** [comment] 2022-04-26 14:55
You might want to check that the appropriate .lu files are also present in the directory, since this is a Composer bot. Can you reproduce this issue with other bots or on other machines? I do not get this error when using a bot with LUIS.

If you can repro it, I'd advise opening a new issue, since this is a different problem.
