### ISSUE TITLE
Unable to find a QnA Maker service with Knowledge Base ID XXXXXXX-XXXX-XXXX-XXXXX. Please add a QnA Maker service to your bot.

### ISSUE THREAD

**Issue by mn-invia** [microsoft/BotFramework-Composer#5817] opened 2021-02-17 23:32 UTC
Hi There,

I need some urgent Help. I have created a Bot using Microsoft Bot Framework COMPOSER. I have added the QnA as well. I have the Subscription for QnA and the Keys as well. I have added all the required keys to the COMPOSER in the BOT Settings. When I run the Bot, I get the above error in the Emulator. However when I test the KB in QnA Portal, It works fine.

**THE BOT HAS NOT BEEN Published and I have not put in the Microsoft App-ID and Password. Also, the KBID that the Emulator is throwing up is totally different to the KBID in the QnA Portal.**

OS: Windows 10 pro
Composer: 1.3.1
NodeJS: 12.13.0

Here is the Screen-Shot of the Error in the Emulator:
![image](https://user-images.githubusercontent.com/79118685/108281520-02dd6000-71d4-11eb-97ae-c38a2f4dac66.png)

Here is the Screen-Shot of the CODE in the Bot. The Code has been commented out....Can't understand why? When I try to remove the comment, it throws up SYNTAX error:
![image](https://user-images.githubusercontent.com/79118685/108281605-29030000-71d4-11eb-9803-e9ea5305069f.png)

Here is the Screen-Shot of the KB running successfully in the QnA Portal:
![image](https://user-images.githubusercontent.com/79118685/108281718-5ea7e900-71d4-11eb-8eec-a331659f08d7.png)

Can you help please? Many Thanks.

**Comment by zxyanliu** [comment] 2021-02-17 23:53
The following is the doc you should follow to add a QnA KB to your Composer bot:
https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot

Specifically, you need to add the following values as described in the [edit settings](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot#edit-settings) section:

```
"qna": {
    "knowledgebaseid": "",
    "hostname": "",
    "endpointKey": "",
  },
```

![image](https://user-images.githubusercontent.com/32497439/108283524-408cab00-7138-11eb-878b-cefdd53fffe7.png)

Please try again, thanks!

**Comment by mn-invia** [comment] 2021-02-18 01:26
Hey zxyanliu,

Many Many Thanks for that……It works BEAUTIFULLY Now !!!  Can’t say Thanks Enough, Very much appreciated.

Cheers,
Murali

**Comment by zxyanliu** [comment] 2021-02-18 01:34
Thanks for bringing this up. I guess I can close this issue for now as it is resolved.
Thanks for supporting our product, we appreciate it!

**Closed by zxyanliu** 2021-02-18 01:34 UTC
Labels: Needs-triage

**Comment by mn-invia** [comment] 2021-02-18 02:26
Hi zxyanliu,

Sorry to bother yet again…..I made some changes/additions to my KB in the QnA Portal. After that I did the ‘Train & Save’, then Published the same.

Now, when I re-start my BOT….I am getting the same previous error. I have checked the settings and they have not changed as such. Why is this happening?  I need you help urgently, as I need to fix this issue ASAP. You valuable inputs will be much appreciated. Many Thanks.

Cheers,
Murali

**Comment by zxyanliu** [comment] 2021-02-18 06:02
I just tested your scenario: publish a QnA kb, make changes in QnA portal, and then publish again. I was unable to reproduce your error. I saw the changes when restarting my bot in Composer and tested in Emulator.

Please make sure you save and train, and publish again after whatever changes you made in the QnA portal.
Sometimes, if things are not working, it might be an issue of QnA rather than Composer. 

Please try again. Thanks!
