### ISSUE TITLE
Allow multiple composer processes to run side-by-side

### ISSUE THREAD

**Issue by arturl** [microsoft/BotFramework-Composer#3231] opened 2020-05-29 19:14 UTC
Often when developing a bot I need to look up how things are done in another bot. I cannot do that today, and switching between bots is unproductive.

**Comment by cwhitten** [comment] 2020-05-31 20:34
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3091

**Closed by cwhitten** 2020-05-31 20:34 UTC
Labels: Needs-triage, Type: Enhancement
