### ISSUE TITLE
Can't publish bot

### ISSUE THREAD

**Issue by samaroj** [microsoft/BotFramework-Composer#3561] opened 2020-07-04 00:42 UTC
400 - {"error":{"code":"BadArgument","message":"Failed to parse azure account information object object."}}

Message:
![image](https://user-images.githubusercontent.com/25364986/86502106-27fe9900-bdd2-11ea-8565-48cd62563075.png)

My publish configuration

{
  "accessToken": "eyJ0eXAixx",
  "name": "QnAMaxx",
  "environment": "composer",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<check applicaiton insights section>"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<check cosmosdb section>",
      "authKey": "<check cosmosdb section>",
      "databaseId": "<check cosmosdb section>",
      "collectionId": "<check cosmosdb section>",
      "containerId": "<check cosmosdb section>"
    },
    "blobStorage": {
      "connectionString": "<check blob section>",
      "container": "<check blob section>"
    },
    "luis": {
      "authoringKey": "767xxx",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com",
      "endpointKey": "",
      "endpoint": "<luis prediction endpoint>",
      "region": "westus"
    },
    "MicrosoftAppId": "f29f8xxx",
    "MicrosoftAppPassword": "4xxxx"
  },
  "subscription": "452xxx",
  "hostname": "qna-rxxx",
  "luisResource": "luis-xxt"
}

**Comment by hibrenda** [comment] 2020-07-06 10:11
@samaroj you need to provide the endpointkey as well for luis publish.

**Comment by zxyanliu** [comment] 2020-07-20 23:49
Hi @samaroj Thanks for reporting this issue.
I was unable to reproduce the error you had. I used [Composer electron 1.0.2](https://github.com/microsoft/BotFramework-Composer/releases) and followed [this doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot).

**Comment by zxyanliu** [comment] 2020-07-22 20:41
Hi @samaroj any updates?

**Comment by zxyanliu** [comment] 2020-07-23 22:04
Hi @samaroj I am closing this issue for now. Feel free to reopen it when you think it necessary. Thanks!

**Closed by zxyanliu** 2020-07-23 22:04 UTC
Labels: Topic: Publish, Type: Question

**Comment by prakashclt** [comment] 2020-09-29 10:16
Where do you find the luis endpoint key ?

**Comment by StefanoAngoneseITS** [comment] 2020-10-14 13:58
I'm having the same issue. When I add LUIS to my BOT I can't publish it on Azure. But in local with Emulator it's running good.

**Comment by tekram** [comment] 2020-10-15 21:38
Was this ever resolved? I am getting the same error now

**Comment by zxyanliu** [comment] 2020-10-15 21:43
Hi @tekram 

Composer has released its 1.1.1 version, which you can try [here](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.1.1).
Apologies for the inconvenience of the publishing issues. We will address as many as we can for the next release in November.

Thanks again for your feedback.

**Comment by tekram** [comment] 2020-10-15 23:02
I am currently running 1.1.1. Until the next release, what do you recommend? 

@zxyanliu

**Comment by prakashclt** [comment] 2020-10-16 06:06
> Was this ever resolved? I am getting the same error now

I couldn't get any fixes for it still

**Comment by tekram** [comment] 2020-10-16 13:30
Alternatives for deploying?
