### ISSUE TITLE
Requirement to invoke a skill from another skill

### ISSUE THREAD

**Issue by alishajain7** [microsoft/BotFramework-Composer#8162] opened 2021-06-22 10:22 UTC
Hi Team,

I have 3 individual skills linked to my Bot (Main Bot developed using Bot Composer).  Say suppose the user is currently interacting woth Skill A and in between it uttered an intent of Skill B. So, my requirement is to now invoke Skill B from Skill A, so that the user doesn't have to re-utter the intent again.

And hence once the flow ends for skill B, it should return back to the Composer.

Is there a way to do this presently?

**Comment by dmvtech** [comment] 2021-06-24 00:09
Hi @alishajain7 This is possible, but possibly a bit clumsy. I have something working, but am looking to see if there is a more streamlined way to do it in Composer.

> Say suppose the user is currently interacting woth Skill A and in between it uttered an intent of Skill B. So, my requirement is to now invoke Skill B from Skill A, so that the user doesn't have to re-utter the intent again. And hence once the flow ends for skill B, it should return back to the Composer.

If the intent will always be coming through the root bot, it can be setup in such a way that the intent for SkillB, doesn't have to be called by SkillA. That's somewhat how adaptive dialogs (behind the scenes) are supposed to work. _BUT_ if you need SkillA to be independent of the root bot (say SkillA is it's own bot, **_or_** SkillB should only be called from SkillA, then that is a moot point).

**Comment by dmvtech** [comment] 2021-06-24 17:48
Related: #7765

**Comment by alishajain7** [comment] 2021-06-29 08:58
Hi Dana,
In my current implementation I already am redirecting the intent to the right skill (Intent A invokes Skill A and Intent B invokes Skill B). In my case, in between a conversation (specific to skill A), user can enter the intent of Skill B. So since the intent gets directly sent to the Skill A in the middle of conversation (instead of going through composer - the root bot) , I need a way to invoke skill B from Skill A.  And then when endofConversation() is invoked from the last skill, it should go back to skill root Bot composer instead of Skill A.

**Comment by tonyanziano** [comment] 2021-07-20 18:10
@dmvtech can you provide an update on this?

**Comment by alishajain7** [comment] 2021-07-21 01:03
@dmvtech  I can get the message (of skill B) redirected to skill A to be sent back to the composer using endOfConversation. I am also successful in redirecting the same message to Skill B from the Composer. But this still does not work, probably because it expects a different Activity object. Can you please confirm if this approach is right and what next should be done here to unblock the issue?

**Comment by alishajain7** [comment] 2021-07-22 07:17
@dmvtech @tonyanziano 
![image](https://user-images.githubusercontent.com/33221676/126602257-b033ef10-7952-460c-9087-ac6521487a41.png)

I see this in the document:  https://docs.microsoft.com/en-us/composer/concept-skills Can you please help us with how this can be done!

**Comment by dmvtech** [comment] 2021-07-28 22:33
Hi @alishajain7 

While a skill can indeed be a skill consumer in itself (in the Bot Framework), the functionality to accomplish this in Composer isn't there. 

I tried to get it working (a workaround) by creating a skill (Skill B), then creating another skill (Skill A) that then consumed that skill. Then finally, creating a bot that implemented calling Skill A, but had both Skill A and Skill B listed as skills so that it could start them both, etc.

This _almost_ worked. The functionality worked, although I was getting hits for unknown intents as well as an error that I do not know the root cause of.

This could be achieved, but not _simply_, through a single Composer instance. You would need to run separate instances of Composer (one electron for the root bot, and skill A [as consumer] and skill B from source-built Composer. For example). Quite convoluted.

> Is there a way to do this presently?

So, to answer this; no. Unfortunately not. We can turn this into a **feature request** issue and see if it is something that can be achieved at some point. Please confirm you would like me to do that.

**Comment by dmvtech** [comment] 2021-08-03 17:23
Closing as this is currently not doable in current build. Please open a [feature request ](https://github.com/microsoft/BotFramework-Composer/issues/new?assignees=&labels=feature-request%2C+Needs-triage&template=bot-framework-composer-feature-request.md&title=)as needed.

**Closed by dmvtech** 2021-08-03 17:23 UTC
Labels: Bot Services, Support, Type: Question, customer-replied-to, customer-reported
