### ISSUE TITLE
When starting a QnA Maker Bot with Start Bot getting "Unable to get value for EndpointKey from state"

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#7220] opened 2021-04-21 16:18 UTC
## Describe the bug

When creating a QnA Maker bot from template and then generating the QnA Maker as part of the rocket ship process, you get "Unable to get value for EndpointKey from state." when you ask a question to webchat.

![image](https://user-images.githubusercontent.com/18688053/115586904-ad383900-a292-11eb-97f6-ef709472115a.png)

## Version

Version:  1.4.0-nightly.237504.97571e0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a QnA Maker bot from template
2. Create a new QnA Maker KB
3. Use Rocket Ship to Generate a QnA Maker Key
4. Add a couple of QnA pairs to your bot
5. Start Bot
6. Using WebChat in Composer ask a question from your QnA KB
7. See Error

## Expected behavior

QnA Maker KB should be called and response should be returned.

**Comment by Dewain27** [comment] 2021-04-21 18:57
Confirmed with Ryan that this seems to be only in Windows build:
![image](https://user-images.githubusercontent.com/18688053/115606578-7d486000-a2a9-11eb-80df-963b3b45e045.png)

I will work to replicate to see if this is an issue that happens in 1.4 next.

**Comment by Dewain27** [comment] 2021-04-21 18:58
Confirmed that on Mac it is working in nightly build.

**Comment by cleemullins** [comment] 2021-04-21 20:13
Dupe of #7200

**Closed** 2021-04-22 15:45 UTC
Labels: P0, R13 Bugbash, Type: Bug, topic: creation
