### ISSUE TITLE
Remove dialog error

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6223] opened 2021-03-04 23:58 UTC
Several issues showed up, one captured here.

Repro:
1. Create new dialog
2. Rename dialog
3. Remove dialog
--> the error below.

ENOENT: no such file or directory, scandir 'c:\workspace\botroot\TempPlay\MultilingualOrchestrator\MultilingualOrchestrator\dialogs\TestDialog\recognizers'

**Comment by cwhitten** [comment] 2021-03-05 00:17
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/1741

**Closed by cwhitten** 2021-03-05 00:17 UTC
Labels: Needs-triage, R12 Bugbash, Type: Bug
