### ISSUE TITLE
"Conversation not found" and "Index was out of range" errors at conversationUpdate

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#8726] opened 2021-10-06 15:03 UTC
## Describe the bug

Occasionally after starting the bot in composer, the first conversation in the webchat window will throw these errors.  The response payloads show "Conversation not found. BadArgument" and "An error occurred posting activity to the bot. Internal Server Error" which you can see in the JSON below. It doesn't happen again if you just click to Restart Conversation. A user also had this happen once when messaging the bot deployed in Azure.
![image](https://user-images.githubusercontent.com/16640521/136229360-51fac421-aa33-4be8-9b88-65b64f6cfdd0.png)
![image](https://user-images.githubusercontent.com/16640521/136229425-7733357a-3160-4a65-8083-12c6044c10bf.png)

## Version

v2.1.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

This isn't easily reproduced. It happens only occasionally after starting the bot in composer, and happened once in Direct Line channel. It goes away after starting a new conversation.

## Expected behavior

There should be no error, just the welcome message.

## Screenshots

App Insights logs  from the user's conversation with the deployed bot. I think the reason you see the one welcome message is related to https://github.com/microsoft/BotFramework-Composer/issues/8625
![image](https://user-images.githubusercontent.com/16640521/136229026-737ad835-b641-469f-9f44-a783598d06a5.png)

### JSON

First conversationUpdate:
```
{
  "activity": {
    "type": "conversationUpdate",
    "membersAdded": [
      {
        "id": "97848c62-952b-4b8b-b3bc-baec6285dfe4",
        "name": "User",
        "role": "user"
      }
    ],
    "membersRemoved": [],
    "id": "5a8e2a66-3893-49b5-ae73-e7765127c70c",
    "channelId": "emulator",
    "recipient": {
      "id": "739a3e10-0f79-4bbc-b7b0-eb32fa5f59de",
      "name": "Bot",
      "role": "bot"
    },
    "localTimestamp": "2021-10-06T10:34:04-04:00",
    "timestamp": "2021-10-06T14:34:04.845Z",
    "conversation": {
      "id": "d1e61130-0853-40cd-b5b0-9215c683ccd0|livechat"
    },
    "from": {
      "id": "97848c62-952b-4b8b-b3bc-baec6285dfe4",
      "name": "User",
      "role": "user"
    },
    "locale": "en-us",
    "serviceUrl": "http://localhost:5000"
  },
  "id": "649b0227-9da6-48e4-bec1-a45b88bdaeba",
  "timestamp": 1633530844845
}
```

First 500 error:
```
{
  "error": {},
  "id": "5e5f015c-6366-4e5e-806d-d8ec3dd9d301",
  "request": {
    "method": "POST",
    "payload": {
      "type": "message",
      "serviceUrl": "http://localhost:5000",
      "channelId": "emulator",
      "from": {
        "id": "739a3e10-0f79-4bbc-b7b0-eb32fa5f59de",
        "name": "Bot",
        "role": "bot"
      },
      "conversation": {
        "id": "16133692-eb94-4c90-bc0a-a5188130700e|livechat"
      },
      "recipient": {
        "id": "f67b8018-a377-4a97-9b2c-5bcfc50dde71",
        "name": "User",
        "role": "user"
      },
      "locale": "en-us",
      "text": "Operation returned an invalid status code 'InternalServerError'",
      "inputHint": "acceptingInput",
      "replyToId": "f325292f-7fe8-4852-9eca-35d2ed433447"
    },
    "route": "/v3/conversations/16133692-eb94-4c90-bc0a-a5188130700e%7Clivechat/activities/f325292f-7fe8-4852-9eca-35d2ed433447"
  },
  "response": {
    "payload": {
      "message": "Conversation not found. BadArgument"
    },
    "statusCode": 500
  },
  "timestamp": 1633530848556
}
```

Last 500 error:
```
{
  "error": {
    "message": "An error occurred posting activity to the bot. Internal Server Error"
  },
  "id": "354e4ae6-05ed-4086-a688-f4df8bc9c247",
  "request": {
    "method": "POST",
    "payload": {
      "type": "conversationUpdate",
      "membersAdded": [
        {
          "id": "f67b8018-a377-4a97-9b2c-5bcfc50dde71",
          "name": "User",
          "role": "user"
        }
      ],
      "membersRemoved": []
    },
    "route": "/v3/directline/conversations/16133692-eb94-4c90-bc0a-a5188130700e%7Clivechat/activities"
  },
  "response": {
    "payload": {
      "error": {
        "status": 500,
        "message": "An error occurred posting activity to the bot. Internal Server Error"
      }
    },
    "statusCode": 500
  },
  "timestamp": 1633530848658
}
```

**Comment by tonyanziano** [comment] 2021-10-06 16:37
@lshade can you try running Composer from a terminal by directly executing the .exe and then trying to reproduce this? Maybe we will be able to see what function is throwing the exception.

Also, if you could check the developer tools console window for any error messages that would be very helpful.

**Comment by Kirill-Ovc** [comment] 2021-12-03 10:20
I have the same error when using package "Microsoft.Bot.Components.Teams"
After adding some activities from the package and restarting the bot, i got error:
```
POST 500 /v3/directline/conversations/9081df15-6172-4d3f-8b9d-9dce70e0e87c%7Clivechat/activities
An error occurred posting activity to the bot. Internal Server Error
```
And no messages in chat. The error does not disappear after deleting the activities or restarting.
Only removing the package helped to solve the problem.

**Comment by EricDahlvang** [comment] 2022-03-17 23:32
This is likely due to a bug in ForEach https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEach.cs#L30

Which has been fixed by replacing with https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs 

ForEach/ForEachElement registration:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveBotComponent.cs#L96

**Closed by EricDahlvang** 2022-03-17 23:32 UTC
Labels: Type: Bug
