### ISSUE TITLE
Unable to create project using Basic conversational bot template

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7259] opened 2021-04-22 18:11 UTC
## Describe the bug

Unable to create a project

## Version

Version:  1.4.0-nightly.238024.b6ea776
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115765221-c9c59580-a3a6-11eb-8bd6-5b4f9cf33cd1.png)

**Comment by pavolum** [comment] 2021-04-26 16:50
Cannot repro, may be something specific to the customers env. Going to downgrade to P1, if this is evident across all machines then will upgrade to p0.

@rvinothrajendran can you try and repro in the latest nightly build of Composer? I was able to build this template without issue on the below version. Please try again with latest and if the issue is still present then post any additional errors here
![image](https://user-images.githubusercontent.com/22845013/116120835-fc64dc00-a68d-11eb-83e3-4a433ee2a980.png)

**Comment by rvinothrajendran** [comment] 2021-04-26 17:04
@pavolum one is pc is working fine ... another pc has an issue. ( Last time both pc has an issue)


![image](https://user-images.githubusercontent.com/16264167/116122445-16b8ad00-a6c2-11eb-9369-d2320c0cb461.png)

**Comment by Dewain27** [comment] 2021-04-27 22:15
Waiting for bugbash to see if we can repro.  Not able to repro and believe to be a local environment issue.

**Comment by pavolum** [comment] 2021-04-28 14:43
@rvinothrajendran I have an idea to get a bit more error info from you since I cannot repro. 

Can you use the PC that still has the issue and navigate to the directory of the bot you created through Composer (the bot files should be created even though the creation process errored out at the dotnet build part). 

In the command line navigate to the directory that contains your .csproj file (from the screenshot it appears it is called conversational_core.csproj) and then run `dotnet build conversational_core.csproj`. Please send over a screen shot of the command line. It should error out and the command line should provide better error info. Please send over everything the command line outputs. Many thanks!

**Comment by rvinothrajendran** [comment] 2021-04-28 15:20
@pavolum 

1. This morning I have updated the new build for the first time the same issue raised ... But no project folder has created.

![image](https://user-images.githubusercontent.com/16264167/116428167-f6fdc200-a844-11eb-944f-f6ccd6e37c12.png)


2. I try to create video ( In this project has created but there is error at the end.)



https://user-images.githubusercontent.com/16264167/116428624-61166700-a845-11eb-9f42-c11fc4b43385.mp4



3. Updated new build ... This time all should be ok

**Comment by pavolum** [comment] 2021-04-28 16:45
Hmm so the dotnet build issue is no longer present but now you are getting this javascript error, correct? If this is the case then we should close this issue and open a new one for this new error you are seeing. I will surface your video to others on the team now to start triaging.

**Comment by rvinothrajendran** [comment] 2021-04-28 16:50
@pavolum java script has raised only one time  incase in future any issue , I will open new issue.

**Comment by pavolum** [comment] 2021-04-28 17:29
Ahh good stuff, yes please raise an issue if it arises again. Thank you very much for reporting this dotnet build bug. It seems the newer build has resolved the issue. If you hit it again please reopen and send over the dotnet build output when you run the command directly through command line.

**Closed by pavolum** 2021-04-28 17:29 UTC
Labels: P1, R13 Bugbash, Type: Bug, topic: creation
