### ISSUE TITLE
Cannot start new bot from template: Cannot find module @microsoft/generator-bot-adaptive

### ISSUE THREAD

**Issue by ilhamfadhil14** [microsoft/BotFramework-Composer#9045] opened 2022-03-09 03:09 UTC
## Describe the bug

I recently installed bot composer, every time I created project it keeps throwing error:

`Error hit when instantiating remote template: Cannot find module '@microsoft/generator-bot-adaptive' Require stack: - C:\Users\ilham\AppData\Roaming\BotFrameworkComposer\.yo-repository\node_modules\@microsoft\generator-bot-empty\generators\app\index.js - C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\node_modules\yeoman-environment\lib\store.js - C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\node_modules\yeoman-environment\lib\environment.js - C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\lib\workers\templateInstallation.worker.js`

I have manually installed npm missing package on target folder but it did not work.

## Version

Version:  2.1.2-nightly.294637.6eb3075
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I have installed npm and dotnet

`$ node --version
v16.14.0`
`$ dotnet --version
3.1.417`

## Browser

I'm using dekstop version on Windows 11

- [x] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on 'Create New'
2. Select `C#` tab
3. Select Empty Bot
4. Click on 'Next'
5. Type 'Name'
6. Select Runtime type `Azure Web App`
7. Click on 'Create'
8. See error `Cannot find module '@microsoft/generator-bot-adaptive'`

## Expected behavior

Bot composer initiate project template and start using bot composer to create bot

## Screenshots

![image](https://user-images.githubusercontent.com/80385722/157364606-c1f9999c-2d70-44e9-947b-8113ec64e789.png)

![image](https://user-images.githubusercontent.com/80385722/157364972-0658698d-1312-4c85-a6c2-eb0d04c81c2f.png)

![image](https://user-images.githubusercontent.com/80385722/157364951-c6f7853a-aadd-4010-8ea8-8f28b481b2d2.png)

**Comment by anishprasad01** [comment] 2022-03-09 18:11
Hi @ilhamfadhil14,

There's a couple of simple troubleshooting steps we can try to start with.

1. You appear to be using the latest nightly build. Perhaps you could try the latest [stable release](https://github.com/microsoft/BotFramework-Composer/releases/tag/v2.1.2) and see if that fixes the problem?
2. The [installation instructions](https://docs.microsoft.com/en-us/composer/install-composer?tabs=macos#prerequisites) suggest that Composer is best used with Node.js 14.x LTS, whereas you are using 16.14.0. If switching to stable alone doesn't work, perhaps you can attempt to install and used Node 14?

**Comment by ilhamfadhil14** [comment] 2022-03-10 01:20
I have uninstalled bot composer and install stable version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Also I changed node and npm to: 
`node --version
v14.17.3`
`npm --version
6.14.13`
`dotnet --version
3.1.417`

But the issue is the same

![image](https://user-images.githubusercontent.com/80385722/157568284-6e13072b-ef58-403f-8c1a-d1b0a2a24d17.png)

**Comment by anishprasad01** [comment] 2022-03-10 18:45
Let's try verifying that you can create bots at all, outside of the Composer interface. Try following the steps to create and run a [C#](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvscode) and [JavaScript](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvscode) bot using the command line and let me know what does and doesn't work.

**Comment by ilhamfadhil14** [comment] 2022-03-11 06:42
Hi @anishprasad01, 

I have successfully run bot on C# and JavaScript
This is for JavaScript:
![image](https://user-images.githubusercontent.com/80385722/157815674-9e95d1e3-a9a4-4d1b-bb0a-3e4a145ee785.png)
![image](https://user-images.githubusercontent.com/80385722/157815704-58b5bf13-e717-4690-b358-1e4e677c2084.png)

This is for C#:
![image](https://user-images.githubusercontent.com/80385722/157816010-0d10aee9-84f3-40ba-9ed8-91e510ae04ee.png)

**Comment by anishprasad01** [comment] 2022-03-11 18:31
Hmm, another thing you might try is checking your firewall settings for Composer to see if any domains are blocked. Alternatively, something that I would like you to try if possible is downgrading to Composer 2.1.1.

**Comment by ilhamfadhil14** [comment] 2022-03-12 08:20
I installed Composer 2.1.1, but the error still persist.

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

![image](https://user-images.githubusercontent.com/80385722/158009817-0e9f755a-9d52-42f1-9fcd-93b1755b3c17.png)

Also, I have try to disable firewall while running bot composer. Error message is still the same.

**Comment by ilhamfadhil14** [comment] 2022-03-15 04:13
No, I use this machine for daily works and until now do not have any major issue regarding connectivity. 

Even I tried to run as administrator, bot composer failed to get the templates. 

I can try to use bot framework on a VM if this continue to not work. 

Any network or connection settings should I change or configure?

**Comment by ilhamfadhil14** [comment] 2022-03-15 18:43
No, this machine is not managed by IT department and this is my personal machine that I use for daily work.

**Comment by anishprasad01** [comment] 2022-03-15 19:00
Ok, now I'm clear on that. Do you happen to have another machine to test with regardless? That way we can see if the issue is specific to your machine or external to it.

**Comment by ilhamfadhil14** [comment] 2022-03-21 05:17
Hi @anishprasad01, 

I managed to install and run bot composer on ubuntu VM. Yeah, maybe just it does not work on my machine.

**Comment by anishprasad01** [comment] 2022-03-21 15:42
If Composer works in a VM, then we can rule out your network as a potential cause. That suggests that there is some configuration issue on your machine that is preventing you from reaching the endpoints needed to run Composer properly. The logical fix here would be for you to check firewall settings, antivirus settings (sometimes these programs can inadvertently affect others), or other software settings that may be specific to your machine.

Since we have identified that this is due to a config issue and not a bug with Composer, I'm going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-03-21 15:42 UTC
Labels: customer-reported, Bot Services, customer-replied-to
