### ISSUE TITLE
[Accessibility][Reflow - Homepage]: Two way scrolling is provided on Homepage when zoom is set to 400%.

### ISSUE THREAD

**Issue by ShellySoni** [microsoft/BotFramework-Composer#2022] opened 2020-02-19 12:36 UTC
**User Experience:**
Users having low vision will get difficulties to interact with the whole page contents by scrolling in two ways I.e. horizontally also & vertically also.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Set page zoom at 400% and observe the issue.

**Actual Result:**
Two way scrolling is provided on Homepage when zoom is set to 400%.

**Expected Result:**
Vertical slider should only be present when zoom is set to 400% because it will create difficulties for low vision users to interact with the whole page contents by scrolling in two ways I.e. horizontally also & vertically also.

**Note:**
Main title of the page is also gets cropped when zoom is set to 400%.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BE12828DF-B35C-4F4D-9289-1F932E19F8CF%7D&file=MAS%201.4.10%20%E2%80%93%20Reflow.docx&action=default&mobileredirect=true&cid=2d02c9a8-ece2-4f80-ad8c-b88ed4018176

**Attachment:**
[MAS1.4.10_Homepage.zip](https://github.com/microsoft/BotFramework-Composer/files/4225044/MAS1.4.10_Homepage.zip)

**Comment by corinagum** [comment] 2020-02-27 05:11
![MAS1 4 10_Homepage](https://user-images.githubusercontent.com/14900841/75414173-7fe53a80-58dc-11ea-8c8f-05d52d6e0534.png)

Only .png provided, pasted above; no video in .zip :)

**Comment by ashish315** [comment] 2020-04-21 19:06
@cwhitten As checked and verified on below environment, the issue is not fixed. I downloaded below Master build file last updated on 18th April.

**Test Environment**
Browser: Microsoft Edge Dev {Version 83.0.467.0 (Official build) dev (64-bit)}
OS build: 2004 (19588.1000)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)
![image](https://user-images.githubusercontent.com/60913131/79755879-6c33de80-8337-11ea-90cd-8dd51ac56600.png)

**Comment by liweitian** [comment] 2020-04-22 14:23
@ashish315 opened a pr to solve the issue found there. We can access every section of the home page  after zoom in.

**Comment by ashish315** [comment] 2020-04-23 19:47
As checked still the name of the "Bot" is gets cropped.
As well as agree with @liweitian now we are able to access controls.

**Comment by liweitian** [comment] 2020-04-24 08:58
@ashish315 On the header, the text is like 'Bot Framework Composer | BotName'. When zoom in 400%, there is no enough room for it. Should I make the 'Bot Framework Composer' part showed in two rows or make the over all text have a smaller font size?

**Comment by ashish315** [comment] 2020-04-24 09:13
@liweitian If possible make it in two lines like "Save As" available in the screenshot.

**Comment by ashish315** [comment] 2020-05-01 02:53
As checked the issue is resolved now. So, HCL is closing the issue.

**Closed by ashish315** 2020-05-01 02:53 UTC
Labels: A11yCT, A11yLowImpact, A11yMAS, Accessibility, Fixed, HCL- BotFrameworkComposer, MAS1.4.10, Severity4
