### ISSUE TITLE
Can't create Empty Bot with Azure Functions

### ISSUE THREAD

**Issue by mfpt** [microsoft/BotFramework-Composer#9639] opened 2023-09-08 15:53 UTC
Command failed: dotnet build PsychoAnamBotBot.csproj Unhandled exception. System.ObjectDisposedException: Cannot write to a closed TextWriter. Object name: 'StreamWriter'. at System.IO.StreamWriter.<ThrowIfDisposed>g__ThrowObjectDisposedException|76_0() at System.IO.StreamWriter.WriteLine(String value) at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.Dispose(Boolean disposing) at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.OnProcessExit(Object sender, EventArgs e)

On a new attempt the error is: Command failed: dotnet build PsychoAnamBotTest.csproj

**Comment by mfpt** [comment] 2023-09-09 10:23
On a new attempt the error is: Command failed: dotnet build PsychoAnamBotTest.csproj

**Comment by ramfattah** [comment] 2023-09-11 05:33
Thanks @mfpt, I'm looking into this.

**Comment by ramfattah** [comment] 2023-09-13 04:45
Thanks @mfpt for reporting.

I'm able to reproduce this issue.
![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/62d86d6b-ca04-44aa-b558-ac58896985bd)

Steps to reproduce:
1. Install Command line tools for Azure Functions per your OS from [here](https://github.com/Azure/azure-functions-core-tools#installing)
2. Open Composer 2.1.2
3. Create a new C# bot
4. Select the **Runtime type** to `Azure Functions`
    ![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/6556d038-1ca0-4a4f-9f69-f1a01bfe5464)
5. See error

<br />

Enabling Composer in debug mode yielded the following logs:
```powershell
  composer:extensions:plugin-runtimes BUILD THIS C# FUNCTIONS PROJECT! at /Users/ram/Documents/bot/BF/ComposerPlayground/ComposerAZFunctionBot/ComposerAZFunctionBot/... +0ms
  composer:extensions:plugin-runtimes Run dotnet user-secrets init... +0ms
  composer:extensions:plugin-runtimes Run dotnet build... +237ms
  composer Cleaning up failed project at  /Users/ram/Documents/bot/BF/ComposerPlayground/ComposerAZFunctionBot +2s
GET /api/status/e828f33d-8f54-44ba-aa71-d1dab8e1fc7f 500 10.266 ms - -
```

**Comment by ramfattah** [comment] 2023-09-13 04:45
@mfpt, I will let the engineers know about this issue and report back. Thanks.

**Comment by ramfattah** [comment] 2023-09-19 21:20
Hi @ceciliaavila, 

I'm able to reproduce this issue. Assigning this to you for now.

Please let me know if you have any questions.
Thanks.

**Comment by sw-joelmut** [comment] 2023-09-25 15:50
Hi @ramfattah and @mfpt,

We weren't able to reproduce the described issue. In our testing, the `Azure Functions` bot was created and started properly.
All our testings were done in a Windows environment and with different Node.js and [Azure Functions Core Tools](https://github.com/Azure/azure-functions-core-tools#azure-functions-core-tools) versions.

Which SO are you using?

![image](https://github.com/microsoft/BotFramework-Composer/assets/62260472/f15b309b-4e14-404d-b80b-9d1ab4f5216b)

**Comment by ramfattah** [comment] 2023-09-26 05:14
Thank you @sw-joelmut, 

I used Mac OS. 

I can try to use Windows OS to see if I'm still able to reproduce. 
Will report back soon.

**Comment by ramfattah** [comment] 2023-10-06 17:09
Thank you @sw-joelmut, 

With your help, I'm not able to reproduce this issue anymore after installing:
1. [azure-functions-core-tools](https://github.com/Azure/azure-functions-core-tools)
2. [dotnet SDK 3.1](https://dotnet.microsoft.com/en-us/download/dotnet/3.1)


https://github.com/microsoft/BotFramework-Composer/assets/38049078/d596727d-3fa4-468f-823c-81febcc9a77c



``` cmd
> dotnet --info

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  4.1.426 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by ramfattah** [comment] 2023-10-06 17:13
Not able to reproduce. Closing this issue. 
@mfpt, please re-open if you continue to face this issue after installing above requirements mentioned.

**Closed by ramfattah** 2023-10-06 17:13 UTC
Labels: customer-reported, Bot Services, customer-replied-to
