### ISSUE TITLE
Getting transcript from a custom action

### ISSUE THREAD

**Issue by jcmorara** [microsoft/BotFramework-Composer#8593] opened 2021-08-24 00:47 UTC
I'm trying to create a custom action to get the conversation transcript. Problems started trying to get the connectionString from settings, it always returns null(no issues with container name). I can see the values in chatbot appSettings. Find below the code I'm using
```csharp
  StringExpression containerExpression = "=settings.runtimeSettings.features.blobTranscript.containerName";
  var containerName = containerExpression.GetValue(dc.State); //OK
  StringExpression connectionStringExpression = "=settings.runtimeSettings.features.blobTranscript.connectionString";
  var connectionString = connectionStringExpression.GetValue(dc.State); //Returns Null
```
Am I doing something wrong? What is the best way to do this?
Also, I was trying to see if there is a way to access the built-in BlobsTranscriptStore service/middleware but I couldn't find a way to do it.
Thanks in advance for all your help on this.

**Comment by srinaath** [comment] 2021-08-24 16:39
@jcmorara Could you follow the default issue template if possible to indicate the version of Composer, OS etc.

**Comment by jcmorara** [comment] 2021-08-24 17:43
## Describe the bug

I'm trying to create a custom action to get the conversation transcript. Problems started trying to get the connectionString from settings, it always returns null(no issues with container name). I can see the values in chatbot appSettings. Find below the code I'm using
StringExpression containerExpression = "=settings.runtimeSettings.features.blobTranscript.containerName";
var containerName = containerExpression.GetValue(dc.State); //OK
StringExpression connectionStringExpression = "=settings.runtimeSettings.features.blobTranscript.connectionString";
var connectionString = connectionStringExpression.GetValue(dc.State); //Returns Null
Am I doing something wrong? What is the best way to do this?
Also, I was trying to see if there is a way to access the built-in BlobsTranscriptStore service/middleware but I couldn't find a way to do it.

## Version

Bot Framework Composer v2.1.0

## Browser



- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS



- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## Expected behavior

Being able to get a conversation tra
![AppSettings](https://user-images.githubusercontent.com/88945358/130664228-027ba184-37bf-4e74-9f57-63744afa99a9.PNG)
nscript from a custom action

**Comment by jcmorara** [comment] 2021-09-01 17:01
Hi @dmvtech!
Any update? Could you replicate the issue?

**Comment by jcmorara** [comment] 2021-09-10 18:33
Is somebody checking this issue?

**Comment by compulim** [comment] 2021-09-21 18:20
@dmvtech Ping.

**Comment by dmvtech** [comment] 2021-09-22 01:12
Hi @jcmorara Apologies for the delay. I'm still looking at finding out how to do this and what the cause might be. I thought at first that it was the `=` character (or other special characters) inside the connection string was throwing things off. But even with a simple setting like:
```json
      "blobTranscript": {
        "containerName": "mycontainername",
        "connectionString": "somesimplename"
      }
```

It still failed. So, my assumption is that there is something in the runtime that is explicitly not populating State values.

This always failed as well, regardless of the string used:
```csharp
var successBool = dc.State.TryGetValue<string>("settings.runtimeSettings.features.blobTranscript.connectionString", out somestring);
```

I'll continue my investigation and update you when I have more info.

---

> Also, I was trying to see if there is a way to access the built-in BlobsTranscriptStore service/middleware but I couldn't find a way to do it.

I guess it depends on what you want to do, and what you mean by access it, but you can build your own off of the[ existing middleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs).

**Comment by dmvtech** [comment] 2021-09-22 01:17
Actually, just found it. There is a blocking list:
https://github.com/microsoft/botbuilder-dotnet/blob/e176bb576105538cd179187f4c19b2818d2578e7/libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/SettingsMemoryScope.cs#L21

It does not populate into memory.

**Comment by dmvtech** [comment] 2021-09-27 16:57
hi @jcmorara I'm going to close this as it seems as though this has been answered. Please let me know if you have further questions.

To work around this issue, a couple of _ideas_ are:

1. Create .NET classes in your project that can populate these values and then share to your custom action.
2. Derive from the existing botbuilder classes and change the code to suit your needs.
3. Store the value in another (additional) field with a path that wouldn't be blocked that it could be pulled from.

**Closed by dmvtech** 2021-09-27 16:57 UTC
Labels: customer-reported, Bot Services, customer-replied-to
