### ISSUE TITLE
Publish Fails in version 2.1.1

### ISSUE THREAD

**Issue by MCKRUZ** [microsoft/BotFramework-Composer#8814] opened 2021-11-23 20:25 UTC
## Describe the bug
When attempting to publish my new bot via composer I am experiencing an error that will not allow me to publish under any circumstances.

## Version
![image](https://user-images.githubusercontent.com/1473014/143097696-51dd0959-b702-41ae-b572-b1918be225ee.png)

## Browser

- [x ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1.) Created a bot that utilizes both LUIS and QnAMaker
2.) Gone to the publishing tab and created a new publishing profile
3.) Selected the "Create new resources" option and created all of the required AND optional resources
4.) Received the error message below

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"{\"stack\":\"Error: Request failed with status code 400\\n    at createError (C:\\\\Users\\\\MKruczek\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102540:17)\\n    at settle (C:\\\\Users\\\\MKruczek\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102554:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Users\\\\MKruczek\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:103498:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\"message\":\"Request failed with status code 400\",\"config\":{}}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Users\\\\MKruczek\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269188:28)\",\"message\":\"Unexpected token u in JSON at position 0\"}"
---

---
"SyntaxError - Unexpected token u in JSON at position 0"
---

5.) I then changed the resources for both LUIS and QnAMaker to the newly created ones made by Composer, tried again, and got the exact same error.
6.) I then copied the JSON out of the app config, created another publishing profile, chose to import existing resources, copied in the JSON and tried again...same error.
7.) I then took the starter JSON that was present in the screen that you get when you choose to import existing resources, copied in ONLY the values from my original JSON into the new JSON, tried again...same error.

## Expected behavior

I would have expected that the bot would have been published.

## Additional context

Here is a redacted copy of my JSON

![image](https://user-images.githubusercontent.com/1473014/143098590-fbf66393-ebc2-4ec5-b47d-711ada3d1c69.png)

**Comment by maydaystella** [comment] 2021-11-25 08:21
I agree, after updating my bot composer, I cant even login and ofcourse publish.

**Comment by GuiRoux5555** [comment] 2021-11-30 08:48
I have same problem. I started from empty project and add gradualy LUIS functionality. 
I try to create resources from Bot Composer and manually. Same result.
I add the prediction resource on the luis' portal and publish from. Same result.

The error when i publish the BOT.

Where I am wrong ?

------------------------------------------------------------------------------------------------------------------------------------
---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"{\"stack\":\"Error: Request failed with status code 400\\n    at createError (C:\\\\Users\\\\g.roux\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102542:17)\\n    at settle (C:\\\\Users\\\\g.roux\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102556:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Users\\\\g.roux\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:103500:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\"message\":\"Request failed with status code 400\",\"config\":{}}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Users\\\\g.roux\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269201:28)\",\"message\":\"Unexpected token u in JSON at position 0\"}"
---

---
"SyntaxError - Unexpected token u in JSON at position 0"
---
-------------------------------------------------------------------------------------------------------------------------------------------
![Capture2](https://user-images.githubusercontent.com/39985518/144014666-ea2812b5-ac0e-4521-be8f-b15f567eeeaf.JPG)

![Capture3](https://user-images.githubusercontent.com/39985518/144014698-d0c7cc22-9acc-4d82-8629-fb77cef2edb4.JPG)

**Comment by GuiRoux5555** [comment] 2021-11-30 16:10
@MCKRUZ I tried with 'Empty Bot' and 'Core Bot with Language' and I have the same problem.
Width Bot Composer 2.0, 2.1 and 2.1.1-nightly

**Comment by MCKRUZ** [comment] 2021-11-30 17:45
hmm...thats worse than my situation then.  did you try just simply empty bot with no changes then try and publish?

**Comment by GuiRoux5555** [comment] 2021-11-30 18:07
Without LUIS implementation publish is successful. The issue is on LUIS.

**Comment by benbrown** [comment] 2021-12-01 18:46
Is it possible that the LUIS key you are using is associated with a tenant that is different than your default tenant? Or different than the tenant you selected when logging in to Composer?

**Comment by GuiRoux5555** [comment] 2021-12-02 09:36
You are right, I am using a different tenant to deploy my application compared to my primary tenant. I tried by creating the resources on the default tenant from the start but unfortunately the same result.

**Comment by metkhoo** [comment] 2021-12-05 00:40
I am using Composer 2.1.1  Nodejs 14.18.2 .  Brand new BOT using "Empty Bot" template will publish OK.  As soon as a new trigger is added it falls over.  Adding the trigger forces LUIS to be used. Even deleting the added trigger still fails to publish.
As far as I can determine it is not possible to publish anything with Composer 2.1.1 except an empty bot with no triggers.
Please team.  Take a look at this as soon as possible.  I can't believe that Composer 2.1.1 would have been released without someone trying to publish to Azure... So how did they get it working?

**Comment by metkhoo** [comment] 2021-12-05 12:07
For my installation,  adding a "trigger" stops publishing.  Removing the trigger allows publishing again.

**Comment by metkhoo** [comment] 2021-12-05 12:36
This is what happens if I add a trigger:
---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"{\"stack\":\"Error: Request failed with status code 400\\n    at createError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102540:17)\\n    at settle (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102554:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:103498:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\"message\":\"Request failed with status code 400\",\"config\":{}}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269188:28)\",\"message\":\"Unexpected token u in JSON at position 0\"}"
---

---
"SyntaxError - Unexpected token u in JSON at position 0"
---

**Comment by benbrown** [comment] 2021-12-06 17:23
@metkhoo does the LUIS key come from the same tenant as the other resources? And the same account you are logged in to Composer with?

**Comment by metkhoo** [comment] 2021-12-07 15:43
Hi Ben,
LUIS key and login are all on the same tenant.

**Comment by metkhoo** [comment] 2021-12-07 18:31
Could it be that it is something to do with my ID?  In that it is linked to multiple tenants since I have to support multiple customers - and things are getting confused?
/Marcus

**Comment by MCKRUZ** [comment] 2021-12-07 18:57
I also have my ID linked to multiple tenants.  Perhaps that is a problem.

**Comment by benbrown** [comment] 2021-12-15 19:07
@MCKRUZ - I reached out to you via email to see if we can schedule time to screen share and hopefully get to the bottom of this. Let me know if you didn't get that!

**Comment by metkhoo** [comment] 2021-12-16 09:04
I could also show you. Will make time for this if you want

**Comment by metkhoo** [comment] 2021-12-22 16:36
Did this get resolved. Is there a workaround?

**Comment by tdurnford** [comment] 2022-01-10 19:27
@benbrown I there a workable solution to this issue?

**Comment by metkhoo** [comment] 2022-01-18 08:46
Any updates?

**Comment by metkhoo** [comment] 2022-02-01 12:26
Any updates?

**Comment by msomanathan** [comment] 2022-02-01 18:05
@benbrown Could you please provide an update to this issue?

**Comment by benbrown** [comment] 2022-02-07 19:06
Working with @MCKRUZ, we determined there seems to be a problem in some cases with the API used to assign LUIS keys to newly created applications.

I am waiting to hear back from a person on the LUIS team as to what might cause this problem for otherwise valid credentials.

**Comment by mrivera-ms** [comment] 2022-02-22 19:52
@benbrown, do you have any information about this? Should we follow up with the LUIS team?

**Comment by axelsrz** [comment] 2022-03-07 19:26
Hello @MCKRUZ do we have any update on this issue?

**Comment by MCKRUZ** [comment] 2022-03-07 19:45
@axelsrz I haven't heard anything @benbrown any news?

**Comment by slapinheimer** [comment] 2022-03-10 20:05
@benbrown & @MCKRUZ , 
This issue happening for me as well.  Created the bot using the Enterprise Calendar template.  The LUIS resource was created when building the publishing profile inside BFC.  I've also created a new authoring resource through Azure Portal. Both instances do not work. The item I see different from above is that my JSON.parse refers to "anonymous" inside the parenthesis. 
I have verified keys and endpoints and they all match.  

I have gone to https://luis.ai and created/configured/linked/published everything I know to connect within my LUIS prediction and Authoring resources. 
I made sure I am PIM'd when performing all publishing event.  
It appears that my permissions are aligned with my LUIS resources in Azure.  That would be my only area of suspicion where something is not passing through, which may explain the "anonymous" reference.  I had to add a space between the "< anonymous >" because this editor strips it out.  I suspect the everyone above sees the same message but their anonymous has been removed from their post as well. Below is my error output, with aforementioned alteration:

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"{\"stack\":\"Error: Request failed with status code 400\\n    at createError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102540:17)\\n    at settle (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:102554:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:103498:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\"message\":\"Request failed with status code 400\",\"config\":{}}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (< anonymous >)\\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269188:28)\",\"message\":\"Unexpected token u in JSON at position 0\"}"
---

---
"SyntaxError - Unexpected token u in JSON at position 0"
---

**Comment by slapinheimer** [comment] 2022-03-21 16:17
![image](https://user-images.githubusercontent.com/24736820/159303261-58681faf-f59b-4b8f-a3ee-09187058fb3b.png)
When going to import existing resources in the publish profile, I noticed a yellow squiggly on the opening bracket '{' in the JSON configuration.  The error mentions it is "Unable to load schema from ...", as well as, "Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from ..."

I am publishing under a single tenant.

**Comment by rslavey** [comment] 2022-03-28 20:22
I can reproduce this:

1. Update composer to latest version
2. Create simple bot with LUIS intent
3. In publish, add new profile creating all resources
4. Creating resources and publishing successful
5. Immediately try to publish again
6. Receive same "SyntaxError - Unexpected token u in JSON at position 0" on "start publish luis" step

**Comment by slapinheimer** [comment] 2022-03-30 13:25
After a little further investigating, the error is referencing a JSON.parse error occurring at line 269188 in the C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js file. Below is that section of code. It seems that something is missing or malformed with the access token.

async function publishLuisToPrediction(name2, environment, accessToken, luisSettings, luisResource, path4, logger, runtime) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  let {
    authoringKey: luisAuthoringKey,
    authoringEndpoint,
    authoringRegion: luisAuthoringRegion
  } = luisSettings;
  if (!luisAuthoringRegion) {
    luisAuthoringRegion = luisSettings.region || "westus";
  }
  if (!authoringEndpoint) {
    authoringEndpoint = `https://${luisAuthoringRegion}.api.cognitive.microsoft.com`;
  }
  const luisConfigFiles = (await getFiles(botPath(path4, runtime))).filter((filename) => filename.includes("luis.settings"));
  const luisAppIds = {};
  for (const luisConfigFile of luisConfigFiles) {
    const luisSettings2 = await fs.readJson(luisConfigFile);
    Object.assign(luisAppIds, luisSettings2.luis);
  }
  if (!Object.keys(luisAppIds).length)
    return luisAppIds;
  logger({
    status: BotProjectDeployLoggerType.DEPLOY_INFO,
    message: "start publish luis"
  });
  let accountList;
  let retryCount = 0;
  while (retryCount < 2) {
    try {
      const getAccountUri = `${authoringEndpoint}/luis/api/v2.0/azureaccounts`;
      const options = {
        headers: {Authorization: `Bearer ${accessToken}`, "Ocp-Apim-Subscription-Key": luisAuthoringKey}
      };
      const response = await import_axios.default.get(getAccountUri, options);
      accountList = (_a = response == null ? void 0 : response.data) != null ? _a : [];
      break;
    } catch (err) {
      if (retryCount < 1) {
        logger({
          status: AzurePublishErrors.LUIS_PUBLISH_ERROR,
          message: JSON.stringify(err, Object.getOwnPropertyNames(err))
        });
        retryCount++;
      } else {
        **const error = JSON.parse(err.error);**
        if (((_b = error == null ? void 0 : error.error) == null ? void 0 : _b.message) && ((_c = error == null ? void 0 : error.error) == null ? void 0 : _c.message.indexOf("access token expiry")) > 0) {
          throw new Error(`Type: ${(_d = error == null ? void 0 : error.error) == null ? void 0 : _d.code}, Message: ${(_e = error == null ? void 0 : error.error) == null ? void 0 : _e.message}, run az account get-access-token, then replace the accessToken in your configuration`);
        } else {
          throw err;
        }
      }
    }
  }

**Comment by Ohron** [comment] 2022-05-16 20:04
Still having this same issue for a couple of months now.  Does anyone have any further insights at to what the problem might be?

This issue only arises when the bot makes use of LUIS.  
Error noted the line number in the extension.js file.
stack":"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\**extension.js:276957:28**)","message":"Unexpected token u in JSON at position 0

Here is the segment of code in the extension.js file where the "Luis Publish" dies:

```
async function publishLuisToPrediction(name2, environment, accessToken, luisSettings, luisResource, path4, logger, runtime) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  let {
    authoringKey: luisAuthoringKey,
    authoringEndpoint,
    authoringRegion: luisAuthoringRegion
  } = luisSettings;
  if (!luisAuthoringRegion) {
    luisAuthoringRegion = luisSettings.region || "westus";
  }
  if (!authoringEndpoint) {
    authoringEndpoint = `https://${luisAuthoringRegion}.api.cognitive.microsoft.com`;
  }
  const luisConfigFiles = (await getFiles(botPath(path4, runtime))).filter((filename) => filename.includes("luis.settings"));
  const luisAppIds = {};
  for (const luisConfigFile of luisConfigFiles) {
    const luisSettings2 = await fs.readJson(luisConfigFile);
    Object.assign(luisAppIds, luisSettings2.luis);
  }
  if (!Object.keys(luisAppIds).length)
    return luisAppIds;
  logger({
    status: BotProjectDeployLoggerType.DEPLOY_INFO,
    message: "start publish luis"
  });
  let accountList;
  let retryCount = 0;
  while (retryCount < 2) {
    try {
      const getAccountUri = `${authoringEndpoint}/luis/api/v2.0/azureaccounts`;
      const options = {
        headers: {Authorization: `Bearer ${accessToken}`, "Ocp-Apim-Subscription-Key": luisAuthoringKey}
      };
      const response = await import_axios.default.get(getAccountUri, options);
      accountList = (_a = response == null ? void 0 : response.data) != null ? _a : [];
      break;
    } catch (err) {
      if (retryCount < 1) {
        logger({
          status: AzurePublishErrors.LUIS_PUBLISH_ERROR,
          message: JSON.stringify(err, Object.getOwnPropertyNames(err))
        });
        retryCount++;
      } else {
        const error = JSON.parse(err.error);
        if (((_b = error == null ? void 0 : error.error) == null ? void 0 : _b.message) && ((_c = error == null ? void 0 : error.error) == null ? void 0 : _c.message.indexOf("access token expiry")) > 0) {
          throw new Error(`Type: ${(_d = error == null ? void 0 : error.error) == null ? void 0 : _d.code}, Message: ${(_e = error == null ? void 0 : error.error) == null ? void 0 : _e.message}, run az account get-access-token, then replace the accessToken in your configuration`);
        } else {
          throw err;
        }
      }
    }
  }
```
Any help would be appreciated.

**Comment by Ohron** [comment] 2022-05-18 16:11
This return from line is causing the logic to fall into the CATCH.  
`const response = await import_axios.default.get(getAccountUri, options);
      accountList = (_a = response == null ? void 0 : response.data) != null ? _a : [];`

In my instance, the publish is calling: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/azureaccounts to get account information.  This call should return: 
`[
    {
        "AzureSubscriptionId": "{subscription_id}",
        "ResourceGroup": "{resource_group_name}",
        "AccountName": "{account_name}"
    }
]
`
But instead, I get this:
`{
  "error": {
    "code": "BadArgument",
    "message": "The source completed without providing data to receive."
  }
}
`
I've completely removed Bot Framework Composer from the equation and have gone directly to the LUIS/Cognitive Test Console: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5be313cec181ae720aa2b26c

I get the same BadArgument error regardless.  
I have confirmed that both the required Bearer token and Ocp-Apim-Subscription-Key being passed are correct.  

Are there any other Azure/LUIS configuration or permission items that could be missing and causing this error?

**Comment by dmvtech** [comment] 2022-06-14 19:10
Hi @MCKRUZ Does the scenario regarding legacy subscription that @Ohron has identified apply to your situation as well?

**Comment by dmvtech** [comment] 2022-06-29 00:00
Closing due to lack of response.

**Closed by dmvtech** 2022-06-29 00:00 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Needs-triage

**Comment by saikrishna-dev** [comment] 2023-10-18 17:02
I cloned the repo again and it worked :) .
