### ISSUE TITLE
Left navigation in home behaves differently

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5166] opened 2020-12-05 01:05 UTC
When I open Composer for the first time, I see bot related icons in the navigation as disabled:
<img width="711" alt="Screen Shot 2020-12-04 at 4 56 59 PM" src="https://user-images.githubusercontent.com/67944302/101228749-e0ff2300-3651-11eb-8590-73829ca106a6.png">

However, when I tap on a bot and then come back to the Composer home, I see a different view where I can see the name of the bot in the header and the icons enabled. This is confusing, as it is not clear whether I have left the bot and reached the Composer home.

<img width="858" alt="Screen Shot 2020-12-04 at 4 59 00 PM" src="https://user-images.githubusercontent.com/67944302/101228837-3c311580-3652-11eb-9ce5-1119d54c30ae.png">
 

v1.2.1-nightly.191674.827857c

4.11.0

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Restart Composer
2. Click on 'any bot'
3. Go back to Composer Home

## Expected behavior

I expect the Composer home to have different controls visible. As a user, when I go to Composer home, I either want to create a new bot, or open recent, or see samples etc. 

When I am in bot view, I expect different controls..

**Comment by mewa1024** [comment] 2021-07-02 17:39
closing as dupe of #7397

**Closed by mewa1024** 2021-07-02 17:39 UTC
Labels: R11 Bugbash, UX Design
