### ISSUE TITLE
Publish not working v2.1

### ISSUE THREAD

**Issue by ggrey** [microsoft/BotFramework-Composer#8526] opened 2021-08-05 03:51 UTC
## Describe the bug

When publishing to Azure status spinner keeps loading and/or displays DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND error message

## Version

Release: 2.1.0-nightly.262125.19cdc4

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Language Bot (nodejs - CoreWithLanguage) bot from Composer
2. Configure LUIS resources -> create new resources
3. Add new publishing profile -> create new resources (except all optional)
4. Resources provisioned

```
greybot002
Azure Bot
Global

greybot002
App Service plan
East US 2

greybot002
App Service
East US 2

greybot002-authoring
Language understanding
West US

greybot002-luis
Language understanding
West US

greybot002-luis-authoring
Language understanding
West US
```

5. Click Publish selected bots
6. Current config
```
{
  "name": "greybot002",
  "environment": "composer",
  "tenantId": "000-0000-000",
  "hostname": "greybot002",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "AZ-RG-grey-Dev-02",
  "botName": "greybot002",
  "subscriptionId": "000-000-000",
  "region": "eastus2",
  "appServiceOperatingSystem": "linux",
  "scmHostDomain": "",
  "luisResource": "greybot002-luis",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<Instrumentation Key>",
      "connectionString": "<connection string>"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<endpoint url>",
      "authKey": "<auth key>",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "<connection string>",
      "container": "<container>"
    },
    "luis": {
      "authoringKey": "00000000000000000000",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "00000000000000000000,
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "<subscription key>",
      "endpoint": "<endpoint>"
    },
    "MicrosoftAppId": "00000000000000000000",
    "MicrosoftAppPassword": "00000000000000000000"
  }
}
```

## Expected behavior

Bot is provisioned to recently deployed resources

## Additional context

Tested first with 2.1 and then updated to nightly version, now Status spinner loads indefinitely but no error message is displayed

**Comment by ohiobobcat** [comment] 2021-08-05 13:28
I'm experiencing the same issue when attempting to publish to a Linux App Service in Azure. I was able to create a C# bot and publish to a windows App Service successfully.

**Comment by srinaath** [comment] 2021-08-05 16:40
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/8489

**Closed by srinaath** 2021-08-05 16:40 UTC
Labels: Type: Bug, customer-reported, Bot Services, Needs-triage

**Comment by ggrey** [comment] 2021-08-05 17:20
Hi @srinaath the issue you linked does not resolve my problem, I already checked advanced json config and all value properties are displaying as they should, what are the next steps here?

**Comment by srinaath** [comment] 2021-08-05 17:22
@ggrey We haven't resolved the issue yet and are trying to find a resolution. I closed this ticket so that we can track the bugfix in the other ticket.
