### ISSUE TITLE
Undo Intent Deleted "Sorry, trigger intent is not found in lu file"

### ISSUE THREAD

**Issue by C0deBless** [microsoft/BotFramework-Composer#3490] opened 2020-06-24 16:24 UTC
I deleted a trigger "Intent Recognized" with name "ProblemaSistema".
After i clicked on Undo and "ProblemTicket" are restored correctly.
When i restared bot, i recived a follow error:

"Sorry, something went wrong with publishing. Try again or exit out of this task.
Sorry, trigger intent 'ProblemaSistema' is not found in lu file: compagnodibancopoc.en-us.lu"

I solved in this steps:
1. deleted "ProblemaSistema" Intent rec
2. Created new Intent Recognized with same name "ProblemaSistema" and past the utterances 

Thanks

**Comment by vishwacsena** [comment] 2020-06-24 20:15
@cwhitten can we prioritize investigating what's causing this error? @tomlm ran into this exact same error yesterday and the repro there was the following - 

1. Go to all up view and manually add an intent `#None` (or whatever intent name) with some utterances
2. Click on (re)start bot so a LUIS app is set up. 
3. Ensure there are no triggers associated with the new intent in the dialog. 
4. Go back to all up view and delete the `#None` intent and its utterances
5. Click on (re)start bot. 

Are we caching the lu somewhere? I suspect the diff we have in bf-lu might be throwing on mismatched set of intents. @boydc2014 @feich-ms

**Comment by feich-ms** [comment] 2020-06-28 03:06
@vishwacsena we didn't cache any lu content. This error `Sorry, trigger intent 'None' is not found in lu file: emptybot-1.en-us.lu` come from the cross train library. I think there might be some issues when composer calling cross-train lib. I will sync with @lei9444  to figure out the cause.

**Comment by lei9444** [comment] 2020-08-10 08:01
fixed in #3780

**Closed by lei9444** 2020-08-10 08:01 UTC
Labels: Needs investigation, Type: Bug
