### ISSUE TITLE
Text layout of About Tab on About Screen is incorrect

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6955] opened 2021-04-14 19:01 UTC
## Describe the bug
The "About Text" on the "About Tab" on the "About Screen" is incorrectly formatted. The text width appears to be 1/2 of the page width, resulting in formatting that looks very unexpected. 

See screen shot below. 

## Version

Composer Nightly.
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to About Page
2. Click on the About Tab
3. Read the About Text
4. Observe that the text isn't full-width, and is curring off at what looks like ~40 columns. 

## Expected behavior
Normally formatted / justified HTML. 

## Screenshots
![image](https://user-images.githubusercontent.com/1165321/114764408-c2ecb200-9d18-11eb-89ce-2533b9820d5a.png)

**Comment by garypretty** [comment] 2021-04-20 09:24
@mewa1024 does issue #7121 encapsulate the items within this bug?  If so please close as a dup. If not, let's get everything for the About page into a single issue and close the others to reduce noise.

**Comment by mewa1024** [comment] 2021-04-20 15:00
Good point. Closing as a dupe of #7121

**Closed by mewa1024** 2021-04-20 15:00 UTC
Labels: R13 Bugbash, Team: Authoring, Type: Bug, UX Design
