### ISSUE TITLE
multi choice using json array

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#8580] opened 2021-08-19 15:12 UTC
hi 

i need to present multiple choices to the user from a json array. when i run it in the emulator the choices dont appear
please help

![2021-08-19 at 5 11 PM](https://user-images.githubusercontent.com/49028761/130093936-03581287-7de2-4465-85bb-acd04609c599.jpg)

![2021-08-19 at 5 11 PM](https://user-images.githubusercontent.com/49028761/130094035-1e16f12c-7a90-438e-ba67-80dc48edf490.jpg)

**Comment by stevkan** [comment] 2021-08-19 22:32
@afahmy11, the problem is you are passing in an object into the array instead of values. The prompt is recognizing that you have supplied a value within the property and starts listing them, starting with '1'. But, it doesn't know what to do with the passed in object because it was expecting a spread.

Change the `dialog.array` property value to: `["1","2","3"]`. You will then see the output like below:

![image](https://user-images.githubusercontent.com/18403946/130152622-ee21b928-5786-4b3c-8438-820ae78cd8ee.png)

**Comment by afahmy11** [comment] 2021-08-20 08:16
thanks, isn't there a way to present the values from an array of objects? my array is actually a json content

**Comment by stevkan** [comment] 2021-08-20 19:34
If it's a requirement that you pass in an array of objects, then you can use the below expression. Testing proved successful when I ran it.

**dialog.array**
```js
[
  {
    "1": "One",
    "2": "Two"
  },
  {
    "3": "Three",
    "4": "Four"
  }
]
```

**Multi-choice prompt:** In User input => Array of choices => Write an expression, we need to iterate over every object in `dialog.array`. For each item in each object, we need to iterate over the choices and return each of the values. This is all wrapped in the `flatten()` function so only a single array is returned.
```js
flatten(foreach(dialog.array, item => foreach(item, choice => choice.value)))
```

**End result**
![image](https://user-images.githubusercontent.com/18403946/130284254-21c69723-5afe-48b6-8549-37046de0646b.png)

You can read about the pre-built functions used here (and others) in this [doc](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0). You can also safely test the use of these functions using the LG and Expression Playground, located [here](https://playgroundclient.azurewebsites.net/).

As this should resolve your issue, I am going to close this.

**Closed by stevkan** 2021-08-20 19:34 UTC
Labels: customer-reported, Bot Services, customer-replied-to
