### ISSUE TITLE
Error when navigating to 'Package manager' or when trying to merge schemas

### ISSUE THREAD

**Issue by timtos** [microsoft/BotFramework-Composer#8781] opened 2021-11-08 10:01 UTC
I found [this issue here](https://github.com/microsoft/BotFramework-Composer/issues/8435#issue-948763485) but as it is closed, I decided to create a new issue. Hopefully that is ok.

## Describe the bug
Navigating to the Package Manager always gives an error message and it is not possible to merge schema files.

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

I installed the Bot Framework Composer and all prerequisites like described in [Install Bot Framework Composer](https://docs.microsoft.com/en-us/composer/install-composer?tabs=windows).

After that I created the Enterprise People Bot:
![image](https://user-images.githubusercontent.com/2648014/140720837-7582aed2-cc73-4052-8e48-b4b19a9f9c32.png)

After everything is generated, I navigate to the package manager and immediately the following pop-up is shown:
![image](https://user-images.githubusercontent.com/2648014/140721151-e3dad9cf-5d9c-448c-8da6-a41144d536c0.png)

> Could not load component list:Error GetManagerDialog.dialog: Interface Microsoft.IDialog is not defined Error GetProfileDialog.dialog: Interface Microsoft.IDialog is not defined Error ResolveUserDialog.dialog: Interface Microsoft.IDialog is not defined Error must have a merged .schema to merge .uischema files *** Could not merge components ***

And trying to execute the schema merge in Visual Studio Code gives the following output:

![image](https://user-images.githubusercontent.com/2648014/140721451-2b909283-7548-49fb-8367-c49ab9bf3d7e.png)

>  .\update-schema.ps1          
> Running schema merge.
> Finding component files
> Parsing component .schema files
> Merging component schemas
> Error GetManagerDialog.dialog: Interface Microsoft.IDialog is not defined 
> Error GetProfileDialog.dialog: Interface Microsoft.IDialog is not defined 
> Error ResolveUserDialog.dialog: Interface Microsoft.IDialog is not defined
> 
> 
> *** Could not merge components ***
> Schema merge failed. Restoring previous versions.

## Expected behavior

All needed types should be found and all components should be able to load.

**Comment by timtos** [comment] 2021-11-09 13:01
Update: I compiled the bot framework composer locally and in debug mode, I'll get the following output:

![image](https://user-images.githubusercontent.com/2648014/140928203-4c0d0fe7-4471-4013-90e8-3eb2d3e39814.png)

As also stated in [this stackoverflow post](https://stackoverflow.com/questions/69848569/bot-framework-composer-installed-packages-do-not-appear-in-installed-menu), it is a problem with special characters in the path.

Unfortunately, I couldn't find the exact spot where things go wrong. Anybody here with more experience debugging node? If I could apply a quick fix in code that would be perfect for a start. :)

Thanks a lot and cheers,
Tim

**Comment by johnataylor** [comment] 2021-11-15 19:21
@dmvtech any update on this?

**Comment by dmvtech** [comment] 2021-11-18 20:25
Hi @timtos If you try and do the same from a path that doesn't have the special character, does it still fail? I am not able to reproduce the issue at all. Can you share what the special character is; perhaps that might allow me to repro.

**Comment by timtos** [comment] 2021-11-19 10:49
Hi @dmvtech, in my case it is the German Umlaut 'ü', in the stackoverflow article it seems to be some kind of asian character. And yes, everything is running smooth, when running the project on different machines or within the account of different users without any special characters. I tried to debug more but I cannot find the line where this actually happens. In the places I looked, UTF-8 is used correctly?! Thanks a lot for your support.

**Comment by benbrown** [comment] 2021-11-30 19:27
The source of this problem might be the bf-cli libraries that do the schema merging.  It could also be the electron packaging having a hard time with the special characters.

Can you bot project or the composer app to a different location?

**Comment by gabog** [comment] 2021-12-13 19:04
Hi @timtos, let us know if @benbrown suggestion worked, I am closing this one for now, feel free to re-open if you are still having issues.

**Closed by gabog** 2021-12-13 19:04 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
