### ISSUE TITLE
FactSet is not working $data from set property

### ISSUE THREAD

**Issue by jsia9** [microsoft/BotFramework-Composer#8798] opened 2021-11-17 13:04 UTC
## Describe the bug
i ve been trying for a few hours to get this working.
when using SetProperty to set the array used by FactSets in Adaptive Cards, the key and value entries are not taken into account.
## Version
Version:  1.4.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

 as I am using a few custom behaviors in nodejs.

## OS

 macOS

## To Reproduce

my situation is identical to [this one ](https://stackoverflow.com/questions/67673769/botframework-composer-use-factset-to-show-multiple-data), the only difference is that i get 'a scope of 'key' wasnt found'
set property dialog.carddataproperties with the array:

`[
  {
    "key": "Assigned to",
    "value": "Matt Hidinger"
  },
  {
    "key": "Due date",
    "value": "Not set"
  }
]`

`        {
            "type": "FactSet",
            "facts": [
                {
                    "$data": "${dialog.carddataproperties}",
                    "title": "${key}:",
                    "value": "${value}"
                }
            ]
        }`

The error in Bot Framework Emulator is consistently the same.
```label:"TurnError"
valueType:"https://www.botframework.com/schemas/error"
value:"DialogContextError: Error: Error: DialogStateManager.getValue: a scope of 'key' wasn't found. [SendActivity_mpITBn] Error occurred when evaluating 'Attachments=${json(fromFile('.\\adaptivecard-Broken.json'))}'. [__temp__3c036cd87b1042cbbdc81b93d3c81283] Error occurred when evaluating '-```${SendActivity_mpITBn()}```'., Error: Error: DialogStateManager.getValue: a scope of 'key' wasn't found. [SendActivity_mpITBn] Error occurred when evaluating 'Attachments=${json(fromFile('.\\adaptivecard-Broken.json'))}'. [__temp__202e876c26e340e1b1bf93d7ace0e385] Error occurred when evaluating '-```${SendActivity_mpITBn()}```'."
```
it seems that I am not the only one to have this issue[ but never solved here](https://stackoverflow.com/questions/67673769/botframework-composer-use-factset-to-show-multiple-data)

Even more confusing is that , I tried to replicate it the exact sequence in the official designer
https://adaptivecards.io/designer/ and it works. 

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${dialog.carddata.title}",
            "wrap": true
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "style": "Person",
                            "url": "${dialog.carddata.creator.profileImage}",
                            "size": "Small"
                        }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "text": "${dialog.carddata.creator.name}",
                            "wrap": true
                        },
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "text": "Created {{DATE(${string(dialog.carddata.createdUtc)}, SHORT)}}",
                            "isSubtle": true,
                            "wrap": true
                        }
                    ],
                    "width": "stretch"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "${dialog.carddata.description}",
            "wrap": true
        },
        {
            "type": "FactSet",
            "facts": [
                {
                    "$data": "${dialog.carddata.properties}",
                    "title": "${key}:",
                    "value": "${value}"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "View Standards",
            "url": "${dialog.carddata.viewUrl}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

Data:
```
{"dialog":{ "carddata" :
{
  "title": "my title",
  "description": "Ok, details and description",
  "creator": {
    "name": "Debugging request",
    "profileImage": "https://www.example.com/growth_96x96.svg"
  },
  "createdUtc": "2017-02-14T06:08:39Z",
  "viewUrl": "https://example.com/wiki",
  "properties": [
    {
      "key": "1.",
      "value": "my first value"
    },
    {
      "key": "2",
      "value": "my second value: this is 2"
    },
    {
      "key": "Assigned to",
      "value": "Matt Hidinger"
    },
    {
      "key": "Due date",
      "value": "Not set"
    }
  ]
}
}}```

is there a difference in the type of a dialog property?
## Expected behavior

I should have a generated adaptive card.
## Screenshots
https://stackoverflow.com/questions/67673769/botframework-composer-use-factset-to-show-multiple-data

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by dmvtech** [comment] 2021-11-19 17:18
Hi @jamalsia I can reproduce and see the same. I'm not sure yet on how to make this work, but obviously some colliding between adaptive expressions and adaptive card templating.

I can (not surprisingly) get the card to work if I avoid the `$data` templating and just hard coding something like:
```
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "mytitle",
                    "value": "myvalue"
                }
            ]
        }
    ],
```

@boydc2014 Can you take a look at this and see if you have any thoughts/ideas/suggestions?

**Comment by boydc2014** [comment] 2021-11-24 01:41
@jsia9 Is that possible for you to avoid $ in your data's key? 

$ in Composer represents a shorthand for a special memory path (dialog.foo) https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-memory-states?view=azure-bot-service-4.0#dialog-scope.

I think for that reason, it complains as not found.

**Comment by dmvtech** [comment] 2021-11-24 17:01
Hi @boydc2014 Adaptive Card templating uses the `$`. Please see more info [here](https://docs.microsoft.com/en-us/adaptive-cards/templating/).

Do we need to make changes to resolve this or will/would this be a limitation of using Adaptive Cards within Adaptive Expressions?

**Comment by munozemilio** [comment] 2022-01-04 22:10
Hello @boydc2014 ...is there any update on this?

**Comment by carlosscastro** [comment] 2022-01-24 18:37
@boydc2014 could you please follow up on this issue? Do we have updates on this front?

**Comment by msomanathan** [comment] 2022-02-04 18:59
@boydc2014 Could you please provide updates to this issue? Thanks!

**Comment by mrivera-ms** [comment] 2022-02-22 19:55
@boydc2014, do you  have any updates on this?

**Comment by dmvtech** [comment] 2022-03-01 04:16
@jsia9 It looks like adaptive card templating is not implemented in the SDK.
https://github.com/microsoft/botframework-sdk/issues/6477

Closing this for tracking on that issue/feature request. 

Thanks for bringing this to our attention and for your patience.

**Closed by dmvtech** 2022-03-01 04:16 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
