### ISSUE TITLE
Bot deployed in teams

### ISSUE THREAD

**Issue by Laktos** [microsoft/BotFramework-Composer#5052] opened 2020-12-02 15:41 UTC
We've set up a bot, deployed it on Kubernetes, which contains our backend and the bot image. We've registered the bot on Azure Portal, and then connected our bot to the Teams client by using the link that was provided on Azure Portal. 

The bot is reachable, but doesn't respond as expected. For one person in the team, all commands and buttons seems to work, but only for his desktop client on Windows. On mobile and his web-client with teams, he can still press some buttons and get responses, but not use our "reset-user-ID" command. 

I'm not really sure what the issue is here, and therefore this issue might be in the wrong place. On places where he gets responses, the others in the project either get no response at all (we can still see the request coming in to our Kubernetes pod), or "An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set." in the chat. We can however get some output from our "Cancel" dialog, with our greeting card being displayed, but no further than this. 

We've edited the buttons to send "msteams" objects as data. We've reverted to an older commit, and the reset-user-ID still doesn't work for other than this one person in the team, but we can get further into the dialog without getting the same error as before. 

We've tried restarting the backend and using another client first, but that doesn't seem to help. We don't have authentication for the bot yet, if that could be an issue. 

Any suggestions on how to fix this? 
I'm using MacOS, but we've had others with Windows which have came to the same result.

**Comment by dmvtech** [comment] 2020-12-02 17:50
Hi @Laktos This does sound very odd. It makes me want to assume that is due to Kubernetes , but I can't say for sure.

A few questions:

- What state store are you using? 
  - Default memory state or have you configured CosmosDB or Blob storage?
- Is this in production or development?
- If prod, do you have the option to create another bot for testing/troubleshooting?

**Comment by Laktos** [comment] 2020-12-03 09:38
We have default memory state, we assume, since we haven't made any changes there. We noticed that there's a trial for cosmos db which we could try to see if that works better. We're reverting back to working commits of the bot, and trying baby-steps to see what seems to break the bot. 
The bot is in production, but we don't have the resources to create another bot for testing. But I guess you could say the reverted branch now is a testing bot. Will update with progress!

**Comment by dmvtech** [comment] 2020-12-03 17:32
Thanks! Yes, memory state is great for development, [but is horrible for production](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state?view=azure-bot-service-4.0#storage-layer). This would completely explains erratic behavior like you are seeing. 

Cosmos works well, and there is also a new server less Cosmos, but beware; that is in preview (additionally, you'll need to make sure the container is created already with partition key `\id`

**Comment by dmvtech** [comment] 2020-12-07 18:19
@Laktos Any updates?

**Comment by Laktos** [comment] 2020-12-07 22:37
We believe the issue was that we either had empty "sendactivities" lying around. Like: 
SendActivity12345()
-
Either that, or it was that we resolved a merge conflict incorrectly. But it still seems strange that it would work for some, but not others. 
Could be that we just got lucky and it worked long enough to see that the bot crashed and re-deployed. This happened when running reset. This was fixed by increasing the available RAM on kubernetes. Now it seems to work as intended!

**Comment by dmvtech** [comment] 2020-12-07 23:13
Ok, thanks. I'm going to go ahead and close this one. Feel free to open another if you are able to identify any specific and reproducible bugs. Thanks!

**Closed by dmvtech** 2020-12-07 23:13 UTC
Labels: Bot Services, Type: Question, customer-replied-to, customer-reported

**Comment by Laktos** [comment] 2020-12-08 00:35
@dmvtech We figured out what was causing the first set of issues. It was that we when deploying the bot to teams, or elsewhere in the process of starting the bot, generated two sets of language generation files, where only the .en-us.lg files were changed when editing in composer. This caused the people using teams with Swedish to not get the correct responses.
