### ISSUE TITLE
New bot dialog: Needs a way to paste a path for the location

### ISSUE THREAD

**Issue by RustyDes** [microsoft/BotFramework-Composer#3190] opened 2020-05-26 21:43 UTC
## Describe the bug
The location field on the new bot dialog does not let the user type or paste a path. One is forced to navigate up and down to find the relevant location which is painful for long paths, and lacks discoverability for switching to a different drive (at least for Windows Users).

Expected the control would be a textbox with an auto complete drop down or recent drop down similar to what one would find on a search engine page or on typical desktop apps (e.g. see the search box in Visual Studio).

## Version
1.0.0

## Browser
N/A

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer
2. Click on New
3. Click on Next
4. Try to paste a value in the Location field, or to edit the Location

## Expected behavior
Can type and paste text in the Location box.

**Comment by liweitian** [comment] 2020-05-27 06:28
![aaaa](https://user-images.githubusercontent.com/24380525/82985009-d1a97800-a025-11ea-8324-84e331954e75.gif)
Hi @RustyDes, you can navigate to the root path first then switch to other disks. And we will consider your other suggestions and discuss with designers. We will have a solution to make it easier to use. Thx.

**Comment by hibrenda** [comment] 2020-05-28 00:42
https://github.com/microsoft/BotFramework-Composer/issues/3009

**Comment by cwhitten** [comment] 2020-05-31 20:22
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3009

**Closed by cwhitten** 2020-05-31 20:22 UTC
Labels: Type: Bug
