### ISSUE TITLE
numbered list not working in bot on web channel

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5374] opened 2020-12-17 11:51 UTC
Hi,

We have added a logic for numbered list in the bot. Numbered list is getting displayed as expected when bot is run in the emulator but same numbered list not working on web channel.

We have referred below docs for text formatting.

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html

![image](https://user-images.githubusercontent.com/70739031/102483056-31cb3e80-408a-11eb-9cce-cb13cb40c109.png)

Below is the screenshot in emulator.

![image](https://user-images.githubusercontent.com/70739031/102483431-bcac3900-408a-11eb-8072-8aecc7b9fc48.png)

Below is the screenshot in web channel.

![image](https://user-images.githubusercontent.com/70739031/102483825-4eb44180-408b-11eb-8c1a-cdef92d97526.png)

We have used bot framework web chat to integrate with web channel.

Would you please suggest some solution.

Thanks....

**Comment by dmvtech** [comment] 2020-12-18 00:00
Hi @BeheraMadan 

Unfortunately, I am unable to reproduce this issue. Here is my LG:

```
# HeroCard()
[HeroCard
   title = BotFramework Hero Card
   subtitle = If you do not see an option to renew your Action Pack Subsription in Partner Center, please check your partner verification status in your orgianization's profile:
   text = 1. Navigate to your account settings\r2. Select organization\r3. Then choose legal, then "Partner" tab.
   buttons = ${cardActionTemplate('imBack', 'Show more cards', 'Show more cards')}
]
```

Would you mind sharing yours? If any different, does the above work for you?

For me, it is working in Emulator, Test in Web Chat, Web Chat iframe, and my own implementation of Web Chat using the [welcome sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event).

Does it work for you in **Test in Web Chat** or the **iframe** versions of Web Chat?

**Comment by dmvtech** [comment] 2020-12-18 01:01
Possibly related: https://github.com/microsoft/BotFramework-Composer/issues/4876

**Comment by BeheraMadan** [comment] 2020-12-18 14:26
Hi,

We have used same logic as you mentioned above. It is working in Test in Web Chat and the iframe versions of Web Chat as well. 

In our scenario Bot is integrated in sitecore page with the help of  bot framework webchat. May be we need to investigate more on sitecore.

Thanks...

**Comment by dmvtech** [comment] 2020-12-18 18:03
Ok, thanks. Sound like a good plan. I'm going to close this as it doesn't sound like it's related to either Composer or Emulator. If you do find some sort of bug with Web Chat (and outside of sitecore) please open a bug [here](https://github.com/microsoft/BotFramework-WebChat/issues/new?assignees=&labels=Bug%2C+Pending%2C+customer-reported%2C+Bot+Services&template=bug_report.md&title=).

**Closed by dmvtech** 2020-12-18 18:03 UTC
Labels: Bot Services, customer-replied-to, customer-reported
