### ISSUE TITLE
Components: communicating creation time and visibility

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6248] opened 2021-03-05 18:17 UTC
## Describe the bug
Not sure if it's just me, but this definitely takes longer than 1 minute (around 5). 
After I've installed multiple other templates already, an Empty bot takes long too. Let's set expectations and communicate the estimated time, now I have no idea how long it might take and be tempted to click it away (seems like it's frozen). Plus it's not very visible the spinner with the actions (can we leverage a banner/pop up with white background for contrast, rest surrounding is non actionable grey). 

## Version
![image](https://user-images.githubusercontent.com/43533472/110155857-86a76700-7de6-11eb-84f3-e06cdd28dde3.png)

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
Select any package, wait after create. 

## Expected behavior
communicate estimated time (_"this will take a few minutes"_) and the 3 states you already have (loading (i), building runtime (ii), merging packages (iii) as 1 -3, so you know how long it might take still. For contrast and you will watch it for a longer time, include a white banner of some sort. 

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/110156717-996e6b80-7de7-11eb-86f1-9dbb46db2cbd.png)
![image](https://user-images.githubusercontent.com/43533472/110156766-a8551e00-7de7-11eb-9b7c-b3417a1a7d0c.png)

**Comment by hatpick** [comment] 2021-03-09 23:04
closing, Duplicate of #6224

**Closed by hatpick** 2021-03-09 23:04 UTC
Labels: Area: Components, R12 Bugbash, Type: Bug, UX Design
