### ISSUE TITLE
Deleted bot remains in recents and some files still on disk

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Composer#7007] opened 2021-04-15 13:27 UTC
## Describe the bug

When deleting a bot, it remains in the recents list until Composer is restarted.  Additionally, the sln and directory still remain on disk.

## Version

Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot
2. Delete it via Project Settings
3. Note it still appears in Recents
4. Check disk for remain files.

## Expected behavior

Should be deleted in entirety and recents refreshed.

**Comment by srinaath** [comment] 2021-04-15 17:20
Closing this as a dupe of #6808

**Closed by srinaath** 2021-04-15 17:20 UTC
Labels: Needs-triage, R13 Bugbash, Type: Bug
