### ISSUE TITLE
Composer should attempt retries if it receives rate limiting response from LUIS

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3094] opened 2020-05-15 21:38 UTC
With large LUIS models, Composer may receive 429 errors from the LUIS API if too many calls are made too quickly.

We should implement a retry / backoff feature so that Composer can gracefully handle these and still make sure the publish completes.

**Comment by Stevenic** [comment] 2020-05-15 21:40
It doesn't even have to be a large model. The Free Tier is rate limited to 5 request/second so you can easily hit this with even small models.

Related issue #3024

**Comment by cwhitten** [comment] 2020-05-24 23:13
Closing this as a dupe of #3024

**Closed by cwhitten** 2020-05-24 23:13 UTC
Labels: Needs-triage, Type: Enhancement
