### ISSUE TITLE
Telemetry: unexplained discrepancy between Start/end session. Suspect issue in capturing end session

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7280] opened 2021-04-22 22:30 UTC
Need to review & verify end-session telemetry capture as we observe huge discrepancy with end-session captured only 2 vs. start at ~12k.

FYI @garypretty

**Comment by tdurnford** [comment] 2021-04-22 23:02
@scheyal When the user closes Composer, Electron emits a ['before-quit'](https://www.electronjs.org/docs/api/app#event-before-quit) event, which we use to capture the session end telemetry event.  As noted in the Electron documentation - ['before-quit'](https://www.electronjs.org/docs/api/app#event-before-quit) "will not be emitted if the app is closed due to a shutdown/restart of the system or a user logout." So if the user logs out or shuts the down computer without closing Composer first, Composer would not send a session end telemetry event on Windows. I'll have to investigate if there is a better way than listening for the ['before-quit'](https://www.electronjs.org/docs/api/app#event-before-quit) Electron event to determine if the user closed Composer.

Also, when the user closes Composer, we flush all of the queued telemetry events including the session end event to the server which processes and forwards the events to App Insights. It might be the case that Composer is closing before it finishes processing all of the events. We should see if there is a way to persist the server until it finishes processing all of the telemetry events.

Additionally, @garypretty, mentioned that the App Insights NPM package uses sampling by default when you are using an instrumentation key instead of a connection string. This could also cause a discrepancy between the start and end session events - probably not that large of a discrepancy though. We should update the pipelines to use the connection string before the next release to avoid unnecessary data loss.

**Comment by darrenj** [comment] 2021-04-28 11:47
@tdurnford Have we made the move to connection strings for Composer level telemetry that we collect? I suspect sampling may well be the root cause for gaps in telemetry... If not, I would debate a loss of product level telemetry is candidate for p0.

**Comment by tdurnford** [comment] 2021-04-28 14:26
@cwhitten @garypretty  Can you weigh in on updating the instrumentation key to the connection string in the build pipelines? I'm not sure we'll have adequate time to test in the nightlies before the release.

**Comment by cwhitten** [comment] 2021-04-28 14:35
@tdurnford if we've got the connection strings lets go ahead and start testing

**Comment by tdurnford** [comment] 2021-04-28 14:38
@cwhitten @garypretty Due to the App Insights permission changes, I'm not able to access the resource and get the connection string.

**Comment by cwhitten** [comment] 2021-04-28 14:47
Makes sense. Lets block this one until we can connect with @garypretty to get these.

**Comment by sgellock** [comment] 2021-04-28 15:40
@garypretty can you get the connection string?  @tdurnford also, Kate can get you the connection string.  @cwhitten can provide more details.

**Comment by garypretty** [comment] 2021-04-28 16:52
@tdurnford If you don't have it by then, I can get this for you tomorrow. Travelling home right now and I don't have my Yubikey.

**Comment by tdurnford** [comment] 2021-04-28 18:16
@garypretty @cwhitten @sgellock 

@kaerm  was kind enough to retrieve the connection string for me, and I updated the pipelines accordingly. I'm waiting for the nightlies to run, so we can confirm that there aren't any issues with the connection string. I tested the build locally with the connection, and there weren't any issues, so I don't think there should be any regressions.

**Comment by tdurnford** [comment] 2021-04-28 22:04
@garypretty @cwhitten @sgellock 

I updated all of the pipelines to use the connection string instead of the instrumentation key, and @kaerm verified that the nightly builds using the connection string are still logging telemetry data to App Insights. 

@kaerm Thanks for your help!

**Closed by tdurnford** 2021-04-28 22:04 UTC
Labels: P0, ShipRoom-Approved, Type: Bug

**Comment by sgellock** [comment] 2021-04-28 23:15
Thanks @tdurnford

**Comment by darrenj** [comment] 2021-04-29 11:23
Thanks @kaerm and @tdurnford !
