### ISSUE TITLE
intent=DeferToRecognizer_LUIS_ getting added to QnAMaker

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#6677] opened 2021-04-04 21:05 UTC
I created BOT with 2 dialogs and and added QnAMaker KB to each one of them. BOT is able to recognize text using LUIS and fetching as requested.  Since BOT is crosstrained, **intent=DeferToRecognizer_LUIS_**  is getting added to QnAMaker KB as shown below.
![image](https://user-images.githubusercontent.com/2491903/113521388-19c3f000-9591-11eb-9760-dd872f052d09.png)

When I type which is of crosstrained item then, **intent=DeferToRecognizer_LUIS_** is prompting. I tried to filter data based on dialog. But this one, I'm unable to stop showing to user.
![image](https://user-images.githubusercontent.com/2491903/113521425-4972f800-9591-11eb-8bc3-c82965b2b766.png)

Any help would be much appreciated.

**Comment by peterinnesmsft** [comment] 2021-04-05 18:07
@narulasrinivas would you be able to share any specifics around the various dialog assets (.dialog, .lu, .lg, .qna) files that you are feeding into cross-training that are producing this result? That will help us better diagnose where any potential issues exist. Thank you!

**Comment by narulasrinivas** [comment] 2021-04-07 11:07
@peterinnesmsft - Here is repo link where you can download required assets.

https://github.com/narulasrinivas/devp2

**Comment by narulasrinivas** [comment] 2021-04-08 20:34
@peterinnesmsft -Can you please help me to resolve this issue? I given the code in github repo link. Please let me know if you want me to provide any other information.

**Comment by peterinnesmsft** [comment] 2021-04-09 16:40
Hi @narulasrinivas, I'll be taking a further look today and get back to you shortly. Apologies for the delay.

**Comment by lauren-mills** [comment] 2021-04-12 16:26
@peterinnesmsft, I'm going to assign this to support to try to repro

**Comment by dmvtech** [comment] 2021-04-13 18:39
@lauren-mills I'm able to reproduce. Happy to share or try/test anything.

![image](https://user-images.githubusercontent.com/43397658/114603584-c155b800-9c4c-11eb-8050-f2dcfde96565.png)

**Comment by narulasrinivas** [comment] 2021-04-16 20:17
@dmvtech / @cwhitten - Can you please help me on this issue?

**Comment by narulasrinivas** [comment] 2021-04-20 13:12
@cwhitten - Can you please help me with this ticket or any alternate way to achieve this functionality?

**Comment by narulasrinivas** [comment] 2021-04-23 12:39
@lei9444 - Can you please help me to resolve this issue?

**Comment by tsuwandy** [comment] 2021-05-06 04:06
@lei9444, @boydc2014, can we look into this issue?

**Comment by boydc2014** [comment] 2021-05-06 04:17
> @lei9444, @boydc2014, can we look into this issue?

Yes, looks like the crossTrainedRecognizerSet isn't catching this intent. let us repro this first @lei9444

**Comment by narulasrinivas** [comment] 2021-05-14 20:08
@boydc2014 & @lei9444 & @cwhitten - Can someone help me on this to move forward?

**Comment by boydc2014** [comment] 2021-06-03 01:34
@narulasrinivas sorry for the late response. 

The root cause of this issue is in our default setup of recognizers(LUIS and QNA), we did a pre-processing step called cross-train which added a special QA pair into the final QnA KB, with a special answer (intent=DeferToRe...). This special answer works as an tip in the final post-processing of recognizer results and usually helpful to get a balanced result between Luis and QnA.

In your case, besides the default qna recognizer, in you dialog, there is also an explicit QnaDialog that directly visit the kb and get answer in which the special answer (intent=DeferTo...) was not respected. This is a gap in the SDK code, and we will look to address it soon. 

For now, there are a few workarounds
1. disable cross-train by adding a section in the settings page
2. add an explicit filter of answer after the qna dialog step
I will get more detailed samples for the workarounds and get back to you

**Comment by boydc2014** [comment] 2021-06-17 08:33
Update @narulasrinivas, with #6549 been merged, what you can do is disable qna cross-train via adding a section like 
```
crossTrain : {
   inner: false
}
```

Closing this for now，let us know if this works for you

**Closed by boydc2014** 2021-06-17 08:33 UTC
Labels: Bot Services, ExemptFromDailyDRIReport, Support, Team: Platform, customer-replied-to, customer-reported

**Comment by SSanjeevi** [comment] 2021-08-31 19:29
@boydc2014  - even after updating this in appsettings json , these qna are added in deployments.

**Comment by SSanjeevi** [comment] 2021-11-18 06:52
Managed this by hitting the qnamaker with strict filters of the sources i need to be filtered with "source_name_metadata".

So that i can use both the cross-train feature and qnamaker querying flow smoothly.  Now i have the qnaIntentRecognizer as an intent for cross train featured answers switching between qna and luis effectively and custom qnamaker call without cross train data in answer.

Made the qnamaker call as an http request with the following query - so that avoiding the 'crosstrain' source.

`
{"question":"how",
"strictFilters": [
      { "name": "source_name_metadata","value": "Custom Editorial"},
      { "name": "source_name_metadata","value": "chitchat"}
    ],
    "strictFiltersCompoundOperationType": "OR"}
`

[Detailed explanation here](https://lkgforit.com/cross-train-feature-issue-and-work-around-in-bot-framework-composer).

**Comment by Ramabhishek97** [comment] 2023-08-08 14:52
Is this error resolved? Please someone help I'm also facing the same error intent=DeferToRecognizer_LUIS
