### ISSUE TITLE
Failing to install prerelease packages

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#5919] opened 2021-02-24 03:36 UTC
My package is marked as preview and an error occurs when trying to install on latest nightly build:

![image](https://user-images.githubusercontent.com/698939/108943881-7afdb880-760e-11eb-8f93-2f06ddf37cfb.png)

**Comment by Stevenic** [comment] 2021-02-24 03:47
Actually it's failing to install any package :(

**Comment by carlosscastro** [comment] 2021-02-24 15:19
The problem is the '&' that is present in the query string of the --source parameter used by composer will be interpreted by the command line since it is not escaped. As such, cmd will say 'this is the end of the current command and the next command is to run prerelease.exe' which clearly doesn't exist. Did you add the package source yourself? If yes, could you share the name and url you added? If not, we likely just have to escape the query string in this url in the package manager code. Let us know which one it is and we can take it from there.

**Closed** 2021-02-24 22:59 UTC
Labels: Needs-triage, Type: Bug
