### ISSUE TITLE
Hostname case sensitivity causes publishing to fail

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7366] opened 2021-04-26 10:53 UTC
## Describe the bug

I provisioned new resources using Composer for a bot.  I set the hostname as ContosoInsurancePVASkill and the provisioning was successful.  However, when I tried to publish I received an error that the "hostname was incorrect".

In the publishing profile was set as

```json
  },
  "hostname": "ContosoInsurancePVASkill",
  "luisResource": "ContosoInsurancePVASkill-luis"
}
```

I tried a couple of times, got the same error.

I then manually updated the publishing profile to the following, which seems to have resolved the issue, allowing me to publish successfully. So it seems that the hostname is case sensitive?

```json
  },
  "hostname": "contosoinsurancepvaskill",
  "luisResource": "ContosoInsurancePVASkill-luis"
}
```

## Version

Version:  1.4.0-nightly.239011.99a74b9
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

cc @Dewain27

**Comment by cwhitten** [comment] 2021-04-27 16:07
@GeoffCoxMSFT we have experienced this where these failures have been hard to repro or arbitrary with the zip deploy mechanism. Retrying the operation is usually successful

**Comment by garypretty** [comment] 2021-04-27 16:09
FWIW I tried several times with the same issue and it was only when I manually updated the resource name that it worked.

**Comment by GeoffCoxMSFT** [comment] 2021-04-30 17:24
@garypretty Could you tell me a little more as I'm not able to reproduce this yet.  
Are you on Mac or Windows?  
What type of bot did you create? (e.g. empty-bot C#, Azure Web)
What optional resources did you deploy? (e.g. cosmos, etc.)  And did you deploy both authoring and runtime LUIS?

**Comment by Dewain27** [comment] 2021-04-30 19:17
@garypretty  moving to P1 as we can't repro the issue.  When you get back, please connect with @GeoffCoxMSFT.

**Comment by garypretty** [comment] 2021-05-11 16:13
@benbrown I just tried again, using the original bot, reverting the settings back to the original string. It published fine 🤔

**Closed** 2021-05-25 17:03 UTC
Labels: Area: Publish, P1, R13 Bugbash, Type: Bug
