### ISSUE TITLE
Wrap command bar in overflow set

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2807] opened 2020-04-28 16:57 UTC
Currently as small viewports (>1200px) the Start bot gets cut off and scrolling is not enabled.

**Comment by cwhitten** [comment] 2020-04-28 16:58
https://developer.microsoft.com/en-us/fluentui#/controls/web/overflowset

**Comment by a-b-r-o-w-n** [comment] 2020-06-25 16:43
Duplicate of #3494

**Closed by a-b-r-o-w-n** 2020-06-25 16:43 UTC
Labels: R10, Type: Bug
