### ISSUE TITLE
Rocket menu top level menu icon does not toggle rocket menu display behavior

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#7232] opened 2021-04-21 19:24 UTC
## Describe the bug
The behavior of the rocket menu icon is not consistent with the notifications icon.  The notifications icon will acts as a toggle to display or hide the notifications pane.  The rocket ship menu only displays the rocket ship menu, but doesn't not hide it when the pane is visible and the icon is clicked.

## Version
Version:  1.4.0-nightly.237625.d1378c6
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Open an existing bot, though you could create a new one
3. If the rocket menu is visible, click the rocket menu icon in the top level menu, far right hand side. Notice the pane does not go away.  
4. If the rocket menu is not visible, click the rocket menu icon in the top level menu, far right hand side.  now with the rocket menu displayed, perform step 3 above.

## Expected behavior
rocket menu icon behaves consistently with other information panels, e.g. notifications panel.

**Comment by emivers8** [comment] 2021-04-21 21:16
Duplicate of #6993

**Closed by emivers8** 2021-04-21 21:16 UTC
Labels: Needs-triage, Type: Bug
