### ISSUE TITLE
How to implement CI/CD pipeline/ version control system in composer?

### ISSUE THREAD

**Issue by SaikatRoyChowdhury** [microsoft/BotFramework-Composer#3679] opened 2020-07-22 15:36 UTC
Is Bots created out of Bot Composer are ready for Enterprise wide implementation -- like Bot with potential of 200 K users ?
Then how to maintain the version control of development.

**Comment by cwhitten** [comment] 2020-07-23 16:41
Closing as a dupe of: https://github.com/microsoft/BotFramework-Composer/issues/3339

@SaikatRoyChowdhury follow the linked issues for updates on this.

**Closed by cwhitten** 2020-07-23 16:41 UTC
Labels: Needs-triage
