### ISSUE TITLE
Teams OAuth not working

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#8941] opened 2022-01-25 12:01 UTC
## Describe the bug
BOT Developed using Bot Composer , Teams channel, OAuth not working

## Version

![image](https://user-images.githubusercontent.com/26645750/150973177-3cedf356-127c-4cae-99f1-7c274a48726e.png)

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1. Create a Bot with OAuth Card
2. Test locally - Success
3. Post to Cloud - Enable Teams Channel
4. Test in teams
5. 5. It shows the below error

## Expected behavior
It should be able to authenticate

## Screenshots
![image](https://user-images.githubusercontent.com/26645750/150972986-cd262a08-8e96-4d1c-840c-5333f9feb1cc.png)

## Additional context
Referred to suggestions as well in bug id #8941

**Comment by anishprasad01** [comment] 2022-01-25 20:09
There is an ongoing investigation into this problem [here](https://github.com/microsoft/botbuilder-dotnet/issues/6071).

**Comment by anishprasad01** [comment] 2022-01-31 16:34
@aparnaji,

As per the [documentation on Teams Auth](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#adding-teams-authentication), you need to create and upload an `app manifest` to Teams in order to test OAuth scenarios. If you just click `Open in Teams`, you're communicating with the bot by ID and not installing it. Due to security considerations, that scenario is not intended to work.

Please see the [Teams auth sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth) for an example on how to use an app manifest. You don't need any of the code in the sample, just the Teams App Manifest folder. See the README to understand how to fill it in, though it is straightforward JSON.

Let me know if this works for you.

**Comment by aparnaji** [comment] 2022-02-03 11:43
________________________________

**Comment by aparnaji** [comment] 2022-02-03 11:44
Hi @anishprasad01 

This worked as a App in teams.

**Comment by anishprasad01** [comment] 2022-02-03 20:40
Since this is expected behavior, I am going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-02-03 20:40 UTC
Labels: customer-reported, Bot Services, customer-replied-to
