### ISSUE TITLE
Can't create resources for node function bots

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7433] opened 2021-04-27 21:17 UTC
## Describe the bug
Azure can't find the directory when trying to create resources for node function bots.

Probably related to #7343 

## Version
Version:  2.0.0-nightly.239895.e3e1b3e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. create a blank node bot template
2. go to the publishing screen
3. create a new profile

## Expected behavior
Azure directories should be selectable

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116313801-191f1380-a763-11eb-903f-c0b955dc7f47.png)

## Additional context
Probably related to #7343

**Comment by Virtual-Josh** [comment] 2021-04-27 21:37
Copying this note from the other issue here:

As one more weird thing it seems like this issue is related to a cached state. Once you see this error it prevents you from provisioning any new resources. However if you close and reopen composer it seemingly unblocks itself?

**Comment by Virtual-Josh** [comment] 2021-04-28 00:22
One extra note, it seems like this only occurs when the bot is a function bot. web apps seem to be fine.

**Comment by sgellock** [comment] 2021-04-28 17:45
@GeoffCoxMSFT can you investigate and determine if this is the same issue as #7343, and if not, then let's understand what the issue is.  would like to get this one in

**Comment by sgellock** [comment] 2021-04-29 15:34
Shiproom - @Virtual-Josh we're not able to repo.  can you repro?  if so, can you reach out to @GeoffCoxMSFT

**Comment by Virtual-Josh** [comment] 2021-04-29 16:39
I worked with Geoff yesterday and it appears the problem is once Composer expires your login credentials due to inactivity it doesn't subsequently reprompt you to login again. I was able to repro that twice yesterday with Geoff. I'll copy this message over to the other ticket since it's very likely these are dupe tickets.

**Comment by GeoffCoxMSFT** [comment] 2021-04-29 17:02
I am pretty confident this is a dupe of #7343, so will close this.  If we discover different we can re-open.

**Closed by GeoffCoxMSFT** 2021-04-29 17:02 UTC
Labels: Area: Publish, P0, Type: Bug
