### ISSUE TITLE
Custom Action Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Laktos** [microsoft/BotFramework-Composer#5106] opened 2020-12-04 12:53 UTC
## Describe the bug
I'm getting "Object reference not set to an instance of an object" whenever using a custom action. MultiplyDialog, the given example, doesn't work either. It has worked before, with the custom actions that I have made, but now none is working. 

## Version

Release: 1.2.1

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

Follow steps on https://docs.microsoft.com/en-us/composer/how-to-add-custom-action. 
That is: 
Add <ProjectReference Include="..\customaction\Microsoft.BotFramework.Composer.CustomAction.csproj" /> to Microsoft.BotFramework.Composer.WebApp.csproj. 
Decomment line 30 and 138 on Startup.cs in azurewebapp folder. 
Create new schemas and cs files for custom actions, with "arg1" in schemas being referenced in the .cs file as JsonPropery. 
Run ./update-schemas.ps1. 
Try using custom action in emulator.
Problem appearing

## Expected behavior
MultiplyDialog returning the value of arg1*arg2.

## Screenshots
![custom](https://user-images.githubusercontent.com/74136596/101166094-05e69c80-3638-11eb-9fe1-4b380b723740.png)

**Comment by dmvtech** [comment] 2020-12-04 23:55
I am unable to reproduce this issue. Although I _am_ hitting this one: https://github.com/microsoft/BotFramework-Composer/issues/4582

Are you able to debug? Can you see what gets sent in the output/console? One way to do so is; close Composer (you can keep Emulator open), navigate to your `runtime` folder, then run `dotnet run --project azurewebapp`. When it's up and running, start a new conversation in Emulator to make sure the welcome happens. Then trigger the dialog to run your custom action. Hopefully there's some useful info when the error happens. Share that here. Alternatively, you can open the runtime solution in Visual Studio or VS Code.

**Comment by Laktos** [comment] 2020-12-05 11:20
Improvement! The commant dotnet run --project azurewebapp made the custom action work without the error. It does however present the same issue after starting the bot through composer after closing the instance of dotnet run.

**Comment by Laktos** [comment] 2020-12-05 11:26
Okay I figured it out.. The custom runtime wasn't referenced in the config. This has been a bit problematic in git however as it seems to keep the local reference instead of refering to the local machine it is being run on. But it does work now!

**Comment by dmvtech** [comment] 2020-12-07 18:18
> Okay I figured it out.. 

Great!

>The custom runtime wasn't referenced in the config. This has been a bit problematic in git however as it seems to keep the local reference instead of refering to the local machine it is being run on. But it does work now!

I'm not completely clear on what you describe above. Are you talking about a local .git repo? Is the config (assuming you mean appsettings.json here), in a modified/changed state or has it been staged/committed? Just wanted to see if there seems to be another (different) bug or not.

**Comment by dmvtech** [comment] 2020-12-10 23:36
I'm closing this one as it it is working for you. If you have reproducible steps to exhibit a bug, please open another issue.

**Closed by dmvtech** 2020-12-10 23:36 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
