### ISSUE TITLE
Unable to Publish bot

### ISSUE THREAD

**Issue by nickfrancis** [microsoft/BotFramework-Composer#9236] opened 2022-06-17 14:16 UTC
I have a Bot built in Framework Composer. I have an existing subscription in Azure with what I believe to be all the right resources however when publishing using existing resources I am continually getting this error:

```
---
"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: getaddrinfo ENOTFOUND mks1cpm-chatbot.scm.azurewebsites.net\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\\\",\\\"message\\\":\\\"getaddrinfo ENOTFOUND mks1cpm-chatbot.scm.azurewebsites.net\\\",\\\"code\\\":\\\"ENOTFOUND\\\",\\\"config\\\":{}}\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\nfrancis\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Users\\\\nfrancis\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectDeploy.deployZip (C:\\\\Users\\\\nfrancis\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276954:13)\"}"
---

---
"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). {\"stack\":\"Error: getaddrinfo ENOTFOUND mks1cpm-chatbot.scm.azurewebsites.net\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\",\"message\":\"getaddrinfo ENOTFOUND mks1cpm-chatbot.scm.azurewebsites.net\",\"code\":\"ENOTFOUND\",\"config\":{}}"
```

One question I have is if a Web App resource is needed for successful deployment?

Would appreciate any help that can be given!

FYI I am working within an Azure tenant that has limited my permissions & rights. I can create Web Apps but have no access to Azure AD or Apps....

**Comment by nickfrancis** [comment] 2022-06-17 15:08
Hi Anish
Thanks for the reply. I've already got various resources up & running which I believe should cover all the resources needed for the bot:

- Key Vault
- Language
- Azure Bot
- Azure Cosmos DB Account
- Managed Identity
- App Service Plan
- Search service
- Cognitive services multi-service account
- Application Insights
- Log Analytics workspace
- Language understanding
- QnA maker
- App service plan
- App service
- App insights
- Storage account
- Language understanding
- Search service

I'm unsure whether a Web App is needed.

Also in Composer when I went to configure development resources it seemed to grab all the details of the various resources successfully....

[](url
![Details](https://user-images.githubusercontent.com/2065211/174325288-628f7187-ebc4-4e96-9ffb-b267e34bd90a.jpg)
)

**Comment by anishprasad01** [comment] 2022-06-17 15:20
The Azure resource labeled "Web App" is not specifically needed, no. It just runs on App Services anyway. 

I suppose the next steps would be to check that the regions for everything line up, and if you can, try to publish a simple empty bot to new Azure resources, then delete them immediately. This will tell us whether your issue is specific to this bot, which might help narrow down the cause.

**Comment by nickfrancis** [comment] 2022-06-17 15:30
App creation failed on a blank bot pointing to new resources - believe part of my Azure restrictions:
![image](https://user-images.githubusercontent.com/2065211/174329935-d139feff-8e13-4de6-aba9-68a4bebbdb62.png)

**Comment by anishprasad01** [comment] 2022-06-17 15:49
Hmm, yeah, if that's the case, it's likely there's nothing we can do about it. Looks like you will need to reach out to your tenant admin and request a permissions elevation. If your permissions are supposed to be enough, you would then need to turn to Azure Support. We manage the SDK, but we don't have control over Azure permissions.

That said, since this is outside of our scope, I'm going to go ahead and close this issue. If you have further issues after you get your permissions sorted out, please feel free to open a ticket in the appropriate repository.

**Closed by anishprasad01** 2022-06-17 15:49 UTC
Labels: customer-reported, Bot Services, customer-replied-to
