### ISSUE TITLE
[Accessibility][Object Information - Settings-Publish-Create Azure Resource]: For empty edit field, its information is not correctly read by Screen reader in scan mode. 

### ISSUE THREAD

**Issue by ShellySoni** [microsoft/BotFramework-Composer#2110] opened 2020-02-27 11:52 UTC
**User Experience:**
Screen reader users will not get the proper information if for empty edit field, its information is not correctly read by Screen reader in scan mode. 

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. "Bot Framework Composer" homepage will gets opened.
3. Select any of the previously created bot from "Recent Bots" or create one from the available Bots under 'Examples' and activate it.
4. Select 'Settings' from left navigation.
5. Select 'Publish' button available under 'Configuration'.
6. Navigate to "Create azure resources" and activate it.
7. "Set bot name and password" dialog gets opened.
8. Leave all the edit field empty and navigate in scan mode using up/down arrow keys and observe the issue.

**Actual Result:**
When all the edit fields left blank, its information is not correctly read by Screen reader in scan mode. Screen reader read as 'Bot Framework Composer' i.e. start reading the page title information.

**Expected Result:**
Whether any edit field is having some data or empty, screen reader should convey its proper information.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%204.2.1%20%E2%80%93%20Object%20Information.docx?d=weee97bbd999048a08b036ea775581aa8&csf=1&e=UYEfO3

**Attachment:**
[MAS4.2.1_Settings.zip](https://github.com/microsoft/BotFramework-Composer/files/4261441/MAS4.2.1_Settings.zip)

**Comment by beyackle** [comment] 2020-03-26 16:57
I've tested this out and I couldn't repro it - the screen reader reads out the field names, including "invalid" if it's a required field that's been left empty. So it looks like it's already been fixed.

**Comment by ashish315** [comment] 2020-04-04 09:09
As checked and verified on below environment, the issue is fixed now. So, we are closing the issue.
**Test Environment**
Browser: Microsoft Edge Dev {Version 83.0.467.0 (Official build) dev (64-bit)}
OS build: 2004 (19588.1000)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Closed by ashish315** 2020-04-04 09:09 UTC
Labels: A11yCT, A11yLowImpact, A11yMAS, Accessibility, Fixed, HCL- BotFrameworkComposer, MAS4.2.1, Severity4
