### ISSUE TITLE
HTTP Request Body JSON Array is converted to JSON Object with index as keys

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Composer#8876] opened 2021-12-30 07:55 UTC
I am trying to hit a backend REST API (Method: PATCH) that accepts the following JSON array as body:
```
[
  {
    "op": "replace",
    "path": "/dueDate",
    "value": "${user.control_assignment_due_date}"
  }
]
```
However, when I view the emulator's trace, I see that the body is transformed into a JSON object like below, which is not accepted by our backend service.

`content:"{"0":{"op":"replace","path":"/dueDate","value":"12/31/2021"}}"`

I am facing the same issue with yet another POST API where I need to send a JSON array as body. 

Please help me in resolving this issue.

About my Bot Framework Composer:
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by anishprasad01** [comment] 2021-12-30 23:08
Hi @RamkumarManavalan,

I attempted to reproduce your issue, and I was able to send a JSON array to an endpoint. I created a simple C# test bot in Composer 2.1.1 and sent an array payload in the request body to Postman Echo to verify functionality. 

In the following image, you can see the implementation in Composer:
<img width="248" alt="3" src="https://user-images.githubusercontent.com/33945547/147793289-041aaa3a-4f60-4d8e-ad1e-68c6660465a9.png">

Make sure when you implement the HTTP request action, that you select `array` as the body type.

Here you can see the bot running and getting a response back:
<img width="251" alt="1" src="https://user-images.githubusercontent.com/33945547/147793313-21fa9d41-636e-4a61-9460-7e72c40b87fe.png">

Finally, here's an image of the trace in the Emulator. As you can see, the array structure is preserved.
<img width="137" alt="2" src="https://user-images.githubusercontent.com/33945547/147793335-f8b6c16e-ad3e-4c82-9f29-e20ba80ffe87.png">

Let me know if this solves your issue. If not, can you please provide more details regarding your bot and the implementation of your HTTP requests?

- What version of Composer are you running?
- What type of bot is this? C# or Node?
- What bot runtime is this? Web App or Functions?

**Comment by RamkumarManavalan** [comment] 2021-12-31 05:22
Thank you Anish for your response. Yes, I have selected array only. But it is still converted to json object.

<img width="351" alt="Screenshot 2021-12-31 at 10 48 33 AM" src="https://user-images.githubusercontent.com/7835046/147804845-171173bf-8c6d-4e35-961e-c0d51f124e76.png">

Below is the emulator screenshot:
<img width="601" alt="Screenshot 2021-12-31 at 10 48 11 AM" src="https://user-images.githubusercontent.com/7835046/147804866-ab231b56-a6d9-48c5-8ae2-e825e2d186f3.png">

About my Bot Framework Composer:
Version: 2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I have chosen Node, but I have not written any custom code/extension.

My runtime settings:
"runtime": {
    "command": "npm run dev --",
    "customRuntime": true,
    "key": "adaptive-runtime-js-webapp",
    "path": "../"
  }

**Comment by RamkumarManavalan** [comment] 2022-01-02 04:26
I upgraded to 2.1.1, but am still facing the issue.

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by anishprasad01** [comment] 2022-01-03 16:28
Perhaps the JsonStringify method might help you achieve this. https://github.com/microsoft/botbuilder-js/search?q=JsonStringify

It makes use of the standard JSON Stringify method.

**Comment by RamkumarManavalan** [comment] 2022-01-03 18:31
Let me try that. However, I was able to get rid of the issue, just a while ago, by selecting string and just specifying the array directly. Please see below.
<img width="339" alt="Screenshot 2022-01-04 at 12 01 55 AM" src="https://user-images.githubusercontent.com/7835046/147966265-b476b89f-fac9-48ed-ab13-d4b94fd4e2ef.png">

**Comment by anishprasad01** [comment] 2022-01-03 18:40
Since we have a functional workaround, I am going to go ahead and close this issue. If you have further difficulties regarding this item, please comment and we can reopen it.

**Closed by anishprasad01** 2022-01-03 18:40 UTC
Labels: customer-reported, Bot Services, customer-replied-to
