### ISSUE TITLE
LUIS region & QnA maker subscription key not present when it's been added via pop-up

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6896] opened 2021-04-13 14:58 UTC
## Describe the bug
When adding LUIS key + region, and then QnA maker key in the next step. Only my LUIS key shows in the settings page. 

## Version
![image](https://user-images.githubusercontent.com/43533472/114574200-19f77600-9c8a-11eb-9473-7ecc3e025932.png)

## Expected behavior
Expect the QnA keys to be present plus LUIS region.

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/114573948-e4528d00-9c89-11eb-89ef-514cc2e7824c.png)

**Comment by benbrown** [comment] 2021-04-13 16:43
Thanks for the report @Quirinevwm! This is a dupe of #6822  that should be fixed momentarily.

**Closed by benbrown** 2021-04-13 16:43 UTC
Labels: R13 Bugbash, Type: Bug, topic: creation
