### ISSUE TITLE
Start Bot Failed with exception 1260

### ISSUE THREAD

**Issue by deepak1959** [microsoft/BotFramework-Composer#5450] opened 2021-01-05 16:56 UTC
## Describe the bug

I got installed the Bot Frame Work Composer by my admin team. I created the Sample Bot project.
But when I try to start bot I am getting following error:
Start bot failed

System.ComponentModel.Win32Exception (1260): This program is blocked by group policy. For more information, contact your system administrator. at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Microsoft.DotNet.Cli.Utils.Command.Execute() at Microsoft.DotNet.Tools.Run.RunCommand.Execute() at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args) at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient) at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Version

Bot Framework Composer 1.3.0
.net version 3.1.404

## OS

Windows

**Comment by dmvtech** [comment] 2021-01-05 19:39
Hi @deepak1959 This appears to be an issue with your Environment. Specifically, that the Windows group policy is not allowing that application to run. I think it is the bot/runtime that is probably not allowed, not the authoring Composer application (which your admin team already installed for you).

Please work with your administration team to further troubleshoot and investigate. You may want to [export your runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime) for ease of use/troubleshooting.

**Comment by MPCoreDeveloper** [comment] 2021-01-06 07:45
If you are not a local admin you are at the mercy of the domain admin when it comes to group policies 
f you are a local admin and you do not like to be trumped by the domain admin you have the power to leave the domain. However, you do not have the power to override the rules of the domain set forth by the group policy. (Well, you have, but only by hacking your way out the policies you do not like in the registry )

**Comment by deepak1959** [comment] 2021-01-06 15:06
> Hi @deepak1959 This appears to be an issue with your Environment. Specifically, that the Windows group policy is not allowing that application to run. I think it is the bot/runtime that is probably not allowed, not the authoring Composer application (which your admin team already installed for you).
> 
> Please work with your administration team to further troubleshoot and investigate. You may want to [export your runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime) for ease of use/troubleshooting.

Please check the exception, it is trying to create a diagnostic process:  System.Diagnostics.Process.StartWithCreateProcess, which is being blocked. Is it required to run Bot? Please remember many users will have this king of restrictions.

**Comment by MPCoreDeveloper** [comment] 2021-01-06 15:14
Your bot runtime is created by the composer and then executed  , so the program that creates the executable is allowed to run but the executable that is generated is NOT allowed to run on your system ( that is thus the problem )

**Comment by dmvtech** [comment] 2021-01-14 19:05
Closing as the issue is identified and the changes need to be made on your end. You need to export the runtime and then have the administrators allow that executable to run.

**Closed by dmvtech** 2021-01-14 19:05 UTC
Labels: Bot Services, Team: Runtime & Publishing, Type: Bug, customer-replied-to, customer-reported
