### ISSUE TITLE
[Usable_Create from Template]: Complete focus is visible on 'Create from Template section' rather than only on radio button.

### ISSUE THREAD

**Issue by ShellySoni** [microsoft/BotFramework-Composer#2012] opened 2020-02-19 07:44 UTC
**User Experience:**
For users to understand the focus on radio buttons, ocus should only be visible on 'Create from Template' radio button rather than to its whole section i.e. including its all templates. 

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Navigate on homepage with tab key up to 'New' button and press enter on it.
3. 'Create from scratch' pop up will open.
4. Observe the issue with keyboard focus on 'Create from Template' radio button.

**Actual Result:**
Complete focus is visible on 'Create from Template section' rather than only on radio button.

**Expected Result:**
Focus should only be visible on 'Create from Template' radio button rather than to its whole section i.e. including its all templates. 

**MAG Guidelines:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7bF98F4235-B6BD-47D3-8DA4-F28B9B6FBFA8%7d&file=Guideline%20101%20%E2%80%93%20Recommended%20Assistive%20Technology%20Tools%20for%20MAS%20Testing%20of%20Microsoft%20Digital%20Properties.docx&action=default&mobileredirect=true

Attachment:
[Usable_Create from template.zip](https://github.com/microsoft/BotFramework-Composer/files/4223676/Usable_Create.from.template.zip)

**Comment by liweitian** [comment] 2020-04-16 11:26
@corinagum I updated UI last week. I think the issue here is solved.

**Comment by corinagum** [comment] 2020-04-16 17:25
@liweitian I agree! Thank you!

**Comment by ashish315** [comment] 2020-04-21 18:52
As UI gets updated, the issue is not repro any more. So, HCL is closing the bug.

**Closed by ashish315** 2020-04-21 18:52 UTC
Labels: A11yCT, A11yUsable, Accessibility, Fixed, HCL- BotFrameworkComposer, Severity4
