### ISSUE TITLE
Dotnet function bots don't work in Azure

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7541] opened 2021-04-30 22:04 UTC
## Describe the bug
Dotnet function bots throw errors when deployed to azure.

This MIGHT be related to #7501, but since it's a different platform the core issue might be different.

## Version
Version:  2.0.0-nightly.241421.a3f796f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Using the empty bot template create a dotnet function bot
2. Provision resources for the bot (leave all the addons checked)
3. Deploy the bot
4. In the azure portal test the bot in web chat

## Expected behavior
The bot should respond

## Additional context
Here's the log from azure 

2021-04-30T21:56:34.572 [Information] Initializing Warmup Extension.
2021-04-30T21:56:34.576 [Information] Initializing Host. OperationId: 'accc8185-a57c-4b09-a760-f5402751a635'.
2021-04-30T21:56:34.577 [Information] Host initialization: ConsecutiveErrors=3, StartupCount=4, OperationId=accc8185-a57c-4b09-a760-f5402751a635
2021-04-30T21:56:34.581 [Information] ApplicationInsightsLoggerOptions{"SamplingSettings": {"EvaluationInterval": "00:00:15","InitialSamplingPercentage": 100.0,"MaxSamplingPercentage": 100.0,"MaxTelemetryItemsPerSecond": 20.0,"MinSamplingPercentage": 0.1,"MovingAverageRatio": 0.25,"SamplingPercentageDecreaseTimeout": "00:02:00","SamplingPercentageIncreaseTimeout": "00:15:00"},"SamplingExcludedTypes": null,"SamplingIncludedTypes": null,"SnapshotConfiguration": null,"EnablePerformanceCountersCollection": true,"HttpAutoCollectionOptions": {"EnableHttpTriggerExtendedInfoCollection": true,"EnableW3CDistributedTracing": true,"EnableResponseHeaderInjection": true},"LiveMetricsInitializationDelay": "00:00:15","EnableLiveMetrics": true,"EnableDependencyTracking": true,"DependencyTrackingOptions": null}
2021-04-30T21:56:34.581 [Information] LoggerFilterOptions{"MinLevel": "None","Rules": [{"ProviderName": null,"CategoryName": null,"LogLevel": null,"Filter": "<AddFilter>b__0"},{"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider","CategoryName": null,"LogLevel": "None","Filter": null},{"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider","CategoryName": null,"LogLevel": null,"Filter": "<AddFilter>b__0"},{"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider","CategoryName": null,"LogLevel": "Trace","Filter": null}]}
2021-04-30T21:56:34.582 [Information] LoggerFilterOptions{"MinLevel": "None","Rules": [{"ProviderName": null,"CategoryName": null,"LogLevel": null,"Filter": "<AddFilter>b__0"},{"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider","CategoryName": null,"LogLevel": "None","Filter": null},{"ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider","CategoryName": null,"LogLevel": null,"Filter": "<AddFilter>b__0"},{"ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider","CategoryName": null,"LogLevel": "Trace","Filter": null}]}
2021-04-30T21:56:34.582 [Information] FunctionResultAggregatorOptions{"BatchSize": 1000,"FlushTimeout": "00:00:30","IsEnabled": true}
2021-04-30T21:56:34.582 [Information] SingletonOptions{"LockPeriod": "00:00:15","ListenerLockPeriod": "00:00:15","LockAcquisitionTimeout": "10675199.02:48:05.4775807","LockAcquisitionPollingInterval": "00:00:05","ListenerLockRecoveryPollingInterval": "00:01:00"}
2021-04-30T21:56:34.582 [Information] HttpOptions{"DynamicThrottlesEnabled": true,"MaxConcurrentRequests": 100,"MaxOutstandingRequests": 200,"RoutePrefix": ""}
2021-04-30T21:56:34.582 [Information] Starting JobHost
2021-04-30T21:56:34.583 [Information] Starting Host (HostId=dfecho430, InstanceId=778f3a49-a041-4295-b651-c8820f1e1467, Version=3.0.15571.0, ProcessId=7156, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~3)
2021-04-30T21:56:34.587 [Information] Loading functions metadata
2021-04-30T21:56:34.588 [Information] 3 functions loaded

-- nasty bit
2021-04-30T21:56:34.602 [Error] A host error has occurred during startup operation 'accc8185-a57c-4b09-a760-f5402751a635'.System.IO.FileLoadException : Could not load file or assembly 'DFEcho430, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext,String ilPath,String niPath,ObjectHandleOnStack retAssembly)at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)at Microsoft.Azure.WebJobs.Script.ScriptHost.GetDirectTypes(IEnumerable`1 functionMetadataList) at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 667at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync(CancellationToken cancellationToken) at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 302at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs : 254at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at D:\a\1\s\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 278

**Comment by sgellock** [comment] 2021-05-03 15:03
Shiproom - let's get a PR for this and then discuss

**Comment by peterinnesmsft** [comment] 2021-05-03 17:47
Initial assessment is that this appears to be a dupe of #7538 - will dig in and confirm.

**Comment by tracyboehrer** [comment] 2021-05-05 17:12
I believe this is a dupe.  This is the load error I was getting.  This has been corrected by https://github.com/microsoft/BotFramework-Composer/issues/7538

**Comment by peterinnesmsft** [comment] 2021-05-05 21:03
Closing as dupe.

**Closed by peterinnesmsft** 2021-05-05 21:03 UTC
Labels: P0, Type: Bug
