### ISSUE TITLE
I can't add a trigger

### ISSUE THREAD

**Issue by amesquitaACD** [microsoft/BotFramework-Composer#5760] opened 2021-02-11 10:20 UTC
## Describe the bug
When I want to add a new Dialog Started trigger, I have an error.

## Version
1.3.1 nightly

## OS
Windows

## To Reproduce

1. Go to 'Add a trigger'
2. Choose 'dialogue event' and 'Dialog Started'
3. Send

## Screenshots
![image](https://user-images.githubusercontent.com/78791585/107621834-298d1b00-6c57-11eb-828f-479efa070410.png)
![image](https://user-images.githubusercontent.com/78791585/107621850-301b9280-6c57-11eb-8581-68236946f880.png)

## Additional context
I am using version 1.3.1 nightly due to a problem I recently reported : https://github.com/microsoft/BotFramework-Composer/issues/5738

**Comment by srinaath** [comment] 2021-02-11 17:39
Closing as its a dupe of #5728

**Closed by srinaath** 2021-02-11 17:39 UTC
Labels: Bot Services, Needs-triage, Type: Bug, customer-reported
