### ISSUE TITLE
Sluggish performance after running for 30 minutes or more

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4728] opened 2020-11-09 18:37 UTC
## Describe the bug

I've been using Bot Composer for 30+ minutes, and now the UI is very slow. Sometimes shows "not responding"

Task Manager:
![image](https://user-images.githubusercontent.com/9756166/98581970-4862c680-2290-11eb-80df-464b10d24e3d.png)

## Version
v1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer
2. Wait 30 minutes
3. Sloooooow

## Expected behavior

Expect that it does not get slow.

## Screenshots

![image](https://user-images.githubusercontent.com/9756166/98582060-6defd000-2290-11eb-92da-3632a049a566.png)

![image](https://user-images.githubusercontent.com/9756166/98582110-79db9200-2290-11eb-88d2-edb25daeb7e2.png)

**Comment by dmvtech** [comment] 2020-11-10 23:02
Hi @kdubious Thanks for reporting. Currently looking into this. I am unable to reproduce so far. 

A few questions:

- This is just with Composer open, no bot loaded/running correct?
- If not, does it behave any differently depending on the bot you have open/loaded? (close Composer and reopen another bot after, as a test)

**Comment by dmvtech** [comment] 2020-11-10 23:38
@kdubious 

_If possible_, I'd be interested in seeing the memory leak over time. We can do this by looking at Performance Monitor logs.

If you're up for this, here are the steps:

- Save [this template](https://raw.githubusercontent.com/dmvtech/randomstuff/master/composer_memory_perfmon.xml) to your machine.
- Open perfmon (start->run->_perfmon_)
- Data Collector Sets
- New Data Collector Set
- Give it a good name and use the option `Create from a Template`
- Browse...
- Select the xml template previously saved 
- Select a location that can store the logs
- Finish
- When you are ready, right click the collector set and start. 
- Open Composer
- I've set the duration to be 35 minutes (if that isn't going to be too impactful for you) and it should stop automatically at that point.

Send a link to the log file(s). This isn't required, but might help in determining what is happening.

**Comment by kdubious** [comment] 2020-11-10 23:41
@dmvtech It's running

**Comment by kdubious** [comment] 2020-11-10 23:42
I do have / have had a bot loaded when this happens. (demo Echo Bot)

**Comment by kdubious** [comment] 2020-11-11 03:22
[perf.zip](https://github.com/microsoft/BotFramework-Composer/files/5521535/perf.zip)

@dmvtech : Here are 2 runs, one with a fresh composer, and the second after it had been running for a few hours.

**Comment by kdubious** [comment] 2020-11-12 16:32
@dmvtech Is this what you need?

**Comment by dmvtech** [comment] 2020-11-14 00:19
Yes @kdubious Thank you.

Through my amateur eyes, it does appear to be a leak. Most concerningly/blatantly in the private bytes. Starts tracking the process with an amount of 191MB and ends with 2.4GB (assuming these two logs were of the same process, I forgot to have you record `process Id`). 

Seen here:
![image](https://user-images.githubusercontent.com/43397658/99131582-65690380-25c8-11eb-817e-763dc19e8dbe.png)

Can you give us the output of `dotnet --info` on this machine please?

@cwhitten Do you have someone to assign to this who can look into it further or have other ideas? Unfortunately, I am unable to reproduce this behavior at all.

**Comment by kdubious** [comment] 2020-11-14 14:52
Here it is:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7                                                                                                                                                                                                                          Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\                                                                                                                                                                                              Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8                                                                                                                                                                                                                           .NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]                                                                                                                                                                                                         .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by dmvtech** [comment] 2020-11-17 18:13
Thanks @kdubious Can you please try with the most recent version of Composer (`1.2.1`)? 

Also, if you're able; update to `3.1.9` or `3.1.10` of [.NET core runtime](https://dotnet.microsoft.com/download/dotnet-core/3.1).

**Comment by mudasar** [comment] 2020-11-20 13:36
I am facing a similar issue with web app performance as well. if using the custom runtime the first time load is really really slow and it taking more then 1GB of RAM
![image](https://user-images.githubusercontent.com/4255491/99806126-6ef8eb00-2b35-11eb-8714-fe0f00b73865.png)

**Comment by kdubious** [comment] 2020-11-30 03:07
Any updates or thoughts?

**Comment by zhixzhan** [comment] 2021-02-02 03:32
I did some investigate, but failed to reproduce app crash. but I noticed app sometimes may auto reload after a long time idle. @kdubious  @mudasar  Can you upgrade to 1.3.0+, see this problem still exist ?

**Comment by cwhitten** [comment] 2021-02-18 23:27
Closing due to inactivity

**Closed by cwhitten** 2021-02-18 23:27 UTC
Labels: Bot Services, P1, Team: Platform, Type: Bug, customer-replied-to, customer-reported
