### ISSUE TITLE
Update Activity and Microsoft Teams

### ISSUE THREAD

**Issue by davidfischl** [microsoft/BotFramework-Composer#7737] opened 2021-05-11 12:41 UTC
I have been trying to use the Update Activity and Delete Activity as part of a bot built in BFC (as a PVA extension) and added as an app in Microsoft Teams.

The documentation says that this should be working. See:
https://docs.microsoft.com/en-us/composer/concept-memory#update-activity

I get an error when I run my bot in Teams.

Is this a known issue ?

Happy to add more detail if this is not a known issue.

Thanks

**Comment by davidfischl** [comment] 2021-05-14 11:22
@anusharavindrar would really appreciate you looking at this asap. thank you

**Comment by anusharavindrar** [comment] 2021-05-14 16:02
@davidfischl, apologize for the delay. I will attempt a repro & update the thread with my findings.

**Comment by anusharavindrar** [comment] 2021-05-14 22:51
@davidfischl, are you able to test and see if you can reproduce the error without the PVA layer(just the composer bot in Teams)?  Also, can you elaborate on the steps you followed to reproduce the error in Teams?

**Comment by davidfischl** [comment] 2021-05-15 00:42
thankyou @anusharavindrar, appreciate you looking at this. I am trying to finish a project for a client. Does this mean that Update Activity etc is not currently working for BFC where there is a PVA layer ?

**Comment by davidfischl** [comment] 2021-05-15 01:05
I just run the bot in Teams with the detail above and got the error. I think the issue relates to turn.lastresult.id not getting a value.

Sorry I don’t have the skills to use BFC without PVA. Do you mind checking if the issue is present when you extend PVA with BFC ?

Thanks!

[cid:image740064.jpg@A8E9C0E6.657BCF3F]
David Fischl​
Partner
M +61 (0) 411 197 528<tel:+61%20(0)%20411%20197%20528>

E ***@***.******@***.***>

One International Towers Sydney, Level 24, 100 Barangaroo Avenue
Barangaroo NSW 2000, Australia
www.hicksons.com.au<https://www.hicksons.com.au/>  |  LinkedIn<https://www.linkedin.com/company/hicksons-lawyers/>  |  Blog<https://www.hicksons.com.au/insight-news?category=Blog>  |  App on App Store<https://itunes.apple.com/au/app/hicksons/id1068728601?mt=8> or Google Play<https://play.google.com/store/apps/details?id=au.com.hicksons.androidapp&hl=en>


[cid:image492152.png@EEE7EDD1.39840F79]



________________________________

**Comment by davidfischl** [comment] 2021-05-15 01:06
I just run the bot in Teams with the detail above and got the error. I think the issue relates to turn.lastresult.id not getting a value. Sorry I don’t have the skills to use BFC without PVA. Do you mind checking if the issue is present when you extend PVA with BFC ? Thanks!

**Comment by anusharavindrar** [comment] 2021-05-17 23:17
Able to reproduce the error when testing with a composer bot as a PVA extension in Teams. Investigating further.
+@tonyanziano 

![image](https://user-images.githubusercontent.com/48731427/118567647-c5895f80-b73b-11eb-906e-29d6a4109986.png)

**Comment by babrekel** [comment] 2021-05-17 23:31
@anusharavindrar I am seeing the following error message internally from the execution of your dialog.
```
Microsoft.CCI.OnlineEngine.Exceptions.AdaptiveDialogException: Exception executing adaptive dialog. ActiveDialogId: UpdateActivity(${UpdateActivity_Activity_uvd4...). Microsoft.Rest.ValidationException: 'activityId' cannot be null.
```

One thing you could do to help debug the issue on your end is to add an InstrumentationKey to the bot, which will send telemetry to Application Insights (CustomEvents table). 

![image](https://user-images.githubusercontent.com/26589708/118568763-602e7200-b72d-11eb-9e59-3c4bd5565825.png)

![image](https://user-images.githubusercontent.com/26589708/118568712-42610d00-b72d-11eb-95d2-812fb72271fa.png)

Power Virtual Agents team is following up internally to understand the root cause of the issue.

**Comment by davidfischl** [comment] 2021-05-18 09:35
Thank you @babrekel. Sorry I don't have access to get and InstrumentationKey. Appreciate your help.

It looks like turn.lastresult.id is not getting a value when Bot Framework Composer is being used as an extension to Power Virtual Agents. When I look at the variable after running a Send Activity, it appears to be null.

**Comment by babrekel** [comment] 2021-05-18 17:04
Thanks @davidfischl for clarifying. We will track this in Power Virtual Agents.

**Comment by anusharavindrar** [comment] 2021-06-01 21:01
@davidfischl, the PVA team is tracking this bug. Will update the thread once the fix is out and you can give it a try.

**Comment by tonyanziano** [comment] 2021-07-19 20:46
The PVA team has notified us that a fix for this has been checked in and deployed to their testing environment where it was verified. This fix will be deployed to production in about 3 - 4 weeks.

**Comment by davidfischl** [comment] 2021-07-24 12:04
Thank you Tony, appreciated!

**Comment by benbrown** [comment] 2021-08-05 18:21
Closing this issue - feel free to reopen if the issue resurfaces.

**Closed by benbrown** 2021-08-05 18:21 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Area: PVA
