### ISSUE TITLE
How to save a file from bot to Azure File Share

### ISSUE THREAD

**Issue by joegreen690** [microsoft/BotFramework-Composer#9369] opened 2022-09-02 14:09 UTC
I have a bot developed using Bot Framework SDK and I'm trying to save a file uploaded by user to Azure File Share but keep getting error - The filename, directory name, or volume label syntax is incorrect. : 'C:\\Bot Framework SDK\\AttachmentsBot\\AttachmentsBot\\http:\\localhost:62308\\v3\\attachments\\24aa5c80-2ac2-11ed-93d8-ddc808cd3bf9\\views\\original'

The following code only works when uploading a file from local hard drive such as c:\temp\[test.txt](http://test.txt/). It doesn't work when user uploads a file in a bot
```     
   string connectionString = "<connection_string_to_Azure_fileshare>";
      
   // Name of the share, directory, and file we'll create
   string shareName = "sample-share";
   string dirName = "sample-dir";
   string fileName = "sample-file";
      
   // Path to the local file to upload
   string localFilePath = @"<path_to_local_file>";
      
   // Get a reference to a share and then create it
   ShareClient share = new ShareClient(connectionString, shareName);
   share.Create();
      
   // Get a reference to a directory and create it
   ShareDirectoryClient directory = share.GetDirectoryClient(dirName);
   directory.Create();
      
   // Get a reference to a file and upload it
   ShareFileClient file = directory.GetFileClient(fileName);
   using (FileStream stream = File.OpenRead(localFilePath))
   {
       file.Create(stream.Length);
       file.UploadRange(
           new HttpRange(0, stream.Length),
           stream);
   }
```

Here is my method looks like

```
private static  IMessageActivity HandleIncomingAttachment(IMessageActivity activity)
{
 var replyText = string.Empty;
 foreach (var file in activity.Attachments)
 {
	 var remoteFileUrl = file.ContentUrl;

	 string connectionString = "<connection_string_to_Azure_fileshare>";

	 // Name of the share, directory, and file we'll create
	 string shareName = "fileuploads";
	 string dirName = "test";
	 string fileName = file.Name;

	 // Path to the local file to upload
	 string localFilePath = remoteFileUrl + "/" + file.Name;

	 // Get a reference to a share and then create it
	 ShareClient share = new ShareClient(connectionString, shareName);

	 // Get a reference to a directory and create it
	 ShareDirectoryClient directory = share.GetDirectoryClient(dirName);

	 ShareFileClient f = directory.GetFileClient(fileName);
	 using (FileStream stream = File.OpenRead(localFilePath))
	 {
		 f.Create(stream.Length);
		 f.UploadRange(
			 new HttpRange(0, stream.Length),
			 stream);
	 }

	 replyText += $"Attachment \"{file.Name}\" has been received and saved." + Environment.NewLine.ToString();
 }

    return MessageFactory.Text(replyText);
}
```

**Comment by anishprasad01** [comment] 2022-09-02 20:43
Hi @joegreen690,

As the error message suggests, the following is not a valid path to a file.
```
'C:\Bot Framework SDK\AttachmentsBot\AttachmentsBot\http:\localhost:62308\v3\attachments\24aa5c80-2ac2-11ed-93d8-ddc808cd3bf9\views\original'
```
How exactly are you storing the attachments a user sends to your bot? How is the path that the error message cites generated?

You could try something simple, like accessing a text file and sending its contents back as a message to verify that you are able to store and access files from the bot's local storage with the correct path before attempting to reach Azure Files.

**Comment by joegreen690** [comment] 2022-09-06 16:04
This is how I'm tring to read and write the uploaded file to Azure File Share
`using (FileStream stream = File.OpenRead(localFilePath))
      {
      	f.Create(stream.Length);
      	f.UploadRange(
        	new HttpRange(0, stream.Length),
        	stream);
      }`
I'm getting error _"The filename, directory name, or volume label syntax is incorrect. : 'C:\\Bot Framework SDK\\AttachmentsBot\\AttachmentsBot\\http:\\localhost:55871\\v3\\attachments\\a202f590-2def-11ed-b2c0-593d44b01992\\views\\original\\1.pdf'"_

As you can see path is messed up. Path of the bot  ('C:\\Bot Framework SDK\\AttachmentsBot\\AttachmentsBot\\) is appended with the path of  uploaded file.

**Comment by anishprasad01** [comment] 2022-09-06 16:30
Are you actually storing the file locally before sending it to Azure File Share? The comments in the code example you're using imply that the file should be present locally, rather than at a remote endpoint.

I suspect your issue is probably that the attachment is not being saved to local storage properly first. Does this code work outside of the bot for a local file?

**Comment by joegreen690** [comment] 2022-09-06 16:42
I should have used a different variable name than localfilepath as it is gives an impression that I'm saving the file locally. I'm storing the file locally. User is selecting a file from local hardrive from bot and I want to save it to Azure File Share.

**Comment by joegreen690** [comment] 2022-09-06 17:12
Thank you for the clue, after I saved the file to local temp folder, I was able to upload the file to Azure. Is there a way to save the file to Azure File Share from bot without saving it first to local hard drive?

**Comment by anishprasad01** [comment] 2022-09-06 20:46
You're welcome.

Based on my understanding of the Azure File Service [API documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/file-service-rest-api), you cannot copy a file from an arbitrary online location. Azure File Service is intended to be a cloud-based replacement to local network file shares, and thus needs to be mounted and accessed by the OS' native file system APIs. 

Thus, the source must be one of three options:
- The local filesystem of the calling application.
- An Azure blob belonging to the same Azure Storage Account.
- A File Share snapshot belonging to the same Azure Storage Account.

Perhaps File Share is not the appropriate solution for your use case? Rather than trying to force Azure File Share to operate in this way, perhaps you might consider using Azure Blobs or another offering to store your attachments?

**Comment by anishprasad01** [comment] 2022-09-13 16:20
Since this is expected behavior, I am going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-09-13 16:20 UTC
Labels: customer-reported, Bot Services, customer-replied-to
