### ISSUE TITLE
Interrupt dialog not working for unknown intent

### ISSUE THREAD

**Issue by philip-mc** [microsoft/BotFramework-Composer#6422] opened 2021-03-16 12:10 UTC
## Describe the bug

I have a parent dialog triggering a child via an intent. There is also an unknown intent trigger in the parent linked to a Q and A knowledge base. 

On the screenshot attached I start with an unknown intent and the Q and A triggers as expected. I then use the intent to trigger the child dialog. When I run the unknown intent again (trying to trigger the Q and A) nothing happens and I am reprompted for the question in the child. If I run the intent again the parent triggers as expected. 

The question in the child is set to allow interruption and it works when the intent is recognized but fails on the unknown intent. If I am in the parent everything works as expected. 

## Version

1.3.1

## OS

- [ ] Windows

## To Reproduce

As described above

## Expected behavior

When an unknown intent 'xyz' is presented in the child dialog as the interruption is set to 'true' the parent trigger should activate. 

## Screenshots

![image](https://user-images.githubusercontent.com/73343537/111306465-20c1a780-8650-11eb-8a08-5454b219004d.png)

**Comment by philip-mc** [comment] 2021-03-18 15:49
Hi, please can I bump this one I was hoping to launch Q and A next Monday......

**Comment by dmvtech** [comment] 2021-03-18 18:30
Hi @philip-mc I'm looking into this. Are you able to share a repository of your bot? I'd like to understand some more of the specifics of how you have it configured.

**Comment by philip-mc** [comment] 2021-03-19 07:50
Morning, Ill give you a DM as the project is a business one and perhaps we can arrange a videocall/Teams screenshare with me and my lead developer?

**Comment by philip-mc** [comment] 2021-03-19 07:53
I can share the privately with you via screenshare with one of our devs if you get an email I can contact you on at all?

**Comment by philip-mc** [comment] 2021-03-22 13:16
Afternoon, Ive put a mock bot together and invited you to take a look. Let me know if you can figure out why the 'unknown intent' trigger of the parent will not go off even though it does for intent recognised. 

As a separate note I have noticed composer creating separate apps for each dialog which may or may not be related - https://github.com/microsoft/BotFramework-Composer/issues/6423

**Comment by dmvtech** [comment] 2021-03-25 03:24
@philip-mc I believe this is by design (with regards to the _interruption + unknown intent_). I think interruptions only trigger other actual intents (not the unknown intent). I have confirmed that other intents will interrupt and trigger.

I think to accomplish your goal, there are other (more appropriate) approaches. I am working to confirm all of this and will share when I have that complete.

**Comment by dmvtech** [comment] 2021-03-26 17:13
Hi @philip-mc I have confirmed that the reason for the behavior is as I've shared above. 

The suggested approach is to author your KB from within Composer, and use the `QnA Recognized Intent` trigger. This will allow for the QnA to be an actual LU intents instead of a fall-back dialog within the unknown "intent".

Please find more info here:
https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb

**Comment by dmvtech** [comment] 2021-03-30 20:35
Closing as answered.

**Closed by dmvtech** 2021-03-30 20:35 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported

**Comment by philip-mc** [comment] 2021-04-06 06:25
Morning, ok yea I went down this route myself. It is not quite optimal to build the knowledge base within composer as I have a dynamic URL I wish to use to keep the knowledge base fresh as a site is updated. The sync from composer to QnA maker appears to be one way from at the - is there a way to keep this sync up?
