### ISSUE TITLE
Bot settings section title incorrectly shown as 'Application Settings' on initial navigation

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#3922] opened 2020-08-27 11:55 UTC
Currently, when I open Composer (nightly build 8/27), open a bot and click the settings button, I see a page like the below.  Note that the title is shown as 'Application Settings', but it is the Bot Settings screen that is displayed.  If I navigate to a different settings tab and back, the problem disappears, so this only appears to be an issue on initial navigation to settings.

One thing to note is that I only currently see this on some of the bots I have installed.  I do not get this problem on the recently created QnA bots created from the QnA template - so it is possible that this issue has been rectified already, but I wanted to raise anyway.

**Comment by cwhitten** [comment] 2020-08-27 16:38
@garypretty did you forget to attach the screenshot?

**Comment by zxyanliu** [comment] 2020-11-20 19:33
@garypretty I was unable to reproduce the incorrect behavior you described in [Composer 1.2.1 release](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.1) nor in the main branch. I think it is safe to close this issue? 

![image](https://user-images.githubusercontent.com/32497439/99842091-110fd780-2b24-11eb-9854-d6848a5db2bd.png)

**Closed** 2021-02-11 23:09 UTC
Labels: Type: Bug
