### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by michaelvassilchenko** [microsoft/BotFramework-Composer#8474] opened 2021-07-27 01:17 UTC
For context, I've just begun working with Bot Framework Composer and am following the weather bot tutorial https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help?tabs=v2x

I ran into the following issue when attempting to set Allow Interruptions to True in a User input (Text) block:
![uncaught syntaxerror issue](https://user-images.githubusercontent.com/88011766/127079542-9f4af781-d89a-49d4-ab36-969b5cf83822.PNG)

Edit: 
I also read about toggling developer console, here is what i am receiving:
![image](https://user-images.githubusercontent.com/88011766/127090427-d687cd08-d4e2-4444-8b86-cdf642767525.png)

**Comment by michaelvassilchenko** [comment] 2021-07-27 03:23
I read about toggling developer console, here is what i am receiving:
![image](https://user-images.githubusercontent.com/88011766/127090370-724b0e97-512a-41dc-9618-567b95abb9ef.png)

**Comment by hatpick** [comment] 2021-07-27 05:29
Duplicate of #8455. It's due to a bug in Fabric UI that is fixed in office-ui-fabric-react@v7.93.1 and after.

**Comment by hatpick** [comment] 2021-07-27 05:31
Duplicate #8464

**Comment by michaelvassilchenko** [comment] 2021-07-27 15:21
> Duplicate of #8455. It's due to a bug in Fabric UI that is fixed in office-ui-fabric-react@v7.93.1 and after.

I have never used fluentui, is that something I need for bot framework composer? How would I install version ofice-ui-fabric-react@v7.93.1?

**Comment by hatpick** [comment] 2021-07-27 16:15
@michaelvassilchenko the resolution is not for you, it's for the team to fix this. Sorry if it was misleading.

**Comment by michaelvassilchenko** [comment] 2021-07-27 17:02
@hatpick Sorry if I am misunderstanding but should I wait for the Composer team to fix this? What are my next steps to continue working with Bot Framework Composer?

**Comment by tonyanziano** [comment] 2021-07-27 17:15
Closing as this is a duplicate of both #8455 and #8464

@michaelvassilchenko you do not have to fix anything on your side. The Composer team will bump the fluent dependency in our codebase and update the DOM IDs so that this doesn't happen anymore.

**Closed by tonyanziano** 2021-07-27 17:15 UTC
Labels: Bot Services, Needs-triage, customer-reported
