### ISSUE TITLE
When creating a bot fails, empty bot folder is left behind

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6759] opened 2021-04-08 03:02 UTC
## Describe the bug

I tried to create a bot and it failed. I tried later with the same name and got a validation error that the name was already in use.

## Version

Version:  1.4.0-nightly.232411.9f6c16e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot:
![image](https://user-images.githubusercontent.com/39317542/113962089-ec1eb700-97db-11eb-9b4d-6392e89daeed.png)

2. Bot creation failed:
![image](https://user-images.githubusercontent.com/39317542/113962118-f3de5b80-97db-11eb-9e38-be879eb31ef8.png)

3. Create a bot of the same name. See error message:
![image](https://user-images.githubusercontent.com/39317542/113962145-fd67c380-97db-11eb-8562-873e4ed4d128.png)

The folder is empty:
![image](https://user-images.githubusercontent.com/39317542/113962246-25572700-97dc-11eb-98b0-f376ca48ef04.png)

## Expected behavior

I expected Composer to remove the empty folder if the bot creation did not succeed.

**Comment by srinaath** [comment] 2021-04-08 17:16
Closing as its a dupe of https://github.com/microsoft/BotFramework-Composer/issues/6726

**Closed by srinaath** 2021-04-08 17:16 UTC
Labels: Area: Components, P0, R13 Bugbash, Type: Bug, topic: creation
