### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code NotFound

### ISSUE THREAD

**Issue by yangkaiDCM** [microsoft/BotFramework-Composer#9516] opened 2023-02-21 07:00 UTC
1. Tried provisioning resources following instructions on Bot FrameworkComposer documentation for **publish**>**Hand over to admin**.
2. After provsioning resources, proceeded to **Publish**>**Import Existing Resources** on Bot Framework Composer.
3. After replacing the JSON template with JSON given by Azure CLI, pressed "Import" to publish unto Azure.
4. **Test on webchat** yields the error: "**There was an error sending this message to your bot: HTTP status code NotFound**".
![image](https://user-images.githubusercontent.com/122245660/220270973-02f05345-8836-4959-a571-2c3c0f39eb1b.png)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/122245660/220269056-ded13609-d359-4fe1-bd24-af443dfa90bf.png">
#6570

**Comment by yangkaiDCM** [comment] 2023-02-21 10:01
messaging endpoint is correctly shown in the configurations page of Azure Bot, viewing the messaging endpoint on browser shows error: **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.**

App service wasn't deleted or modified so what could be the issue here?

**Comment by anishprasad01** [comment] 2023-02-21 18:35
Hi @yangkaiDCM,

After importing the settings to the publishing profile, did you press "Publish" to actually deploy the bot to your Azure resources?

**Comment by yangkaiDCM** [comment] 2023-02-22 01:27
@anishprasad01 
I didn't press "Publish" previously and somehow it worked, but now when I try to press "Publish" it gives a login error 2002:
![image](https://user-images.githubusercontent.com/122245660/220496962-bbc2349a-164d-489d-9757-df883211fb24.png)

**Comment by anishprasad01** [comment] 2023-02-22 15:53
- Is Composer able to communicate with the internet? Are there any firewalls blocking it?
- Have you tried logging out and signing-in again?
- Are you able to sign into other Microsoft apps on the same machine with the same account?

**Comment by anishprasad01** [comment] 2023-02-22 15:53
- Is Composer able to communicate with the internet? Are there any firewalls blocking it?
- Have you tried logging out and signing-in again?
- Are you able to sign into other Microsoft apps on the same machine with the same account?

**Comment by yangkaiDCM** [comment] 2023-02-23 04:11
@anishprasad01 
- Yes it is able to connect to the internet as I have tested the chatbot on the "web chat" function in Composer.
- I have attempted to sign in multiple times but they yield the same error 2002.
- I am not able to sign in to my onedrive as well(error 2002), but for teams, outlook I am able to sign in.

**Comment by anishprasad01** [comment] 2023-02-23 16:28
Hmm...based on those results, the issue is probably in the login credentials.

- Does this replicate on another machine (if you have one available to test)?
- Is your machine joined to an AAD domain?
- Are you on Windows? If so, there is a folder called IdentityCache which you can find at: `AppData -> Local -> Microsoft -> IdentityCache`. You could try deleting the contents of this folder and then signing-in to Composer or OneDrive again.

**Comment by yangkaiDCM** [comment] 2023-02-24 02:09
@anishprasad01 

- The same error occurred on another machine
- Yes it is joined to my company's AAD domain.
- I tried as you have instructed to delete the contents of `IdentityCache` and but unfortunately still got the error 2002 for both Composer and OneDrive.

**Comment by anishprasad01** [comment] 2023-02-27 16:00
You might need to contact your company's IT department for help on this matter. The fact the problem persists across multiple machines and multiple apps suggests a potential problem with your credentials, which is not something I will be able to resolve.

I will leave this issue open for the time being, in the event that the issue persists after you get your account issues resolved and we can localize it to Composer.

**Comment by yangkaiDCM** [comment] 2023-02-28 07:42
Hello @anishprasad01 I see. 

Current workaround is to use zip deploy method to publish the bot to Azure which works fine. Thanks for helping out 😀👍

**Comment by johnataylor** [comment] 2023-02-28 19:06
closing with a workaround, thanks

**Closed by johnataylor** 2023-02-28 19:06 UTC
Labels: customer-reported, Bot Services
