### ISSUE TITLE
Issue when there a multiple choice question type is selected and the dialog is LUIS enabled 

### ISSUE THREAD

**Issue by likith3611** [microsoft/BotFramework-Composer#3839] opened 2020-08-13 13:09 UTC
I have enabled allow interruptions in multiple question  so that LUIS can be enabled so that if any unwanted string is detected it should go to unknown
<img width="241" alt="Capture" src="https://user-images.githubusercontent.com/49705166/90138110-21315180-dd94-11ea-8022-6c837ab17eb2.PNG">
 intent but when I run the code the LUIS is called twice and it doesn't go to unknown intent. So how do i solve this issue

**Comment by cwhitten** [comment] 2020-08-13 16:34
@likith3611 can you upload your bot assets to this ticket? You should not be seeing multiple LUIS trace events within a single turn of the conversation.

**Comment by likith3611** [comment] 2020-08-14 04:30
<img width="940" alt="Capture" src="https://user-images.githubusercontent.com/49705166/90213915-a1979700-de14-11ea-8d1e-603d651ab72f.PNG">
I am currently using older version of composer not the newer once hence assets cant be uploaded. But these are my settings as shown and the dialog is LUIS enabled

**Comment by hibrenda** [comment] 2020-08-14 14:42
I can repro what you mentioned above. @luhan2017 for awareness

**Comment by luhan2017** [comment] 2020-08-18 11:55
@likith3611 I think it is by-design the UnknownIntent will not be triggered in this scenario, otherwise, it will be almost always triggered by any input which doesn't make sense, I've tried to create an valid trigger, and verified it can be triggered if you input the trigger phrases in choice prompt. 

For the luis trace shown twice issue, I am investigating more on that.

**Comment by pavolum** [comment] 2020-09-01 16:09
Closing this issue as this behavior is by design

**Closed by pavolum** 2020-09-01 16:09 UTC
Labels: Bot Services, Type: Question, customer-replied-to, customer-reported
