### ISSUE TITLE
Pre built-in function where does not work

### ISSUE THREAD

**Issue by formore5points** [microsoft/BotFramework-Composer#6586] opened 2021-03-29 11:51 UTC
Hello everyone,

I am trying to use the pre built-in function where inside the bot. Everything works fine when experimenting with the emulator. The length of the list returned from where method is different from 0. But when I test it with the web chat feature that comes with version 1.4, the length of the list returned from the where method is 0.

More details:
I have a json file containing dates and I'm trying to filter through those dates. For example, I want to filter the 3rd day of each month (Actually, this is not what I want to do, but I said it in terms of example.). While testing in the emulator, a list with dates comes up and when I check the length of the list with the count method, I can observe a value other than 0. However, when I do the same operations in the web chat, the length of my list is 0 and I cannot filter. I am 100% sure that where method does not work in web chat. I would be glad if you help.

Note: I will try to add SS but I would appreciate if you try to help until I add ss. 

Platform: Bot Framework Composer 1.4
OS:Window 10

**Comment by formore5points** [comment] 2021-03-29 12:21
Here are the SSs.

Piece of the bot that the error occured:
![3](https://user-images.githubusercontent.com/50989796/112835549-18cb2400-90a2-11eb-9b68-bef08ce01f8c.png)

Emulator SS:
![1](https://user-images.githubusercontent.com/50989796/112835637-37c9b600-90a2-11eb-9405-11e2e8b51215.png)

WebChat SS:
![2](https://user-images.githubusercontent.com/50989796/112835673-41531e00-90a2-11eb-9533-653262f632a2.png)

As you can see, the same bot gives different outputs on webchat and emulator without any changes.

**Comment by msomanathan** [comment] 2021-03-30 18:15
@formore5points we are working on a major release, so apologies for the delay in getting to this issue. We will respond back with a resolution as soon as we can.

**Comment by formore5points** [comment] 2021-03-30 18:40
@msomanathan As I have seen in my recent works, the value part of the input from the calendar does not work on the web chat, not the where function. Here is the ss (output of calender input): 

![photo_2021-03-30_21-32-05](https://user-images.githubusercontent.com/50989796/113039214-17802100-91a0-11eb-9a43-b41b2e059866.jpg)

How can we ensure that the value field is not null ?

**Comment by peterinnesmsft** [comment] 2021-04-05 18:14
@formore5points can you confirm which control you are using to specify the date input as seen above? Is this from an adaptive card that we provide, or is it some custom mechanism? Any additional info will help us root cause. Thank you!

**Comment by peterinnesmsft** [comment] 2021-04-08 18:20
@jwiley84 are you able to assist with getting a repro?

**Comment by formore5points** [comment] 2021-04-09 22:01
@peterinnesmsft I am using an adaptive card for calendar.I didn't show above but there is an adaptive card before the input(user.appointmentDate). I can observe the input in emulator correctly but in webchat hand, value field comes null.

**Comment by lauren-mills** [comment] 2021-04-13 17:15
Hi @formore5points, since it looks like the null value is causing the issue in webchat (which is expected since a date range would have a null value) try changing your expression to this:

dialog.timeSlots = where(dialog.slots, x, x.date == coalesce(user.appointmentDate[0].value, user.appointmentDate[0].start))

This will check for both the dates value and start, and choose whichever one is not null.

**Comment by lauren-mills** [comment] 2021-04-13 17:22
As for the locale problem, I'm not sure I completely understand, but the formatDateTime does accept a locale parameter which might help you convert to your desired locale: https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#formatdatetime

**Comment by emrecanergor** [comment] 2021-04-13 19:53
Hey @lauren-mills, i'm @formore5points ' teammate. In webchat, we need to dynamically use the locale from browser. So i think we can't set statically locale text to formatdatetime. What do you think about that case?

**Comment by lauren-mills** [comment] 2021-04-14 18:12
@emrecanergor  - would you mind opening a separate issue for that in the the webchat repo [here](https://github.com/microsoft/BotFramework-WebChat/issues)? The team over there may be able to better help with that scenario.

**Comment by lauren-mills** [comment] 2021-04-14 18:13
Also, any update on the original issue?

**Comment by emrecanergor** [comment] 2021-04-14 19:42
Okay, That sounds good. Original issue has the same problem.

**Comment by formore5points** [comment] 2021-04-15 07:40
@lauren-mills Hello, We opened the subject in the section you said. Thank you so much. 
Here is the link : https://github.com/microsoft/BotFramework-WebChat/issues/3852

**Comment by formore5points** [comment] 2021-04-23 11:47
@lauren-mills The issue was solved. I updated the last issue. Thanks

**Comment by tsuwandy** [comment] 2021-05-05 17:56
@formore5points, closing this as issue was solved.  Please reopen otherwise.  Thanks!

**Closed by tsuwandy** 2021-05-05 17:56 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
