### ISSUE TITLE
QnA Error is insufficient

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7186] opened 2021-04-20 22:48 UTC
## Repro
* Create a new bot
* Add a KB from scratch. Use embedded auto, select KB from provided list
* Create a few Q/As, add QnA Intent recognized
* Build
* Error: 
```
Sorry, something went wrong with publishing. Try again or exit out of this task.

Qnamaker build failed: Runtime error.
```

## Expected
Actionable error. I did everything using happy path flow but hit an error and no guidance how to resolve it next.

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Visual

![image](https://user-images.githubusercontent.com/8867670/115473020-c936ce80-a1ef-11eb-94b6-162dd2c3b15c.png)

**Comment by benbrown** [comment] 2021-04-22 16:08
This is a dupe of #7217

**Closed by benbrown** 2021-04-22 16:08 UTC
Labels: Type: Bug
