### ISSUE TITLE
Missing various options in Dialog Management

### ISSUE THREAD

**Issue by abhishekkumar717** [microsoft/BotFramework-Composer#9451] opened 2022-12-20 09:57 UTC
## Describe the bug
Unable to find all the options under Dialog Management 

## Version
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
 [ ] Chrome

## OS
[ ] Windows

## To Reproduce

1) Open Bot Framework Composer
2) Open any created bot
3) Click on any Dialog, for ex : Greetings
4) Click on the (+) node
5) Hover over Dialog Management

Missing options under Dialog Management : 
Continue Conversation, Continue Conversation Later, Get Conversation Reference, Go to action

**Comment by abhishekkumar717** [comment] 2022-12-20 09:58
![Expected](https://user-images.githubusercontent.com/120561285/208639063-f43e30c7-c529-45d9-8dcd-985b69e6dc4c.JPG)
![Observed](https://user-images.githubusercontent.com/120561285/208639199-6c826ccc-883f-490d-9f67-710d0fb2f68f.JPG)

**Comment by ramfattah** [comment] 2022-12-20 18:14
Thanks @abhishekkumar717, we are investigating.

**Comment by abhishekkumar717** [comment] 2022-12-22 09:53
@ramfattah Hello, could we please have any update on this.

**Comment by ramfattah** [comment] 2022-12-22 17:07
Thanks @abhishekkumar717, 

Using Composer mixed with PVA, I was able repro this issue. If using standalone Composer, this issue is not reproducible.

Sharing screenshots.

PVA + Composer (reproducible, Dialog management contains less options)
![image](https://user-images.githubusercontent.com/38049078/209188407-60dcf284-ad93-4825-849a-9650d6962b4f.png)


Only Composer (not reproducible):
![image](https://user-images.githubusercontent.com/38049078/209188201-4e41702c-4790-476d-a4e5-a56a0483c526.png)

#

@abhishekkumar717 I'm not sure if this is by design or a bug, I will discuss with the engineering team and report back.
Thanks.

**Comment by abhishekkumar717** [comment] 2022-12-23 05:42
@ramfattah Thanks for your response, For me it is not coming for both of the approaches neither on a PVA integrated BFC BOT nor on a BOT created on BFC. However, I am more interested in the PVA integrated BFC BOT as I am working currently on the same. If this is something which is as per design, then could you pls let me know how do I navigate back to an activity within a same dialogue without using Send to Action. Earlier  I had created   https://github.com/microsoft/BotFramework-Composer/issues/9452

**Comment by abhishekkumar717** [comment] 2022-12-26 14:40
@ramfattah Hello, could we please have an update on this.

**Comment by ramfattah** [comment] 2022-12-27 18:29
Hi @abhishekkumar717, 

The engineering team are on holiday and returning tomorrow. Thank you for your patience.

**Comment by abhishekkumar717** [comment] 2023-01-03 14:31
@ramfattah Any update on this ?

**Comment by ramfattah** [comment] 2023-01-09 18:53
Hi @abhishekkumar717,

I attempted to exchange the scheme between PVA bot and fresh composer non PVA bot.
It appears I was only able to get the `Go To Action` came back under Dialog management menu.

Sharing the steps I took:
1. Open PVA bot project directory
2. Navigate and open schemas/app.uischema
3. Paste the following in app.uischema:
    ```json
    "Microsoft.GotoAction": {
      "menu": {
        "label": "Go to action",
        "submenu": [
          "Dialog management"
        ]
      }
      },
      "Microsoft.ContinueConversation": {
        "menu": {
          "label": "Continue conversation",
          "submenu": [
            "Dialog management"
          ]
        }
      },
      "Microsoft.ContinueConversationLater": {
        "menu": {
          "label": "Continue conversation later",
          "submenu": [
            "Dialog management"
          ]
        }
      },
      "Microsoft.ContinueConversation": {
        "menu": {
          "label": "Continue conversation",
          "submenu": [
            "Dialog management"
          ]
        }
      },
    ```
4. Start Composer 2.1.2 application
5. Open the PVA bot in Composer
6. Only the `Go to action` came back
    ![image](https://user-images.githubusercontent.com/38049078/211384516-23c7aa1d-0c70-472a-955f-25b4ade32a9c.png)


I will discuss with the engineers today about my findings and report back. 
Thanks for your patience, @abhishekkumar717.

**Comment by ramfattah** [comment] 2023-02-03 19:38
Closing as this by design.

**Closed** 2023-02-03 19:39 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
