### ISSUE TITLE
Unable to publish web app bot code behind proxy

### ISSUE THREAD

**Issue by sudhanrv** [microsoft/BotFramework-Composer#7543] opened 2021-05-01 04:46 UTC
while we're trying to publish/create/import the code from bot composer to web app bot encountered the attached error.  This we are trying to archive from the server within the corporate network firewall. All other Azure resource were able to connect from the same network and proxy except bot composer. Looking for earliest solution on this issue.
![image](https://user-images.githubusercontent.com/52436478/116771088-06228100-aa8c-11eb-8702-81463056c8c0.png)

**Comment by tdurnford** [comment] 2021-05-03 20:35
@benbrown Do you have suggestions?

**Comment by cwhitten** [comment] 2021-05-06 17:53
Hi @sudhanrv - Composer does not yet support proxy configurations in a stable release, but this is actively being worked on. This will be supported in an upcoming release.

**Comment by tdurnford** [comment] 2021-05-06 18:15
@cwhitten Per your comment, can you add this to a milestone?

**Comment by cwhitten** [comment] 2021-06-04 00:05
Added into R14 with the ongoing proxy work cc @lei9444 @boydc2014

**Comment by cwhitten** [comment] 2021-06-08 00:28
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/2654

**Closed by cwhitten** 2021-06-08 00:28 UTC
Labels: Bot Services, Team: Platform, Team: Runtime & Publishing, customer-replied-to, customer-reported
