### ISSUE TITLE
dotnet run - “” is not a valid LUIS application id.

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#2751] opened 2020-04-23 18:05 UTC
## Describe the bug

If I create a bot with Composer (Todo with LUIS) and run in from Composer the testing in the emulator works fine. But if I run the bot from the CLI using dotnet run, I always get this message when it should detect the intent with LUIS:

“” is not a valid LUIS application id.

![image](https://user-images.githubusercontent.com/29750798/80133494-9686d580-859d-11ea-81d0-fab502224830.png)

## Version

test

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create bot
2. Open cmd and run dotnet run

## Expected behavior

The bot should be using LUIS to detect the intent correctly.

**Comment by hibrenda** [comment] 2020-04-24 06:37
not only for dotnet run but reproduced for  new created bot as well even use the emulator.

**Comment by luhan2017** [comment] 2020-04-24 07:15
I have investigated on this, this is because Ben's latest change has updated the bot folder location from ComposerDialogs to ..\, while in code, we searched "ComposerDialogs\settings\appsettings.json".  @zidaneymar will create a PR soon to fix this issue.

**Comment by cwhitten** [comment] 2020-04-26 16:28
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2761

**Closed by cwhitten** 2020-04-26 16:28 UTC
Labels: P0, R9, Type: Bug
