### ISSUE TITLE
Composer should support setting the LUIS app region in addition to the authoring region

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#5762] opened 2021-02-11 16:54 UTC
## Describe the bug

Composer only allows you to set the LUIS authoring region and gives you three options which is correct. 

![image](https://user-images.githubusercontent.com/12264946/107668335-90fa9900-6c5e-11eb-8658-d240164a76cb.png)

However, it is possible to deploy your LUIS prediction app to other regions, here is a screenshot of the azure portal options for a LUIS prediction app:

![image](https://user-images.githubusercontent.com/12264946/107668224-70324380-6c5e-11eb-9730-bddc15359421.png)

In my case, I created a LUIS app that is in EastUS and I get a 401 when I try to run my bot:
![image](https://user-images.githubusercontent.com/12264946/107668455-b38cb200-6c5e-11eb-804c-e6ce2da026b4.png)

## Version

I am running a local build with the latest from main from today 2/11/2021.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a LUIS resource in the azure portal and set the prediction resource region to a different region than west US:
![image](https://user-images.githubusercontent.com/12264946/107668902-2f86fa00-6c5f-11eb-92c3-4a80bc50c5b3.png)

2. Configure a LUIS bot with the authoring key from the authoring app in azure portal
3. Configure the LUIS bot with the prediction key for the region you selected 
![image](https://user-images.githubusercontent.com/12264946/107669278-91476400-6c5f-11eb-8c18-2f9a1fabb445.png)

4. Try to run the bot and you'll get a 401 when trying to access LUIS

## Expected behavior

I would like to be able to set the region of my prediction key so I can use a LUIS instance that is close to me. 

This is how a LUIS resource would look like in the azure portal when the prediction app is deployed to non authoring region:

![image](https://user-images.githubusercontent.com/12264946/107670131-6c9fbc00-6c60-11eb-86c5-a654bff4f582.png)

**Comment by gabog** [comment] 2021-03-02 14:31
Hi @srinaath, @cwhitten and @garypretty, I think this issue is pretty serious, users won't be able to deploy bots to any region outside the 3 main LUIS authoring regions. Can we see if we can fix this in the upcoming release? 

Let me know if you need more details.

**Comment by cwhitten** [comment] 2021-03-02 17:52
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/5827

**Closed by cwhitten** 2021-03-02 17:52 UTC
Labels: Backlog, Needs-triage, Team: Runtime & Publishing, Type: Bug
