### ISSUE TITLE
Launching of Botframework composer throws error with pop up -> "Something went wrong"

### ISSUE THREAD

**Issue by SundaresanSivakumar** [microsoft/BotFramework-Composer#8531] opened 2021-08-06 06:07 UTC
Launching the botframework composer throws error with popup title "Something went wrong" and the content says to report an issue in Github
After it loads & in the workflow after selecting "Send Response" activity & trying to click "Show Code". It once again throws the same error "Something went wrong"

## Version
Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS
Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎1/‎29/‎2021
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

## To Reproduce

Refer to the above issue description

## Expected behavior

The Botframework composer shouldn't throw any error

## Screenshots

![image](https://user-images.githubusercontent.com/3501042/128463985-f745551f-59ae-496a-87cf-8033c20a2d9e.png)

**Comment by dmvtech** [comment] 2021-08-09 22:47
Hi @SundaresanSivakumar 

Do you see any **error** listed in the `Problems` section at the bottom of Composer?

**Comment by SundaresanSivakumar** [comment] 2021-08-16 08:55
Hi @dmvtech ,
I didn't notice anything. However I uninstalled the bot framework composer 2.1.0 last week and installed the 2.0.0 version as we had product release close by. I will try installing the latest version tomorrow and let you know. 

Thanks

**Comment by SundaresanSivakumar** [comment] 2021-08-18 17:53
I installed the 2.1.0 version . The screenshot that I had shared while creating this issue pops up. However i don't see any error listed in the problem section.

**Comment by dmvtech** [comment] 2021-08-18 21:51
Thank you @SundaresanSivakumar 

Can you try the following?:

- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

Then run the same steps to reproduce the issue. Then share the output from the terminal.

**Comment by dmvtech** [comment] 2021-08-24 23:28
Hi @SundaresanSivakumar Any luck with the above steps?

**Comment by SundaresanSivakumar** [comment] 2021-08-25 05:03
Here is the terminal o/p Dana

2021-08-25T04:59:29.619Z composer:publisher-controller Setting up runtime
log server
GET /api/publish/runtimeLogUrl/90574.58464532069 304 32.908 ms - -
2021-08-25T04:59:29.752Z composer:bot-project Schemas directory found.
GET /api/publish/90574.58464532069/status/default 404 158.125 ms - 66
GET /conversations/ws/port 200 39.554 ms - 39
GET /conversations/ws/port 200 0.516 ms - 40
2021-08-25T04:59:30.162Z composer:bot-project Schemas directory found.
2021-08-25T04:59:30.185Z composer Update file check.botproj {
  "$schema": "
https://raw.githubusercontent.com/microsoft/BotFramework-Composer/main/Composer/packages/server/schemas/botproject.schema
",
  "name": "check",
  "skills": {}
}
PUT /api/projects/90574.58464532069/files/check.botproj 200 116.151 ms - 74
2021-08-25T04:59:30.243Z composer:bot-project Schemas directory found.
PUT /api/projects/90574.58464532069/files/appsettings.json 200 77.860 ms -
34
GET /api/storages 304 0.873 ms - -
GET
/api/storages/default/blobs?path=C%253A%252FUsers%252FSivakumarSundaresan%252Fsource%252Frepos
304 19.620 ms - -
GET
/api/storages/default/blobs?path=C%253A%252FUsers%252FSivakumarSundaresan%252Fsource%252Frepos
304 13.565 ms - -
2021-08-25T04:59:43.307Z composer:bot-project Schemas directory found.
GET /api/projects/90574.58464532069/variables 304 61.324 ms - -
2021-08-25T04:59:52.271Z composer:bot-project Schemas directory found.
GET /api/projects/90574.58464532069/variables 304 60.625 ms - -
2021-08-25T05:00:56.127Z composer:bot-project Schemas directory found.
GET /api/projects/90574.58464532069/variables 304 64.117 ms - -
2021-08-25T05:00:57.915Z composer:bot-project Schemas directory found.
GET /api/projects/90574.58464532069/variables 304 60.442 ms - -

**Comment by dmvtech** [comment] 2021-08-30 20:56
@SundaresanSivakumar You should have 2 schema files as well. I have attached them. Can you extract them from the zip and add them to the schemas folder and see if that resolves the issue?

[schemas.zip](https://github.com/microsoft/BotFramework-Composer/files/7079555/schemas.zip)

**Comment by dmvtech** [comment] 2021-09-03 21:23
@SundaresanSivakumar Any luck?

**Comment by dmvtech** [comment] 2021-09-08 22:54
Closing due to lack of response. Please comment if you are still having this issue.

**Comment by SundaresanSivakumar** [comment] 2021-09-09 06:46
Sorry @dmvtech , couldn't get back to you early. However i tried to copy the schema file but still the issue remains

![image](https://user-images.githubusercontent.com/3501042/132636402-5c90836f-914e-4633-9985-110644824d82.png)

**Comment by dmvtech** [comment] 2021-09-09 16:47
@SundaresanSivakumar 

- If you expand the Details section, what does it show? (Any error different than the above console trace?)
- Are you able to share your bot with me? Either in a zip or in a (private) repository?

**Comment by dmvtech** [comment] 2021-09-16 18:01
Hi @SundaresanSivakumar Just checking in. Can you comment on the questions above?

**Comment by dmvtech** [comment] 2021-09-17 21:51
Closing due to lack of reply. If you are still need assistance, please comment with the information asked above and anything else that may help troubleshoot and we will reopen.

**Closed by dmvtech** 2021-09-17 21:51 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
