### ISSUE TITLE
Publish failed Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by f14eagle** [microsoft/BotFramework-Composer#8850] opened 2021-12-13 02:58 UTC
## Describe the bug

Click on the Publish selected bots and get the error: unable to get local issuer certificate

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Go to Publish -> Check on the bot you want to publish -> Click Publish selected bots

## Screenshots

![image](https://user-images.githubusercontent.com/3694968/145745196-e18c01ad-fc7c-4ed1-9f6f-8cfb8d713eaa.png)

## Additional context

I also get the same issue when opening the Package Manager tab, is that possible to add some configuration to ignore such issue, like NODE_TLS_REJECT_UNAUTHORIZED=0

Thanks.

**Comment by tdurnford** [comment] 2021-12-15 19:20
@f14eagle This is most likely caused by a DNS/SSL issue or a network proxy issue. Can you:

1. Try to reboot, they might have some DNS/SSL certs in a cache
2. Check to see if there is  a network proxy or restricted internet access

**Comment by f14eagle** [comment] 2021-12-16 02:04
@tdurnford since I'm not able to change the corp network environment, is there any other way to resolve this issue?

On Windows I can use below command to bypass the tls issue

C:\Windows\System32\cmd.exe /c "SET NODE_TLS_REJECT_UNAUTHORIZED=0&& START ^"^" ^"C:\Program Files\Bot Framework Composer\Bot Framework Composer.exe^" --remote-debugging-port=8881"

Is there similar way on MAC?

**Comment by dmvtech** [comment] 2021-12-16 23:11
hi @f14eagle Unfortunately I'm not a mac user and do not have a mac to test on, but my assumption is that you should be able to launch terminal (or other memory runspace) and supply commands to set the environment variable and launch Composer.

With a quick peek, it looks to me like there's no straightforward equivalent of the `set` command, but depending on how you need this configured, looks like there is a few different options.
https://apple.stackexchange.com/questions/106778/how-do-i-set-environment-variables-on-os-x

I think `open` is the equivalent of `start`:
https://scriptingosx.com/2017/02/the-macos-open-command/

**Comment by f14eagle** [comment] 2021-12-17 06:25
@dmvtech 

I tried below command on my MAC but the variable is not passed to the Bot Framework Composer, and I'm not able to find any documentation about such situation for the Bot Framework Composer on MAC

NODE_TLS_REJECT_UNAUTHORIZED=0 & open 'Bot Framework Composer 2.0.0.app'/

**Comment by dmvtech** [comment] 2021-12-18 00:47
hi @f14eagle I'm not sure either. There is no way to add this type of configuration to Composer, unfortunately. 

If you are going with this workaround, you need to figure out how to launch Composer in a runspace that will allow you to configure that environment variable. That is more of a MAC thing and you should pursue resources in that arena. 

Otherwise, it might be a better route to discover what the root cause is and what might be the issue with the cert/TLS.

Closing this as there is nothing to be done from Composer side.

**Closed by dmvtech** 2021-12-18 00:47 UTC
Labels: customer-reported, Bot Services, customer-replied-to, Support

**Comment by f14eagle** [comment] 2021-12-20 02:58
@dmvtech

C:\Windows\System32\cmd.exe /c "SET NODE_TLS_REJECT_UNAUTHORIZED=0&& START ^"^" ^"C:\Program Files\Bot Framework Composer\Bot Framework Composer.exe^" --remote-debugging-port=8881"

With above command the NODE_TLS_REJECT_UNAUTHORIZED env variable can be passed to Composer successfully on Window. So do you mean there is no way to add this type of configuration to Composer for **macOS only**?

Previously I have encountered another issue of the Composer on macOS and raise a ticket, another collaborator took the ticket and told me follow below steps to enable the debug info.

- Navigate to Composer's install directory. On Windows that will often be in your AppData folder, located somewhere like C:\Users\<your username>\AppData\Local\Programs\Bot Framework Composer
- Open a terminal/command prompt in this directory (you can do this by right-clicking and selecting "Open Terminal/Command Prompt here", or by navigating to this directory though the terminal directly)
- Run the command set DEBUG=composer*
- Now run the Composer from the command line. Again on Windows with a command like .\'Bot Framework Composer.exe' (don't forget the apostrophes, you need them since the name of the executable has spaces)
- Do not close the terminal window, the debug messages should populate there
- Attempt to run your bot again, and screenshot any error or debug messages that appear

Those steps are for Windows, and need to set the DEBUG env variable to enable the feature, is that mean I'm not able to enable the DEBUG info on macOS as well?

Thanks.

**Comment by f14eagle** [comment] 2021-12-23 04:37
@dmvtech could you please look at the problem above?

**Comment by bharathidineshz** [comment] 2023-10-03 19:21
I hav followed the above steps in windows machine.And am still facing the issue.
![image](https://github.com/microsoft/BotFramework-Composer/assets/72759810/43572738-a99f-4e31-b216-2acba42aef19)
