### ISSUE TITLE
Provision Failure when deploying a bot to Azure

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Composer#7107] opened 2021-04-19 18:35 UTC
## Version
1.4.0-nightly.236490.3735dd3

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a Blank bot in Composer
2. Add a new 'Publishing Profile'
3. Enter a bot name, set the publishing target to 'Publish bot to Azure'. Click 'Next: Configure resources'
4. Choose 'Create new resources', click 'Next'
5. Enter subscription, for resource group select 'create new', for region select US West. Click 'Next: Review'
6. Remove optional resources. Click 'Next'
7. Click 'Done'

## Expected behavior
The Bot should successfully deploy, but instead, I get this error:
![image](https://user-images.githubusercontent.com/29185255/115285834-36206a80-a103-11eb-877d-1e9cf956d50f.png)

**Comment by GeoffCoxMSFT** [comment] 2021-04-21 19:04
@Dewain27 I cannot reproduce this.  I verified the code has retry logic around it.

**Comment by sgellock** [comment] 2021-04-21 19:19
I am running the following nightly and I'm not able to repo this scenario.  I do remove all service options except what's mandatory.  so if there were service options that caused this, it's hard to know from the repro steps.

**Comment by GeoffCoxMSFT** [comment] 2021-04-21 19:25
Closing issue as this can no longer be reproduced

**Closed by GeoffCoxMSFT** 2021-04-21 19:25 UTC
Labels: Area: Publish, P0, R13 Bugbash, Type: Bug
