### ISSUE TITLE
Open dialog should allow me to type in path

### ISSUE THREAD

**Issue by arturl** [microsoft/BotFramework-Composer#3233] opened 2020-05-29 20:47 UTC
Make this drop-down editable:
![image](https://user-images.githubusercontent.com/1875734/83303951-d2bbe000-a1b2-11ea-91d5-b0e38f07275a.png)

**Comment by cwhitten** [comment] 2020-05-31 20:34
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3009

**Closed by cwhitten** 2020-05-31 20:34 UTC
Labels: Needs-triage, Type: Bug
