### ISSUE TITLE
Start/restart bot with LUIS primary key cause error

### ISSUE THREAD

**Issue by WTobor** [microsoft/BotFramework-Composer#1573] opened 2019-11-13 15:32 UTC
## Version
branch `stable`, commit a4a2697

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Generate bot from template ToDoLuis (no LUIS primary key set)
2. Run `pwsh ./Scripts/create.ps1` with valid parameters (status: Done)
3. Run `pwsh ./Scripts/deploy.ps1` with valid parameters (status: Publish Success)
4. Start/Restart bot with LUIS primary key set

##Current behaviour
There is an error
![image](https://user-images.githubusercontent.com/22730914/68777835-923faf00-0632-11ea-9be8-838dbc74450a.png)
![image](https://user-images.githubusercontent.com/22730914/68777883-a5527f00-0632-11ea-9e99-6ebb6c1959c0.png)

## Expected behavior
There is no error

**Comment by a-b-r-o-w-n** [comment] 2019-11-13 16:52
Hi @WTobor I am looking into this issue and in the screenshot you shared, there appears to be an error in the value of one of the `allowInterruptions` fields. Did you modify the dialog properties before restarting? Would you mind sharing the contents of the `Main.dialog` file?

**Comment by WTobor** [comment] 2019-11-13 18:04
I did not modify the dialog. `Main.dialog` in attachment.
[Main.zip](https://github.com/microsoft/BotFramework-Composer/files/3842708/Main.zip)

**Comment by a-b-r-o-w-n** [comment] 2019-11-13 20:29
I will need to work with our SDK team to diagnose this. I'll get back to you when I get more information.

**Comment by luhan2017** [comment] 2019-11-14 00:44
I suspect this is because the deployment and local environment are using different luis authoring key, which cause the failure on luis recognizer and the expression failed to be evaluated. Investigating more on this.

**Comment by WTobor** [comment] 2019-11-14 07:13
This issue is the same for the new template app
- created new bot app from template Todo LUIS,
- set LUIS authoring key,
- waited for the spinner to finish "publishing" and "reloading" (spinner position: in the place of "Test in Emulator") 
![image](https://user-images.githubusercontent.com/22730914/68834183-77fae500-06b5-11ea-9449-0f857f1ade5f.png)
![image](https://user-images.githubusercontent.com/22730914/68834522-4c2c2f00-06b6-11ea-91a7-9fbdb8cc3be8.png)
Even when I set `luis:enpointkey` according to the instructions
![image](https://user-images.githubusercontent.com/22730914/68834605-75e55600-06b6-11ea-9f13-1013dc344526.png)
it did not help

**Comment by hibrenda** [comment] 2019-11-14 07:37
@WTobor Could you sync with latest stable branch and have a try again?  As both I and @luhan2017 test on stable and master branch, we could not reproduce it. It might be fixed with latest PR related to LUIS key management.

**Comment by WTobor** [comment] 2019-11-14 07:52
as I wrote before, I have latest changes (branch `stable`, commit a4a2697)

**Comment by smithbrianscott** [comment] 2019-11-14 17:23
I have a similar issue but not directly related, When I enter my primary key in the prompt, I am given a very generic error message "Error publishing to LUIS".

Steps:

1. Set Recognizer Type to LUIS
1. Click on Start Bot
1. I receive a pop up stating I need to publish LUIS Models. I enter my primary key
![image](https://user-images.githubusercontent.com/19986009/68880261-edc47800-06d8-11ea-841b-08d444354bd3.png)
1. I get an error right away that simply states "Error publishing to LUIS"
![image](https://user-images.githubusercontent.com/19986009/68880436-41cf5c80-06d9-11ea-8488-dc931d5aec7d.png)

Any ideas why? I created an authoring resource via luis.ai and pasted the Primary key value into the pop up.

**Comment by VanyLaw** [comment] 2019-11-18 08:19
Hi @smithbrianscott, this error message "Error publishing to LUIS" is a general response when runbuild luismodel throw error. Many reasons may cause this error, such like error in building luis model, error in training luis morel, and error in publishing luis model. To figure out what error you have, you can add a` console.error(error) `in publish method of server/src/models/bot/lupublisher.ts file, then you can get it in server's console.
FYI.
![image](https://user-images.githubusercontent.com/21174180/69035073-b0842100-0a1d-11ea-9e49-ee9984d21836.png)

@lei9444, to solve this type of issues thoroughly, we need to enhance the runbuild package, and format those error messages to reply to client.

**Comment by smithbrianscott** [comment] 2019-11-18 16:49
@VanyLaw Thank you, I found the error ended up being a self signed certificate since I am behind a corporate firewall.

**Comment by hibrenda** [comment] 2019-12-04 16:30
As the issue has been solved and new issue #1597 will track further feature updates. so close this issue.

**Closed by hibrenda** 2019-12-04 16:30 UTC
Labels: Bot Services, Type: Bug, Type: Enhancement, customer-replied-to, customer-reported
