### ISSUE TITLE
Form Dialog , when mapping property to personname.schema is throwing error

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6491] opened 2021-03-22 11:05 UTC
## Describe the bug

Form Dialog , when mapping property/ attribute to personname.schema is throwing error while generating dialog. Error "Generating form dialog using "FormDialog01" schema failed. Please try again later."

Same is applicable to email

## Version

![image](https://user-images.githubusercontent.com/26645750/111980357-172bba00-8afe-11eb-855f-036bf8d398a1.png)

## Browser

- [ ] Chrome

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Go to Form Dialog
2. Click on ' add property -> map to personname.schema
3. Click on Generate Dialog

**Comment by hatpick** [comment] 2021-03-24 16:51
@aparnaji can you share the entire schema (or partially the part related to property of type person name)?

**Comment by msomanathan** [comment] 2021-03-30 16:29
@aparnaji could you please help with the information regarding the schema you are using?

**Comment by aparnaji** [comment] 2021-03-30 17:04
I deleted the generated dialog and regenerated , Now it worked
Looks like if we map to particular type and generate dialog , subsequently map to different type and regenerate made the dialog generation fail.  Post deleting the dialog completely and regeneration of form dialog helped to fix the issue

**Comment by msomanathan** [comment] 2021-03-30 18:31
Thanks @aparnaji for confirming the issue is fixed. Closing this issue.

**Closed by msomanathan** 2021-03-30 18:31 UTC
Labels: Area: Form Dialogs, Bot Services, Type: Bug, customer-reported
