### ISSUE TITLE
Object reference not set to an instance of an object on OAuth login

### ISSUE THREAD

**Issue by kshyambabu** [microsoft/BotFramework-Composer#3631] opened 2020-07-15 03:29 UTC
## Describe the bug

Added OAuth prompt using. Access External resources => OAuth login. User is prompted with consent to enter the credentials(first time only). Getting the access token after successful login. Getting "Object reference not set to an instance of an object" error response automatically after that. 

## Version

![image](https://user-images.githubusercontent.com/66311936/87499826-c1eaff00-c678-11ea-8411-c1cfaa8d7e2b.png)

## Browser

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Add OAuth Login from access external resource
2. Run it on emulator
3. Login card is prompted => user enter the credentials and press login

## Expected behavior

Should not be any error response

## Screenshots

![image](https://user-images.githubusercontent.com/66311936/87500001-24dc9600-c679-11ea-8b4d-d899b6ac5625.png)

Login dialog
![image](https://user-images.githubusercontent.com/66311936/87500050-3a51c000-c679-11ea-832b-5abe14296295.png)

Emulator

![image](https://user-images.githubusercontent.com/66311936/87500128-61a88d00-c679-11ea-951f-c466bd6059f2.png)

**Comment by luhan2017** [comment] 2020-07-16 00:54
@kshyambabu , this is a known issue. Please refer to this issue https://github.com/microsoft/botbuilder-dotnet/issues/3901
we recommend you don't use turn memory + prompts under foreach action. You can always mitigate this by assigning the turn memory to a dialog memory and use that in the foreach action.

**Comment by kshyambabu** [comment] 2020-07-16 18:05
@luhan2017 We are not using turn memory as you see the screen shots of our implementation. We need to authenticate each user of the bot. So that I used OAuth prompt in for each loop. 
And I followed the instruction as explained in the Microsoft docs to assign the token dialog context. Given this scenario in the screenshots, could you explain bit further how to avoid the error?

activity
![image](https://user-images.githubusercontent.com/66311936/87705975-5e69ea00-c7bc-11ea-8496-2ccdcf3ca070.png)

LogEx dialog
![image](https://user-images.githubusercontent.com/66311936/87706111-9c670e00-c7bc-11ea-9d83-42710ceb024e.png)

**Comment by luhan2017** [comment] 2020-07-22 05:07
@kshyambabu , sorry for the late response, turn.Activity.membersAdded is used in the for loop, that's the root cause of this issue.
If you want to add OAuth login will update the turn.Activity, so that in the next loop, you will get an error "Object reference to null".

I recommend you to fix this issue by assigning turn.Activity to dialog.Activity and use dialog.Activity in the for loop.

![image](https://user-images.githubusercontent.com/32191031/88136613-32b38d80-cc1c-11ea-8ea9-5864091d745d.png)

Please let me know if it still not works.

**Comment by kshyambabu** [comment] 2020-07-22 14:00
@luhan2017 I can understand. 
And, I added "Set a property" as you suggested. But, getting the same error. Could you suggest alternative  fix.

**Comment by kshyambabu** [comment] 2020-07-22 19:05
@luhan2017 I can understand. The fix worked on emulator. 
We are using iframe of channel's web chat on sharepoint. The fix is not working on sharepoint deployment. 
Moreover the actions (like getting userinfo by using the token got from OAuth prompt) below OAuth prompt are not executing. And directly giving this error.

**Comment by luhan2017** [comment] 2020-07-23 09:24
@kshyambabu , could you share more information on the emulator vs webchat behavior? my understanding is in emulator, everything worked as expected, but in iframe of webchat, you got an error just after the OAuth login, which is saying: "Object reference not set to an instance of an object", is this correct?

**Comment by kshyambabu** [comment] 2020-07-24 17:51
@luhan2017 
**Emulator**
Everything seems working fine

### On SharePoint page
**Web Chat**
Using iframe. Login card is displaying and immediately "Object reference not set to an instance of an object" Error is poping up without even logging. 
And, getting getsessionid() 400 error when I click on login after "Object reference not set to an instance of an object" error is poped up.

**DirectLine**
Using dynamic rendering of chatbot by using DirectLine token. Everything seems working fine

**Comment by luhan2017** [comment] 2020-07-30 10:21
@kshyambabu sorry for the late response, just want to let you know that I can reproduce this issue and I am still investigating on this.

**Comment by luhan2017** [comment] 2020-08-04 08:44
@kshyambabu, we have investigated and found the root cause. 
In one word, the issue is because when using iframe there are two separated ConversationUpdate sending to the bot, and when user first talks to the bot, it doesn't know the user id and use conversation id as the user id so it will cause the failure of validation on the magic code. (user id changed, so get user token error.)

For more detail 
In Emulator or DirectLine mode, the conversation is like this:
1. bot received ConversationUpdate with two members added botid and userid
2. bot prompt for OAuthInput.
3. user click the link and get the token. Done

But for iframe, the conversation is like this:
1. bot received ConversationUpdate from botid
2. bot prompt for OAuthInput. (at the moment the userid is not initialized)
3. user click the link and get an magic code.
4. user send the code to bot (Note here, there are two messages sent to the bot).
5. bot received ConversationUpdate from the user.
6. bot received the magic code from the user. (the user id mismatch with the user id of step2.)

That's why you see different behavior between directline and iframe. To mitigate this issue, we propose to use this to host a bot in you website.

```
<!DOCTYPE html>
<html>
<body>
    <div id="webchat" role="main"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script>
      (async function () {
        const user = {
          id: "user1",
          name: "testuser",
          role: "user",
        };

        const res = await fetch(
          "https://directline.botframework.com/v3/directline/tokens/generate",
          {
            headers: {
              "Content-Type": "application/json",
              Authorization:
                "Bearer <Your Secret In the Iframe Page>",
            },
            method: "POST",
            body: JSON.stringify({ user }),
          }
        );

        const { token } = await res.json();

        window.WebChat.renderWebChat(
          {
            directLine: window.WebChat.createDirectLine({ token }),
            userID: user.id,
            username: user.name,
          },
          document.getElementById("webchat")
        );
      })().catch((err) => console.error(err));
    </script>
    <div id="webchat" style="height: 100%;"></div>
</body>
</html>
<html>
<head>
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
    <meta name="Robots" content="NOINDEX " />
</head>
<body>
</body>
<script type="text/javascript">
    var gearPage = document.getElementById('GearPage');
    if(null != gearPage)
    {
       gearPage.parentNode.removeChild(gearPage);
       document.title = "Error";
    }
</script>
</html>
```

Could you please have a try and let me know if it still not works?

**Comment by kshyambabu** [comment] 2020-08-05 17:00
@luhan2017 Thanks for response. We used DirectLine instead of WebChat Iframe because of the limitations for OAuth. DirectLine seems work fine. But, we had to write seperate function to get the token from DirectLine for DirectLine secret security reasons.

**Comment by luhan2017** [comment] 2020-08-06 01:52
@kshyambabu, great to know this. 
In this page, https://github.com/microsoft/botframework-webchat, there is a message that 
```
We strongly recommend using the token API instead of providing the app with your secret. To learn more about why, see the [authentication documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0) on the [token API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0) and client security.
```

**Comment by kshyambabu** [comment] 2020-08-08 04:08
@luhan2017 , yes, We are using the [token API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0).
But, We used a HTTP function (with function key secret) as middleware to get the bearer token for the chat from DirectLine, instead of exposing the DirectLine secret to the client.

**Comment by luhan2017** [comment] 2020-08-11 09:11
@kshyambabu , can we close this issue?

**Closed** 2020-08-11 15:54 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported

**Comment by Khanh-Ngy** [comment] 2021-01-04 10:34
@luhan2017 ,

I did an example at here
![image](https://user-images.githubusercontent.com/71876037/103526074-e2bb4100-4eb2-11eb-81f8-a619b67bf648.png)
But it still threw this error
![image](https://user-images.githubusercontent.com/71876037/103526119-f8c90180-4eb2-11eb-8403-fc829036d408.png)

Hope you can help. So many tks !
