### ISSUE TITLE
Edit menu doesn't appear to honor clipboard state

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3225] opened 2020-05-29 18:05 UTC
## Describe the bug
I can break this out into multiple issues if you prefer.  just assign back to me, let me know, and I'll create individual items.

Launching Composer.  Click on the Edit menu.  All menu items are enabled.  

This behavior also exist when I open an existing bot project.

This behavior also exist when I open a Dialog 

## Version
1.0.0

## Browser

- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

See above for steps.

## Expected behavior

I expect any menu item to be enabled when it can perform its intended action and to be disabled when conditions don't exist for it to perform its intended action.

**Comment by cwhitten** [comment] 2020-05-30 16:23
Closing this as a dupe of #3227

**Closed by cwhitten** 2020-05-30 16:23 UTC
Labels: Needs-triage, Type: Bug
