### ISSUE TITLE
Provisioning modal  fit and finish

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#7236] opened 2021-04-21 20:41 UTC
![add resources](https://user-images.githubusercontent.com/67944302/115618217-41ac9680-a2a7-11eb-9fc1-5216020a106c.png)

Electron, OS, v1.4.0

**Comment by GeoffCoxMSFT** [comment] 2021-04-22 22:14
@JaskeeratBedi-cmk Are you not signed in to Azure when you get to this page?  The reason it is on the left is because the sign-out and badge is missing.

**Comment by JaskeeratBedi-cmk** [comment] 2021-04-23 19:22
@GeoffCoxMSFT this is the Hand off to admin scenario, where technically I do not need to signed in. Regardless, I would like the main CTA's to be on the left hand side, where they usually are for our modals..

**Comment by GeoffCoxMSFT** [comment] 2021-04-26 17:31
@VamsiModem I think this is a partial dupe of the sign out issue you are working on already.  When the sign-out is hidden, it seems the buttons move to the left.  We should update the layout/css for each of the footers to make sure the buttons stay on the right.

**Closed** 2021-04-28 22:18 UTC
Labels: Area: Publish, P2, Type: Bug

**Comment by sgellock** [comment] 2021-04-28 22:59
Shiproom - you guys merged a PR that didn't have a ship room approved issue.  let's follow the process or I'm going to ask you to back these out in the future.

I've assed Shiproom-Approved to keep the bookkeeping correct.  :-(
