### ISSUE TITLE
Unable to deploy to azure - Get error "Required field 'accessToken is missing from publishing profile"

### ISSUE THREAD

**Issue by KarlXOL** [microsoft/BotFramework-Composer#5695] opened 2021-02-04 17:34 UTC
## Describe the bug
I did following:
1. Provisioned successfully azure ressouces by running <provisionComposer.js>
2. created a simple bot based on echo template
3. added a publishing profile in which I filled outpout from running <provisionComposer.js>
4. When trying to publish I get this error in the composer frontend
![grafik](https://user-images.githubusercontent.com/21153915/106931373-cfe89600-6716-11eb-8a52-276a93c4ee49.png)
![grafik](https://user-images.githubusercontent.com/21153915/106932014-7d5ba980-6717-11eb-9ede-d6849d48ddee.png)

Output in developer tools:
![grafik](https://user-images.githubusercontent.com/21153915/106931482-ef7fbe80-6716-11eb-856c-d4d371186f43.png)
![grafik](https://user-images.githubusercontent.com/21153915/106931543-fdcdda80-6716-11eb-8a36-07b2712f80c8.png)

## Version
Composer Version 1.3.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

Would appreciate any help!!
Thanks in advance

**Comment by v-kydela** [comment] 2021-02-04 19:18
Thank you for the report, @KarlXOL. I'd like to help and I have a few questions.

1. Can you link to any documentation you followed?
2. Where did you get provisionComposer.js?
3. What arguments did you pass into provisionComposer.js?
4. Since you've checked every browser option except Safari, does that mean you've tried this using both the desktop version of Composer and the web-hosted version built from source code?

**Comment by KarlXOL** [comment] 2021-02-04 19:31
Thanks for quick response:
1) Documentation
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

2) Got provisionComposer from folder <scripts> inside the generated bot directory

3) Arguments I passed: --subscriptionId --name --appPassword

4) I used composer from installation ; Actually I'm not sure how this is related to the browser?
    But I entered the composer-URL also into FF, Chrome, ... But deployment didn't work also when trying this from browser

**Comment by v-kydela** [comment] 2021-02-04 21:26
@KarlXOL - Thank you for the information.

The documentation you linked to doesn't mention provisionComposer.js. Does that mean you followed the instructions in README.md in your bot's project folder? Did you get an access token from running provisionComposer.js? What did you do with that access token?

What do you mean by "the composer-URL"? Do you mean the bot's messaging endpoint? You say you used Composer from installation, so I'm guessing that means you're using the desktop version. Composer is also available as a locally-running web application. If you build the source code by following [these instructions](https://github.com/microsoft/BotFramework-Composer#build-composer-locally), you can run Composer in a browser like any other website.

**Comment by KarlXOL** [comment] 2021-02-05 05:57
Yes, you are right. For the creation of the publishing profile I followed the readme.
I got an accesstoken and pasted it in the publishing profile as described.

I used the desktop-version then. By composer-URL I mean the URL <localhost:5000> which I found in the developer tools of the desktop version then.

**Comment by luhan2017** [comment] 2021-02-05 07:17
Did composer ask you to login before you start publish? @KarlXOL

**Comment by KarlXOL** [comment] 2021-02-05 09:06
Yes, I get the login request, authentication was successful and then fails with the error above

**Comment by v-kydela** [comment] 2021-02-05 19:49
@KarlXOL - What happens if you [create new resources using the built-in Composer wizard](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-new-azure-resources) instead of provisionComposer.js?

**Comment by KarlXOL** [comment] 2021-02-05 20:15
I tried this, but it was not working. No dialog opened for configuration of azure resources.

**Comment by v-kydela** [comment] 2021-02-05 22:48
@KarlXOL - That's very strange. I wonder if the problem you're experiencing with the wizard is related to the problem you're experiencing with provisionComposer.js.

Please tell us the steps you're taking to reproduce the problem you've experienced with the wizard and provide screenshots so we can see which point it's failing at. Also, try using the developer tools to see if the console shows any errors.

**Comment by KarlXOL** [comment] 2021-02-06 06:54
Ok, tried to create azure resources via composer
1. logon to 
2. add publishing profile 
![grafik](https://user-images.githubusercontent.com/21153915/107111413-41782f80-6850-11eb-947d-d3cdb661106c.png)

3. select option to create new resource
then it hangs with this error
![grafik](https://user-images.githubusercontent.com/21153915/107111440-77b5af00-6850-11eb-93e5-f285232b261f.png)


Hope this helps
Thanks

**Comment by KarlXOL** [comment] 2021-02-06 19:12
Found a workaround which might be of interest for your investigation:
1. Started bot-composer desktop version
2. then I entered the URL localhost:5000 in firefox to use the web version of the composer (bot-composer seems to start a server)
3. then I tried to publish, add a profile, provision azure resources which all worked here
    the major difference I encountered was that I get asked the access-tokens for account and ms-graph. Bot of these tokens I created with the commands shown on the form.

This way I was able to publish a  bot and test in azure web-chat. 
There were some errors when trying to use europe region. At the end I used us-west. But that seems to be a different thing.

Hopefully that could give you an hint?

**Comment by luhan2017** [comment] 2021-02-07 08:11
@KarlXOL, thanks a lot for this information. I got some clues from your workaround, the issue should relate to the oneauth library. Somehow, it showed that you logged in successfully, but failed to get the token. There is a similar issue #5436. @carlosscastro, I remember we had a thread with oneauth team on this issue, let's follow up on this offline.

**Comment by KarlXOL** [comment] 2021-02-07 11:22
Can't see nothing else than this when adding a new profile  (besides the token error in the console) => 
![grafik](https://user-images.githubusercontent.com/21153915/107144982-e1ac8200-693e-11eb-8130-a2e20c8ba406.png)

**Comment by luhan2017** [comment] 2021-02-08 02:37
@KarlXOL thanks a lot for your info, the issue is exactly same as #5436 , we are working with oneauth team on this error now. will keep this thread updated. Thanks!

**Comment by tonyanziano** [comment] 2021-02-10 21:23
@KarlXOL to correct @luhan2017 's update slightly:

This is a different error but with a similar solution to that of #5436. The authentication library we are using wasn't able to acquire a token silently after signing you in, and so we need to write some code on our side that will detect this and allow you to acquire a token interactively (clicking through some more authentication UI).

**Comment by luhan2017** [comment] 2021-03-31 02:17
This should be fixed by #6467

**Closed by luhan2017** 2021-03-31 02:17 UTC
Labels: Area: Publish, Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
