### ISSUE TITLE
UX Backlog item | Do a toolbar button pass across all screens

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1435] opened 2019-10-31 22:15 UTC
Objective:
Show the right toolbar buttons for the right page 

- (authoring canvas, All up LU and LG etc)
- show the right/relevant toolbar buttons for the selected item
- make sure that users can 'add' from all places (add dialog add trigger etc.

**Comment by a-b-r-o-w-n** [comment] 2020-06-25 16:44
Duplicate of #3494

**Closed by a-b-r-o-w-n** 2020-06-25 16:44 UTC
Labels: UX Design
