### ISSUE TITLE
Version 2.1.3: Existing Action gets replaced when adding new Action nearby.

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#9670] opened 2023-11-15 22:15 UTC
Existing Action gets deleted when adding new Action nearby. This has been observed a few times.
Occasionally when adding a new action in the canvas, the nearby existing action gets replaced by the app with the new added action.
See a sample below: I was adding a new "Send a response" action above the existing "Begin a new dialog" action, what the app does is beyond adding the new "Send a response" action, it also replaced the "Begin a new dialog" action with another "Send a response" action.

<img width="917" alt="image" src="https://github.com/microsoft/BotFramework-Composer/assets/44714043/8dd656d0-f741-4c81-aa7a-d8db32e818fb">

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment] 2023-11-17 00:04
Hi @dawwa 

So, it only happens some of the time? I'm not able to reproduce it. Does it happen in certain scenarios more than others?

**Comment by dawwa** [comment] 2023-11-22 07:17
> Hi @dawwa
> 
> So, it only happens some of the time? I'm not able to reproduce it. Does it happen in certain scenarios more than others?

hmm... I'm not sure how it could repro either, kinda random, happened a few times.

**Comment by dmvtech** [comment] 2024-07-05 23:42
Closing due to inability to reproduce.

**Closed by dmvtech** 2024-07-05 23:42 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
