### ISSUE TITLE
Conversational core bot not connecting to LUIS?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6757] opened 2021-04-08 01:14 UTC
## Describe the bug

I created a bot with the "Basic conversational" template and added a LUIS resource. When I test the bot in Web Chat or in 
Emulator, the bot does not understand any utterances and it also does not send LUIS trace events.

(tagged as both "Components" and "Webchat integration" since I'm not sure where the issue is.)

## Version

Version:  1.4.0-nightly.232411.9f6c16e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

**1. Open Composer.**

**2. Select New.**

**3. Choose "Basic conversational bot" template, and give it a name.**

**4. When bot has been created and you land on the rocket ship, click "Add a LUIS key".**

**5. Follow Azure sign in screens.**

**6. Create a new LUIS resource.** This is what I selected:**
![image](https://user-images.githubusercontent.com/39317542/113950532-6f351280-97c6-11eb-83ba-9d75ba0c0a43.png)
![image](https://user-images.githubusercontent.com/39317542/113950579-8d027780-97c6-11eb-8add-5879f14232cd.png)

**7. Start bot.**

**8. Test in Web Chat** with "help" which should be recognized since it is an example trigger phrase for the "Help" trigger. 

The bot sends a message that it has hit an error:
![image](https://user-images.githubusercontent.com/39317542/113950940-642eb200-97c7-11eb-88a8-9bc0bd1de340.png)

Here are the details of the "trace" event sent:
![image](https://user-images.githubusercontent.com/39317542/113951025-8f190600-97c7-11eb-862d-0035d1d1ff1f.png)

```
{
  "activity": {
    "type": "trace",
    "serviceUrl": "http://localhost:5000",
    "channelId": "emulator",
    "from": {
      "id": "663ca979-4a05-435a-9707-a71c60754b6e",
      "name": "Bot",
      "role": "bot"
    },
    "conversation": {
      "id": "f0c5c620-70cb-48de-9386-d3a2ad1a9193|livechat"
    },
    "recipient": {
      "id": "61e572a8-8b9e-40cb-a66c-891362dadc4f",
      "role": "user"
    },
    "locale": "en-us",
    "replyToId": "1d142a78-87a7-4660-ab97-8184bfba793a",
    "label": "ErrorOccurred",
    "valueType": "Exception",
    "value": {
      "StackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\n   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.GetLuisResponseAsync(String utterance, LuisPredictionOptions options, HttpClient httpClient, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeAsync(ITurnContext turnContext, String utterance, LuisPredictionOptions options, HttpClient httpClient, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeInternalAsync(DialogContext dialogContext, Activity activity, HttpClient httpClient, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeInternalAsync(DialogContext dialogContext, Activity activity, LuisRecognizerOptions predictionOptions, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.AI.Luis.LuisAdaptiveRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.MultiLanguageRecognizer.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.CrossTrainedRecognizerSet.<>c__DisplayClass7_0.<<RecognizeAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.CrossTrainedRecognizerSet.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.RecognizerSet.RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.OnRecognizeAsync(ActionContext actionContext, Activity activity, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ProcessEventAsync(ActionContext actionContext, DialogEvent dialogEvent, Boolean preBubble, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.OnPreBubbleEventAsync(DialogContext dc, DialogEvent dialogEvent, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Dialog.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.DialogContainer.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)\n   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)",
      "Message": "Response status code does not indicate success: 403 (Forbidden).",
      "Data": {
        "DialogContext": {
          "ActiveDialog": "conversational_core_0407b",
          "Parent": null,
          "Stack": [
            "conversational_core_0407b"
          ],
          "State": {
            "dialog": {
              "eventCounter": 3,
              "_adaptive": {
                "actions": []
              }
            },
            "this": {
              "eventCounter": 3,
              "_adaptive": {
                "actions": []
              }
            },
            "conversation": {
              "DialogState": {
                "dialogStack": [
                  {
                    "id": "conversational_core_0407b",
                    "state": {
                      "eventCounter": 3,
                      "_adaptive": {
                        "actions": []
                      }
                    },
                    "StackIndex": null,
                    "Version": "bQm9lNchdeoxuUfQaDOYRNEvF0fo5NmxIwZFxBnUb/A="
                  }
                ]
              }
            },
            "user": {
              "greeted": "true"
            }
          }
        }
      },
      "InnerException": null,
      "HelpLink": null,
      "Source": "System.Net.Http",
      "HResult": -2146233088
    },
    "name": "Trace",
    "id": "6ab3cd3a-51e2-41f7-813e-1e88b955740b",
    "localTimestamp": "2021-04-07T17:32:32-07:00",
    "timestamp": "2021-04-08T00:32:32.812Z"
  },
  "timestamp": 1617841952812
}
```

**8. Test bot in Emulator** (I did this step to see if the LUIS traces appeared in Emulator). 

In Emulator, the same utterance, "help", seems to trigger the "Unknown intent" dialog, rather than the "Error occurred dialog" and no LUIS traces appear in the log:

![image](https://user-images.githubusercontent.com/39317542/113952958-980bd680-97cb-11eb-8de4-62e857f7c9ad.png)

Looking in LUIS.ai, the model created from the template is there, so I don't know why the bot is not talking to it:
![image](https://user-images.githubusercontent.com/39317542/113953236-34ce7400-97cc-11eb-91b8-69d46b1a99be.png)

## Expected behavior

I expected the bot to work since I didn't get any errors when creating the bot or adding the LUIS resource. 
I also expected to see LUIS traces in Emulator so I could check to see what the results from LUIS were.
I also expected the bot to respond the same in Web Chat as in Emulator, instead of causing the "ErrorOccurred" trigger to fire in Web Chat but the "Unknown Intent" to fire in Emulator.

**Comment by benbrown** [comment] 2021-04-09 20:37
This was caused by the endpoint key being set in the bot's configuration, but not "assigned" to the published LUIS application.

This was resolved by *no longer creating or setting an endpoint key*.  This should be resolved in the latest.

Fixed by #6791

**Closed by benbrown** 2021-04-09 20:37 UTC
Labels: Area: Components, P0, R13 Bugbash, Type: Bug
