### ISSUE TITLE
Composer generates bogus $schema reference when creating .dialog files

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6451] opened 2021-03-17 19:30 UTC
## Describe the bug

Dialog files are driven by schema.  The schema is the **application schema** which should be in **app.schema**, but is instaed in extremely poorly named **sdk.schema** file.  

But the generated .dialog files have a $schema file pointing to some random file checked into github repo which has no correlation at all with the active schema (which is the merge of all installed components.) 
## Version

1.4.rc2

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create project.
Look at generated .dialog file

## Expected behavior

a. It should be pointing to a **local file** which is the application schema
b. that file should be called **app.schema** NOT **sdk.schema**. 
```json
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$schema": "https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/Composer/packages/server/schemas/sdk.schema",
}
```
This should be 

```json
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$schema": "./schemas/app.schema",
}
```

**Comment by cwhitten** [comment] 2021-03-22 19:56
Closing as a dupe of https://github.com/microsoft/botframework-components/issues/780

**Closed by cwhitten** 2021-03-22 19:56 UTC
Labels: Team: Platform, Type: Bug
