### ISSUE TITLE
Error running yarn build

### ISSUE THREAD

**Issue by Brambi-Amb** [microsoft/BotFramework-Composer#2353] opened 2020-03-24 18:21 UTC
I have a machine with WIndows 10.
When I run the command yarn build I receive the following error
src/utils/dialogChecker.ts:5:34 - error TS2307: Cannot find module 'botbuilder-expression-parser'.

**Comment by cwhitten** [comment] 2020-03-25 02:18
hi @Brambi-Amb 

are you using the `stable` branch? can you try running `yarn tableflip` and then `yarn startall`

**Comment by zxyanliu** [comment] 2020-03-25 22:16
FYI. We have the instructions in this [article](https://docs.microsoft.com/en-us/composer/setup-yarn).
If you still have errors, please let us know. Thanks!

**Comment by Brambi-Amb** [comment] 2020-03-28 09:36
Thanks for your help.
4-Yan Liu: I have done what you suggested in the article but the error is the same.
4-Chris Whtten: Node version 2.16.1, Yarn version 1.22.4. I have done what you suggested and during the execution of the command yarn tableflip I received the same error. 
You can see the command execution list and the error here under:
Compiling TypeScript..
$ yarn build:dev && yarn build:server && yarn build:client
$ yarn build:lib && yarn build:tools && yarn build:extensions
$ yarn workspace @bfc/libs build:all
$ yarn build:shared && yarn build:indexers && yarn build:code-editor
$ cd shared && yarn build
$ yarn clean && yarn build:css && yarn build:ts
$ rimraf lib demo/dist
$ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
$ tsc --build tsconfig.build.json
$ cd indexers && yarn build
$ yarn clean && yarn build:css && yarn build:ts
$ rimraf lib demo/dist
$ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
$ tsc --build tsconfig.build.json
src/utils/dialogChecker.ts:5:34 - error TS2307: Cannot find module 'botbuilder-expression-parser'.

5 import { ExpressionEngine } from 'botbuilder-expression-parser';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

**Comment by zxyanliu** [comment] 2020-03-30 21:47
@Brambi-Amb could you please check if you have the [.NET Core SDK 3.1](https://dotnet.microsoft.com/download/dotnet-core) and above? I was unable to reproduce the error you were having with either stable or master branch. Composer works well on my side using either branch.

**Comment by Brambi-Amb** [comment] 2020-04-03 13:27
Yan Liu thanks. I have .Net Core sdk 3.1.200.15016 (x64)

**Comment by cwhitten** [comment] 2020-04-20 19:59
@Brambi-Amb closing as we cannot reproduce this behavior.

**Closed by cwhitten** 2020-04-20 19:59 UTC
Labels: Type: Question
