### ISSUE TITLE
Unable to change `trigger` types

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1480] opened 2019-11-03 20:43 UTC
## Describe the bug
If you create a `MessageActivity` or `Dialog Type` trigger (perhaps others) you are unable to change properties such as the `Message Type` or `Event` requiring you to delete the trigger and re-create it.

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
The property page surface the trigger properties

![image](https://user-images.githubusercontent.com/33519520/68091682-8db81100-fe50-11e9-966e-11046d8e8b8c.png)

**Comment by cwhitten** [comment] 2019-11-04 21:03
Closing as "by design" at the moment, but we have an open UX discussion around making the triggers changeable.

**Closed by cwhitten** 2019-11-04 21:03 UTC
Labels: Status: wontfix
