### ISSUE TITLE
Typing Activity Not Working 

### ISSUE THREAD

**Issue by GitWizardGaurav** [microsoft/BotFramework-Composer#9685] opened 2024-01-08 08:06 UTC
## Describe the bug

Teams Bot Had a feature to show a typing activity to user , that the bot is typing by the time the response is processed.

But with the new team the same feature is not working, however when switched to older teams version the same is working,

Please suggest what changes needs to be done for same to work

**Comment by tracyboehrer** [comment] 2024-01-22 20:17
Duplicate of https://github.com/microsoft/BotFramework-Composer/issues/9679

**Closed by tracyboehrer** 2024-01-22 20:17 UTC
Labels: Type: Bug, Needs-triage
