### ISSUE TITLE
QnA Sample template doesn't work out of the box

### ISSUE THREAD

**Issue by peterbozso** [microsoft/BotFramework-Composer#4872] opened 2020-11-18 09:00 UTC
## Describe the bug

If you create a new bot with the QnA Sample template, it won't work just by clicking on the Start Bot button. You need to first [follow this documentation](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot) and manually add a new trigger for Unknown intent and configure a QnAMaker dialog action to make it work.

## Version

1.2.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot with the QnA Sample template.
2. Click on Start Bot.
3. Click Test in Emulator.
3. Send a message to the bot. Observe the QnAMaker Trace it sends back:
   ```text
   Unable to find a QnA Maker service with Knowledge Base ID c85519cf-adc2-4c9c-9bf6-325e4a97bad6. Please add a QnA Maker service to your bot.
   ```
   This happens even if you provide the `knowledgebaseid` in the Bot Settings page.

## Expected behavior

The template should work out of the box, just by providing the subscription key. The user shouldn't have to add a new trigger and an action to make the template project work. An obvious fix would be to include the Unkown intent trigger and the QnAMaker dialog action inside it in the template.

**Comment by johnataylor** [comment] 2020-11-19 19:08
@luhan2017 any update on this?

**Comment by stevkan** [comment] 2020-11-19 19:22
@peterbozso, unfortunately, the description of this sample is somewhat misleading and needs to be clarified. The sample actually works as expected when its intent is understood.

To explain: the sample is meant to demonstrate two things:
1. How one can use Composer to create a QnA knowledge base by consuming a document, either locally stored or via URL, or by creating one by scratch, and
2. How to utilize that local knowledge base by use of the `QnA Intent recognized` trigger.

When the sample is set up and run, as intended, it works just fine. When the intent is recognized, the bot responds. When it is not, it does nothing (tho, inclusion of an unknown intent would be helpful, out of the box).

**Scratch-built KB**
![image](https://user-images.githubusercontent.com/18403946/99711831-1c490180-2a57-11eb-8072-518d4bf3304c.png)

**Emulator**
![image](https://user-images.githubusercontent.com/18403946/99712125-79dd4e00-2a57-11eb-860f-b6ff5cf59ac8.png)

The primary issue with the sample is the description ("A sample bot that import online QnA resource"). While it doesn't specify an actual QnA(Maker) resource, I think many people naturally think of that, first.

**Comment by stevkan** [comment] 2020-11-19 19:24
Closing this as resolved.

**Closed by stevkan** 2020-11-19 19:24 UTC
Labels: Bot Services, Team: Runtime & Publishing, Type: Bug, Type: Sample, customer-reported, feature-request

**Comment by peterbozso** [comment] 2020-11-20 11:37
@stevkan I agree that the sample works as expected if one figures out how to make it work. :) To me personally, the intent of the sample is totally not clear right now. I would expect to create a new bot using the sample, (optionally create a knowledge base, but I think there should be a default one included too), click start, provide the subscription key and tart sending questions to the bot via the Emulator.
Of course it's expected of any developer to read the whole documentation before starting to use a development tool like the Composer, and I personally did that, and I was able to figure out how to make this sample work based on [this article](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot), no complaints on that front.
But to me, this sample feels like if I'd create an ASP.NET Core Web API project with Visual Studio, build it, run it, then it would crash with an exception, because first I have to manually add a NuGet package to the project, because it's missing from the template. But to know that, I would first have to go through most of the ASP.NET Core docs (to understand what is a NuGet package, or how package management works in .NET overall) before even trying to play around with something simple in the IDE.
Personally I have no issues with this approach neither, but then I'd expect some form of explicit documentation that guides the user step-by-step about what to do in order to make the sample work - because I fully agree that, as a learning experience, can be very useful too.
Because of this, I think you shouldn't have closed this issue without further actions. This issue should have been closed only when the process of making the sample work is clearly documented and that documentation is provided in an easily accessible place alongside the sample itself. (Maybe it already is and I just failed to locate it. In that case, please excuse me my ignorance and feel free to keep this issue closed!) Otherwise, I can already see my less tech-savvy customers coming to me complaining that one of the Microsoft-provided samples inside the application doesn't work. That's something I really don't like to deal with. :)

**Comment by peterbozso** [comment] 2020-11-20 12:21
@stevkan I retried with a new instance of the sample and it turns out that the real problem I was facing when creating this issue is this: #4873 
Thanks for the clarification!

**Comment by stevkan** [comment] 2020-11-20 23:05
@peterbozso, you are right in that Composer's settings should update with the `hostname` and `knowledgebaseid` property values (`endpointKey` auto-fills along with `subscriptionId`).

To clarify my above post a little bit: the sample does make use of the QnAMaker service. When the sample loads it asks for a document to be loaded as the QnA source (or build one from scratch). Composer uses your QnA `subscriptionId` and creates a new KB in the QnAMaker portal retrieving the `endpointKey` as well as the `hostname` and newly created `knowledgebaseid`, at the same time.

However, in my testing, the lack of these two items doesn't hinder the sample from running. Wondering how this was, I searched and found that the `hostname` and `knowledgebaseid` are stored in a separate generated file, located here: `\Composer\QnASample-0\generated\qnamaker.settings.composer.westus.json` which Composer must be accessing.
