### ISSUE TITLE
Renaming a dialog doesn't rename the files.  There is no way to do that.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6291] opened 2021-03-06 22:29 UTC
## Describe the bug

Managing the name of files is super important, because it is the name which is used for mergning files, updates, etc. 
While I can give a different "label" to a dialog, the funderlying assets are not renamed.  This is not just super confusing it will lead to merges in files that you don't understand what the files are. 

## Version

1.3.1-nightly220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. create a bot
2. Try and rename the file, you can't
3. rename the dialog, the file name and assets are unchanged. 

## Expected behavior

That I can manage my assets from composer. This includes the name of the assets.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110222608-51535580-7e88-11eb-8cac-574d3faf0062.png)

**Comment by mewa1024** [comment] 2021-07-04 07:39
(Is #1741 a dupe of this issue?)

**Closed** 2021-11-23 15:41 UTC
Labels: Backlog, Team: Authoring, feature-request
