### ISSUE TITLE
Enabling a custom action causing 'definition not found' error

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#4582] opened 2020-10-29 11:21 UTC
## Describe the bug

I have created a new project in Composer v1.1.1 (stable and also repro'd in nightly) and followed the instructions to enable the sample multiply custom action, re-building the runtime and running the PS script to merge the custom action schema.

Once I have ran the PS script, I now see an error "Definition not found for Microsoft.Ask/properties/activity/oneOf/1/properties/membersAdded/items".

I know we have seen this issue recently (#4416 was recently closed) and some folks fixed it by updating the URL for the schema in the custom action schema file, but I did that before running the script and I am still seeing this error.  The custom action itself does execute correctly when the bot is ran, so this doesn't appear to be affecting the bot's execution.

I believe I am running the latest CLI version too 
@microsoft/botframework-cli/4.11.0-rc.20201028.6f4722f win32-x64 node-v12.18.3

```
{
    "$schema": "https://schemas.botframework.com/schemas/component/v1.0/component.schema",
    "$role": "implements(Microsoft.IDialog)",
    "title": "Multiply",
    "description": "This will return the result of arg1*arg2",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "arg1": {
            "$ref": "schema:#/definitions/integerExpression",
            "title": "Arg1",
            "description": "Value from callers memory to use as arg 1"
        },
        "arg2": {
            "$ref": "schema:#/definitions/integerExpression",
            "title": "Arg2",
            "description": "Value from callers memory to use as arg 2"
        },
        "resultProperty": {
            "$ref": "schema:#/definitions/stringExpression",
            "title": "Result",
            "description": "Value from callers memory to store the result"
        }
    }
}
```

![definition_not_found](https://user-images.githubusercontent.com/3900649/97561860-aeba3000-19d8-11eb-9b0d-822097b06bf0.PNG)

## Version

v1.1.1 stable and also reproduced in nightly.

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

@chrimc62 @zxyanliu

**Comment by cwhitten** [comment] 2020-10-29 16:38
@garypretty, we think something may be amiss with your bf cli toolchain. Root cause is unclear at the moment

**Comment by garypretty** [comment] 2020-10-29 16:41
Thanks @cwhitten Sure, here is the output.

@microsoft/bf-generate 4.9.0-preview-130557
@microsoft/bf-dialog 4.10.0-dev.20200730.3786d10

**Comment by garypretty** [comment] 2020-11-06 12:13
@cwhitten Any obvious change I need to make based on the above output?

**Comment by zxyanliu** [comment] 2020-11-24 20:39
@garypretty FYI. There is a major update to the [doc](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action) on custom action since Composer 1.2 release. You only need to run `npm i -g @microsoft/botframework-cli` to install bf-cli tools (no need to install bf-dialog tool separately). The custom action should work as I tested using both [1.2.0](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.0) and [1.2.1](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.1).

**Comment by dmvtech** [comment] 2020-12-05 00:03
I am hitting this as well. The only thing I can think of possibly contributing is that I did install a preview/nightly for the last bug bash, then rolled back to 1.2.1. Just a shot in the dark.

**bf plugins:list**

`@microsoft/bf-dialog 4.10.0-dev.20200730.3786d10`

**Comment by cwhitten** [comment] 2021-02-11 23:27
This should be fixed with latest version of the bf-cli and merged schema. Closing. Please let us know if this is still not working for you.

**Closed by cwhitten** 2021-02-11 23:27 UTC
Labels: Type: Bug
