### ISSUE TITLE
Unable to add a trigger on a non-English bot imported from PVA

### ISSUE THREAD

**Issue by abharath27** [microsoft/BotFramework-Composer#5728] opened 2021-02-08 23:05 UTC
## Describe the bug

Composer throws an error when I try to add a trigger on the main dialog in an imported PVA French bot. Error message: "lu file PowerVirtualAgentRoot not found"

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.210994.30d3ec2 

## Browser
- [x] Electron distribution

## OS

- [x] Windows

## To Reproduce

1. Create a bot in PVA. Select your language as "French"
2. Go to the Topics page and click "Open In Bot Framework Composer" button
3. Add an "Intent recognized" trigger on the main dialog.

## Screenshots

![error](https://user-images.githubusercontent.com/5294276/107292374-98336400-6a1e-11eb-80c7-b2d83d38b0fb.PNG)

The "PowerVirtualAgentRoot.fr-fr.lu" file is in the language-understanding/fr-fr folder
![image](https://user-images.githubusercontent.com/5294276/107292549-e5afd100-6a1e-11eb-9206-7f3045bb7dd9.png)

**Comment by tonyanziano** [comment] 2021-02-10 19:32
I followed the repro steps and was able to reproduce the issue:

![image](https://user-images.githubusercontent.com/3452012/107561489-71e30500-6b93-11eb-8747-54b5dbab0c99.png)

Logs:

```
2021-02-10T19:29:07.170Z composer Attempting to create project at C:/Users/tonya/Documents/Composer
2021-02-10T19:29:07.187Z composer Creating project from remote template at C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885
2021-02-10T19:29:07.196Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-generation to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-generation
2021-02-10T19:29:07.199Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-generation/fr-fr to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-generation/fr-fr2021-02-10T19:29:07.203Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-generation/fr-fr/common.fr-fr.lg to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-generation/fr-fr/common.fr-fr.lg
2021-02-10T19:29:07.208Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-generation/fr-fr/PowerVirtualAgentRoot.fr-fr.lg to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-generation/fr-fr/PowerVirtualAgentRoot.fr-fr.lg
2021-02-10T19:29:07.213Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-understanding to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-understanding
2021-02-10T19:29:07.218Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-understanding/fr-fr to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-understanding/fr-fr
2021-02-10T19:29:07.223Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/language-understanding/fr-fr/PowerVirtualAgentRoot.fr-fr.lu to C:/Users/tonya/Documents/Composer/toanzian-french-bot/language-understanding/fr-fr/PowerVirtualAgentRoot.fr-fr.lu
2021-02-10T19:29:07.233Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/PowerVirtualAgentRoot.dialog to C:/Users/tonya/Documents/Composer/toanzian-french-bot/PowerVirtualAgentRoot.dialog
2021-02-10T19:29:07.242Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/schemas to C:/Users/tonya/Documents/Composer/toanzian-french-bot/schemas
2021-02-10T19:29:07.249Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/schemas/app.schema to C:/Users/tonya/Documents/Composer/toanzian-french-bot/schemas/app.schema
2021-02-10T19:29:07.269Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/schemas/app.uischema to C:/Users/tonya/Documents/Composer/toanzian-french-bot/schemas/app.uischema
2021-02-10T19:29:07.285Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/settings to C:/Users/tonya/Documents/Composer/toanzian-french-bot/settings
2021-02-10T19:29:07.290Z composer copying C:\Users\tonya\AppData\Roaming\BotFrameworkComposer\temp\extractedTemplate-1612985344885/settings/appsettings.json to C:/Users/tonya/Documents/Composer/toanzian-french-bot/settings/appsettings.json2021-02-10T19:29:07.310Z composer Updating project location data for 47282.65831404099: {
  alias: '839eace6-59ab-4243-97ec-a5b8fcc104e4.8629f5bb-ea98-42c7-b7f0-1d15915ff7df',
  eTag: 'W/"none"'
}
2021-02-10T19:29:07.461Z composer:bot-project Schemas directory found.
2021-02-10T19:29:07.476Z composer:bot-project Customized SDK schema found
2021-02-10T19:29:07.496Z composer:bot-project UI Schema found.
2021-02-10T19:29:07.623Z composer:bot-project Creating file: C:/Users/tonya/Documents/Composer/toanzian-french-bot/toanzian-french-bot.botproj
2021-02-10T19:29:07.763Z composer:bot-project Schemas directory found.
2021-02-10T19:29:07.770Z composer:bot-project Customized SDK schema found
2021-02-10T19:29:07.772Z composer:bot-project UI Schema found.
2021-02-10T19:29:07.774Z composer:bot-project Customized SDK schema found
2021-02-10T19:29:07.776Z composer:bot-project UI Schema found.
2021-02-10T19:29:07.780Z composer Project created successfully.
POST /api/projects 200 620.616 ms - -
GET /api/storages 304 0.887 ms - -
GET /api/storages/default/blobs?path=C%253A%252FUsers%252Ftonya%252FDocuments%252FComposer 200 23.489 ms - -
GET /api/assets/projectTemplates 304 0.494 ms - -
GET /api/storages/default/blobs?path=C%253A%252FUsers%252Ftonya%252FDocuments%252FComposer 304 16.055 ms - -
```

**Comment by tonyanziano** [comment] 2021-02-11 17:56
@boydc2014 @hibrenda can you find an owner for this once you are back from break?

**Comment by tonyanziano** [comment] 2021-02-11 18:53
@abharath27 This appears to be a bug with how the bot folder structure is organized when using a different locale than the default one -- such as French. Composer is expecting the root LU file to be in a different location than it actually is.

We will have someone take a look at this and fix it.

**Comment by amesquitaACD** [comment] 2021-02-16 07:31
Hi,
Still haven't found the solution? I also have this same problem.
Thanks.

**Comment by tonyanziano** [comment] 2021-02-16 17:12
Hi @amesquitaACD ,

Some folks on the team are out for Lunar New Year and will be back on the 18th to look into this issue.

**Comment by tonyanziano** [comment] 2021-02-18 05:08
Here is a .zip of the imported French bot from PVA 

[french-bot.zip](https://github.com/microsoft/BotFramework-Composer/files/6000363/french-bot.zip)

**Comment by boydc2014** [comment] 2021-02-18 08:05
Hey, @tonyanziano, after investigation, the root cause is the settings field "defaultLanguage" after exported is wrong. Given a fr-fr bot (without en-us), the active language can't be en-us.

**Comment by lei9444** [comment] 2021-02-18 08:08
@tonyanziano @boydc2014 the bot setting is 
![image](https://user-images.githubusercontent.com/39758135/108324952-83678500-7203-11eb-8b00-eea94be7334e.png)

**Comment by tonyanziano** [comment] 2021-02-18 18:13
Awesome, thanks for investigating @lei9444  and @boydc2014!

I did some digging, and here is what the `appsettings.json` file looks like during the import process when the .zip has just been downloaded from PVA:

```{
  "publishTargets": [
    {
      "type": "pva-publish-composer",
      "name": "Publish 'toanzian-french-bot' to PVA",
      "configuration": "{\"botId\":\"8629f5bb-ea98-42c7-b7f0-1d15915ff7df\",\"envId\":\"839eace6-59ab-4243-97ec-a5b8fcc104e4\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"baseUrl\":\"https://powerva.microsoft.com/\",\"deleteMissingDependencies\":true}"
    }
  ],
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "luFeatures": {
    "enablePattern": false,
    "enableMLEntities": false,
    "enableListEntities": false,
    "enableCompositeEntities": false,
    "enablePrebuiltEntities": false,
    "enableRegexEntities": false,
    "enablePhraseLists": false
  }
}
```

and here is what it looks like after we've transformed it into a bot project and saved it within Composer:

```
{
  "publishTargets": [
    {
      "type": "pva-publish-composer",
      "name": "Publish 'toanzian-french-bot' to PVA",
      "configuration": "{\"botId\":\"8629f5bb-ea98-42c7-b7f0-1d15915ff7df\",\"envId\":\"839eace6-59ab-4243-97ec-a5b8fcc104e4\",\"tenantId\":\"72f988bf-86f1-41af-91ab-2d7cd011db47\",\"baseUrl\":\"https://powerva.microsoft.com/\",\"deleteMissingDependencies\":true}"
    }
  ],
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "luFeatures": {
    "enablePattern": false,
    "enableMLEntities": false,
    "enableListEntities": false,
    "enableCompositeEntities": false,
    "enablePrebuiltEntities": false,
    "enableRegexEntities": false,
    "enablePhraseLists": false
  },
  "downsampling": {
    "maxImbalanceRatio": -1
  },
  "luis": {
    "endpoint": "",
    "authoringEndpoint": ""
  },
  "skillConfiguration": {
    "isSkill": true,
    "allowedCallers": []
  },
  "customFunctions": [],
  "defaultLanguage": "en-us",
  "languages": [
    "en-us"
  ]
}
```

So it is something that we are doing as a default I am assuming. Maybe the right thing to do would be for PVA to serialize these properties to the settings file on their end?

**Comment by tonyanziano** [comment] 2021-02-19 18:43
A work item has been created to reflect the change in PVA that needs to be made: https://msazure.visualstudio.com/CCI/_workitems/edit/9367333

**Comment by iMicknl** [comment] 2021-03-31 12:35
Is there an ETA for a Power Virtual Agents update that will fix this? (see #6036 and #6385). Will this be part of their 2021 Wave 1 release, or won't it be handled before Wave 2 (October 2021 through March 2022).

This is a bug that really blocks the adoption of Composer in customer projects.

**Comment by tonyanziano** [comment] 2021-03-31 16:25
Hello @iMicknl ,

The work item I linked above has been marked as "Closed," and I believe we are just waiting for the change to propagate into their deployment. If I remember correctly, it will be deployed in the next week or two, but I can double check with someone from the PVA team if needed.

That being said, as soon as the change is live in PVA, we expect to have a nightly Composer build shortly afterwards that contains the fix.

I'll keep this thread updated.

**Comment by iMicknl** [comment] 2021-03-31 20:44
Thank you, @tonyanziano. I wasn't able to access the work item. Great to hear that this is planned for short term!

**Comment by tonyanziano** [comment] 2021-04-12 17:16
Update: According to the PVA team, this **should hit their production environment at the end of April**. It is currently deployed in their PPE environment.

**Comment by cwhitten** [comment] 2021-04-14 23:51
Closing in lieu of https://github.com/microsoft/BotFramework-Composer/issues/5728#issuecomment-817983907

**Closed by cwhitten** 2021-04-14 23:51 UTC
Labels: Area: PVA, Bot Services, Type: Bug, customer-replied-to, customer-reported

**Comment by iMicknl** [comment] 2021-04-15 09:05
@cwhitten doesn't this PVA update require a change (+ new build) of Composer? This was mentioned before, thus in that case it would be great to keep this open so that it could be tracked.

**Comment by iMicknl** [comment] 2021-05-02 18:40
@tonyanziano, @cwhitten any updates? This hasn't been fixed yet in last nightly builds.

**Comment by cwhitten** [comment] 2021-05-03 21:45
Hi @iMicknl. We don't expect there to be a needed change in Composer. Once PVA addresses this issue and releases the fix, it should just work. I am reaching out to the PVA team to confirm this.
