### ISSUE TITLE
Transcripts not stored from bot in Azure

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#8829] opened 2021-12-03 17:51 UTC
I created a bot in Composer and implemented Blob transcript storage. Transcript storage works when I run the bot locally using the emulator. 

Once I publish the bot to azure, no transcripts are saved from either a webchat session or emulator session. I don't see any azure errors. 

These symptoms appears to be the same as [closed issue 6206](https://github.com/microsoft/BotFramework-Composer/issues/6206). 

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Channels
- [x] Webchat
- [x] Emulator
- [x] Teams

## To Reproduce

1.  Enable transcript storage in bot settings
`    "features": {
      "showTyping": true,
      "useInspection": false,
      "removeRecipientMentions": false,
      "blobTranscript": {
        "connectionString": "<Connection String>",
        "containerName": "transcripts"
      }
`
2. Run bot locally
3. Chat with bot locally using emulator
4. Use Azure storage explorer to inspect transcripts container in storage account. New transcripts appear with each new conversation.
5. Publish the bot successfully to azure
6. Connect using channel of choice (emulator or webchat in this case)
7. Use Azure storage explorer to inspect storage account. No new transcripts.

## Expected behavior

Expected the Azure bot to store transcripts in the same manner as the bot running locally. 

## Azure
- Azure Bot, location global
- Storage account, WestUS

**Comment by benbrown** [comment] 2021-12-06 17:49
@dinobrago is the blob storage provider also configured in your publishing profile?  During publishing, the settings are updated to reflect the remote environment.

Can you check whether the settings on your remote app service contain the expected values?

**Comment by dinobrago** [comment] 2021-12-06 18:02
Yes, the storage account settings also appear in the publishing profile. The connection string and container name in the publish settings>blobStorage match the settings in runtimeSettings>features>blobTranscript

```
    "blobStorage": {
      "connectionString": "<Connection String>>",
      "container": "transcripts",
      "name": "jurybot308"
    }
```

**Comment by benbrown** [comment] 2021-12-06 18:08
Thanks for confirming, @dinobrago. We will investigate further.

**Comment by anishprasad01** [comment] 2021-12-08 00:17
Hi @dinobrago,

I just attempted to reproduce your issue, and was able to successfully store transcripts in an Azure Blob. Here are the exact steps I followed:

- In Azure, create a new resource group (I put everything in West US)
- Create a new storage account
- Create a container
- Create a simple Echo bot in Composer (I used C#)
- In the Advanced Settings View (json) window in Composer, go to `runtimeSettings -> features` and add `"blobTranscript": { "connectionString": "<NEW_STORAGE_ACCT_CONN_STRING>", "containerName": "<NEW_CONTAINER_NAME>" }`, filling in the required information for your new blob container
- Test the bot in Emulator and verify that transcripts are stored
- Create a new publishing profile with *only the required resources*. Do not create a new blob storage resource
- Publish the bot to the same resource group as the storage account
- Test the bot in Web Chat
- Use the Azure Portal or Storage Explorer to find within your Blob Container a folder labeled `webchat` (emulator conversations would similarly be saved in a folder called `emulator`), within which will be a folder labeled with the generated conversation ID. Within that folder will be the transcript JSON files.

As you can see from the below images (I've removed any IDs), I have logs from this test in my Azure Blob.

![image](https://user-images.githubusercontent.com/33945547/145125257-7e2ea5a0-9a4a-4b98-9c15-a23f35ac0b57.png)

![image](https://user-images.githubusercontent.com/33945547/145125093-5fea7e86-fe67-4d82-a5c6-b6a8a5e7f340.png)

![image](https://user-images.githubusercontent.com/33945547/145125198-a852d80f-0c41-49c2-9536-bd39204c87ec.png)


Could you double check and verify that nothing got overridden when you published your bot, and that you also placed the `blobTranscript` in the correct spot in the settings JSON?

**Comment by dinobrago** [comment] 2021-12-08 00:29
I will test this as soon as I can. But reading your steps, I do see a big difference. My bot was created and originally published without transcripts. After some time, I subsequently added transcripts which is when I reported the issue. So the process was different than perhaps I originally described in the bug report.

Dean

**Comment by dinobrago** [comment] 2021-12-08 06:23
Following your steps, I was able to create an echo bot that stores transcripts in the storage account both locally and after publishing to Azure.

**Comment by dinobrago** [comment] 2021-12-08 06:45
I found the issue and my bot in Azure is now storing transcripts.

The connection string in the publish profile only contained the key not the actual connection string.

I presume that Composer updated the publish profile when I added the information in the feature. I did not manually update the publish profile.

After walking through your steps below, I went back to my original bot and created a new storage account, basically following the steps below. I got this working locally but then manually edited the Publish Profile. That’s when I noticed that the Publish Profile for the storage account was incorrect.

The publish profile calls for the same info (essentially) as the feature but the connection string was only the key, not the actual connection string.

I’ll have to do some work to see if I can reproduce this. I don’t think it was human error on my part because I did not change the publish profile after I added the transcript to the runtimeSettings > features.

Alternatively, there should be some documentation to indicate that the publish profile has to manually edited to include the new storage account when the transcript feature is added later.

I’ll see if I can reproduce the problem.

Dean

**Comment by anishprasad01** [comment] 2021-12-08 15:32
I will also try to add transcripts to an existing bot using the UI and see if I get the same results.

**Comment by anishprasad01** [comment] 2021-12-10 22:32
I was successfully able to add transcripts to a bot with blob storage created by the Composer publish tool. However, I had to manually supply the connection string and container name.

**Comment by anishprasad01** [comment] 2021-12-14 22:44
@dinobrago 

Did you have the chance to test?

**Comment by dinobrago** [comment] 2021-12-15 01:14
I reproduced the problem with a simple Echo Bot. 
1. Create an empty bot in composer.
2. Add a new trigger for Message Received. 
3. Echo back You said: ${turn.activity.text}
4. Test the bot locally using the emulator.
5. Set the Language Understanding to "Regular Expression"
6. Set up a publish profile to Azure
In the publish profile, create a new resource group, use only the minimal components but include blob storage. 
7. Publish the bot. Test that it is working. No transcripts are stored.
8. In the storage account, add a blob container, public access
9. Get the connection string.
10. In composer, open the settings and add to runtimeSettings
```
      "blobTranscript": {
        "connectionString": "DefaultEndpointsProtocol=https;AccountName=bottesttranscript;AccountKey=hfya---Q==;EndpointSuffix=core.windows.net",
        "containerName": "transcripts"
      }
```

I don't know exactly when Composer updates the publishTargets but the new feature is added to the publishTargets incorrectly. When I inspect the publish target I see that the blob storage is defined as follows:
```
\"blobStorage\": {\n      \"name\": \"bottesttranscript\",\n      \"connectionString\": \"hfya---Q==\",\n      \"container\": \"transcripts\"\n    },
```

It puts in the correct key but it should be putting in the complete connection string. So this bot in Azure does NOT store transcripts until I manually edit the publish target to use the complete connection string which resolves the problem.

**Comment by anishprasad01** [comment] 2021-12-16 15:57
Interesting. When I test publishing, the `publishTargets` are never updated by Composer. In fact, the blob connection details are never added there at all.

**Comment by dmvtech** [comment] 2021-12-16 18:21
@benbrown @tdurnford 

Any ideas here? We are unable to reproduce the issue (as per Anish above, for us; publishTargets never gets modified to include the blob storage connection details). Do we know if the above behavior (replacing full connection string with just the key) is by design? Could it have to do with the parsing of the connection string (some special character in the string cause it to truncate)?

**Comment by dinobrago** [comment] 2021-12-16 18:59
If publishTargets never gets modified based on the runtime settings, I assume that the storage key was added when I first provisioned the bot. I haven't checked this yet but it should be easy to do.

**Comment by dinobrago** [comment] 2021-12-16 20:14
Yes, I've verified that when Composer creates the publish profile and provisions Blob Storage, it puts the blob storage key in the ConnectionString publish setting rather than the actual connection string.

You are correct that it does not update the publish settings. It just happened that I was using the same blob storage so the key was already in the publish settings. 

I don't see anything in the documentation of the transcripts that says you also need to update the settings in the Publish Profile to add transcripts to a bot in Azure, only that you need up update the runtimeSettings. So maybe it's partly a documentation issue but it seems that it also is a bug in the Composer doesn't insert the correct Connection String into the publish profile when it first provisions the blob storage in Azure.

**Comment by anishprasad01** [comment] 2021-12-21 19:11
I'd like to run this issue by some folks, but due to the holiday, people are in and out of the office. I'll try to have something for you as soon as I can.

In the meantime, have you tried uninstalling and reinstalling Composer? I know it sounds cliche, but sometimes it does fix issues.

**Comment by dinobrago** [comment] 2021-12-21 20:06
I have not tried uninstalling and probably won’t go through the process. Now I know what the issue is, the work around is easy.

Dean

**Comment by anishprasad01** [comment] 2021-12-22 23:43
That's interesting, since I do not even have a `publishSettings` where the connectionString gets added. 

As we have a workaround, I am going to close this issue, but I will still run it by some folks to see if we can clarify this or isolate this behavior.

**Closed by anishprasad01** 2021-12-22 23:43 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
