### ISSUE TITLE
Composer & Azure Devops 

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3170] opened 2020-05-23 09:37 UTC
I am currently investigating on the best setup for using Composer in combination with Azure Devops. We are looking for a solution whereby;

1) Bot is pushed to Devops repo
2) Pipeline is triggered
    - Build, Test & Publish
    - Incremental Arm templates for DEV, ACC & PROD
    - Push Webapp & Update Luis models for DEV automatically, with approval steps for ACC & PROD

I was wondering if this is something that is planned for Composer to be integrated into the publish menu with the ARM scripts and pipeline.yml files? Or is it worth developing it ourselves for now (with the danger it is incompatible with what is delivered by Composer in the future)?

**Comment by hibrenda** [comment] 2020-05-26 12:20
@cwhitten @benbrown be aware of this feature requirement.

**Comment by benbrown** [comment] 2020-05-26 17:04
@cxbuilders - I would approach this as a plugin project. You can create a new method for takign a bot and pushing it to a destination - that destination can be pipelines.  This would allow you to write your pipeline.yml files or other necessary components as it passes out of Composer and into the environment.

We aren't planning on building Azure Devops publish immediately. It would be great to have this as a contributed module!

There are docs for the plugin API here:
https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/plugins/README.md

**Comment by cxbuilders** [comment] 2020-05-26 18:26
@benbrown I am currently setting up a manual method, whereby I move the required dialog etc files in the right location using the pipeline. I am working for a customer that has just choosen MS as their new framework for bots, so I need to check if they're open to this. When they are would it be possible to have a call on this so I am sure the route we're taking is the beat one?

**Comment by benbrown** [comment] 2020-05-26 18:44
sure.

**Comment by cwhitten** [comment] 2020-06-16 16:43
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3170

**Closed by cwhitten** 2020-06-16 16:43 UTC
Labels: Needs-triage

**Comment by cxbuilders** [comment] 2020-06-22 06:34
@benbrown I have tried to contact you last week via the email provided on https://github.com/benbrown. Can you let me know if you have time to discuss the best way on setting this up globally?

**Comment by benbrown** [comment] 2020-06-22 15:36
@cxbuilders - hrrm! try benbro@microsoft.com

**Comment by cxbuilders** [comment] 2020-06-22 17:30
@benbrown sent you a mail. In case it did not arrive, please send me an email to bastiaan cxbuilders.com

**Comment by cxbuilders** [comment] 2020-06-30 08:44
@benbrown Any update on this? If there is no time, please let me know, then I don't need to keep track of this anymore.

**Comment by benbrown** [comment] 2020-06-30 15:51
@cxbuilders sorry I never got back to your email. inboxes! :/

One of my peers here on the team just sent me a draft of the devops build pipeline.  I am hoping to include a version of it in the next release.
