### ISSUE TITLE
Build failed  : Command failed: dotnet build  projectname.csproj

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7143] opened 2021-04-20 09:27 UTC
## Describe the bug

Not able to build the bot in the composer 

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.	Open the Bot project (ex: Trigger) 
2.	Update new Bot composer version (Enable auto-restart option)
3.	Open the Bot project (ex: Trigger) 

Build the project …. The build has failed due to (Ref screenshots) reason 

Just noticed while closing the Bot composer  (ex: Trigger.exe is running in the background) …. 

And one more observation only one time I faced the same problem working with Visual Studio (custom action project) If I stop the bot using the “Local bot runtime manager” its stopped but the application is running in the background . 

## Expected behavior

Background process should be closed 

Note : After killed background exe ... Build is working fine. 👍

## Screenshots

![error1](https://user-images.githubusercontent.com/16264167/115372037-cc6b9380-a1ca-11eb-8afa-fffbb561d3eb.png)

## Additional context

May be the same problem in  #7054

**Comment by pavolum** [comment] 2021-04-20 16:46
Seems to be a duplicate of #7054 but will keep open until we validate that assumption

**Comment by pavolum** [comment] 2021-04-28 17:43
This is a duplicate and the original issue has been resolved

**Closed by pavolum** 2021-04-28 17:43 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported
