### ISSUE TITLE
with 2.1 the Value  field of a Trace Activity is throwing warnings where it did not previously

### ISSUE THREAD

**Issue by Uggi** [microsoft/BotFramework-Composer#8472] opened 2021-07-26 17:33 UTC
## Describe the bug

Pre 2.1, I could have the Value field of a trace activity, with a value type of string, without quotes and just call properties as needed. no warning was raised. 
`turn.activity.listOfScores = ${turn.activity.listOfScores}`
`turn.activity.value = ${turn.activity.value} and turn.activity = ${turn.activity}`

No single quotes were necessary as they were always implied. 
I now have hundreds of warnings for trace events properties where there wasnt a problem before.  

## Version

Version 2.1

## Browser

![image](https://user-images.githubusercontent.com/4349731/127031845-0b07a1ec-daca-4165-9497-218f26f7f351.png)

## OS

- [ ] Windows

## To Reproduce

Create a Trace Event  with a value type of string and enter 
a string with escaped properties. 
see screen shots for examples.
warning is received. 

## Expected behavior

the value fields with value type of string should not need quotes since its defined as a value type of string. 

## Screenshots

**Screenshot 1**
![image](https://user-images.githubusercontent.com/4349731/127031356-065c0bf8-a1fe-4e1a-8fe7-eedced4ec75d.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/4349731/127031644-9ebaec92-f769-4210-856e-2009b48fb3eb.png)

**Comment by tonyanziano** [comment] 2021-07-27 17:19
@stevkan can you please try and reproduce this?

**Comment by stevkan** [comment] 2021-07-28 19:43
@tonyanziano, I was able to repro the issue once. But, unable to repro any, again. I don't remember what steps I took to get the error to show in the UI, but everything I tried, including trying to retrace my steps (no pun intended), failed to repro after the first occurrence.

However, a warning is shown in the 'Problems' output that does capture the same message that was displayed in the error (see below).

It also doesn't appear to be a blocking issue. While the warning / error is displayed, it isn't keeping the bot from outputting the trace. @Uggi, is this your experience, as well?

![image](https://user-images.githubusercontent.com/18403946/127385150-75ba5715-b7d1-4d70-8763-db10f13b8090.png)

**Comment by rR6kULhc5xgS** [comment] 2021-07-29 13:10
@stevkan I'm experiencing the same issue where I have an error underneath the input box, but it's just a warning in the "Problems" tab. Everything still builds fine, but these warnings/errors weren't there prior to Composer 2.1. Adding quotes removes the error.

![image](https://user-images.githubusercontent.com/88147020/127497409-c003a7e3-ac42-4c3c-b812-86d5e9b1e751.png)

![image](https://user-images.githubusercontent.com/88147020/127497481-49f24f32-6d43-4e0a-a398-70ecb85d0ff7.png)

Thankfully I only have a handful of these warnings, but I am wondering if the guidance going forward is that quotes should be around those values, or if this is a false positive in Composer that will be fixed in a later version.

Thanks

**Comment by benbrown** [comment] 2021-08-02 18:16
@tonyanziano any insights into this? Weird intermittent behavior!

**Comment by Uggi** [comment] 2021-08-03 11:58
> @tonyanziano, I was able to repro the issue once. But, unable to repro any, again. I don't remember what steps I took to get the error to show in the UI, but everything I tried, including trying to retrace my steps (no pun intended), failed to repro after the first occurrence.
> 
> However, a warning is shown in the 'Problems' output that does capture the same message that was displayed in the error (see below).
> 
> It also doesn't appear to be a blocking issue. While the warning / error is displayed, it isn't keeping the bot from outputting the trace. @Uggi, is this your experience, as well?
> 
> ![image](https://user-images.githubusercontent.com/18403946/127385150-75ba5715-b7d1-4d70-8763-db10f13b8090.png)

Agreed @stevkan. It doesnt break when it builds. That said, currently this occurs for me for any existing or new Trace Event I add. If I wrap it in quotes, the warning disappears but the eventual generated value of "hi ${user.profile.name}" is ""hi neil"" with double quotes.  image of property in emulator: 

![image](https://user-images.githubusercontent.com/4349731/128010518-1f978442-5a79-45a9-92cb-7dd3802badcb.png)

below is the JSON for the trace activity in the code window with and without the extra quotes.
![image](https://user-images.githubusercontent.com/4349731/128011223-e7bd7f27-474d-43b0-a737-0672a7520334.png)

**Comment by tonyanziano** [comment] 2021-08-03 20:51
That is very strange behavior, and I do not think that it is intended for users to have to wrap strings in a pair quotation marks.

I will look into this and see if I can reproduce it and maybe find out what is causing it.

**Comment by tonyanziano** [comment] 2021-08-04 17:34
I can reproduce this in both the nightlies, and in the `main` branch. I only see a warning though and no errors in the "Problems" tab.

From my testing, it appears to think the string is invalid when there is a space in the string or an expression symbol such as an equals sign:

![image](https://user-images.githubusercontent.com/3452012/128227506-0c986a58-57fe-45fe-8347-f49897256cc6.png)

![image](https://user-images.githubusercontent.com/3452012/128227535-bcb2415b-6b99-4f19-afc2-e12986dd9f37.png)
> In Testing.triggers[0].actions[5]: Microsoft.ThrowException: errorValue must be an expression: syntax error at line 1:5 extraneous input 'test' expecting <EOF> 

![image](https://user-images.githubusercontent.com/3452012/128227562-c92f52d9-47bd-4142-86c2-7149cf7be65d.png)
>In Testing.triggers[0].actions[5]: Microsoft.ThrowException: errorValue must be an expression: syntax error at line 1:4 mismatched input '=' expecting {<EOF>, '+', '-', '!', '^', '*', '/', '%', '==', NOT_EQUAL, '&', '&&', '||', '<', '>', '<=', '>=', '(', '.', '[', '??', '?'}

**Comment by tonyanziano** [comment] 2021-08-04 17:47
@GeoffCoxMSFT this appears to be an issue with validation in the LG server - could you assign someone to investigate?

**Comment by srinaath** [comment] 2021-08-16 20:03
@boydc2014 Is there someone on your team to investigate this ticket?

**Closed** 2021-09-10 18:10 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Area: LG, Support
