### ISSUE TITLE
Webchat toolbar buttons (and any other toolbar buttons that only have an icon and no label) need tooltip to show label

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7079] opened 2021-04-18 19:20 UTC
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by mewa1024** [comment] 2021-04-20 05:00
@mareekuh is this a dupe of #7080?

**Closed** 2021-04-20 23:11 UTC
Labels: Needs-triage, Type: Bug
