### ISSUE TITLE
[MCS-DE-GO] Ability to rename Dialogs

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5366] opened 2020-12-17 11:03 UTC
It should be possible to rename Dialogs. Change should be reflected in related filenames as well.

@joaollq @goergenj @garypretty

**Comment by cwhitten** [comment] 2021-02-11 23:43
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/1741

**Closed by cwhitten** 2021-02-11 23:43 UTC
Labels: UX Design, feature-request
