### ISSUE TITLE
The composer is saying "This project was created in an older version of Composer. To open this project in Composer 2.0, we must copy your project and convert it to the latest format. Your original project will not be changed."

### ISSUE THREAD

**Issue by RohanNayaks** [microsoft/BotFramework-Composer#8895] opened 2022-01-13 11:14 UTC
I created a project in v2.1.1 and was trying to open from the folder . but i was seeing this error. Not able to solve it , Please help.

I have pasted the screenshot of the error.

![image](https://user-images.githubusercontent.com/52638040/149320324-fcdfe363-65ff-4e13-9145-47ea1b593c0f.png)

**Comment by anishprasad01** [comment] 2022-01-14 15:52
Hi @RohanNayaks,

Could you click that convert button and let me know what happens?

Could you also tell me a bit more about your system configuration?

**Comment by Bolleman** [comment] 2022-01-15 23:32
I just had the same error, but not sure if what caused it was the same.  In my case it was caused by the fact that the project did not contain an settings/appsettings.json.  This was because the settings were in gitignore and therefore not in the repo I cloned.  Everything worked fine after adding a settings/appsettings.json back into the project folder before opening it in Composer,

**Comment by anishprasad01** [comment] 2022-01-17 16:09
@Bolleman Interesting, thank you.

@RohanNayaks Do you have that file in your project folder? Do you get this error if you create a new project in composer, close it, and reopen it?

**Comment by anishprasad01** [comment] 2022-01-21 19:39
Closing this issue due to inactivity. If you still require assistance, please comment and we can reopen the issue.

**Comment by dawwa** [comment] 2022-01-22 06:33
@anishprasad01, would you please reactivate this issue? this seems a bug as the composer should not complain this for settings/appsettings.json is missing, in our case, for consistency reason, we need to have the appsettings.json under the project root folder instead of the settings folder, and it's a valid option for the [AddBotRuntimeConfiguration](https://github.com/microsoft/botbuilder-dotnet/blob/3775c0aa5ca00966eacf38a854bb058b09d611a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ConfigurationBuilderExtensions.cs#L36) used by composer.

**Comment by anishprasad01** [comment] 2022-01-24 18:47
Hi @dawwa,

What I can tell you right off the bat is that at this time, Composer's [Bot Structure Template](https://github.com/microsoft/BotFramework-Composer/blob/06e1b66d9bd31ad086505fc15cbed15253f6a6bd/Composer/packages/server/src/models/bot/botStructure.ts#L19) requires that files be in certain place in order for Composer to work correctly. Composer will create files in those spots if they're missing to maintain consistency with the defined template.

I'm investigating to see if there's perhaps a way that this behavior can be modified, but there is no way to do so out of the box.

**Comment by anishprasad01** [comment] 2022-01-27 01:09
@dawwa, 

I've looked into it, and it looks like Composer operates this way in order to ensure that when bots are authored and deployed, the required files are present where Composer expects them to be. This is why it will ask and/or create a new file in the `settings` folder if you move it.

We'll take this issue as a feature request and add it to the backlog for prioritization. We do not have an ETA at this time for when this feature will be available.

As there is no workaround at this time, I'm going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-01-27 01:09 UTC
Labels: Type: Bug, customer-reported, Bot Services, Needs-triage
