### ISSUE TITLE
Can't create new publishing profiles

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7261] opened 2021-04-22 18:20 UTC
## Describe the bug
The final page of the publishing profiles does not provide the summary, and the `done` button doesn't work

## Version

Version:  1.4.0-nightly.238024.b6ea776
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new empty bot template bot
2. Go to the `publish` tab
3. create a new publishing profile

## Expected behavior
When you get to the end there should be a summary of the resources, and the `Done` button should work.

## Screenshots

![image](https://user-images.githubusercontent.com/50158775/115766264-a249db00-a35c-11eb-9e11-c1b172e60532.png)

**Comment by benbrown** [comment] 2021-04-22 18:29
Caused by #7250 should be resolved in the next build

**Closed** 2021-04-22 20:53 UTC
Labels: Needs-triage, P0, Type: Bug
