### ISSUE TITLE
e2e testing: Using Get LUIS or Get QnA Key option does not work in Composer

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Composer#6963] opened 2021-04-14 20:43 UTC
## Version
![image](https://user-images.githubusercontent.com/29185255/114775618-57114600-9d26-11eb-9627-880fd89b176d.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an Enterprise bot in Composer
2. Click on 'Project Settings' in left nav to go to the following page

![image](https://user-images.githubusercontent.com/29185255/114776072-e7e82180-9d26-11eb-8ea3-40ca4a171e98.png)

3. Click on 'Get LUIS keys', the dialog box is greyed out, see below:
![image](https://user-images.githubusercontent.com/29185255/114776196-0f3eee80-9d27-11eb-8d56-4f826e239097.png)

Note: QnA keys also show a dialog that has the subscription greyed out.

## Expected behavior
I should be able to select the subscription and proceed.

**Comment by srinaath** [comment] 2021-04-15 17:02
@pavolum Can you verify this fix?

**Comment by Dewain27** [comment] 2021-04-19 20:34
This seems associated to the non-corporate logon.  We need to test it that way, it seems to not be an issue with Enterprise logons.

**Comment by pavolum** [comment] 2021-04-26 17:16
I am able to repro a bug with a non organizational account but now get blocked at this modal
![image](https://user-images.githubusercontent.com/22845013/116123967-a98d2380-a691-11eb-9497-81e90a599389.png)

**Comment by cwhitten** [comment] 2021-04-27 15:52
History:

https://github.com/microsoft/BotFramework-Composer/issues/5706

https://github.com/microsoft/BotFramework-Composer/pull/6112

**Comment by cwhitten** [comment] 2021-04-27 15:52
@a-b-r-o-w-n can you work with Patrick on understanding the delta with this dialog?

**Comment by benbrown** [comment] 2021-04-27 17:42
Based on #6112 this seems reasonable. 

The key thing I need @a-b-r-o-w-n  to way in on is whether a tenant *SELECTION* is required here...

**Comment by a-b-r-o-w-n** [comment] 2021-04-28 00:38
I did some digging on this today and unfortunately didn't make much progress. I am able to sign in with an MSA account during provisioning so I suspect that tenant selection / arm token will be required. I plan on testing this 1st thing in the morning with a signed build.

**Comment by a-b-r-o-w-n** [comment] 2021-04-28 20:30
I have identified the root cause. We need to get an ARM token in order to work with MSA accounts. We will need to port the tenant selection UX from `azureProvisionDialog.tsx` to `ManageService.tsx` as well as `ABSChannels.tsx`. I have also written a guide to help the engineering effort.

## Getting an ARM token process

ARM tokens are required for managing Azure resources with MSA accounts (personal accounts). Here is the process to get an ARM token for a user.

1. Invoke the `getTenants()` api. This initiates a login flow which returns a token that is valid to request the list of tenants (aka  directories) that a user belongs to.
2. Once the tenants are fetched, show some UI so that the user can select which tenant they want to modify resources in.
3. Once the user selects a tenant, use the `getArmTokenForTenant(tenantId)` api to fetch a token that is valid for interacting with Azure resources.

Use the code in `azureProvisionDialog.tsx` as a guide — pay attention to error handling at each step and handle the errors based on your specific scenario.

fetching tenants example - https://github.com/microsoft/BotFramework-Composer/blob/main/extensions/azurePublish/src/components/azureProvisionDialog.tsx#L443
fetching an arm token example - https://github.com/microsoft/BotFramework-Composer/blob/main/extensions/azurePublish/src/components/azureProvisionDialog.tsx#L485

**Comment by cwhitten** [comment] 2021-04-28 22:00
@VamsiModem will need a design peer on this. @emivers8 would this be you?

**Comment by benbrown** [comment] 2021-04-30 17:10
Just to re-iterate what @a-b-r-o-w-n said, this problem also exists on the 'connections' section of the settings page, and would hopefully also be addressed by this solution.

**Comment by sgellock** [comment] 2021-05-03 15:45
Shiproom - we need to get this in by Tuesday please.

**Closed** 2021-05-03 22:49 UTC
Labels: Area: Publish, P0, ShipRoom-Approved, Type: Bug
