### ISSUE TITLE
Two C# options exist when ejecting runtime

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#5828] opened 2021-02-18 18:15 UTC
## Describe the bug

Two C# options exist when ejecting the runtime.

## Version

1.3.1-nightly.214892.a16c00c

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to settings page and toggle "Use custom runtime"
2. Click on "Get a new copy of the runtime code"
3. Notice 2 options for C#

## Expected behavior

A single option for C# (or a distinction between the two options).

## Screenshots

![image](https://user-images.githubusercontent.com/3619060/108402108-f526db00-71d1-11eb-9a65-2eff96bbef30.png)

**Comment by cwhitten** [comment] 2021-02-23 17:36
@pavolum @VanyLaw we believe this may have been introduced by the recent creation & config changes to get into the tree last week. We should only have one C# option when ejecting. cc @luhan2017

**Comment by cwhitten** [comment] 2021-02-23 17:39
Closing as a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/5836

**Closed by cwhitten** 2021-02-23 17:39 UTC
Labels: Team: Runtime & Publishing, Type: Bug
