### ISSUE TITLE
How to handle "OnTurnError" ( unhandled error ) in bot framework composer ?

### ISSUE THREAD

**Issue by Elsa2604** [microsoft/BotFramework-Composer#9255] opened 2022-06-23 11:21 UTC
After the deployment of the bot using bot framework composer, The first response is coming as 
**The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process.**

![image](https://user-images.githubusercontent.com/104147442/175286037-25ce2e51-26f6-4e8d-9821-2c9ca9b8959f.png)
Also, I have configured the API's used in http request in bot's app service( getting dynamically, not hardcoding) 
![image](https://user-images.githubusercontent.com/104147442/175288332-2ef900e4-495a-4885-85f0-d30e7470dc4d.png)
![image](https://user-images.githubusercontent.com/104147442/175288409-8d231454-7852-4b3f-aa2d-5726eb49a8f9.png)

after this implementation..I'm getting the response as 
**Invalid URI: The hostname could not be parsed.** after the response **The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process.**

![image](https://user-images.githubusercontent.com/104147442/175286955-6a917aa7-5ca2-4e3d-af39-eee17c24eedf.png)

The thing is after refreshing, the error response is not displaying and bot flow is working fine.

**Comment by anishprasad01** [comment] 2022-06-24 17:58
Hi @Elsa2604,

Let's deal with the invalid URI first. What URI are you attempting to reach?

**Comment by Elsa2604** [comment] 2022-06-24 18:04
@anishprasad01 Yes, the api I mentioned here is a example..when I try the actual api  outside the bot I'm able to access it (postman)

**Comment by anishprasad01** [comment] 2022-06-24 18:14
Rather than using `${converstion.testapi}`, if you just supply the complete URL to the HTTP request action, does it work? I want to eliminate the HTTP action itself as the potential issue.

**Comment by Elsa2604** [comment] 2022-06-24 18:17
Yes, it works with the actual url in the https request and it doest throw that uri error message

**Comment by anishprasad01** [comment] 2022-06-24 18:23
Then you may need to try debugging the bot in Visual Studio or another tool of your choice and check the URI format is coming through correctly when you use a field. It seems like it is not.

**Comment by Elsa2604** [comment] 2022-06-24 18:25
So this format of configuration shd not be followed?

**Comment by anishprasad01** [comment] 2022-06-24 18:28
I'm not 100% sure if this format is supported or not, though it's not mentioned in the documentation. That said, it might still be possible, but we still need to know what your bot is doing, and for that you must debug it.

**Comment by Elsa2604** [comment] 2022-06-24 18:30
How to debug the bot composer in visual studio ? I haven't done it before

**Comment by anishprasad01** [comment] 2022-06-24 18:33
If you are using a C# bot, you can open the solution file as you would any other C# project. You can then run the project like any other C# project. You can then use the Bot Framework Emulator to connect to the bot and test it. Hopefully you will be able to isolate what the format is. 

You might also just try printing the URI in Composer as a response.

**Comment by Elsa2604** [comment] 2022-06-24 18:35
@anishprasad01 thanks.. will look into this

**Comment by Elsa2604** [comment] 2022-06-26 04:00
@anishprasad01 Earlier I use to get these responses but after refreshing, the bot works fine but for the last two days I'm getting 
<filename>.en-us.lg:[Error] C:\home\site\wwwroot\language-generation\en-us\<filename>.en-us.lg line 1:0 - line 1:21: The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process. 

![image](https://user-images.githubusercontent.com/104147442/175798776-c1ecd0c3-2c07-40bc-9168-102fb65e9aae.png)

As I am facing this issue in production, can you pls help me on this ?

**Comment by anishprasad01** [comment] 2022-06-27 15:59
I just realized something as I was looking into this. The issue is probably the [memory scope](https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x#properties-and-memory-scopes) you're using. The URI stored in the application settings of your app service will not be accessible from the `conversation` scope, but rather the `settings` scope. 

In Composer, try setting the URI to `settings.api_name` with api_name being exactly what you named the setting in the app settings. based on the screenshots you supplied it would be something like `settings.Sample:Testapi`. I'd suggest changing that to something without a colon.

**Comment by Elsa2604** [comment] 2022-06-27 17:14
> What does refreshing mean? You refreshed the client, or you restarted the bot's App Service? As I understand it, after you refreshed it, the bot works correctly for some time before it fails again?

Earlier, when I refresh the browser page , and after opening the bot.. the error goes **The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process.**
But  for the response " **{filename}.en-us.lg:[Error] C:\home\site\wwwroot\language-generation\en-us{filename}.en-us.lg line 1:0 - line 1:21: The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process.** " , after restarting the app service only, the bot is responding

**Comment by Elsa2604** [comment] 2022-06-27 17:15
> I just realized something as I was looking into this. The issue is probably the [memory scope](https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x#properties-and-memory-scopes) you're using. The URI stored in the application settings of your app service will not be accessible from the `conversation` scope, but rather the `settings` scope.
> 
> In Composer, try setting the URI to `settings.api_name` with api_name being exactly what you named the setting in the app settings. based on the screenshots you supplied it would be something like `settings.Sample:Testapi`. I'd suggest changing that to something without a colon.

![image](https://user-images.githubusercontent.com/104147442/175997896-f4121afa-6a13-471f-9d12-45ed73e005cc.png)
You mean to try in this way, as we do for accessing QNA ?

**Comment by anishprasad01** [comment] 2022-06-27 17:20
Correct. I tested it by adding a URI (I just used Postman Echo in this case) to my app service's app settings with the name `testapi`. I then sent a GET request in Composer to `${settings.testapi}` and got back the `200 OK` response from the endpoint.

**Comment by Elsa2604** [comment] 2022-06-28 07:10
@anishprasad01 , This works for direct API, what about if passing dynamic  value to that API ?

1. In app service's app setting, I have **https://fruit=fruitname&color=fruitcolor**

2. In Composer, I store this API to a variable : conversation.fruitAPI : =settings.fruitAPI

3. And before passing it to the HTTP request, I replace the fruitname and fruitcolor with the dynamic value 
**conversation.fruitname : ='mango'** , **conversation.fruitcolor: ='yellow'**
https://fruit=**fruitname**&color=**fruitcolor**

4. and store that in a variable conversation.fruit : =replace((replace(conversation.fruitAPI,"fruitname",conversation.fruitname)),"fruitcolor",conversation,fruitcolor) 

5.After replace the conversation.fruit wil looks like **https://fruit=mango&color=yellow**
6. and this variable is passed in HTTP request as ${conversation.fruit}

**Comment by Elsa2604** [comment] 2022-06-28 16:22
It is working, but the issue is after deployment.. for the first time when I load the bot, I'm getting the error response mentioned above **Invalid URI: The hostname could not be parsed**. After refreshing the browser page, It is loading perfectly.

**Comment by Elsa2604** [comment] 2022-06-28 17:39
> A couple more clarifying questions, for my own understanding:
> 
> * Is the fruit example a real example from your application?  **It's an example from my application** 

> * Is the channel Web Chat? If not, what is it? **Directline channel**

> * What is an example of a URI you are actually trying to generate?  **That I can't share as it confidentials**


If this is causing an error, is this not the format to use?

**Comment by Elsa2604** [comment] 2022-06-28 17:56
Apologise,  example url : https://mybot.com/api/name=username

In composer, I pass the dynamic value (conversation. Username : ='john') in the url 
Which looks like 

https://mybot.com/api/name=${conversation. Username}

https://mybot.com/api/name=john

**Comment by anishprasad01** [comment] 2022-06-29 00:07
To do that in Composer, you'll want to make use of the `Headers` option in the HTTP request action.

For example:

![image](https://user-images.githubusercontent.com/33945547/176324150-c21feb76-6645-454f-b4be-83a4ee32a765.png)

In this example, the bot is pulling `testapi` from the Azure application settings, asking the user a question, and then POSTing to an endpoint using the user's answer as a header parameter. This takes the form: `https://<test-api-endpoint>?<param-name>=<param-value>`. You don't need to use replace.

**Comment by Elsa2604** [comment] 2022-06-29 05:26
As you mentioned, I tried but its not working.. Pls review the below screenshots and confirm

1. Endpoint configured in app settings
![image](https://user-images.githubusercontent.com/104147442/176357851-adf5b818-afd4-41c2-9b6c-cbb0598eaf1e.png)

2. Pulling the corresponding endpoint in  HTTP request
![image](https://user-images.githubusercontent.com/104147442/176358043-b76d2ac4-5420-4e9a-843e-035a80e1a126.png)

3. Passing the parameters in Headers
![image](https://user-images.githubusercontent.com/104147442/176358203-f75b49ec-f452-468d-b305-56305575b020.png)

![image](https://user-images.githubusercontent.com/104147442/176358307-6ebc90f0-5f4b-4bf3-ae55-f25cba0aafae.png)

**Comment by Elsa2604** [comment] 2022-06-29 05:30
shd I mention the endpoint as **https://mybot.com/api/callOData?fruit=fruitname&color=fruitcolor** in app settings and 
mention key as  fruitname and value as  ${conversation.fruitname} in header ?

**Comment by Elsa2604** [comment] 2022-06-29 05:51
> shd I mention the endpoint as **https://mybot.com/api/callOData?fruit=fruitname&color=fruitcolor** in app settings and mention key as fruitname and value as ${conversation.fruitname} in header ?

Even tried in this way, not working.. The call itself failing

**Comment by Elsa2604** [comment] 2022-06-30 10:12
> Have you tried printing out the URL in the test dialog or debugging the bot to see what URL is actually produced? If you haven't, try that and note down what URL is produced. Once you can compare what's produced with what you were expecting, you'll be able to decipher what's wrong with the actions that build the URL.


When I print out, I'm getting   the actual url only https://mybot.com/api/callOData?fruit=fruitname&color=fruitcolor  not the url I'm expecting with dynamic value

**Comment by anishprasad01** [comment] 2022-06-30 14:57
You only add the header parameters in the `Headers` section. You don't also put them in the URL. The URL should just be `[https://mybot.com/api/callOData](https://mybot.com/api/callOData?fruit=fruitname&color=fruitcolor)`

**Comment by anishprasad01** [comment] 2022-06-30 15:35
I used the headers in my test and they worked correctly. The next step then is to double check the parameters themselves. Are they actually stored in the conversation scope? What do you get if you just print those?

**Comment by anishprasad01** [comment] 2022-06-30 15:40
I didn't say you cannot use that. I just want you to verify they are there. There must be some error in your setup if they're not showing up. Since you've reused variable names and parameter names as placeholders, it's difficult to understand what you've done. Can you please provide a more concrete example with example values instead of just placeholder names?

**Comment by Elsa2604** [comment] 2022-06-30 16:42
> Can you pls try with this example ?, even for this I am not able to get the response:
> 
> https://api.openweathermap.org/data/2.5/weather?zip=98052&appid=f90fa087672c81be1659a9bf48f9444d
> 
> ![image](https://user-images.githubusercontent.com/104147442/176731197-3cf88adf-4f60-462b-acd9-5e41173f5f0f.png)
> 
> ![image](https://user-images.githubusercontent.com/104147442/176731346-58d524d7-4986-45a2-a1d3-31ec00edf7c6.png)
> 
> ![image](https://user-images.githubusercontent.com/104147442/176731436-51a2250f-2510-4b0d-a38a-5e308808c2d3.png)
> 
> ![image](https://user-images.githubusercontent.com/104147442/176731807-82077155-d5d4-44a8-9670-15eff3f5d5f8.png)
> 
> ![image](https://user-images.githubusercontent.com/104147442/176731971-e041d562-d16b-4cad-94b5-0ba770fc3897.png)

For the same, able to get response from postman :

![image](https://user-images.githubusercontent.com/104147442/176732334-026e924f-15ab-4b44-b18b-a8b65c0a375e.png)

**Comment by Elsa2604** [comment] 2022-07-04 09:53
@anishprasad01 Were you able to reproduce ?

**Comment by anishprasad01** [comment] 2022-07-04 17:43
Firstly, this is a **public** page. Please **do not** post any API keys here for your own security. I would advise you to cease use of that key and generate a new one.

Now, as to the question, my apologies. I got a bit confused from the back and forth and gave you some incorrect advice. The headers are *not* the correct way to pass those parameters. Placing them in the URL itself is the correct method, as I believe you tried before. You would use the `${property_scope.property_name}` format to place the variables in the URL.

For example with OpenWeatherMap, perform a GET request on `${settings.testapi}?appid=${user.appid}&zip=${user.zip}`, with all of these properties set ahead of time, or collected from the user first, as appropriate.

Here is a screenshot of the execution. The bot asks the user for a zip code, then sends a GET request to OpenWeatherMap for the current weather data.

![image](https://user-images.githubusercontent.com/33945547/177199253-847e68e2-dce5-4d67-a762-9b4eedeb62cd.png)

**Comment by Elsa2604** [comment] 2022-07-04 17:48
Thanks @anishprasad01
So the parameters should be hard-coded in send a http request and it can't be called from config file. Correct me if I am wrong.

**Comment by anishprasad01** [comment] 2022-07-04 17:51
The structure of the URL must be known ahead of time. The values themselves can be obtained dynamically, as the example shows.

**Comment by Elsa2604** [comment] 2022-07-04 17:53
Got it, Thanks

**Comment by Elsa2604** [comment] 2022-07-05 13:36
@anishprasad01 Thanks, It is working good and I'm not able to reproduce the issue "Invalid URI".

**Comment by Elsa2604** [comment] 2022-07-05 13:38
Can you also investigate on the error "The process cannot access the file 'C:\home\site\wwwroot\language-generation\en-us\common.en-us.lg' because it is being used by another process" ?

**Comment by anishprasad01** [comment] 2022-07-05 14:43
Under what circumstances does it appear? Which channels? Does it still occur even after fixing the URI issue? Where has it been deployed?

**Comment by Elsa2604** [comment] 2022-07-05 14:47
> Under what circumstances does it appear? Which channels?  **After Deployment, when I open the bot in the directline channel sometimes when testing in webchat in composer**
  Does it still occur even after fixing the URI issue?  **Yes**
 Where has it been deployed? **To  Azure app service**

**Comment by anishprasad01** [comment] 2022-07-05 16:25
Does it only appear immediately after deployment? I have deployed test bots to Azure when testing the URI issue, and I didn't see this other error. 

Is there anything else about the bot's implementation that might be helpful to know? Number of languages, custom actions, general implementation, etc.?

**Comment by Elsa2604** [comment] 2022-07-08 12:38
> Does it only appear immediately after deployment?  Yes
> 
> Is there anything else about the bot's implementation that might be helpful to know? Number of languages, custom actions, general implementation, etc.?  Only general implementations and no custom actions or any middleware used

**Comment by anishprasad01** [comment] 2022-07-08 14:40
How many languages does your bot support?

**Comment by Elsa2604** [comment] 2022-07-08 14:53
> How many languages does your bot support?

Only english

**Comment by Elsa2604** [comment] 2022-07-12 19:10
@anishprasad01 Some information I can provide you is I have exported the code (zip) and I use it for other env with different appsettings.json and publishing profile

**Comment by anishprasad01** [comment] 2022-07-14 15:43
The same issue occurs?

**Comment by Elsa2604** [comment] 2022-07-14 15:46
Yes

**Comment by Elsa2604** [comment] 2022-07-15 14:57
Will this get resolve when Microsoft.Bot.Builder is updated ? 
Current version in the bot is 4.15.0.
If yes, How to update Microsoft.Bot.Builder in bot composer ?

**Comment by anishprasad01** [comment] 2022-07-15 15:37
You could attempt to do that using the package manager. It's one of the options in the left sidebar.

**Comment by anishprasad01** [comment] 2022-07-15 18:02
@Elsa2604,

My mistake, you cannot update the base Bot Builder libraries through the package manager. You would need to use VSCode or the terminal or some other method, as you would with a non-Composer project.

**Comment by Elsa2604** [comment] 2022-07-19 16:05
@anishprasad01  I upgraded to the latest version 4.16.0 and I am not able to reproduce the issue. But at the same time, I am not  able to see telemetry track event (Custom Event) in Application Insights. 
Only if I revert it back to the version 4.15.0, I am able to see telemetry track event in Application Insights.

**Comment by anishprasad01** [comment] 2022-07-19 17:12
@Elsa2604,

The telemetry track bug is a [known issue](https://github.com/microsoft/botbuilder-dotnet/issues/6367). A PR addressing it has been merged, and will be made available in the upcoming 4.17 release. If you would like to test it out ahead of time, you can clone main and build it or download a [daily](https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily) build. Naturally these builds do not represent a stable version and should not be used in production scenarios.

**Comment by Elsa2604** [comment] 2022-07-19 17:29
Oh okay. Any solution to over come the issue I raised in bot builder 4.15.0 ?

**Comment by anishprasad01** [comment] 2022-07-22 16:14
@Elsa2604,

Unfortunately, it is unlikely that there will be any backport of fixes to version 4.15. Since 4.16 fixes the main issue, and the upcoming 4.17 fixes the telemetry bug, I would advise you to test and then update to 4.17 as soon as it becomes available (as a reminder, you can download and test the daily build now, but it may not yet reflect its final release form).

In light of this, I am going to go ahead and close this issue. If you should encounter other issues or have a feature request, please feel free to open a ticket in the appropriate repository.

**Closed by anishprasad01** 2022-07-22 16:14 UTC
Labels: customer-reported, Bot Services, customer-replied-to
