### ISSUE TITLE
Allowed callers screen is not at all obvious that it's editable

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7277] opened 2021-04-22 22:01 UTC
## Describe the bug
It's not at all obvious that the elements on this screen are editable.

## Version

Version:  1.4.0-nightly.238265.5106247
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. In the design view click the 3 dots on the root -> share a skill
3. Fill out the form until you get to the allowed caller screen

## Expected behavior
The fields should be input/text fields instead of totally unmarked text on screen. It's purely by accident I found out they are editable. 

## Screenshots

![image](https://user-images.githubusercontent.com/50158775/115790252-4f335080-a37b-11eb-9d6e-dc95d803f4c2.png)

**Comment by cwhitten** [comment] 2021-04-23 00:24
closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/7147

**Closed by cwhitten** 2021-04-23 00:24 UTC
Labels: Needs-triage, Type: Bug
