### ISSUE TITLE
Ubuntu: Sign-out button doesn't work; just closes publish profile dialog

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7307] opened 2021-04-23 15:22 UTC
## Describe the bug

Trying to publish a bot (that I created and published using the Windows Composer) through Ubuntu. as far as I can tell from the logs it makes the call but nothing happens and I'm still signed in.

GET /api/auth/logOut - - ms - -
GET /api/runtime/templates 304 0.413 ms - -
GET /api/publish/types 304 0.803 ms - -
GET /api/projects/34013.942144006745/boilerplateVersion 304 336.234 ms - -

## Version

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [X] Ubuntu

## To Reproduce

1. Create and publish a bot on Windows
2. Migrate the project to linux (or open in Ubuntu on WSL2 with WSLG installed)
3. open the project and test in composer (works fine)
4. Manage the publish profile you created on the windows side
5. Click sign out - experience; nothing, dialog closes, open again and still signed in

## Expected behavior

Expected to actually sign out

## Screen shots

![image](https://user-images.githubusercontent.com/5997512/115893027-987fb080-a40c-11eb-9a4d-690aa8c48272.png)

**Comment by Dewain27** [comment] 2021-04-23 18:43
Duplicate of #7235

**Closed by Dewain27** 2021-04-23 18:43 UTC
Labels: Area: Publish, P0, R13 Bugbash, Type: Bug
