### ISSUE TITLE
Composer sends endless requests with 500 responses and eventually crash when skillHostEndpoint is not configured properly

### ISSUE THREAD

**Issue by OEvgeny** [microsoft/BotFramework-Composer#9569] opened 2023-04-25 19:37 UTC
## Describe the bug

The user has discovered a bug in the two last versions of Bot Composer. The issue is caused by a skill server endpoint port misconfiguration which Bot Composer attempts to connect to on the wrong port. This sends endless requests with 500 responses until it crashes Bot Composer. Furthermore, the user reports that Bot Composer's performance decreases over time.
## Version

nightly 

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Use Bot Composer in the latest two versions.
2. Set the skillHostEndpoint to http://localhost:39XX/api/skills not matching the right port.
3. Bot Composer will attempt to connect to the skill server on the wrong port.
4. As a result, Bot Composer will send endless requests with 500 responses and crash.

## Expected behavior

Bot Composer should connect to the correct skill server endpoint port and not crash. Furthermore, its performance should remain consistent over time.

## Screenshots

![image](https://user-images.githubusercontent.com/13846122/231719577-8e354c3e-a785-4141-8c65-8b349cefa1a1.png)

<details>

```json
{
  "error": {},
  "id": "3d5328d2-4dc9-4cdb-95c1-a68929498aed",
  "request": {
    "method": "POST",
    "payload": {
      "type": "trace",
      "serviceUrl": "http://localhost:5000",
      "channelId": "emulator",
      "from": {
        "id": "d169c709-15fb-4db3-b913-5c23669f19e7",
        "name": "Bot",
        "role": "bot"
      },
      "conversation": {
        "id": "e31de584-237f-448b-a91f-6c6c47538b83|livechat"
      },
      "recipient": {
        "id": "1649e6f9-4779-4137-bb90-27171d8c7719",
        "name": "",
        "role": "user"
      },
      "locale": "fr-fr",
      "replyToId": "90ad2766-53c9-4d97-89f4-2053d9b2c552",
      "label": "Bot State",
      "valueType": "https://www.botframework.com/schemas/botState",
      "value": {
        "turn": {
          "locale": "fr-fr",
          "activity": {
            "type": "message",
            "id": "90ad2766-53c9-4d97-89f4-2053d9b2c552",
            "timestamp": "2023-04-12T11:56:33.976Z",
            "localTimestamp": "2023-04-12T11:56:33Z",
            "localTimezone": "Europe/Paris",
            "serviceUrl": "http://localhost:5000",
            "channelId": "emulator",
            "from": {
              "id": "1649e6f9-4779-4137-bb90-27171d8c7719",
              "name": "",
              "role": "user"
            },
            "conversation": {
              "id": "e31de584-237f-448b-a91f-6c6c47538b83|livechat"
            },
            "recipient": {
              "id": "d169c709-15fb-4db3-b913-5c23669f19e7",
              "name": "Bot",
              "role": "bot"
            },
            "textFormat": "plain",
            "locale": "fr-fr",
            "text": "cc",
            "attachments": [],
            "entities": [
              {
                "type": "ClientCapabilities",
                "requiresBotState": true,
                "supportsListening": true,
                "supportsTts": true
              }
            ],
            "channelData": {
              "clientActivityID": "1681300593932c6rullfvt3"
            },
            "callerId": "urn:botframework:azure"
          },
          "dialogEvent": {
            "Bubble": false,
            "Name": "endOfActions",
            "Value": null
          },
          "recognized": {
            "text": "cc",
            "alteredText": null,
            "intents": {
              "None": {
                "score": 1
              }
            },
            "entities": {
              "$instance": {}
            },
            "intent": "None",
            "score": 1
          },
          "interrupted": true,
          "lastresult": null
        },
        "dialog": {
          "eventCounter": 1337995,
          "_adaptive": {
            "actions": []
          },
          "lastIntent": "None",
          "lastEvent": "endOfActions"
        },
        "this": {
          "eventCounter": 1337995,
          "_adaptive": {
            "actions": []
          },
          "lastIntent": "None",
          "lastEvent": "endOfActions"
        },
        "conversation": {
          "DialogState": {
            "dialogStack": [
              {
                "id": "CoreWithQnA",
                "state": {
                  "eventCounter": 1337995,
                  "_adaptive": {
                    "actions": []
                  },
                  "lastIntent": "None",
                  "lastEvent": "endOfActions"
                },
                "StackIndex": null,
                "Version": "OPMnpbVwjGnKlZ41OUoqyFYQho11+L9yPmPe2qorUWM="
              }
            ]
          }
        },
        "user": {}
      },
      "name": "BotState"
    },
    "route": "/v3/conversations/e31de584-237f-448b-a91f-6c6c47538b83%7Clivechat/activities/90ad2766-53c9-4d97-89f4-2053d9b2c552"
  },
  "response": {
    "payload": {
      "message": "Conversation not found. BadArgument"
    },
    "statusCode": 500
  },
  "timestamp": 1681378138978
}
```

</details>

## Additional context

See #9557

**Comment by ramfattah** [comment] 2023-05-03 16:23
Hey @ceciliaavila, 

We are able to reproduce this issue. Assigning this to you for now.

Please let me know if you have any questions.
Thanks.

**Comment by ceciliaavila** [comment] 2023-05-04 18:10
> Hey @ceciliaavila,
> 
> We are able to reproduce this issue. Assigning this to you for now.
> 
> Please let me know if you have any questions. Thanks.

Hi @ramfattah, thanks. We added this to our backlog and we'll be tackling it next week.

**Comment by ceciliaavila** [comment] 2023-05-08 20:23
Hi @ramfattah, we couldn't reproduce this issue. We tested nightly versions [nightly.347274.c2cbc47](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.2-nightly.347274.c2cbc47) and [nightly.349502.c018e9b](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.2-nightly.349502.c018e9b). In both cases, after starting the bot and running it in Webchat, we got the 'jwt.encode' error which fix is ready in [PR#9547](https://github.com/microsoft/BotFramework-Composer/pull/9547). After this error, Composer crashes.
We also noticed that even if we set a wrong value in the root's _skillHostEndpoint_ property, Composer updates it to the correct value when the bot starts.
Can you please provide more information on your repro steps?
Thanks!

**Comment by ramfattah** [comment] 2023-05-08 22:35
Hey @ceciliaavila, 

Thanks for your effort in trying to reproduce the issue and for providing details on the tests conducted using nightly versions.

I'm discussing internally with the Engineering team about PR [#5947](https://github.com/microsoft/BotFramework-Composer/pull/9547) and working on getting this PR merged potentially resolve the customer's issue.

Thank you for your assistance.

**Comment by ramfattah** [comment] 2023-07-12 23:30
PR #9547 has been merged.

**Closed by ramfattah** 2023-07-12 23:30 UTC
Labels: Type: Bug, customer-reported, Bot Services
