### ISSUE TITLE
Provision & Publish: When the provisioning fails, should provide a 'try again' path

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#6159] opened 2021-03-03 22:31 UTC
## Describe the solution you'd like
When provisioning fails (in my case because I had too many app registrations) it would be nice if the window where I set all the properties and names up popped back up to allow me to try again. Right now, when it fails I have to start all the way over which is frustrating. 

Also, it points me to the log file, but it would be helpful if I could click the file path directly from the error message instead of navigating to find it on my own

**Comment by cwhitten** [comment] 2021-03-22 19:27
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/6252

**Closed by cwhitten** 2021-03-22 19:27 UTC
Labels: R12 Bugbash, Team: Runtime & Publishing, feature-request
