### ISSUE TITLE
Save bot does not create .sln file

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#7088] opened 2021-04-19 08:07 UTC
## Describe the bug

Create a empty bot will create a file structure:

```
emptyBot  (1)
  + emptyBot  (2)
  - emptyBot.sln  (3)
```

Next time I open the bot, `+ emptyBot  (2)` will be treated as a bot, not `emptyBot  (1)`.

When I save it as a new bot, only created folder is
```
  + emptyBot  (2)
```

no parrent folder `emptyBot  (1)` and no  solution file `emptyBot.sln  (3)`

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

The root folder should be treated as a bot, when save as a new bot, the structure should same to create from template

```
emptyBot  (1)
  + emptyBot  (2)
  - emptyBot.sln  (3)
```

**Comment by boydc2014** [comment] 2021-04-19 09:03
@benbrown  is this by design or a bug?

**Comment by mewa1024** [comment] 2021-04-19 20:57
Changes to the UX are described in bug #6808.

Basically, in the current behavior, creating a new bot creates a bot project folder; opening a bot opens the bot itself (root or skill); and "Save As" also saves only the selected bot, not the entire project. We would like to add the ability for "Save As" and Delete to affect either an individual bot or the entire bot project.

**Comment by boydc2014** [comment] 2021-04-20 01:47
> Changes to the UX are described in bug #6808.
> 
> Basically, in the current behavior, creating a new bot creates a bot project folder; opening a bot opens the bot itself (root or skill); and "Save As" also saves only the selected bot, not the entire project. We would like to add the ability for "Save As" and Delete to affect either an individual bot or the entire bot project.

Thanks @mewa1024  for clarifying, so i removed the "bug" label. Do we want to just close this or leave this  as a feature request?

**Closed** 2021-04-20 23:14 UTC
Labels: Needs-triage
