### ISSUE TITLE
npm root -g --prefix C:\Users\ADMIN\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by ArushiSingh** [microsoft/BotFramework-Composer#8710] opened 2021-09-29 12:30 UTC
I am also getting the error.

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\ADMIN\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file

Could you please help?

**Comment by jnair7291** [comment] 2021-09-29 13:50
Hi, 

can you verify your node installation is done over globally in your system?  To check this

 try 
![image](https://user-images.githubusercontent.com/11803138/135281783-6d068f43-51ef-4ce3-a7e3-a4910f79351e.png)


If that did not go through, 
Check npm Path is provided under advanced system setting -> environment variables after nodejs installation is completed
![image](https://user-images.githubusercontent.com/11803138/135281542-c50db113-92e5-4a3e-a360-4c2e5076ac8f.png)

**Comment by tonyanziano** [comment] 2021-09-29 16:36
Hi @ArushiSingh ,

Please try the guidance provided by @jnair7291 , and let us know if that fixes the issue.

I'm going to close this issue as it is a dupe of #8694 and is being tracked there.

**Closed by tonyanziano** 2021-09-29 16:36 UTC
Labels: Needs-triage
