### ISSUE TITLE
[10/30 Hack] 'pwsh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#1398] opened 2019-10-30 22:54 UTC
When creating the Azure Resources from the Settings > Publish page, the command that I need to run is "cd C:/code/BotFramework-Composer/SampleBots/WeatherBot2
pwsh ./Scripts/create.ps1 -name WeatherBot2 -environment Production -location WestUS2 -appPassword 'A12345678912345*'".

When I run it I get this error
![image](https://user-images.githubusercontent.com/17152540/67905021-60f0ba80-fb2d-11e9-83ee-9ce2e03d1765.png)

Put some link to install the right powershell in the dialog as a prerequisite.

**Comment by cwhitten** [comment] 2019-11-06 23:44
Closing as by design

**Closed by cwhitten** 2019-11-06 23:44 UTC
