### ISSUE TITLE
[v1.1.1] Unable to run LUIS based bots

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#4026] opened 2020-09-03 21:56 UTC
## Describe the bug

Bots with LUIS error out.
In the emulator, when a message is sent, bots replies with: "Response status code does not indicate success: 401 (PermissionDenied)."

## Version

v1.1.1

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new ToDoBotWithLUIS
2. Copy the default language to another (e.g.: "it-it"), set it as default and delete the original "en-us".
3. On run a LUIS dialog appears, input an authoring key and select westeurope as authoring region
4. Test it in emulator, after the greeting message, any input results in "Response status code does not indicate success: 401 (PermissionDenied)."

## Expected behavior

LUIS being invoked and parsed.

**Comment by ruifelixpereira** [comment] 2020-09-03 22:32
I am also able to reproduce this error adding pt-br, setting it as default and even without deleting en-us.

**Comment by zxyanliu** [comment] 2020-09-03 22:48
Hey guys, thanks for reporting the issue. I just tested using v1.1.1 and was unable to reproduce the error. 
If you are looking for multilingual language support, this [doc](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language) will be helpful. 

I used `en-us` and tested a LUIS bot in Emulator with successful responses. 
I added `zh-cn` and translated both Bot Responses and User Input, tested in Emulator with successful responses. 

![image](https://user-images.githubusercontent.com/32497439/92180835-d20f9700-edfc-11ea-925b-aa049e1f5a30.png)

**Comment by hibrenda** [comment] 2020-09-04 02:41
@EPinci @ruifelixpereira  You may hit https://github.com/microsoft/BotFramework-Composer/issues/3904#issuecomment-682279009. Could you follow the steps to solve the issues ?

**Comment by EPinci** [comment] 2020-09-04 07:23
@hibrenda I was able to make it work by populating the endpoints in the config but I'm a bit confused in here.

According to another comment on the same thread https://github.com/microsoft/BotFramework-Composer/issues/3904#issuecomment-682445643 the endpoints need to populated only if not using the standard region based ones: I have the standard https://westeurope.api.cognitive.microsoft.com but I still need to populate them.

**Comment by hibrenda** [comment] 2020-09-04 09:40
@EPinci Thanks for the comments. could you provide more detail for your luis setting so we can look into detail ?

**Comment by EPinci** [comment] 2020-09-04 10:07
@hibrenda  Sure.

This is the default luis section I get with the template:
```
  "luis": {
    "name": "ToDoBotWithLuisSample-0",
    "authoringKey": "",
    "endpointKey": "",
    "authoringRegion": "westeurope",
    "defaultLanguage": "it-it",
    "environment": "composer",
    "endpoint": "",
    "authoringEndpoint": ""
  },
```
I changed the default language and the key I get to populate it on the first run.

In order to have it working I have to populate the "endpoint/authoringEndpoint" to  https://westeurope.api.cognitive.microsoft.com (as found in my luis resource overview).
If I do, I it works and I get a LUISv3 trace in the emulator. If I don't... the above error message and no trace.

**Comment by hibrenda** [comment] 2020-09-04 12:57
@luhan2017  @zidaneymar Could you help to look into detail ?

**Comment by eluchsinger** [comment] 2020-09-08 08:50
@EPinci I get the same error. I have no idea if it's because of LUIS or not. What did you change exactly in the LUIS section and what did you leave empty?

**Comment by EPinci** [comment] 2020-09-08 09:11
@eluchsinger I made sure to populate both the authoringKey and the endpointKey.
I also populated the endpoint and authoring Endpoint with the values you can find in the respective LUIS resources on Azure.
Everything else should be prepopulated for you. See https://github.com/microsoft/BotFramework-Composer/issues/4026#issuecomment-687054588
I also made sure that my endpoint key is associated as a prediction key in the LUIS app that gets generated by the Composer.

**Comment by paul-maher** [comment] 2020-09-10 07:36
For me this was resolved by manually setting the 'endpoint' in the LUIS section in the app settings file from the value copied from the Azure portal. Note the upgrade also seems to have reset the QnA Maker key in the app settings files so I had to manually add that back in again too. I guess that is a similar issue.

**Closed** 2020-09-10 21:46 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported, known issue
