### ISSUE TITLE
[MCS-DE] Syntax Validation LU preBuild Entities does not consider locale

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#8475] opened 2021-07-27 12:00 UTC
With Composer v2.1 a preBuild entityname error for a reserved name is thrown. However the mentioned preBuild entity does not exist in the locale (de-DE) of the model, only in English.

Syntax checker should not throw an error in this case.

![image](https://user-images.githubusercontent.com/31212469/127149674-dc6cbb39-9ca9-49d2-81a1-7cb1c3aa6c03.png)

**Comment by tonyanziano** [comment] 2021-07-27 17:11
@stevkan can you please verify this issue?

**Comment by stevkan** [comment] 2021-07-29 18:37
@goergenj, I was able to confirm that the `personName` entity is in fact reserved across all languages by LUIS. This is by design so that if and when this prebuilt entity is included in other languages (beyond English and Chinese) it will be available and won't conflict with similarly named user-defined entities.

I'm closing this as resolved as this should address the issue. If, however, it does not please feel free to re-open.

**Comment by goergenj** [comment] 2021-07-29 21:10
@stevkan This needs to be reopened. Since Composer v2.1 throws an error you cannot start a Bot. In languages which do not  support the preBuild entity you need to be able to train it with the reserved name to enable multi-language Bots which use languages with and without preBuild entity. Composer should max. throw a warning but not prevent the bot application to be started! This behaviour was not there before v2.1 and should be reverted imho.

**Comment by tonyanziano** [comment] 2021-07-30 17:31
@goergenj you are right, I have verified that with a LUIS app using a Dutch locale, LUIS allows me to create an entity named `personName` because it is not supported in that locale:

![validation1](https://user-images.githubusercontent.com/3452012/127690232-3fe65cad-fc88-4ac9-92fc-20ad097549af.PNG)
![validation2](https://user-images.githubusercontent.com/3452012/127690233-5cd02e3c-8a47-4434-b522-03b99e92acca.PNG)

With a LUIS app using the English locale, it prevents me from creating the entity because `personName` is a reserved prebuilt entity name that is supported in the locale:

![validation4](https://user-images.githubusercontent.com/3452012/127690318-0df7dff6-2774-4a11-b39f-efb66850f448.PNG)
![validation3](https://user-images.githubusercontent.com/3452012/127690329-b24c2485-d162-4b5f-89b1-4630feb321da.PNG)

Composer should imitate this behavior when validating entities.

**Comment by stevkan** [comment] 2021-07-30 18:23
@goergenj @GeoffCoxMSFT, it seems there may be some confusion on this. On the one hand, when asking @chrimc62 about the prebuilt personName entity in LUIS, he stated in a Teams conversation:

> Looks like it was dropped from the LUIS UI--I'll ask them why.  You should though still be able to get in in an LU file by doing @ prebuilt personName.  For composer the underlying checker reserves all of the prebuilt entity names--even if they are not available for a language.  They should not define entities using prebuilt names.

and 

> PersonName has not been dropped--user error on my part.  It may be added to de-de in the future.  This is by design--they cannot use prebuilt names for custom entities.

However, as demonstrated above, the LUIS portal is allowing this to happen. I've reached out to a member of the LUIS team for clarification on which is right: Composer or LUIS portal. I'll post an update here once I know more.

**Comment by goergenj** [comment] 2021-08-02 07:17
@stevkan Thanks for checking. As I suggested, Composer should only create a warning but not an error preventing the app to start. If you create an error as introduced in v2.1.0, creating multi language Bots will become a lot more complex as you will need to check the locale first everytime and then add actions per locale which is not very efficient anc will create confusion as well.

**Comment by stevkan** [comment] 2021-08-02 20:02
I confirmed with the LUIS team that the correct functionality should favor the current LUIS user experience. In other words, as @tonyanziano stated above,

> ...using a Dutch locale, LUIS allows me to create an entity named `personName` because it is not supported in that locale...With a LUIS app using the English locale, it prevents me from creating the entity because `personName` is a reserved prebuilt entity name that is supported in the locale...Composer should imitate this behavior when validating entities.

@GeoffCoxMSFT, re-assigning this to you.

**Comment by goergenj** [comment] 2021-09-17 11:40
@stevkan @cwhitten Any update when this will be fixed? This is still open in 2.1.1 and preventing to upgrade to this Composer version.

**Comment by goergenj** [comment] 2021-12-10 10:53
@stevkan @cwhitten @sgellock Any update when this will be fixed? This is still open in 2.1.1 and preventing to upgrade to this Composer version. Will there be a 2.1.2 version fixing this?

**Closed** 2021-12-13 15:49 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Team: Authoring
