### ISSUE TITLE
Cannot open filtered dialogs/triggers when using the filter on the side menu

### ISSUE THREAD

**Issue by skpeter** [microsoft/BotFramework-Composer#9434] opened 2022-11-28 15:18 UTC
## Describe the bug

When filtering dialogs and/or triggers on the side menu by name, when clicking on a filtered trigger, the side menu returns to normal but the selected trigger/dialog is not opened.

## Version

Stable release 2.1.2, downloadable build (not hosted on cloud)

## OS

- [ ] macOS
- [x] Windows 11
- [ ] Ubuntu

## Additional context

It seems that if the filtered dialog/trigger is still in the same line on the list when the side menu goes back to normal, then Composer is able to open that dialog/trigger. This makes it so this behavior is probably only seen in bots with many triggers created, that should help with reproducing the bug.

**Comment by ramfattah** [comment] 2022-12-01 21:09
Thanks @skpeter,

I was able to reproduce this issue using Composer 2.1.2

Steps to reproduce:
1. Open a Composer bot. 
2. Using the left nav, search for a trigger
3. click the searched trigger
4. trigger does not open after searching

Video demo:

https://user-images.githubusercontent.com/38049078/205159624-890c80e2-d528-48a2-aae6-b3f62aeb692e.mp4

**Comment by ramfattah** [comment] 2022-12-01 21:13
Hi @ceciliaavila,

There seems to be an issue with dialogs/triggers not opening properly after filter/search from left nav menu.

Assigning this to you for now.
Please let me know if you have any questions. Thanks

**Comment by ceciliaavila** [comment] 2022-12-05 13:08
Hi @ramfattah, thanks for the repro steps. We'll start working on this issue today.

**Comment by ceciliaavila** [comment] 2022-12-05 16:38
Hi @ramfattah,
We were able to reproduce the issue using version 2.12 of composer, however, with the latest version in main, the error is not reproducible.
We could recommend the customer install the nightly version, but there's an [open issue](https://github.com/microsoft/BotFramework-Composer/issues/9228) reporting an error when downloading these preview versions.
Regarding the open issue, it's on hold as we need information about the release process to continue. Maybe you could help us with this?

**Comment by ramfattah** [comment] 2022-12-19 16:45
Closing with workaround.

**Closed by ramfattah** 2022-12-19 16:45 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, ExemptFromDailyDRIReport
