### ISSUE TITLE
After I upgraded composer to latest version (1.3.0), it fails to publish to azure. Throws something went wrong error everytime.

### ISSUE THREAD

**Issue by Shivanitanwar** [microsoft/BotFramework-Composer#5743] opened 2021-02-09 18:48 UTC
## Describe the bug

After I updated composer to latest version (1.3.0), it fails to publish. Throws something went wrong error everytime.
## Version

1.3.0
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

Windows

- [x] Windows
-
## To Reproduce

I created a publish profile.
Then tried to publish to azure through composer.
It will ask for azure credentials and then starts to publish but fails after sometime and says something went wrong.

## Expected behavior

Throws something went wrong

## Additional context

All the resources in azure are working and accessible. Is this something faced by someone else?? 
I didn't find anything useful in logs as well. Please suggest.

Also, the publish works fine the last version with same publish profile.

**Comment by cwhitten** [comment] 2021-02-10 19:03
@Shivanitanwar can you please upgrade to version 1.3.1 and see if the issue is resolved for you? Thanks.

**Comment by dchumpitaz** [comment] 2021-02-15 03:24
I have this bug too with 1.3.1 version.
I have an Azure subscription using mi personal account (not corporate account) and when I trying to login into Azure, when I choose my personal subscription, the login page shows me "Something went wrong [2002]".

**Comment by congysu** [comment] 2021-02-25 19:29
@joshgummersall could you please take a look at this one?  Thanks.

**Comment by congysu** [comment] 2021-02-25 20:50
@cwhitten could you please ask a team member take a look at this?  Thanks.

**Comment by Shivanitanwar** [comment] 2021-03-15 20:13
The upgrade to 1.3.1 solved the issue for me. Sorry, for the delayed response. @cwhitten

**Comment by cwhitten** [comment] 2021-03-15 20:15
Thanks. Closing

**Closed by cwhitten** 2021-03-15 20:15 UTC
Labels: Bot Services, customer-replied-to, customer-reported
