### ISSUE TITLE
Unknown intent trigger is not called in child dialog

### ISSUE THREAD

**Issue by Jxlle** [microsoft/BotFramework-Composer#9112] opened 2022-04-09 19:11 UTC
## Describe the bug

The bot doesn't recognize the intent of the user input (image (2)), but it doesn't activate the _unknown intent_ trigger of the main dialog while being inside an active child dialog (auto end **off**).  Instead, the bot just doesn't respond (image (1)). This happens in all child dialogs and _unknown intent_ is the only intent trigger that doesn't work from inside the child dialogs.

## Version

v2.1.2 on Windows

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

My current implementation implements a child dialog where the bot asks a question and the user input can be recognized as an 'accept' or 'deny' (image (4)). An unknown intent trigger is implemented in the main dialog, but unknown user input doesn't trigger the unknown intent dialog from inside the child dialog. This is also the case for other child dialogs. The child dialog is set to **not** automatically end.

## Expected behavior

The _unknown intent_ trigger is called.

## Current hacky fix

My current fix for this is to add an extra _none intent recognized_ trigger with the same responses as the _unknown intent_ trigger, but this isn't ideal.

## Screenshots

Image (1): Conversation with the bot
![image](https://user-images.githubusercontent.com/29973052/162588698-550e95cb-f88f-4e6a-9919-1fcd8607bd42.png)

Image (2): LUISV3 trace of the user input
![image](https://user-images.githubusercontent.com/29973052/162588715-3f201525-0167-41e8-8439-debc32c21186.png)

Image (3): LUISV3 trace
![image](https://user-images.githubusercontent.com/29973052/162588669-b915aa74-0303-46b9-9362-2a2cfb8c9a1b.png)

Image (4): dialog setup, **brown** is the current child dialog with a "yes" and "no" intent, **green** is the unknown intent dialog
![image](https://user-images.githubusercontent.com/29973052/162588100-1f481587-c757-4d68-b8c5-86e1af050ed1.png)

**Comment by ramfattah** [comment] 2022-04-11 17:18
Hey @Jxlle -- I'm investigating this issue.

**Comment by ramfattah** [comment] 2022-04-14 01:19
@Jxlle 

I believe the unknown (or None) intent is something generated by the language recognizer and is designed to accept input that matches the choices provided.

#

You could also enable interruptions to let the dialog recognize "cancel" or "help" and then cancel the current operation or provide some assistance before returning back to the prompt. 

Here is the composer package [Microsoft.Bot.Components.HelpAndCancel](https://github.com/Microsoft/botframework-components/tree/main/packages/HelpAndCancel)

**Comment by Jxlle** [comment] 2022-04-14 10:18
Hi @ramfattah 

Interruptions are allowed and I can trigger a dialog when the None intent is recognized, just not with the unknown intent trigger. Do you happen to know the difference between the two?

**Comment by ramfattah** [comment] 2022-04-14 17:03
Hi @Jxlle 

None is a built-in/default intent as far as LUIS is concerned. You can have a none intent using LUIS without using the Bot Framework at all.

Unknown Intent is a bot framework thing in adaptive dialogs. This is a sort of "catch-all" bucket for where to send the conversation when all other avenues in the dialog are not matched.

**Comment by ramfattah** [comment] 2022-04-14 18:41
Closing this issue as it is by design, not a bug. @Jxlle, please feel free to re-open if needed.

**Closed by ramfattah** 2022-04-14 18:41 UTC
Labels: customer-reported, Bot Services, customer-replied-to
