### ISSUE TITLE
Unable to sign in to personal account to create a publish profile

### ISSUE THREAD

**Issue by Jxlle** [microsoft/BotFramework-Composer#9107] opened 2022-04-07 14:08 UTC
## Version
v2.1.2 on Windows

## Describe the bug
When trying to do things in bot composer that require to be logged in, like creating a publish profile, it asks me to sign into my microsoft account although I'm already signed in. After signing in again, it asks me to sign in AGAIN, but now it shows a screen with possible accounts (two used for my uni work). When trying to log in again on my main email account (that I use for Azure), I get a message that I can't log in with a personal account. When choosing one of the other accounts, I get the a message indicating that I need to use my main account. Because of this, I can't publish my bot as authorization fails.

## To Reproduce
1. Go to the "Publish" tab
2. Try to create a publish profile with new resources
3. Be asked to sign in 

## Expected behavior
After logging in (again), the window closes and I'm able to create my publish profile.

## Screenshots
Bot framework asking me to sign in although I'm already signed in (see bottom left)
![image](https://user-images.githubusercontent.com/29973052/162216342-f3f061c7-c82b-4a19-b4c2-abc322906f5b.png)

After signing in again, microsoft asks me again to sign in, now providing two of my other accounts.
![image](https://user-images.githubusercontent.com/29973052/162216806-2a03353a-bbf1-4922-b2f2-e6538f6c753f.png)

After trying to log into my main account again, the following message appears.
![image](https://user-images.githubusercontent.com/29973052/162216940-096c9b59-fd98-4692-89c2-76134468d7e7.png)

After choosing one of the other accounts, the following message appears.
![image](https://user-images.githubusercontent.com/29973052/162217077-bd7bf7ba-9cd5-4dc6-9298-1ac0d6879341.png)

## Additional context
I've been using Azure services for a while now without any account problems. I do have the same problem when I click "View account on Azure" inside the bot composer. It sends me to a login website for microsoft. Using my main account email results in a message that says "The username is potentially wrong.", although I use the same email for my Azure account and can access the portal just fine. Using my account alias results in the same message as before, saying I can't log in using a personal account.

**Comment by dmvtech** [comment] 2022-04-07 21:17
Hi @Jxlle

Thank you for reporting this. Can you please try the following steps:

1. Clear the local cache by using the developer tools to clear site data. Restart Composer, sign in and try again.
![image](https://user-images.githubusercontent.com/43397658/162313720-95089027-b927-43a5-995b-6038174e6e68.png)
2. If that does **not** work, uninstall and reinstall with version `2.1.1` and see if the issue exists there.

**Comment by Jxlle** [comment] 2022-04-09 16:25
Hi @dmvtech, thanks for the reply!

your solution to reset the cache seems to work sometimes, but not always. It worked yesterday but the problem came back today.

**Comment by dmvtech** [comment] 2022-04-20 23:22
@Jxlle Still investigating. We have identified a bug that might be the cause of this issue as well. Stay tuned.

**Comment by Jxlle** [comment] 2022-04-25 08:48
@dmvtech Thanks! That's great to hear, as I still have the same problem.

**Comment by Jxlle** [comment] 2022-04-25 12:12
**UPDATE:** The problem does not occur in version `2.1.1`.

**Comment by dmvtech** [comment] 2022-05-04 20:30
Thanks @Jxlle Glad that workaround works for you.

I'll update when we have an update on the fix post `2.1.2`.

**Comment by dmvtech** [comment] 2022-05-26 23:03
Hi @Jxlle Would you please try the following:

- Upgrade back to 2.1.2
- Update the .csproj file of your bot and update the **Microsoft.Bot.Builder.*** packages (should be at least 3 of them) to use the `4.16.1` version of the SDK.
- Test

**Comment by dmvtech** [comment] 2022-06-07 19:01
Closing as unable to reproduce and unknown if it is resolved in newest build of Composer. If you are still experiencing this issue, please comment and we will revisit.

**Closed by dmvtech** 2022-06-07 19:01 UTC
Labels: customer-reported, Bot Services, customer-replied-to, bug
