### ISSUE TITLE
Published Bot won't work via Direct Channel. Bot responds "Value cannot be null. (Parameter 'key')"

### ISSUE THREAD

**Issue by rubit0** [microsoft/BotFramework-Composer#3554] opened 2020-07-02 21:12 UTC
A bot created and published by the Bot Framework Composer will work fine with the default Web Chat channel.
When adding the Direct Line channel and then performing requests against the API REST endpoint, the Bot will give the initial greeting and then onward responds only with "Value cannot be null. (Parameter 'key')".

## Version

1.01

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. download the Bot Composer project from this [tutorial](https://github.com/onginnovations/mixed-reality/blob/azure-develop/mixed-reality-docs/mrlearning-azure-05.md)
2. remove the two HTTP requests (they are not needed for testing this issue)
3. deploy it accordingly and add the Direct Line channel
4. do a conversation via Postman or other means to talk with Direct Line channel

## Expected behavior

The bot should give proper response and not the error message.

## Screenshots

This is how the Resources on azure look like after deployment:
![Screenshot 2020-07-02 at 01 54 47](https://user-images.githubusercontent.com/14140857/86301793-10bf8000-bc07-11ea-97d4-ca05191e1fc6.png)

Could it be that an App setting is missing on the App Service?
![Capture](https://user-images.githubusercontent.com/14140857/86403819-bd087180-bcae-11ea-9c29-ab27073b4186.PNG)

## Additional context

This is a continuation from this bug report: https://github.com/microsoft/BotFramework-Composer/issues/2240

**Comment by luhan2017** [comment] 2020-07-03 06:22
@rubit0 , I have dowloaded your bot and tested it. It works fine in my side, the only change I did is to remove the httpsteps to the azure functions, because I don't have a azure function example. Could the issue be caused by the http request to azure functions? could you share more details on that? do you use any key to access the azure function urls?

![image](https://user-images.githubusercontent.com/32191031/86438104-7bbca400-bd38-11ea-9670-6e4478bf538b.png)

![image](https://user-images.githubusercontent.com/32191031/86438021-54fe6d80-bd38-11ea-8cc9-8cfa95fc2700.png)

**Comment by viivalerio** [comment] 2020-07-03 14:21
Hey @rubit0 I was facing the exactly for a couple of days and luckly I could find out why this morning. 

In my case what fixed was adding the "locale" field in the json request body when creating an activity. Here is how my POST request looks like:

POST https://directline.botframework.com/v3/directline/conversations/{conversationId}/activities

{
  "from": {
    "id": "customId",
    "name": "customName",
    "role": "user"
  },
  "locale": "pt-BR",
  "recipient": {
    "id": "bot",
    "name": "Bot",
    "role": "bot"
  },
  "text": "some text",
  "textFormat": "plain",
  "type": "message"
}


Hope this helps you somehow

**Comment by rubit0** [comment] 2020-07-03 15:04
@viivalerio I'm glad to hear that you got it sorted out on your side. Sadly I don't quite understand what you mean, when you start a new conversation, you simply do a POST request with no body: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation?view=azure-bot-service-4.0

Are you using a different API? I can't find anything where it says that you need to provide a json in the body of the request.

**Comment by rubit0** [comment] 2020-07-03 15:07
@viivalerio Oh wow now it works! Thank you!

**Comment by rubit0** [comment] 2020-07-03 15:22
@luhan2017 @@DDEfromOR I did submit the problem and solution to the documentation page: https://github.com/MicrosoftDocs/bot-docs/issues/1806

Big thanks again to @viivalerio in providing the fix!

**Comment by hibrenda** [comment] 2020-07-06 11:41
@Danieladu @boydc2014 Do you have more comments for this issue ? sounds like LG language policy issue.

**Comment by hibrenda** [comment] 2020-07-07 10:10
https://github.com/microsoft/botbuilder-dotnet/issues/4219 sdk fixed the issues . composer will adopt latest sdk fix.

**Comment by luhan2017** [comment] 2020-08-20 08:04
composer has updated the sdk version to 4.10.0, so close this.

**Closed by luhan2017** 2020-08-20 08:04 UTC
Labels: Area: SDK, Type: Bug
