### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden) after Azure deploym,e

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#2007] opened 2020-02-18 21:30 UTC
#1316  Describe the bug

I created a new Composer bot (LUIS & QnA) and just added an Adaptive Card as a greeting. The bot works totally fine if I test it locally, but after the deployment to Azure I just get the greeting card and then I always get "Response status code does not indicate success: 403 (Forbidden)." as a message by the bot.

![image](https://user-images.githubusercontent.com/29750798/74779602-1b9ff680-529e-11ea-8901-c7f4e826c500.png)

Am I missing something after the deployment?

## Version

test

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by xieofxie** [comment] 2020-02-20 06:21
Hi @stephanbisser I have tried this and found this might be caused by the following three issues:
* When calling ./Scripts/create.ps1, it creates a luis-Authoring service for you. However this authoring key may not be the same as the one for your account (i.e. when you log in luis.ai)
* When calling ./Scripts/deploy.ps1, it creates a new luis app based on your local user, however it doesn't update the environment
![image](https://user-images.githubusercontent.com/2876650/74906147-12707000-53eb-11ea-9f0d-a69f848c2398.png)
* Even when you update environment, it will not load the correct json

You could do the followings to fix this:
* Change authoringKey in appsettings.json in root
* Delete ComposerDialogs\generated\luis.settings.composer.westus.json when deploy and restore afterwards

@hibrenda Please check and fix these issues, thanks!

**Comment by stephanbisser** [comment] 2020-02-20 10:17
Hi @xieofxie thanks!
Deleting the luis.settings.composer.westus.json file before running Deploy.ps1 did the trick.
The change of the authoring key in the appsettings.json would not help as the key has been set correctly in my case.

But I guess the removal of the file before deploying needs to be fixed to get rid of this issue right?

**Comment by xieofxie** [comment] 2020-02-21 01:22
@stephanbisser Yes, this issue has been tracked and it will be fixed soon.

**Comment by zidaneymar** [comment] 2020-02-25 07:23
@luhan2017 @hibrenda 
conclusion: caused by previously we have two different runtime for local debugging and deployment, after combining them together we don't handle the different settings for those two runtime.

**Comment by cwhitten** [comment] 2020-03-06 16:27
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2153

**Closed by cwhitten** 2020-03-06 16:27 UTC
Labels: R8, Type: Bug
