### ISSUE TITLE
Set properties panel height is not fit

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7300] opened 2021-04-23 06:19 UTC
## Describe the bug

Set properties panel height is not fit 
ex : defined properties  "dialog.username = @username" but in the visual canvas "g" is not display properly. 

## Version

Version:  1.4.0-nightly.238265.5106247
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

Add the properties in the Set Properties panel ... "g" is not visible properly.

## Expected behavior

All the letters should be visible

## Screenshots

![prop](https://user-images.githubusercontent.com/16264167/115827330-6e2df300-a40c-11eb-918d-52cd695631d7.png)

**Comment by GeoffCoxMSFT** [comment] 2021-04-27 21:38
I can't reproduce this, but I was looking at the line-height property, it is showing invalid.

![image](https://user-images.githubusercontent.com/28762486/116314670-3f917e80-a764-11eb-8d50-3d320b2160fb.png)

![image](https://user-images.githubusercontent.com/28762486/116314653-3a343400-a764-11eb-95eb-833f968a5172.png)

I see this style in styledComponents.ts which is the only place a line-height is calculated.  There are some cases where the props being applied cause height to be an object.

export const SingleLineDiv = styled.div<DivProps>`
  ${StandardFontCSS};
  ${TruncatedCSS};
  line-height: ${(height) => (height ? height + 'px' : undefined)};
`;

**Comment by GeoffCoxMSFT** [comment] 2021-04-27 22:34
@rvinothrajendran I think this invalid line-height issue is causing the overlap you are seeing.

**Comment by tsuwandy** [comment] 2021-05-03 18:21
Will be fixed with the next release.

**Comment by OEvgeny** [comment] 2024-02-27 19:35
Looks like it is fixed (can't reproduce)

**Closed by OEvgeny** 2024-02-27 19:35 UTC
Labels: Type: Bug, customer-reported, Bot Services, ExemptFromDailyDRIReport
