### ISSUE TITLE
Unable to publish virtual agents to azure

### ISSUE THREAD

**Issue by asaha7070** [microsoft/BotFramework-Composer#8453] opened 2021-07-22 09:02 UTC
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment] 2021-07-22 16:34
@asaha7070 This isn't currently supported. PVA bots are imported into Composer with their publishing profiles already set. We have a work item to block creation of a new profile in this scenario. Closing this as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/8453

**Closed by srinaath** 2021-07-22 16:34 UTC
Labels: Needs-triage, Type: Bug
