### ISSUE TITLE
Testing in Webchat after deploy on Azure  -Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by Heinzfb** [microsoft/BotFramework-Composer#5592] opened 2021-01-24 13:27 UTC
Hi there,
I created the bot using Composer and then published via VS CLI  (follow the Read.md).
>Your Azure hosting environment has been created! Copy paste the following configuration into a new profile in Composer's Publishing tab.<
I added the relevant info to the profile as described and deployed to existing resources.

When testing in Azure Webchat I get :  Response status code does not indicate success: 404 (Not Found).
If I switch to channels I get this:

![image](https://user-images.githubusercontent.com/67108766/105631537-3cc67b00-5e4f-11eb-95ca-bec166c4764e.png)

I checked that Luis is in published in prod.
Would you help me I I am stuck and need to solve this.
Ty in advance

## Version
Bot Framework Composer - master 
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

>Your Azure hosting environment has been created! Copy paste the following configuration into a new profile in Composer's Publishing tab.<
->  new profile in Composer's Publishing tab
->Publish
->Publish Luis to prod
-> Test in  Azure webchat

## Additional context

After publish it to azure und publish Luis to prod, I can not test the bot in local Emulator. Getting same error as in Webchat.

Thank you for your help,
best Heinz

**Comment by dmvtech** [comment] 2021-01-25 23:59
Hello @Heinzfb 

- Do you have a welcome in your bot? Is that working at all, or is the bot completely failing from the get-go?
- Can you re-publish and does that resolve it?
- Are you able to use [ngrok and test](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) with a locally running bot? (this will confirm the app registry and bot channels registry are working ok.

**Comment by Heinzfb** [comment] 2021-01-26 19:43
Really thank you for your help.  It for a small universety project I need to solve this :D. 

It takes some time and some refreshes unitil the bot take aktion. Here you can see:
![image](https://user-images.githubusercontent.com/67108766/105880258-73dd8d80-6003-11eb-868a-bb8b3e151321.png)

Republish is not possible I get an error. It is the same error as you can see below only in publish tab.
This error also occour if you have an mistake in your LUIS  .lg file, but I can not find one. 
Testing the bot lokally I got this. I had the same problem some time ago. With mac it builded correctly. 


![image](https://user-images.githubusercontent.com/67108766/105881195-7c829380-6004-11eb-9627-7d4971e58bde.png)

I will Try to connect via the public ngrok adress.

Where could I look for the problem do you have any idea? 

Tanks 4 all!

**Comment by dmvtech** [comment] 2021-01-27 00:45
So, above is the error if you try and republish, but if you just run the bot from Composer (with LUIS auth key and region in settings), does it work?

Have you tried removing the publishing profile and recreating from scratch and trying to publish then?

@luhan2017 Any thoughts on this one?

**Comment by luhan2017** [comment] 2021-01-27 04:38
@heinzfb I see you are using the composer main branch, it should relate to this issue #5614 
You can mitigate this issue by one of the following options:
1. Revert your composer main branch to a commit before this one https://github.com/microsoft/BotFramework-Composer/commit/ecf2df0e9966417e33abe76f5a0af4d68a4cebf9
2. Eject your runtime, and update the package versions from 4.12.0-daily to 4.11.0.
3. Use 1.3.0 electron version. 

Please let me know if it still not works.

**Comment by Heinzfb** [comment] 2021-01-29 14:15
Hi both of you, thanks for your reply please give me until tonight to follow the solution paths. 

Thanks 4 all :)

**Comment by Heinzfb** [comment] 2021-01-30 00:59
Hi there,

I choose option 1 and check out to the branch you can see below.

![image](https://user-images.githubusercontent.com/67108766/106335104-6b4bb800-628c-11eb-9292-cb2b24d8c82a.png)

>install >build >upgrade >start 

![image](https://user-images.githubusercontent.com/67108766/106339512-17929c00-6297-11eb-99df-2b257b045c4c.png)

![image](https://user-images.githubusercontent.com/67108766/106339870-2c236400-6298-11eb-8ee1-7a79ddfc5b02.png)

I am geeting some warnings. Are they critical? 

![image](https://user-images.githubusercontent.com/67108766/106339351-989d6380-6296-11eb-854e-b867799e304f.png)


Thank you! Saved my next 3 weeks. 
![image](https://user-images.githubusercontent.com/67108766/106340430-10b95880-629a-11eb-97b5-18476d8d6feb.png)

**Comment by luhan2017** [comment] 2021-02-01 03:40
@Heinzfb The original issue is already fixed in composer, you can try the latest main branch now. For those issues you met. 
1. The Starting bot spinning forever, if you can still reproduce this issue, could you help press F12 and copy the console logs here? 
2. The luis build failed issue, It looks like the it is a network issue, could you help double check if this can be produced in the latest main branch?

**Comment by Heinzfb** [comment] 2021-02-02 16:32
Hi luhan2017, 

thanks 4 your help I will try and give you further information about the spinnigissue.

**Comment by dmvtech** [comment] 2021-02-08 19:38
Hi @Heinzfb Just checking in. Were you able to make any progress or get any further info?

**Comment by dmvtech** [comment] 2021-02-16 19:24
Closing due to inactivity. If you have more information or still need assistance, please let us know.

**Closed by dmvtech** 2021-02-16 19:24 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported

**Comment by Heinzfb** [comment] 2021-02-19 22:14
Hey luhan2017 & dmvtech,
I am sorry for my enormous laziness. Just finished writing my thesis on it and am now back to bot.

This is shown in the console:
![image](https://user-images.githubusercontent.com/67108766/108567182-05d96d00-7308-11eb-9c81-04ec18f5b794.png)

Thank you for your help.

**Comment by luhan2017** [comment] 2021-02-20 02:42
@Heinzfb , I may lose the context, just want to clarify, are you using the latest composer main branch? and the issue is:
1. can't start bot locally. the Starting bot is spinning forever.
2. after you deploy your bot, did you still see the 404 error? 

Any other issues? Are you using a custom runtime here? And could you please share your bot here?

**Comment by Heinzfb** [comment] 2021-02-23 22:13
I cloned the latest one.
First everything worked fine. Btw. Nice Release 👍 

But after the 6 rebuild I got
![image](https://user-images.githubusercontent.com/67108766/108915116-b7d8a800-762c-11eb-826e-55ed84ec1ac0.png)

**Comment by luhan2017** [comment] 2021-02-24 02:54
@Heinzfb, this new issue is unrelated with the 404 error, could we just close this one and create a new issue for the language server?  @boydc2014 for awareness.
