### ISSUE TITLE
Creating a new dialog via the "Begin a new dialog" property pane does not set the dialog property

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1631] opened 2019-11-21 19:01 UTC
## Describe the bug

If you choose "Create a new dialog" from the "Begin dialog" property pane, it does create a dialog, but does NOT set the property as expected to that new dialog.

In addition, an INVALID ACTION is written to the new child dialog's trigger list that includes a circular reference (the newly created child dialog will contain a reference to itself), and this causes the 'Restart bot' process to fail.

![Screen Shot 2019-11-21 at 12 59 32 PM](https://user-images.githubusercontent.com/729873/69367950-d2b8b180-0c5e-11ea-9a50-da51cfa3e8dc.png)

This is an example of the invalid JSON that is added to the trigger list:

```
    {
      "actions": [
        {
          "$type": "Microsoft.BeginDialog",
          "$designer": {
            "id": "445290",
            "name": "Begin a new dialog"
          },
          "dialog": "doNewChildDialog"
        }
      ]
    }
```

## Version
e47d8ecc

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. Add a "Begin a new dialog" action
2. In the dropdown for dialog, select "Create a new dialog"
3. give name/description of new dialog
4. navigate back to parent dialog - notice the dialog property is blank.

... also

5. Notice that the new child dialog has an invalid and INVISIBLE circular reference to itself in the .dialog file. This dialog is broken and cannot be referenced without being manually fixed outside of Composer.

## Expected behavior
Give a clear and concise description of what you expected to happen.

The name of the newly created dialog will be set into the property field where the "create new dialog" option was initially selected

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by benbrown** [comment] 2019-11-21 19:14
It would appear that the dialog property that belongs in the parent dialog's call to BeginDialog is ending up in the new child dialog's trigger list somehow.

**Comment by a-b-r-o-w-n** [comment] 2019-11-21 22:20
duplicate of #1144 which is in development now.

**Closed by a-b-r-o-w-n** 2019-11-21 22:20 UTC
Labels: Needs-triage, Type: Bug
