### ISSUE TITLE
Unknown intent trigger on 2nd attempt and not on 1rst attempt

### ISSUE THREAD

**Issue by ankur0501** [microsoft/BotFramework-Composer#9119] opened 2022-04-13 05:43 UTC
I used prompt for text. Turn count is 1 and Allow Interruption is true.
When user types something other than the intent trigger that i created, then it is not going to Unknown intent. When User types once again then it fires Unknown intent. What i mean is Unknown intent is getting fire at the second user input and not at the first time
![image](https://user-images.githubusercontent.com/20242790/163108063-2e9ae5e4-56a8-4bb3-9737-4130e7f00249.png)
![uknown intent](https://user-images.githubusercontent.com/20242790/163108154-e178835e-ba4d-45f3-a0fb-9c891f396662.PNG)

_Originally posted by @ankur0501 in https://github.com/microsoft/BotFramework-Composer/issues/9069#issuecomment-1097581100_

**Comment by ramfattah** [comment] 2022-04-14 02:09
@ankur0501 

This is expected behavior.

#

From my understanding, this is what's happening:

The first response `credit card` is registered for the prompt for text, then it goes back to the parent dialog.
now, you have a second response of `credit card`, which the unknown intent will fire as you are back in the parent dialog. 

Hope this makes sense.

**Comment by ramfattah** [comment] 2022-04-14 02:09
Closing this issue as it is by design and not a bug.

**Closed by ramfattah** 2022-04-14 02:09 UTC
Labels: customer-reported, Bot Services
