### ISSUE TITLE
Cannot configure channels for newly provisioned bot

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6862] opened 2021-04-12 09:16 UTC
## Describe the bug

- Created a new bot
- Provisioned resources
- Selected publishing profile under Settings -> Connections to configure channels and received error that the resource group did not exist. 

I confirmed the provisioning completed successfully and resource group does exist.

![image](https://user-images.githubusercontent.com/3900649/114370982-f6440b00-9b77-11eb-9553-35c5efe18fd7.png)

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

cc @Dewain27

**Comment by benbrown** [comment] 2021-04-12 16:42
Dupe of #6731

**Closed by benbrown** 2021-04-12 16:42 UTC
Labels: R13 Bugbash, Type: Bug, topic: creation
