### ISSUE TITLE
Composer should provide a way to enable users to delete bots 

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#7348] opened 2021-04-23 22:39 UTC
Currently there is no way to delete a bot in Composer. The delete feature will be very helpful especially for deleting bots like enterprise assistants that deleting would mean deleting both the root bot and connected skills and there are many resources related, so it's a much effective and clean way to delete the assistant if I can just click the assistant to batch delete all the related resources, instead of going to Azure portal to delete all the various resources independently. This is also a scenario that's not only common for us during testing when we easily create many bots and resulted many testing resources in Azure that are actually abandoned but not deleted. In enterprise scenarios, many team members could share the same subscription for a team, so they can easily hit certain limit for the subscription too. For example, there is a limit of not more than 10 LUIS authoring resources is allowed per subscription. Otherwise users will hit the following insufficient quota error.  It's important to provide a way to easily delete bots in Composer. 

![image](https://user-images.githubusercontent.com/25210203/115935881-fd58fc00-a448-11eb-98b1-91210284de09.png)

![image](https://user-images.githubusercontent.com/25210203/115936349-de0e9e80-a449-11eb-9e99-9555998a6b25.png)

**Comment by tdurnford** [comment] 2021-04-23 23:18
@elaine-chang There is a 'Delete' button on the bot settings page that allows users to delete their project.

![image](https://user-images.githubusercontent.com/17039790/115938419-cdfdbb80-a457-11eb-953f-6d471fa79dd0.png)

**Comment by elaine-chang** [comment] 2021-04-24 00:14
Thanks. This shows how undiscoverable the current "delete" button is. I checked with 2 of our own developers and none of them is aware of deleting feature is supported in Composer and "wouldn't have known where to look". 

@emivers8 @mareekuh @Quirinevwm @mewa1024 @lauren-mills @thomas-chung FYI

**Comment by elaine-chang** [comment] 2021-04-24 00:25
@tdurnford I just checked. As you suspected deleting a bot with skills like enterprise assistant bot currently does not delete the skills. #7353

**Comment by mewa1024** [comment] 2021-04-24 04:25
@elaine-chang yes! Xi and I noticed this while investigating bug #6808. The changes to the design are described in the comments in that bug (@emivers8 is working on the details for the Project Settings page where "Delete project" would be the command at the top of the page and a more specific "Delete bot" command would live somewhere on the page in the section about that particular bot). We are hoping to get this in for R13.

I'm closing this bug as a dupe of #6808, but please reopen if they are separate issues.

**Closed by mewa1024** 2021-04-24 04:25 UTC
Labels: Needs-triage, feature-request
