### ISSUE TITLE
WebChat doesn't work if I update the MicrosoftAppId and MicrosoftPassword and restart my bot

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#8226] opened 2021-06-30 06:47 UTC
## Describe the bug

It happens in both nightly and v2.0.

Here is the steps to reproduce this issue:

1. open a bot with MicrosoftAppId and MicrosoftPassword set to empty string, start the bot, it works as expected.
2. set a valid MicrosoftAppId and MicrosoftPassword, and restart the bot. The expected behavior is bot also work well.
But actually I got such error:
![image](https://user-images.githubusercontent.com/32191031/123914309-d8858580-d9b1-11eb-98dd-174e701ab1f8.png)

It seems that webchat always takes the MicrosoftAppId and MicrosoftPassword when the bot is started the first time. update MicrosoftAppId and MicrosoftPassword later will break the webchat.
@srinaath 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment] 2021-06-30 18:51
@luhan2017 Trying it on latest main after https://github.com/microsoft/BotFramework-Composer/pull/8227. Im not able to repro the error. Let me know if i can close it.

**Comment by boydc2014** [comment] 2021-07-01 00:40
I can still repro it in latest main @srinaath . The issue is, it seems like the webchat control init it's config only once from the bot settings, and after that no matter how we update the settings, the webchat seems to be unable to reflect that change

**Closed** 2021-07-02 19:15 UTC
Labels: P0, Type: Bug
