### ISSUE TITLE
If this problem persists, please file an issue on GitHub Details duplicate file found: topics/TestCards/TestCards.dialog

### ISSUE THREAD

**Issue by fernandofas** [microsoft/BotFramework-Composer#9099] opened 2022-04-04 08:42 UTC
## Browser

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'PVA and open the topics with Bot Framework Composer'
2. Click on 'update'
3. See error

## Expected behavior
 Expecting the PVA to be imported into BFC

## Additional context

This error just came out of the blue as everything was working previously.

**Comment by ramfattah** [comment] 2022-04-04 17:55
Hello @fernandofas, I'm investigating this.

**Comment by ramfattah** [comment] 2022-04-04 22:37
Hey @fernandofas,

I'm not able to reproduce. I imported PVA topics into composer without issues.
![image](https://user-images.githubusercontent.com/38049078/161642226-0bc39735-f81c-4d5e-a520-bff1a95304dc.png)

#

You might have a duplicate file in your bot, based on the error message. Have you had a chance to look into that?

**Comment by ramfattah** [comment] 2022-04-06 00:12
@fernandofas any updates?

**Comment by fernandofas** [comment] 2022-04-07 11:45
Yes, I had to delete the topic locally and after that when I opened again on Bot Framework Composer it went through.
I guess the Bot Framework Composer didn't update and threw an error.

**Comment by ramfattah** [comment] 2022-04-07 16:10
Glad you were able to solve the issue. I'm closing this one for now. Please re-open if needed.

**Closed by ramfattah** 2022-04-07 16:10 UTC
Labels: customer-reported, Bot Services
