### ISSUE TITLE
Orchestrator trigger docs link goes to LU page

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6167] opened 2021-03-03 23:46 UTC
## Describe the bug

The documentation in the editor pane leads to the LU file docs, even when we're editing an Orchestrator recognizer that uses different syntax.

## Version

1.3.1-nightly.219296.61c944a

## To Reproduce

1. Make a new bot
2. Install the Orchestrator plugin
3. Create a new "Intent recognized" trigger
4. Write invalid syntax into the editor

## Expected behavior

Documentation about Orchestrator intents should not lead to the LU file format, but to a page explaining how that syntax works.

## Screenshots

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/61990921/109887778-38079a80-7c37-11eb-839f-3b816d85cedd.png)

**Comment by cwhitten** [comment] 2021-03-05 01:25
@scheyal assigning to you. The issue is that Orchestrator does not support the complete syntax of the .lu file format and it isn't explained well.

**Comment by scheyal** [comment] 2021-03-08 16:56
We need to redirect LU learn more link to an intermediate page that explains Orchestrator limitations and LU processing, with a further link to the original LU explanation.

**Comment by scheyal** [comment] 2021-03-08 19:57
Could add this section somewhere:

https://github.com/microsoft/botframework-sdk/blob/scheyal/sdk/Orchestrator/docs/LUFormat.md

**Comment by scheyal** [comment] 2021-03-08 22:02
LU syntax is the same for Orchestrator. It simply ignores entities. We'll add some text to that effect, but we need uber description about when, how to use Orchestrator (docs exist, need to find how to surface this in Composer). 
Not R12.

**Comment by boydc2014** [comment] 2021-04-01 15:04
Are we clear about the actionable items for this ticket? @scheyal @taicchoumsft is it just refining a doc and correctly pointing to that doc, or this ticket indicate changes in the validation process?

**Comment by taicchoumsft** [comment] 2021-05-26 15:54
This ticket was closed as part of #7362 .

**Closed by taicchoumsft** 2021-05-26 15:54 UTC
Labels: Area: Orchestrator, P1, R12 Bugbash, Type: Bug
