### ISSUE TITLE
[Accessibility][Visual Requirement-Create from template]: Luminosity ratio of all templates within 'Create from template' is less than 4.5:1.

### ISSUE THREAD

**Issue by ShellySoni** [microsoft/BotFramework-Composer#2177] opened 2020-03-05 12:33 UTC
**User Experience:**
Users with low vision or sensitive to low luminosity ratio colors would be impacted as the visibility of templates is less than the standard luminosity ratio of 4.5:1.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Navigate on homepage with tab key up to 'New' button and press enter on it.
3. 'Create from scratch' pop up will open.
4. Select 'Create from Template' radio button and then press tab key to land on its first template i.e. Echo bot.
5. Observe the CCA with color contrast analyzer and find the issue.

**Actual:**
Luminosity ratio of all templates within 'Create from template' is less than 4.5:1.

**Expected:**
Luminosity ratio should be >=4.5:1 for all templates within 'Create from template'.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BA78189A8-A3DC-42C4-A464-A051EBBBD5DF%7D&file=Guideline%2017A%20-%20Contrast%20(Minimum)%20When%20Conveying%20Information.docx&action=default&mobileredirect=true

**Attachment:**
[MAS1.4.3_Create From template.zip](https://github.com/microsoft/BotFramework-Composer/files/4292931/MAS1.4.3_Create.From.template.zip)

**Comment by corinagum** [comment] 2020-03-05 18:32
Can we get the attachments added in? Thank you.

**Comment by Padmini171991** [comment] 2020-03-06 11:48
![MAS1 4 3_Create From template](https://user-images.githubusercontent.com/60918692/76081080-5f00a180-5fce-11ea-9fd6-1f3c84dcf172.png)

Attaching screenshot here. Somehow the zip file got dragged on top of User Experience.

**Comment by corinagum** [comment] 2020-03-06 17:53
@Padmini171991 oops, I see it now, thank you!. Moved it to bottom of the post.

**Comment by DesignPolice** [comment] 2020-03-17 22:07
Thanks for the Tag @corinagum, I was wondering when this one would come up. It is a hack of a old design, that was altered just to get things moving. Let me find out if they want to alter the hack, or implement an actual fix that we have.

I will touch back ASAP

**Comment by corinagum** [comment] 2020-03-17 22:16
Related to #1728 , so there will probably be a decent amount of discussion before a spec is ready.

**Comment by DesignPolice** [comment] 2020-03-17 22:18
Thanks Corina - @cwhitten and @mareekuh - Lets talk about this in Stand Up today if we have time or we have someone waiting to fix it.

**Comment by corinagum** [comment] 2020-03-18 04:12
@DesignPolice roger that, will do. Thanks for checking up!

**Comment by awalia13** [comment] 2020-04-07 23:07
Hi Corina ,We will validate this bug and share update asap.

**Comment by ashish315** [comment] 2020-04-08 08:23
As checked, still the issue is not fixed.

**Comment by corinagum** [comment] 2020-04-08 19:37
I have done a fresh build of Composer and verified this fix. Please re-verify on your side.

**Comment by ashish315** [comment] 2020-04-09 11:28
@corinagum Checked on the latest build and the issue is resolved. So, HCL is closing the issue.
Current CCA result-
Foreground:#000000
Background:#EBEBEB

The contrast ratio is: 17.6:1

**Closed by ashish315** 2020-04-09 11:28 UTC
Labels: A11yCT, A11yMAS, A11yMediumImpact, Accessibility, Fixed, HCL- BotFrameworkComposer, MAS1.4.3, Severity3
