### ISSUE TITLE
go back to trigger when selecting action

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#5421] opened 2020-12-30 08:01 UTC
## Describe the bug

go back to trigger when selecting action

## Version

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Clone this bot https://github.com/microsoft/botframework-components/tree/preview-build2020-test/skills/declarative/todoskill
2. Open it
3. Go to MarkToDo and select action in the middle of the flow

## Expected behavior

Do not go back

## Screenshots

https://recordit.co/5hjp2CwKft

**Comment by anusharavindrar** [comment] 2021-01-09 00:15
@xieofxie, let me attempt a repro on my end and update the thread accordingly.

**Comment by anusharavindrar** [comment] 2021-01-12 17:53
@xieofxie, able to reproduce the issue on my end. When I go to MarkToDo and click on an action in the middle of the flow, it redirects me back to the MarkToDo. 
@hibrenda, any idea what might be causing this issue?

**Comment by yeze322** [comment] 2021-02-04 08:14
@anusharavindrar @xieofxie There is a invalid action id with `-` in it. You can fix it by **editing the action id manually**.

See my screenshot:
![image](https://user-images.githubusercontent.com/8528761/106863394-7034bf80-6703-11eb-9a0b-60861be0af76.png)

I'm curious about how this id format is generated? The char `-` is not in the id dictionary.

**Comment by yeze322** [comment] 2021-02-04 08:15
Id generator soure code:
https://github.com/microsoft/BotFramework-Composer/blob/270e0f306e7472cdfe529623e7c83a7e844e3284/Composer/packages/lib/shared/src/generateUniqueId.ts#L9

**Comment by yeze322** [comment] 2021-02-04 08:17
I found the id is generated 10 months ago, close this issue because newly created bot in Composer won't run into this case.

**Closed by yeze322** 2021-02-04 08:17 UTC
Labels: Team: Authoring, Type: Bug, customer-reported
