### ISSUE TITLE
"Connect to QnA Knowledgebase" action returns 500 error on all calls

### ISSUE THREAD

**Issue by abhaycashikar** [microsoft/BotFramework-Composer#8038] opened 2021-06-09 16:55 UTC
## Describe the bug

My team has an existing QnA Maker knowledge base that we'd like to use with our v4 bot. I added the "Connect to QnA Knowledgebase" action from the "Access external resources" menu to an intent, but when the bot attempts to query the knowledge base it returns a 500 (Internal Server Error) error code.

## Version

Release: 2.0.0
I could not find a build SHA on the About page. See the below screenshot:
![image](https://user-images.githubusercontent.com/43579092/121395129-af745680-c917-11eb-967e-49f49e10939c.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open the Electron distribution of Bot Framework Emulator on a Windows PC.
2. Create a bot (or open an existing one).
3. Add the "Connect to QnA Knowledgebase" action to an intent that is run after the user sends a message.
4. Follow [the directions in the documentation](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x) to configure `appsettings.json` with the correct knowledge base ID and hostname.
5. Run the bot.
6. Type a question that would be routed to the existing QnA Maker knowledge base.

## Expected behavior

The bot responds with the respective answer in the QnA Maker knowledge base, or uses the fallback answer if no suitable answer is found.

## Screenshots

![image](https://user-images.githubusercontent.com/43579092/121396090-a33cc900-c918-11eb-85bd-1044f1370989.png)
"Hello" is one of the responses from the ChitChatDialog KB, which works as expected. "what is autori" has a proper response in our QnA Maker KB (verified using cURL), but that is not being propagated to the bot. There are also no errors or warnings in the debug window (I referenced [this issue](https://github.com/microsoft/BotFramework-Composer/issues/7967#issuecomment-854919866) to turn on the debug flag).

## Additional context

QnA Maker knowledge bases created from within the application (for example, the standard ChitChatDialog KB) seem to work perfectly fine.

**Comment by abhaycashikar** [comment] 2021-06-10 17:21
I should mention that I've found a workaround for the time being, which is using the "Send an HTTP request" action and filling in the body, header, etc. with the appropriate data (found in the online settings for the QnA Maker KB). I can then extract the answer provided by QnA Maker from the `turn.results` variable using the expression `turn.lastresult.content.answers[0].answer`. Obviously this isn't the ideal solution, but for anyone that is in need of this functionality immediately, this will work!

**Comment by dmvtech** [comment] 2021-06-15 18:01
Hi @abhaycashikar. This is interesting. I'm able to get it working without issue. Is your chitchat KB live/remote as well? In other words, are you only accessing existing/live/remote KBs and have nothing created from Composer?

**Comment by abhaycashikar** [comment] 2021-06-17 23:44
The chitchat KB was created by Composer when I chose the Core Bot template so I didn't have any control over that. I believe it did make a resource in my QnA Maker subscription though.

P.S. my team has moved on from Composer for various other reasons and is now using the .NET SDK, so this isn't blocking for us anymore (just in case there is more pressing work to be done for Composer).

**Comment by dmvtech** [comment] 2021-06-18 18:31
Thank you @abhaycashikar. I will go ahead and close this as I am unable to reproduce this. If this becomes an issue again, please comment or open a new issue.

**Closed by dmvtech** 2021-06-18 18:31 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported
