### ISSUE TITLE
[adaptive-flow] Begin Skill action is not rendering correcting in the Visual Editor

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#8253] opened 2021-07-02 17:04 UTC
## Describe the bug
Begin Skill action is not rendering correctly in the Visual Editor. See screenshot below. 

## Version
Latest nightly 

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a 'Begin Skill' action

## Screenshots
![image](https://user-images.githubusercontent.com/17039790/124307255-caa44180-db24-11eb-8b78-5a057317cc01.png)

**Comment by srinaath** [comment] 2021-07-03 16:39
@a-b-r-o-w-n Im seeing this bug post https://github.com/microsoft/BotFramework-Composer/pull/8191 merge of the Comments work. Could you take a look at this regression?

**Comment by a-b-r-o-w-n** [comment] 2021-07-06 17:06
@srinaath @cwhitten I'd like to get your thoughts on this. There is a "bug" in the ui schema for this component that just happened to work with the implementation before #8191. I'm investigating if its possible to address the regression without modifying the ui schema, but I'm not making much progress.

There is a naming collision in the schema with the `colors.theme` property. This value is being used to support the note action UI, but because the BeginSkill schema is malformed, the colors are being passed to the wrong components. The simplest fix for this release might be to revert the changes that enable setting a background color on the card and fixing the schemas.

**Closed** 2021-07-06 20:18 UTC
Labels: Area: Visual editor, P0, Team: Authoring, Type: Bug
