### ISSUE TITLE
Internal Server Error 500 from Web Chat, probably firewall issue

### ISSUE THREAD

**Issue by snbuchholz** [microsoft/BotFramework-Composer#8777] opened 2021-11-05 11:39 UTC
## Describe the bug

After clicking "Open Web Chat" with standard "Empty Bot" template (and others), I get in Electron:
```
[11:14:41 AM]POST201/v3/conversations
[11:14:42 AM]POST500/v3/directline/conversations/c0e7bb7d-eff9-41d1-aa9b-de837ec4cea6%7Clivechat/activities
An error occurred posting activity to the bot. Internal Server Error
```
in Chrome/Firefox
```
POST http://localhost:5001/v3/directline/conversations/daac9a83-2eae-4c6c-9d7d-f54a3bec4d89%7Clivechat/activities 500 (Internal Server Error) 
```
and in the console with ```DEBUG=composer'*'```:
```
GET /api/publish/14829.393574961314/status/default/37648115-d7a3-4071-977e-f4ce37fd1a4d 200 37.735 ms - 84
  composer:bot-project Schemas directory found. +396ms
  composer:bot-project Customized SDK schema found +2ms
  composer:bot-project UI Schema found. +2ms
PUT /api/projects/14829.393574961314/files/appsettings.json 200 40.403 ms - 34
POST /v3/conversations 201 0.582 ms - 302
  composer:extensions:localpublish:17974 fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.SetSpeakMiddleware.<>c__DisplayClass3_0.<<OnTurnAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.CoreBotAdapter.<.ctor>b__0_0(ITurnContext turnContext, Exception exception)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.ProcessActivityAsync(AuthenticateRequestResult authenticateRequestResult, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.CloudAdapterBase.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpResponse, IBot bot, CancellationToken cancellationToken)
   at Empty_2.Controllers.BotController.PostAsync(String route) in /Users/s.buchholz/BotFrameworkComposer/Empty_2/Empty_2/Controllers/BotController.cs:line 67
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
 +7s
POST /v3/directline/conversations/58fa9f2e-d3fc-4b8c-b372-4e455a12e426|livechat/activities 500 988.940 ms - 105
```

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [x] macOS Monterey 12.0.1 (x86)
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Home' "Welcome to Bot Framework Composer"
2. Click on 'Create New'
3. Use default C# "Empty Bot" template
4. Click on "Next"
5. Click on "Create"
5. Click on "Start bot"
6. Click on "Open Web Chat"

## Expected behavior

Bot should have said "Welcome to your bot"

## Screenshots

![image](https://user-images.githubusercontent.com/2370438/140502735-abec2b2d-8120-4e42-b87f-780fcdc3c581.png)

## Additional context

I had existing bots which all used to work and now show the same error. I think the problem started after upgrading from MacOS Catalina to Monterey. All bots still work in the Emulator. Have updated node.js and .NET versions, made no difference. I notice someone else's (working!) bot on MacOS Catalina is using localhost:5000 instead of localhost:5001 out of the box. Not sure whether that's relevant...

**Comment by anishprasad01** [comment] 2021-11-05 18:50
Hi @snbuchholz,

Let's get a few clarifying things out of the way so we can narrow down the problem. Can you confirm a couple of things for me?

- Does the bot function when run outside of composer, for example by running the bot from the command line with a command such as `dotnet run --project Test.csproj`?
- Are the App ID and App Password fields either both filled or both empty?

**Comment by snbuchholz** [comment] 2021-11-05 20:39
> Does the bot function when run outside of composer, for example by running the bot from the command line with a command such as dotnet run --project Test.csproj?

There's a warning:

> $ dotnet run --project Empty/Empty/Empty.csproj
warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:3978

but no error when then testing the bot in the Emulator.

> Are the App ID and App Password fields either both filled or both empty?

both empty:
![image](https://user-images.githubusercontent.com/2370438/140575451-b7331e19-d352-4a36-a71f-18140ed6c90b.png)

**Comment by anishprasad01** [comment] 2021-11-09 23:51
> I notice someone else's (working!) bot on MacOS Catalina is using localhost:5000 instead of localhost:5001 out of the box. Not sure whether that's relevant...

So it's actually the Composer application itself that's running on port 5000. MacOS Monterey added an AirPlay component that claims port 5000, so your Composer is using port 5001 instead. The bot itself is actually on a different port. You saw this when you ran the bot outside composer. The bot was `Now listening on: http://localhost:3978`.

I have a couple more ideas we can try:
- Try to reinstall Composer. 
- Double-check firewall settings for Composer.

**Comment by witawatd** [comment] 2021-11-12 00:29
> > I notice someone else's (working!) bot on MacOS Catalina is using localhost:5000 instead of localhost:5001 out of the box. Not sure whether that's relevant...
> 
> 
> 
> So it's actually the Composer application itself that's running on port 5000. MacOS Monterey added an AirPlay component that claims port 5000, so your Composer is using port 5001 instead. The bot itself is actually on a different port. You saw this when you ran the bot outside composer. The bot was `Now listening on: http://localhost:3978`.
> 
> 
> 
> I have a couple more ideas we can try:
> 
> - Try to reinstall Composer. 
> 
> - Double-check firewall settings for Composer.
> 
> 
> 
> 
> 
> 

I do have the same problem with my M1 MacBook (MacOS Monterey), but it works fine on my Intel MacBook with the same MacOS. It is confirmed that the issue come from the composer's Web chat running on port 5000 conflicting with AirPort. My workaround is to use Bot Framework Emulator on MacOS Monterey which running on different ports.

I hope this helps.

**Comment by anishprasad01** [comment] 2021-11-12 00:32
@witawatd 

Composer actually does not support M1 at this time.

**Comment by snbuchholz** [comment] 2021-11-12 09:41
For information, I have 2.6 GHz 6-Core Intel Core i7

> It is confirmed [ that the issue come from the composer's Web chat running on port 5000 conflicting with AirPlay's port.]

@witawatd Could you please add a link/information who confirmed this when/how? @anishprasad01's answer suggests this is already fixed in my version by Composer using 5001 instead...

> I have a couple more ideas we can try:
> - Try to reinstall Composer.
> - Double-check firewall settings for Composer.

Thank you @anishprasad01! I had already tried reinstalling, made no difference. The firewall is a more promising lead, it seems to be very restrictive (since the upgrade?) and won't even let me check details. Waiting for IT to fix that. Another colleague on Monterey has less restrictive firewall settings and ran the "Empty" bot template on WebChat without the issue.

Should I update the ticket's title?

**Comment by anishprasad01** [comment] 2021-11-12 19:03
If you'd like to, feel free. It looks like this issue is more of a firewall thing and less to do with Composer itself, but I'll leave this issue open for a few days while you get your firewall sorted out with your IT department.

**Comment by witawatd** [comment] 2021-11-12 19:33
> For information, I have 2.6 GHz 6-Core Intel Core i7
> 
> 
> 
> > It is confirmed [ that the issue come from the composer's Web chat running on port 5000 conflicting with AirPlay's port.]
> 
> 
> 
> @witawatd Could you please add a link/information who confirmed this when/how? @anishprasad01's answer suggests this is already fixed in my version by Composer using 5001 instead...
> 
> 
> 
> > I have a couple more ideas we can try:
> 
> > - Try to reinstall Composer.
> 
> > - Double-check firewall settings for Composer.
> 
> 
> 
> Thank you @anishprasad01! I had already tried reinstalling, made no difference. The firewall is a more promising lead, it seems to be very restrictive (since the upgrade?) and won't even let me check details. Waiting for IT to fix that. Another colleague on Monterey has less restrictive firewall settings and ran the "Empty" bot template on WebChat without the issue.
> 
> 
> 
> Should I update the ticket's title?

@snbuchholz I just got it sorted out myself after changing to test my bot on Bot Framework emulator application instead. The issue is gone for my case, and it works flawlessly so far. I just assume that running Composer Web chat on localhost:5000 causing the issue since the emulator app runs on different port.

**Comment by snbuchholz** [comment] 2021-11-15 12:42
@anishprasad01 Regardless of whether I can fix my firewall, an unhandled 403 'Forbidden' triggering a 500 'Internal Server Error' is a bug though, isn't it? 

"An unhandled exception has occurred while executing the request.
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'"
"An error occurred posting activity to the bot. Internal Server Error"

**Comment by JonathanFingold** [comment] 2021-11-23 18:43
I too am seeing this error, just for a root bot. I'll add some details as I put together a repro case.

**Comment by anishprasad01** [comment] 2021-11-23 18:46
@JonathanFingold 

For the same system configuration?

**Comment by JonathanFingold** [comment] 2021-11-23 18:57
Here's my config and my repo case...

Composer:
> Version:  2.1.1-nightly.277423.f426bba  
> Electron: 8.2.4  
> Chrome: 80.0.3987.165  
> NodeJS: 12.13.0  
> V8: 8.0.426.27-electron.0

OS:
> Edition	Windows 10 Pro  
> Version	21H1  
> Installed on	‎8/‎31/‎2021  
> OS build	19043.1320  
> Experience	Windows Feature Experience Pack 120.2212.3920.0

Repro:
1. Create an echo bot from the template.
    - Test it in Web Chat. It works fine. (I enabled it for private and domain networks.)
1. Now add a bot (local skill). Again just use the echo bot.
    - Let Composer add Orchestrator to the root bot.
    - Doing nothing else, start all bots again.
    - Enable the "skill" bot to run on private and domain networks.
    - Open the root bot in Web Chat. It now fails with a HTTP 500 on the conversation update activity.

Running the root bot locally and testing it in the Emulator, I get the following exception, which seems to indicate Composer has added something to the root bot that causes an authentication error.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'Void Microsoft.Bot.Connector.Authentication.PasswordServiceClientCredentialFactory..ctor(System.String, System.String, System.Net.Http.HttpClient, Microsoft.Extensions.Logging.ILogger)'.
   at Microsoft.Bot.Builder.Integration.AspNet.Core.ConfigurationServiceClientCredentialFactory..ctor(IConfiguration configuration, HttpClient httpClient, ILogger logger)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.ConfigurationBotFrameworkAuthentication..ctor(IConfiguration configuration, ServiceClientCredentialsFactory credentialsFactory, AuthenticationConfiguration authConfiguration, IHttpClientFactory httpClientFactory, ILogger logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Extensions.ServiceCollectionExtensions.<>c.<AddBotRuntime>b__0_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by anishprasad01** [comment] 2021-11-23 20:43
I was able to reproduce this issue following the steps outlined by @JonathanFingold. There does seem to be a missing package issue relating to the addition of the Orchestrator into a Composer bot. There is a [class related to Authentication](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.authentication.passwordserviceclientcredentialfactory?view=botbuilder-dotnet-stable) that appears to be missing when running the bot, and its host package is not available to install in the Package Manager. This issue does not seem to occur in bots that do not use Orchestrator (such as the skill bot itself).

The skill bot being consumed functions normally, so the issue appears to be localized to the root bot. I attempted to replicate this error on Node v12.30 and v 14.x and in both cases the error occurred. Downgrading the Orchestrator package to 4.14.1 also did not fix the issue. Other packages commonly found in other bots, such as Welcome or HelpAndCancel, also did not contain this missing package.

I am reassigning this issue for further investigation, as no immediate workarounds appear to be available.

**Comment by aaronba** [comment] 2021-11-24 06:02
I ran into this issue with a .NET Core Empty bot as soon as you try to call another bot Skill. (and add the Orchestrator package through the UI)

**Comment by JonathanFingold** [comment] 2021-11-24 16:57
Perhaps this is part of the problem. Orchestrator seems to only have a 4.15 version, but the current release of Composer is still running on top of the 4.14 SDK.

![image](https://user-images.githubusercontent.com/35047199/143281952-36df6779-4ff7-4989-997e-252677960fe6.png)

**Comment by JonathanFingold** [comment] 2021-11-24 17:04
Yep, downgrading Orchestrator to 4.14.4 fixes the root bot.

We've seen a similar issue with other packages. Can't Composer account for this in some much more sane way?

**Comment by anishprasad01** [comment] 2021-11-24 17:45
Can confirm, works on 4.14.1 as well. Additionally, the documentation for this class specifies that it's part of SDK 4.14. Perhaps that's part of it as well.

**Comment by aaronba** [comment] 2021-11-24 18:06
Confirmed that this works for .NET Core bot as well.  However, even if you have 4.14 installed, the UI that adds Orchestrator support when you add another Bot upgrades it to a non-working 4.15 version.  And you need to back out 4.15 and install 4.14 again to get it to work.

**Comment by daveta** [comment] 2021-12-03 16:49
Hi Folks,
Yes, if you're editing a 4.14 solution there's an issue where the incorrect version of the Orchestrator will get installed.  It currently adds the latest version without checking what version of the Bot Framework is being used:
https://github.com/microsoft/BotFramework-Composer/blob/92e6b1be38b712e282e1bdcf2a4427c7cff1cdf5/Composer/packages/client/src/components/AddRemoteSkillModal/helper.ts#L35
 The workaround is what you identified - install the correct version.  We'll supplement the docs.
 Thanks

**Comment by gabog** [comment] 2021-12-14 19:08
Hi @snbuchholz closing this one based on the workaround provided by @daveta, feel free to re-open if you are still experiencing issues.

**Closed by gabog** 2021-12-14 19:08 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Type: Documentation, Needs-triage, Doc Impact, type: docs

**Comment by dluc** [comment] 2022-04-19 00:37
Not sure about the versioning problem mentioned later in the thread, however, I was having the same problem on MacOS and I solved it my turning off "AirPlay Receiver" in Settings->Sharing. After restarting Composer, the app started using port 5000 as expected (before it was using 5001). Aside from the versioning problem, it would be nice if composer worked with dynamic ports, and avoid conflicts with specific OS ports, e.g. detect which port is in use rather than assume it's 5000.

**Comment by davidmw** [comment] 2022-05-17 02:11
> Not sure about the versioning problem mentioned later in the thread, however, I was having the same problem on MacOS and I solved it by turning off "AirPlay Receiver" in Settings->Sharing. After restarting Composer, the app started using port 5000 as expected (before it was using 5001). Aside from the libs versioning problem, it would be nice if Composer worked with dynamic ports, and avoid conflicts with specific OS ports, e.g. detect which port is in use rather than assume it's 5000.

Struggling with the same problem on MacOS - and @dluc's suggestion worked for me (thanks!).

**Comment by anotherRedbeard** [comment] 2022-05-19 18:17
> > Not sure about the versioning problem mentioned later in the thread, however, I was having the same problem on MacOS and I solved it by turning off "AirPlay Receiver" in Settings->Sharing. After restarting Composer, the app started using port 5000 as expected (before it was using 5001). Aside from the libs versioning problem, it would be nice if Composer worked with dynamic ports, and avoid conflicts with specific OS ports, e.g. detect which port is in use rather than assume it's 5000.
> 
> Struggling with the same problem on MacOS - and @dluc's suggestion worked for me (thanks!).

This also worked for me...thanks @dluc!

**Comment by encounter12** [comment] 2022-07-16 06:24
> Not sure about the versioning problem mentioned later in the thread, however, I was having the same problem on MacOS and I solved it by turning off "AirPlay Receiver" in Settings->Sharing. After restarting Composer, the app started using port 5000 as expected (before it was using 5001). Aside from the libs versioning problem, it would be nice if Composer worked with dynamic ports, and avoid conflicts with specific OS ports, e.g. detect which port is in use rather than assume it's 5000.

@dluc 's solution also worked for me. Thank you very much!

Found issue:

Change hardcoded port from 5000 to some number not reserved #9198 

@anishprasad01  @gabog Please, move the solution from nightly build into new stable Composer version and release it at your earliest convenience. This is causing headaches for Composer's MacOS users. Thank you in advance!

**Comment by OEvgeny** [comment] 2024-02-08 04:29
The latest Composer nightly supports dynamic port allocation. Please use it and report issues if any
