### ISSUE TITLE
Click Settings page shows "Data loading"

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#4679] opened 2020-11-05 00:31 UTC
## Describe the bug

Create a new bot and select **Settings** from Composer menu. The Settings page shows Data loading.
The "Data loading" will disappear after clicking any settings (Bot Settings / Application Settings / ...) in the navigation.

## Version

Composer version: [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## To Reproduce

1. Create a bot
2. Select Settings from the menu
3. See error

## Expected behavior

Should not show "Data loading"

## Screenshots

![image](https://user-images.githubusercontent.com/32497439/98182659-2c8ba900-1ebb-11eb-9ca8-5db91d6482a9.png)

## Additional context

The "Data loading" will disappear after clicking any settings (Bot Settings / Application Settings / ...) in the navigation.

**Comment by cwhitten** [comment] 2020-11-05 00:41
this is a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/4639

**Closed by cwhitten** 2020-11-05 00:41 UTC
Labels: Needs-triage, Type: Bug
