### ISSUE TITLE
Getting error in bot framework composer while creating bot from templates.

### ISSUE THREAD

**Issue by Naveen0687** [microsoft/BotFramework-Composer#8159] opened 2021-06-22 03:47 UTC
I am getting this error while creating bot from templates.

![Capture](https://user-images.githubusercontent.com/29903786/122860051-a2edf600-d33a-11eb-99af-1d893c0df70b.JPG)

please let me know the fix for this.

**Comment by srinaath** [comment] 2021-06-22 16:43
We are tracking this bug in another ticket @Naveen0687 
Closing as dupe of #7876

**Closed by srinaath** 2021-06-22 16:43 UTC
Labels: Bot Services, Needs-triage, customer-reported
