### ISSUE TITLE
Uncaught SyntaxError when setting Allow Interruptions

### ISSUE THREAD

**Issue by mikhailgithub** [microsoft/BotFramework-Composer#8464] opened 2021-07-24 14:06 UTC
## Describe the bug

Trying to open Allow Interruptions dropdown in a dialog, getting this error:

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '#root[6hyB6Y].allowInterruptions-list2' is not a valid selector.

## Version

v2.1.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a dialog
2. Click on 'Prompt for text' --> Other --> Prompt Configurations
3. Click on Allow Interruptions dropdown

**Comment by taicchoumsft** [comment] 2021-07-26 18:06
@srinaath , can you repro this?

**Comment by tonyanziano** [comment] 2021-07-27 17:15
Closing as a dupe of #8455 and #8474 -- please see #8474 for an explanation of the underlying issue.

**Closed by tonyanziano** 2021-07-27 17:15 UTC
Labels: Bot Services, Needs-triage, Type: Bug, customer-reported
