### ISSUE TITLE
Login fails in Composer 2.1.1. (Application doesn't support cloud environment)

### ISSUE THREAD

**Issue by PeterPekanovics** [microsoft/BotFramework-Composer#9097] opened 2022-04-04 00:25 UTC
Login was working fine a couple of days ago, but now, I get the following error:
![image](https://user-images.githubusercontent.com/100796571/161455654-8864805b-79be-4f06-8375-eebf4f5646ee.png)
## Version
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows 10

Admins haven't changed anything, and login works on other machines with the same account, but different Composer versions.

**Comment by ramfattah** [comment] 2022-04-04 17:49
Hi @PeterPekanovics, 

What operating system are you using when faced with this error? 
#


> login works on other machines with the same account, but different Composer versions.

May I ask which versions of composer worked?

**Comment by PeterPekanovics** [comment] 2022-04-04 18:02
Hi @ramfattah Thanks for replying.
Edited the question to include OS information.
Logging in works fine on MacOS, using Composer version 2.1.2. (haven't tried 2.1.1. on MacOS).
Using 2.1.2. on Windows yields a different error ([issues/8974](https://github.com/microsoft/BotFramework-Composer/issues/8974))

**Comment by ramfattah** [comment] 2022-04-07 04:00
Hey @PeterPekanovics 

Could you please run Composer in debug mode using the following directions, then sign in again to reproduce the failure. Then send the output of the debugging console window.

1) Completely close Composer if already open
2) Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
3) Open a terminal in that directory
4) run set DEBUG=composer*
5) run the executable from the terminal Ex. `Bot Framework Composer.exe`


We will take a look at the log to see what is the cause of this issue. 
Let me know if you have any questions. Thanks.

**Comment by PeterPekanovics** [comment] 2022-04-07 22:54
@tonyanziano Seems like the commands aren't working, I'm getting the same screen after running the commands provided by @ramfattah in Powershell (I'm running Powershell as an administrator)
![image](https://user-images.githubusercontent.com/100796571/162332521-4ddbd370-ad6a-4ee9-92ee-1717d506a8ea.png)

**Comment by PeterPekanovics** [comment] 2022-04-07 22:58
@tonyanziano Is this information helping? I'm getting it from Composer directly
Correlation Id: d8351068-547a-48ba-97f2-a90ad5e26505
Timestamp: 2022-04-07T22:57:25.000Z
DPTI: f10b44d68977c7156b18051ece8da9a46098090975dd5243fb5f1da29fdba81d

**Comment by ramfattah** [comment] 2022-04-08 02:39
Hey @PeterPekanovics 

I noticed when I used PowerShell, I did not see prefix `composer:____` aswell. 

When I switched my terminal to Windows CMD, and [enable debug from the above steps](https://github.com/microsoft/BotFramework-Composer/issues/9097#issuecomment-1091054098), I can see the prefix `composer:____`.

#

Enabled debugging in Windows Command Prompt:
![image](https://user-images.githubusercontent.com/38049078/162351731-3b80be0e-067e-4829-a8f4-f0ac9fce9562.png)


Output:
![image](https://user-images.githubusercontent.com/38049078/162351804-55d7ef75-8ee5-417b-a334-3fbfc2d5c2e0.png)


Could you please try to enable debugging, this time perhaps with a Windows command prompt? Thanks.

**Comment by ramfattah** [comment] 2022-04-08 02:46
Also, updated the steps to enable debugging, in our above discussion.

**Comment by PeterPekanovics** [comment] 2022-04-08 13:33
Hi @tonyanziano @ramfattah , ran the logs again, here are the results (I think that only the last lines are relevant, correct me if I'm wrong)
```
POST /api/assets/projectTemplates 200 1003.577 ms - -
2022-04-08T13:30:55.185Z composer:electron:one-auth PII logging enabled: false
2022-04-08T13:30:55.186Z composer:electron:one-auth Attempting to load oneauth module from C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\oneauth.
2022-04-08T13:30:55.239Z composer:electron:one-auth Initializing...
OneAuth Version 1.15.0 (com.microsoft.BotFrameworkComposer)
2022-04-08T13:30:55.246Z composer:electron:one-auth Service initialized.
2022-04-08T13:30:55.246Z composer:electron:one-auth Logging user into ARM...
2022-04-08T13:30:55.371Z composer:electron:one-auth 4 [MSAL]    INFO    Startup:59      Starting up MSAL
2022-04-08T13:30:55.371Z composer:electron:one-auth 4 [MSAL]    INFO    AddConfiguration:134    Created a new public client application with ID ''
2022-04-08T13:30:55.372Z composer:electron:one-auth 4 OneAuth Version 1.15.0 (com.microsoft.BotFrameworkComposer)
[OneAuth:Error:9zj76:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] (Code:124) Account hint is an email address from an AAD domain that is in a sovereignty/cloud/environment that is not configured for this app.  MSA is configured for this app.
[OneAuth:Error:9zj76:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] (Code:124) Account hint is an email address from an AAD domain that is in a sovereignty/cloud/environment that is not configured for this app.  MSA is configured for this app.
[OneAuth:Error:9vdpp:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] Unexpected error code: 124
[OneAuth:Error:9vdpp:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] Unexpected error code: 124
2022-04-08T13:31:10.176Z composer:electron:one-auth 2 [OneAuth:Error:9zj76:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] (Code:124) Account hint is an email address from an AAD domain that is in a sovereignty/cloud/environment that is not configured for this app.  MSA is configured for this app.
2022-04-08T13:31:10.176Z composer:electron:one-auth 2 [OneAuth:Error:9vdpp:bdcf52d2-56b5-4173-9d07-2f3d2d808e12] Unexpected error code: 124
```
Thanks

**Comment by tonyanziano** [comment] 2022-04-12 21:32
I went ahead and forwarded this to the OneAuth team (maintainers of the authentication library we use). I will wait to hear back what they say.

**Comment by ramfattah** [comment] 2022-04-13 17:26
Thank you @tonyanziano

**Comment by tracyboehrer** [comment] 2022-04-18 18:07
@tonyanziano Any update on this?

**Comment by tonyanziano** [comment] 2022-04-18 18:11
I have not heard anything back, I will ping them again.

**Comment by tonyanziano** [comment] 2022-04-21 17:46
It's possible that there might have been a breaking API change with a newer version of OneAuth that went unnoticed in our code due to the way we ingest the OneAuth library and types.

I need to investigate a little deeper but I haven't had time due to other commitments. I will get around to it as soon as I can and provide further updates here.

**Comment by PeterPekanovics** [comment] 2022-04-21 19:30
Thanks for the news.

**Comment by PeterPekanovics** [comment] 2022-04-27 00:43
Hi @tonyanziano any update on this?
The issue is gone, now I can log in again, without any problems (at least on Composer version 2.1.1.).
No idea what fixed it, nothing has changed on my side, so I'm a bit reluctant to close this issue, as it may come back randomly anytime.

**Comment by msomanathan** [comment] 2022-04-27 18:10
@tonyanziano Could you please let us know if the issue would recur?

**Comment by tonyanziano** [comment] 2022-04-27 18:24
Hey @PeterPekanovics and @msomanathan ,

That's very odd that the issue just happened to go away, we have not made any changes either AFAIK.

I haven't gotten around to investigating just yet, but I'm going to keep this open until I get a chance to look into it.

**Comment by tonyanziano** [comment] 2022-05-13 17:41
Just looked into this to see if we are calling the OneAuth APIs incorrectly like the OneAuth team suggested, and it appears that the types for the call signatures are all in order. No further updates as of yet.

**Comment by johnataylor** [comment] 2022-05-20 18:23
closing, please reopen if the problem comes back

**Closed by johnataylor** 2022-05-20 18:23 UTC
Labels: Type: Bug, customer-reported, Bot Services
