### ISSUE TITLE
LUIS Rate Limit Error

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4392] opened 2020-10-15 14:48 UTC
## Describe the bug
Publishing the sample ToDoBotWithLuisSample, to which I added 2 intents.

## Version
v1.1.1
Bot Framework Composer
                Version:  1.1.1
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish
2. Click on 'Publish Selected Profile'
3. See error

429 - "{\"error\":{\"code\":\"429\",\"message\": \"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\"}}"

**Comment by cwhitten** [comment] 2020-10-15 16:40
@kdubious it seems like you need to move to a paid-pricing tier of the Luis service. You have a limited amount of Luis apps available to you at the free pricing tirer.

**Comment by cwhitten** [comment] 2020-10-15 16:41
See this comment for more detail https://github.com/microsoft/BotFramework-Composer/issues/3769#issuecomment-675657808

Closing

**Closed by cwhitten** 2020-10-15 16:41 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported

**Comment by kdubious** [comment] 2020-10-15 16:46
@cwhitten I had 10 apps in LUIS, all from this sample bot and from publishing it once. I deleted the 5 that *I think* are created when I test in the emulator. Now I have 5. I am trying to publish to these 5, but I get the same error. Also, I cannot change the LUIS.Authoring to anything other than FREE.

**Comment by kdubious** [comment] 2020-10-15 16:50
@cwhitten now I went back to LUIS (https://www.luis.ai/conversations/applications) and deleted the remaining 5. I get the same error. Do each of these nodes represent an APP?
![image](https://user-images.githubusercontent.com/9756166/96161234-02ab1c00-0ee5-11eb-8cac-b054881e5fae.png)

**Comment by kdubious** [comment] 2020-10-15 16:58
Again, deleted all 5 from LUIS. Published from Composer. Got an error:

400 - "{\r\n \"error\": {\r\n \"code\": \"BadArgument\",\r\n \"message\": \"The source completed without providing data to receive.\"\r\n }\r\n}"

Yet, 5 were created.
Updated the PREDICTION resource for all 5, tried to publish again, failed with 429.
Updated the PREDICTION resource to a PAID level, tried to publish again, failed with 429.

**Comment by dmvtech** [comment] 2020-10-15 19:08
> I get the same error. Do each of these nodes represent an APP?

No, each one is an intent. All should be part of one app. 

I'm not sure why you would still be getting 429 with paid level (unless it takes some time to transition over or something weird like that). My assumption is that maybe it has to do with hitting the [authoring transactions per second limit](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-limits#authoring-resource-limits) _somehow_ (assuredly unintentional).

**Comment by kdubious** [comment] 2020-10-15 19:12
I blew everything away (10 minutes) and created a new set of services with the `provisionCompser.js` script (25 minutes). So far I've been able to develop based off the EchoBot sample and publish with no issues. Not sure if it's a problem with the "TODO with LUIS"
sample. The EchoBot is only creating one "APP" in the Luis.ai site. The "TODO with LUIS" created 5 or so.

**Comment by nitroin** [comment] 2020-10-21 14:44
I'm would like to re-open this issue. We're unable to publish our bot.

No matter what we receive this message:

```
429 - "{\"error\":{\"code\":\"429\",\"message\": \"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\"}}"```

![Screenshot from 2020-10-21 16-41-14](https://user-images.githubusercontent.com/14164969/96735892-52458800-13bc-11eb-916b-7a62080e9688.png)

How can we debug this error?

Cannot understand why, but sometimes we receive this error instead:

```400 - {"error":{"code":"BadArgument","message":"Failed to parse azure account information object object."}}```

**Comment by kdubious** [comment] 2020-10-21 14:47
@nitroin This error happened for me at one point due to the AZ-CLI getting a token from a different subscription... even though I used the same terminal (and I assumed the same subscription) as the one I used to build the services in the first place. See if you can ensure you are getting a token from the right subscription.

**Comment by nitroin** [comment] 2020-10-21 15:00
Thank you @kdubious. Our token seems correct.

```
$ az account get-access-token

AccessToken  ExpiresOn                   Subscription       Tenant      TokenType
-----------  --------------------------  -----------------  ----------  -----------
<token>      2020-10-21 17:38:56.146122  <subscription-id>  <redacted>  Bearer

$ az account list

Name                  CloudName    SubscriptionId     State    IsDefault
--------------------  -----------  -----------------  -------  -----------
<redacted>            AzureCloud   <redacted>         Enabled  False
<redacted>            AzureCloud   <redacted>         Enabled  False
<redacted>            AzureCloud   <redacted>         Enabled  False
<subscription-name>   AzureCloud   <subscription-id>  Enabled  True
```

**Comment by kdubious** [comment] 2020-10-21 15:11
@nitroin I'm grasping at straws, but have you signed in at LUIS.ai, blown away all your apps, and tried to republish?
I ended up bailing on the TODO with LUIS sample, regenerating everything with the script, and starting from the EchoBot sample.

**Comment by nitroin** [comment] 2020-10-21 15:21
Our steps were:
- Remove all the apps/intents from https://eu.luis.ai/ (we are using `westeurope` resources)
- Remove all the resources under the targeted Azure Resource Group
- Wait ~10 minutes (Cosmos DB deletion take a while)
- Recreate all the resources with the provided project script `/scripts/provisionComposer.js`
- Wait ~20 minutes
- Try to deploy the bot

I'll retry again now but looks like a brute force to me and it's mining our confidence to provide a bot using the Composer.

**Comment by nitroin** [comment] 2020-10-23 07:59
In a desperate attempt to have our bot published I tried directly compiling and using Composer from source instead of the electron distribution. Not luck whatsoever.

To repro the issue:

- Checkout `main`
- Build and start Composer
- Start a brand new Bot from template (Todo with LUIS)
- Go to the project folder on disk and provide all the needed Azure resources with `/scripts/provisionComposer.js`
- Provision Azure resources succesfully
- Return to Composer, select the previously created Bot
- Click on the menu "Publish"
- Create a publish profile and provide the json configuration file from `provisionComposer.js`
- Click to "Publish to selected profile"
- Wait

## Expected behavior

Deploy the default ToDo template succesfully.

## Actual behavior

Deploy failed.

## Additional info

Last logs:

```
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":429,\"message\":\"429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\",\"error\":\"{\\\"error\\\":{\\\"code\\\":\\\"429\\\",\\\"message\\\": \\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\"}}\",\"options\":{},\"response\":{\"statusCode\":429},\"stack\":\"StatusCodeError: 429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\\n    at new StatusCodeError (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/errors.js:32:15)\\n    at Request.plumbing.callback (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/plumbing.js:46:31)\\n    at Request.self.callback (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:185:22)\\n    at Request.emit (events.js:315:20)\\n    at Request.<anonymous> (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:1154:10)\\n    at Request.emit (events.js:315:20)\\n    at IncomingMessage.<anonymous> (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:1076:12)\\n    at Object.onceWrapper (events.js:421:28)\\n    at IncomingMessage.emit (events.js:327:22)\\n    at endReadableNT (_stream_readable.js:1220:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\"}"
}
```

@cwhitten what's the desidered behavior? This issue is actionable or we need to file another Issue?

Thanks!
