### ISSUE TITLE
Adding component that has no declarative types is ignored

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7067] opened 2021-04-17 01:23 UTC
## Describe the bug

When you add a component that registers things which don't have schema files (such as custom Expression functions or Adapters) composer
* doesn't say it's installed
* doesn't update the packages section to show that it's there.

## Version
![image](https://user-images.githubusercontent.com/17789481/115097656-57554100-9ee0-11eb-942e-f88db1011c97.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to community packages
2. Add one of these packages 
* Iciclecreek.AdaptiveExpressions.Humanizer (custom functions) 
* Iciclecreek.AdaptiveExpressions.Javascript (custom functions)
* Iciclecreek.AdaptiveExpressions.Python (custom functions)
* Iciclecreek.Bot.Builder.Adapters.Console (custom adapter)
It doesn't say that they are "installed" and the settings doesn't add them.

## Expected behavior
That all components are installable are installable.

## Screenshots
I installed Iciclecreek.AdaptiveExpressions.Javascript, it doesn't show up here:
![image](https://user-images.githubusercontent.com/17789481/115097715-b7e47e00-9ee0-11eb-8288-d3ee033952bb.png)
or here
![image](https://user-images.githubusercontent.com/17789481/115097740-d5b1e300-9ee0-11eb-8e7d-09f1847973f6.png)
or here
![image](https://user-images.githubusercontent.com/17789481/115097751-e6625900-9ee0-11eb-982a-4106ca48eb38.png)

**Comment by cwhitten** [comment] 2021-04-20 23:09
@benbrown @carlosscastro can you comment on this?

**Comment by cwhitten** [comment] 2021-04-21 03:11
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/7043

**Closed by cwhitten** 2021-04-21 03:11 UTC
Labels: Type: Bug, topic: package manager
