### ISSUE TITLE
Facing the same issue as Failed to bind luis prediction resource to luis applications.

### ISSUE THREAD

**Issue by gaurav25dec** [microsoft/BotFramework-Composer#8604] opened 2021-08-26 06:19 UTC
Facing the same issue as Failed to bind luis prediction resource to luis applications.
![image](https://user-images.githubusercontent.com/85859250/130900617-49710008-8011-4cce-b348-acff9ebb6a16.png)
![image](https://user-images.githubusercontent.com/85859250/130900851-9dbf9a1d-d699-4be3-ad99-59c7ca3c88d5.png)

Here is my publishing profile
![image](https://user-images.githubusercontent.com/85859250/130900677-afe67d4f-74de-430e-9b68-45ac2f670447.png)

_Originally posted by @gaurav25dec in https://github.com/microsoft/BotFramework-Composer/issues/6763#issuecomment-906086433_

**Comment by gaurav25dec** [comment] 2021-08-30 04:50
Still stuck in the mentioned issue. Please let me know if I can help with anything else in identifying the issue.

**Comment by gaurav25dec** [comment] 2021-08-30 07:13
From where we can get the deployment logs over Bot Framework Composer 2.1.0
![image](https://user-images.githubusercontent.com/85859250/131300203-aa3c22d1-3cb1-4d67-a1b9-9ad68978211a.png)

**Comment by gaurav25dec** [comment] 2021-08-31 08:50
Please Help

**Comment by dmvtech** [comment] 2021-09-01 21:33
Hi @gaurav25dec I apologize for the delay. We are still investigating the "luis bind prediction" issue. 

But, I do see in the last screen shot that you are getting a different error (zip deploy). Did you do something specific to get by the luis bind error and then get this new error?

**Comment by gaurav25dec** [comment] 2021-09-01 23:08
Thanks for your response.

The last screen shot is irrelevant of the mentioned issue, I just wanted to the know the way to access the deployment logs. In earlier version there  was a button to get the same. That may help me to get more details about the error.

Further about the actual question, I am facing this issue with CoreWithLanguage template. The LUIS Authoring and Prediction services are configures as existing resources. I am able to run/debug the solution over composer with everything working. bot getting error on publishing the same.

**Comment by gaurav25dec** [comment] 2021-09-07 07:24
Please Help

**Comment by dmvtech** [comment] 2021-09-08 22:53
hi @gaurav25dec We are still investigating this internally. We will update with an answer or solution as soon as possible.

**Comment by dmvtech** [comment] 2021-09-09 16:49
Closing as a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/8379

Please monitor progress there.

**Closed by dmvtech** 2021-09-09 16:49 UTC
Labels: customer-reported, Bot Services, customer-replied-to
