### ISSUE TITLE
messageBack returns "Object serialized to String. JObject instance expected."

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#7596] opened 2021-05-04 15:31 UTC
I have been trying to get the messageBack function to work for buttons in a card. Regardless of whether I set the value as an integer, string, or JSON object, I receive the same error message: "Object serialized to String. JObject instance expected."

I'm using v1.4.0 Composer on Mac. 

I created a template following the example Microsoft documentation:

[import](common.lg)
# testTemplate
[HeroCard
  title = Samsung Galaxy S21 Ultra 5G
  subtitle = From £75 a month with £49 upfront.
  text = Samsung Galaxy S21 Ultra 5G captures life's moments perfectly with next generation cameras and cutting edge innovations.
  images = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNROcS2-s7YOPsgpQ_xgqxFog-Hr2HSWLvM_wggbOjmwCqR_kcQaLA1LuvgJUQq83-3nO4e8g&usqp=CAc
  buttons = ${testTemplate2('messageBack', 'example message', '{\"property\": \"propertyValue\" }', 'second example message')}
]
#testTemplate2 (type, title, value, displayText)
[CardAction
Type = ${if(type == null, 'imBack', type)}
Title = ${title}
Value = ${value}
DisplayText = ${displayText}
]

Even when I set the value as {7,7}, I still get the string error. Please could someone investigate this? I have also tried directly adding the JSON in, rather than using a secondary template. This didn't work either.

**Comment by srinaath** [comment] 2021-05-04 16:34
@BellaDunnett Thanks for reporting an issue. Could you follow the bug template we have for future tickets. Thanks.

**Comment by anusharavindrar** [comment] 2021-05-05 16:21
@BellaDunnett, can you specify what Mac OS version you are on? Also, could you elaborate on what you are exactly trying to do(the documentation followed, repro steps, screenshots)?

**Comment by BellaDunnett** [comment] 2021-05-06 09:53
Sure - I'm using version 11.3.1. I'm trying to create a hero card with a button at the bottom which presents text to the user, but sends a different value back to the bot. I'd like to prove the capability so that we can use long buttons e.g. 'more information', but just use a simple phrase to trigger an action with the bot. However, there is an issue with the functionality when I click the 'More information' button, as you will see in the screenshots attached.
1. Create heroCard template
 `# testTemplate
[HeroCard
  title = Samsung Galaxy S21 Ultra 5G
  subtitle = From £75 a month with £49 upfront.
  text = Samsung Galaxy S21 Ultra 5G captures life's moments perfectly with next generation cameras and cutting edge innovations.
  images = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNROcS2-s7YOPsgpQ_xgqxFog-Hr2HSWLvM_wggbOjmwCqR_kcQaLA1LuvgJUQq83-3nO4e8g&usqp=CAc
  buttons = ${testTemplate2('messageBack', 'More information', '{"property": "propertyValue"}', 'More information')}
]`

2. Create template for heroCard template to refer to. 
`#testTemplate2 (type, title, value, displayText)
[CardAction
Type = ${if(type == null, 'imBack', type)}
Title = ${title}
Value = ${value}
DisplayText = ${displayText}
]`

3. Call template in dialog flow. In this case, - ${testTemplate()}


![Screenshot 2021-05-06 at 10 52 27](https://user-images.githubusercontent.com/53485343/117279004-2e79f900-ae59-11eb-9521-f44c61076ca1.png)
![Screenshot 2021-05-06 at 10 52 15](https://user-images.githubusercontent.com/53485343/117279009-2f128f80-ae59-11eb-8c82-354e2e777ade.png)
![Screenshot 2021-05-06 at 10 52 06](https://user-images.githubusercontent.com/53485343/117279012-2fab2600-ae59-11eb-9e3c-4d3ee73e8c95.png)

**Comment by anusharavindrar** [comment] 2021-05-07 23:09
@BellaDunnett, I am able to reproduce the error on macOS Catalina(10.15.4) and also on Windows with composer (v1.4.1) on the Emulator(v4.13.0). Can you also specify if you are testing this on any specific channel or just on the Emulator? Also, did you try testing this on Windows as well?

**Comment by dmvtech** [comment] 2021-05-11 17:13
Hi @BellaDunnett 

Ensure the value is json by using the [prebuilt json function](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#json). Such as:
 `buttons = ${DanaTemplate2('messageBack', 'More information', json({​​​​​​​​"property": "propertyValue"})​​​​​​​', 'More information')}​​​​​​​​`
 
 Please give that a test and let us know if it works for you.

**Comment by tdurnford** [comment] 2021-05-11 17:53
@BellaDunnett If you add `Text` to your card action, it should work fine.

```
#testTemplate2 (type, text, title, value, displayText)
[CardAction
  Type = ${if(type == null, 'imBack', type)}
  Title = ${title}
  Value = ${value}
  DisplayText = ${displayText}
  Text = ${text}
]
```

**Comment by BellaDunnett** [comment] 2021-05-12 15:38
> Hi @BellaDunnett
> 
> Ensure the value is json by using the [prebuilt json function](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#json). Such as:
> `buttons = ${DanaTemplate2('messageBack', 'More information', json({​​​​​​​​"property": "propertyValue"})​​​​​​​', 'More information')}​​​​​​​​`
> 
> Please give that a test and let us know if it works for you.

**Comment by BellaDunnett** [comment] 2021-05-12 15:40
Hey @dmvtech I've just given this a go and get the error "line 8:12 - line 8:133 Close } is missing in Expression."
I've attached a screenshot. Please could you take a look and see what's gone wrong? 
![Screenshot 2021-05-12 at 16 40 02](https://user-images.githubusercontent.com/53485343/118003732-bcb21b80-b340-11eb-8929-9586673db0db.png)
![Screenshot 2021-05-12 at 16 40 07](https://user-images.githubusercontent.com/53485343/118003739-bde34880-b340-11eb-8c42-f4db8dd03306.png)

**Comment by BellaDunnett** [comment] 2021-05-12 15:43
@tdurnford I'm still getting the same error, even with the text field. Though have now added it in to my template :)

**Comment by anusharavindrar** [comment] 2021-05-12 15:55
@BellaDunnett, you need to remove the apostrophe after the braces.
![image](https://user-images.githubusercontent.com/48731427/118006014-8492e480-b310-11eb-831b-dc2ec0a3b186.png)
It should look like this:
![image](https://user-images.githubusercontent.com/48731427/118005713-3e3d8580-b310-11eb-8a50-bc1da7f2d009.png)

**Comment by BellaDunnett** [comment] 2021-05-12 16:10
@anusharavindrar Just tried, but now have a different error. Have attached a screenshot so let me know your thoughts.
![Uploading Screenshot 2021-05-12 at 17.09.46.png…]()

**Comment by BellaDunnett** [comment] 2021-05-12 16:12
@anusharavindrar Just tried, but now have a different error. Have attached a screenshot so let me know your thoughts.
![Screenshot 2021-05-12 at 17 09 46](https://user-images.githubusercontent.com/53485343/118008725-4237ca80-b345-11eb-8bc3-a3cb430ebd01.png)

**Comment by anusharavindrar** [comment] 2021-05-12 16:22
@BellaDunnett, can you try removing the `Text` from the CardAction property ? You are adding the property in the CardAction, but not specifying it in the testTemplate2.
![image](https://user-images.githubusercontent.com/48731427/118009730-edc82700-b313-11eb-828c-5c63461b491e.png)
I tried using the same template which you sent(just added the json part) and did not get any error. Can you try the below template and let me know if you still get the error?
![image](https://user-images.githubusercontent.com/48731427/118009901-1cde9880-b314-11eb-885c-9c5db53562c9.png)

**Comment by anusharavindrar** [comment] 2021-05-12 17:05
@BellaDunnett ,can you try this template?
![image](https://user-images.githubusercontent.com/48731427/118015671-28cd5900-b31a-11eb-8c00-7b9a44087c01.png)

**Comment by tdurnford** [comment] 2021-05-12 17:59
@BellaDunnett Even though you added `Text` as a property to your card action, you did not add `text` as a parameter to the Lg template so `text` is undefined in the template.

```
#testTemplate2 (type, text, title, value, displayText)
[CardAction
  Type = ${if(type == null, 'imBack', type)}
  Title = ${title}
  Value = ${value}
  DisplayText = ${displayText}
  Text = ${text}
]
```

**Comment by BellaDunnett** [comment] 2021-05-12 18:27
Hi @anusharavindrar and @tdurnford - even with the text field added, I'm getting the same error that 'stateType' is undefined. 
![Screenshot 2021-05-12 at 19 26 07](https://user-images.githubusercontent.com/53485343/118025747-1540e300-b358-11eb-8356-a64c04542ab6.png)
![Screenshot 2021-05-12 at 19 26 01](https://user-images.githubusercontent.com/53485343/118025750-170aa680-b358-11eb-8d88-4cbf38b2f966.png)

**Comment by anusharavindrar** [comment] 2021-05-12 18:33
@BellaDunnett, you are missing the text parameter in the lg template 
![image](https://user-images.githubusercontent.com/48731427/118026291-430d3400-b326-11eb-85c6-35c16b017fb7.png)
It should be:
![image](https://user-images.githubusercontent.com/48731427/118026478-7223a580-b326-11eb-88f6-b8ec90cdebe5.png)

**Comment by BellaDunnett** [comment] 2021-05-12 18:36
You're right - still no change to the original error though. 
![Screenshot 2021-05-12 at 19 35 42](https://user-images.githubusercontent.com/53485343/118026958-538ad200-b359-11eb-9193-401eba5e17fb.png)

**Comment by anusharavindrar** [comment] 2021-05-12 19:20
@BellaDunnett, this is damn weird as it works for me both on Mac and Windows with the same template without any error. Can you try to select the `testTemplate2` in the #testTemplate2 & copy that and paste it over the existing testTemplate2 in the buttons property and see if it eliminates the error? Please head over to the screenshots section in this [issue](https://github.com/microsoft/BotFramework-Composer/issues/7713) and try out the same and let me know if it removes the error.

**Comment by BellaDunnett** [comment] 2021-05-12 20:42
@anusharavindrar sorry but still not working! Have copied & pasted as in the video but nada

**Comment by hatpick** [comment] 2021-05-12 20:53
@BellaDunnett would you please copy/paste the text of your LG file here as text?

**Comment by BellaDunnett** [comment] 2021-05-12 20:54
`# testTemplate
[HeroCard
  title = Samsung Galaxy S21 Ultra 5G
  subtitle = From £75 a month with £49 upfront.
  text = Samsung Galaxy S21 Ultra 5G captures life's moments perfectly with next generation cameras and cutting edge innovations.
  images = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNROcS2-s7YOPsgpQ_xgqxFog-Hr2HSWLvM_wggbOjmwCqR_kcQaLA1LuvgJUQq83-3nO4e8g&usqp=CAc
  buttons = ${testTemplate2(type, title, value, text, displayText)('messageBack', 'More information', json({​​​​​​​​"property": "propertyValue"})​​​​​​​, 'Text', 'More information')}
  ]

#testTemplate2 (type, title, value, text, displayText)
[CardAction
  Type = ${if(type == null, 'imBack', type)}
  Title = ${title}
  Value = ${value}
  Text = ${text}
  DisplayText = ${displayText}
]`

**Comment by hatpick** [comment] 2021-05-12 20:58
@BellaDunnett First of all you need to remove the ```(type, title, value, text, displayText)``` from this line:
```buttons = ${testTemplate2(type, title, value, text, displayText)('messageBack', 'More information', json({​​​​​​​​"property": "propertyValue"})​​​​​​​, 'Text', 'More information')}```

Then, there are a bunch of 0 width characters here:
![Screen Shot 2021-05-12 at 1 57 27 PM](https://user-images.githubusercontent.com/1483492/118043360-1d822980-b32a-11eb-9fdd-9c4fb371e95f.png)

Removing them will fix the issue, i dont know how they got added to your code.

**Comment by hatpick** [comment] 2021-05-12 21:04
@BellaDunnett First of all you need to remove the following:
```(type, title, value, text, displayText)```
from this line:
```
buttons = ${testTemplate2(type, title, value, text, displayText)('messageBack', 'More information', json({​​​​​​​​"property": "propertyValue"})​​​​​​​, 'Text', 'More information')}
```

Then, there are a bunch of 0 width space characters here (red dots)

![Screen Shot 2021-05-12 at 1 57 27 PM](https://user-images.githubusercontent.com/1483492/118043360-1d822980-b32a-11eb-9fdd-9c4fb371e95f.png)

Removing them will fix the issue, i dont know how they got added to your code.

```
# testTemplate
[HeroCard
  title = Samsung Galaxy S21 Ultra 5G
  subtitle = From £75 a month with £49 upfront.
  text = Samsung Galaxy S21 Ultra 5G captures life's moments perfectly with next generation cameras and cutting edge innovations.
  images = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNROcS2-s7YOPsgpQ_xgqxFog-Hr2HSWLvM_wggbOjmwCqR_kcQaLA1LuvgJUQq83-3nO4e8g&usqp=CAc
  buttons = ${testTemplate2('messageBack', 'More information', json({"property": "propertyValue"}), 'Text', 'More information')}
]

#testTemplate2 (type, title, value, text, displayText)
[CardAction
  Type = ${if(type == null, 'imBack', type)}
  Title = ${title}
  Value = ${value}
  Text = ${text}
  DisplayText = ${displayText}
] 
```

**Comment by BellaDunnett** [comment] 2021-05-12 21:29
@hatpick it worked!! thank you! It only fixed the issue when I copied and pasted your text, I tried typing the text out myself first but it created the same error. Bizarre!

**Comment by hatpick** [comment] 2021-05-12 21:37
@BellaDunnett Great! I'm gonna close this issue and we'll keep investigating the problem under:
https://github.com/microsoft/BotFramework-Composer/issues/7713

**Closed by hatpick** 2021-05-12 21:37 UTC
Labels: Bot Services, Support, Type: Bug, customer-replied-to, customer-reported
