### ISSUE TITLE
Composer: Storing array of entities values in to property

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#4875] opened 2020-11-18 11:33 UTC
I'm using this regex entity **@ regex hrfnumber = /hrf-[0-9]{6}/** 

entering multiple different values of same entity in a single bot ask's and I'm try to store it into a property

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/51915291/99525312-a5145e80-29bf-11eb-9b1d-db4c2e371a01.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/51915291/99525318-a6458b80-29bf-11eb-9689-1aa687f61b50.png)

getting error like can not convert from string to array how to get eah value and store it to array, how to create array property

**Comment by dmvtech** [comment] 2020-11-19 00:11
Hi @KoradaRajesh 

Would you be able to link or send your .dialog file? (sanitized of personal/sensitive info if needed).

And to clarify; this is not dealing with firing a trigger on intent, but just dealing with the prompt. Correct?

Further; if the user says `hrf-828282 and hrf-353535`, you're looking to capture _**both**_ values `hrf-828282` and `hrf-353535`, into an array property?

**Comment by KoradaRajesh** [comment] 2020-11-19 00:58
@dmvtech Yes, it's dealing with the prompt, if the user says hrf-828282 and hrf-353535, I'm looking to capture both values hrf-828282 and hrf-353535, into an array property

**Comment by KoradaRajesh** [comment] 2020-11-19 04:17
[ComposerDialogs (3).zip](https://github.com/microsoft/BotFramework-Composer/files/5564324/ComposerDialogs.3.zip)

I'm V1.0.2

**Comment by KoradaRajesh** [comment] 2020-11-21 16:42
@dmvtech Any update on this?

**Comment by dmvtech** [comment] 2020-12-01 01:09
Hi @KoradaRajesh My apologies. I was trying to get a v1.0.2 version running, but haven't been able to complete that yet. I tried opening with 1.2.1, and they don't open in that. Anyhow, I'm trying to see if this is possible with 1.2.1 and we can see if it will work for you. I'm working on it and will update you with progress.

**Comment by tonyanziano** [comment] 2020-12-11 20:36
@dmvtech making sure that this is still on your radar.

**Comment by dmvtech** [comment] 2020-12-15 00:54
Yes. I'm getting closer on this. Should have an update in a day or two.

**Comment by dmvtech** [comment] 2020-12-31 05:16
Hi @KoradaRajesh. Sorry for the delay.

Using LU such as:
```
- Give me hrf-121212
- Can I get hrf-565656
- Please give {@hrf1=hrf-123456} and {@hrf2=hrf-789012}

@ regex hrfnumber hasRoles hrf1, hrf2 = /hrf-[0-9]{6}/
```


You can then set properties for each. using the coalesce function to read if the role is assigned, otherwise using the entity:
```
          "$kind": "Microsoft.SetProperties",
          "$designer": {
            "id": "nbSKSO"
          },
          "assignments": [
            {
              "property": "dialog.hrf1",
              "value": "=coalesce(@hrf1,@hrfnumber)"
            },
            {
              "value": "=coalesce(@hrf2,@hrfnumber)",
              "property": "dialog.hrf2"
            }
          ]
```

Then of course use those as needed:
`- Entities: ${dialog.hrf1} and ${dialog.hrf2}`

Do you particularly need those values in an array, or just to be able to capture each one?

**Comment by sammydeprez** [comment] 2021-01-03 13:00
got the same question. But not with regex.
I have a LUIS Entity - lets call it 'topping'
And the user says: 'I want pizza with peperoni & olives'
LUIS recognize Entity Topping and returns ['peperoni', 'olives']
but only the 1th one is added in to a variable.

Above solution might work, but we never know how many items the user will return.

**Comment by KoradaRajesh** [comment] 2021-01-03 13:24
@dmvtech @tonyanziano @sammydeprez I'm fasing one more major issue can you look into that Quickly #5434

**Comment by feich-ms** [comment] 2021-01-08 05:56
Hi @dmvtech, @sammydeprez, I tested in composer and can repro this issue. Array entities cannot be stored into dialog memory directly in TextInput action. This is by design as TextInput only allows setting string property. Fortunately, we have a useful action to set the property. You can add a SetProperty action like below screenshot, set `turn.recognized.entities.toppings` to `dialog.toppings`. This can meet your requirements I think.

![image](https://user-images.githubusercontent.com/43032123/103979560-00d9b780-51b9-11eb-970c-04669359bc09.png)

**Comment by dmvtech** [comment] 2021-01-14 19:13
Closing. Workaround shared, and bug in dotnet repo has been filed.

**Closed by dmvtech** 2021-01-14 19:13 UTC
Labels: Bot Services, Type: Question, customer-replied-to, customer-reported
