### ISSUE TITLE
Publishing not successful, error/reason why hidden due to column sizing

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7831] opened 2021-05-14 15:18 UTC
- will update this issue with longer, better description -

Publish failed. No warning, no error, rocket menu has green checks for LUIS and QnA - no way to found out what happened. 

![Screen Shot 2021-05-14 at 8 16 44 AM](https://user-images.githubusercontent.com/48503434/118291771-cfd20200-b48c-11eb-8e0c-1592ba2031ba.png)
![Screen Shot 2021-05-14 at 8 15 35 AM](https://user-images.githubusercontent.com/48503434/118291776-d1032f00-b48c-11eb-81ec-c1e48963c2df.png)
![Screen Shot 2021-05-14 at 7 55 47 AM](https://user-images.githubusercontent.com/48503434/118291802-d52f4c80-b48c-11eb-9492-5ba356a86d8f.png)

Turns out this was due to the following error during provisioning: LUIS could not be provisioned due to insufficient quota
Expected: Error detail that includes this info in 'status' section of Publishing list/page.

**Comment by sgellock** [comment] 2021-05-14 15:42
Shiproom - @GeoffCoxMSFT can you look at this one, and once we have a root cause, we can assess if we'd take a fix for R13

**Comment by GeoffCoxMSFT** [comment] 2021-05-14 16:09
@mareekuh - Could you tell me a little more about the repro steps.  What kind of project did you create? Are you using a MS or personal subscription? What options did you choose during provisioning?  What did the publishing log say?  

The message in the UI is only the latest status, so it might be that something wrote an empty string last and that hides the error.

**Comment by sgellock** [comment] 2021-05-14 18:03
Shiproom - Per Geoff: Debugged Marieke's issue - it is a column sizing problem hiding the error when the window is narrow.  The error message is sent back and does appear when the window is wide enough (normal size).  Marieke agreed this is now a P1 for R14.

**Comment by OEvgeny** [comment] 2024-02-28 20:29
Should be fixed by reflow work

**Closed by OEvgeny** 2024-02-28 20:29 UTC
Labels: Type: Bug, P0, ExemptFromDailyDRIReport
