### ISSUE TITLE
 Command failed: dotnet build

### ISSUE THREAD

**Issue by DevOpsKiruthi** [microsoft/BotFramework-Composer#9585] opened 2023-05-20 09:48 UTC
Command failed: dotnet build

**Comment by anishprasad01** [comment] 2023-05-22 19:53
Hi @DevOpsKiruthi,

Please provide details regarding your issue.

**Comment by anishprasad01** [comment] 2023-05-29 15:55
Closing issue due to lack of information. Cannot reproduce.

**Closed by anishprasad01** 2023-05-29 15:55 UTC
Labels: customer-reported, Bot Services
