### ISSUE TITLE
PVA: Valid adaptive card json prevents publishing to PVA

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7394] opened 2021-04-27 00:19 UTC
## Repro
* Create a non-PVA bot with adaptive card, test that it works.
* Create a PVA bot, switch to advanced authoring with composer
* Reproduce the adaptive card in PVA bot
* Publish

## Error
```
"severity": "Error",
"source": "MoodCheckerDialog.en-us.lg",
"message": "Error occurred when parsing expression 'json({\r\n \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",\r\n \"version\": \"1.2\",\r\n \"type\": \"AdaptiveCard\",\r\n \"body\": [\r\n {\r\n \"type\": \"Container\",\r\n \"items\": [\r\n {\r\n \"type\": \"ColumnSet\",\r\n \"columns\": [\r\n {\r\n \"type\": \"Column\",\r\n \"width\": \"auto\",\r\n \"items\": [\r\n {\r\n \"type\": \"Image\",\r\n \"url\": \"https://metatour.azurewebsites.net/img/happy.png\",\r\n \"size\": \"small\"\r\n '. missing '}' at '<EOF>'"
}
---
```

## Sample JSON
```
# SendActivity_kUwtny()
[Activity
    Attachments = ${SendActivity_kUwtny_attachment_fpA8bl()}
]

# SendActivity_kUwtny_attachment_fpA8bl()
> To learn more Adaptive Cards format, read the documentation at
> https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots
- \```${json({
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
        "type": "Container",
        "items": [
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "Image",
                    "url": "https://metatour.azurewebsites.net/img/sad.png",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "I'm sorry to hear that. Feel better soon.",
                    "weight": "bolder",
                    "wrap": true,
                    "BlockElementHeight" : "stretch"
                  }
                ]
              }
            ]
          }
        ]
    }
  ]
})}\```
(backslash inserted for rendering in issue comment)
```

**Comment by scheyal** [comment] 2021-04-27 00:28
And another sample json

```
# SendActivity_3su1l3()
[Activity
    Attachments = ${SendActivity_3su1l3_attachment_jGnBkM()}
]

# SendActivity_3su1l3_attachment_jGnBkM()
> To learn more Adaptive Cards format, read the documentation at
> https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots
- \```${json({
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
  {
    "type": "Container",
    "items": [
      {
        "type": "Image",
        "url": "https://metatour.azurewebsites.net/img/happysad.png",
        "size": "large",
        "horizontalAlignment" : "center"
      },
      {
        "type": "TextBlock",
        "text": "**Mood Checker**",
        "weight": "bolder",
        "size": "large",
        "isSubtle": false,
        "horizontalAlignment" : "center"
      },
      {
        "type": "TextBlock",
        "text": "Demonstrate simple intent detection",
        "isSubtle": true,
        "horizontalAlignment" : "center"
      }
    ]
  }
  ]
})}\```
(backslash inserted for rendering in bug)
```

**Comment by iMicknl** [comment] 2021-04-28 13:19
I faced this issue (again) today and logged https://github.com/microsoft/BotFramework-Composer/issues/7450.

Our workaround for now is to move the `json()` function call to the Activity block, however this is a manual action and should not be required. It seems that the PVA back-end has an error in the validation..

```
[Activity
    Attachments = $json({SendActivity_eBobKx_attachment_VNSg6J())}
]
```

**Comment by Dewain27** [comment] 2021-04-30 19:31
@cwhitten please see if this is something @tdurnford should look at.  We are getting multiple reports of this.

**Comment by cwhitten** [comment] 2021-04-30 19:39
@Dewain27, this is a bug in the SDK that was fixed as of 4.12.2 and PVA's runtime is on 4.11

**Comment by cwhitten** [comment] 2021-04-30 19:58
For ship-room discussion:

The Adaptive Card template that is provided with the updated LG authoring widget is not PVA compatible due to this issue. R13 consideration is to update the template to be SDK 4.11 compatible.

**Comment by sgellock** [comment] 2021-05-03 15:33
Shiproom - lets spike the adaptive card template and see where we land

**Comment by sgellock** [comment] 2021-05-04 15:41
Shiproom - approved.  please merge today.

**Comment by scheyal** [comment] 2021-05-13 17:39
My bot is still not able to publish the json.

**Comment by cwhitten** [comment] 2021-05-13 18:02
@scheyal you would need to recreate the response template, which would come with a new format that PVA supports, not reuse the existing one that did not work. Can you please confirm that

**Comment by cwhitten** [comment] 2021-05-13 19:11
I've been able to reproduce this, and the explanation from PVA is that they need to take a bump to a BF lib in order to support the syntax in the updated template that came in with https://github.com/microsoft/BotFramework-Composer/pull/7593

We'll need to deploy a workaround though, as their release timeline for this change is mid June

**Comment by sgellock** [comment] 2021-05-13 20:34
Shiproom - core P0 scenario - approved

**Closed** 2021-05-13 21:29 UTC
Labels: Area: PVA, Build Bugbash, P0, ShipRoom-Approved, Type: Bug
