### ISSUE TITLE
Intent analytics is still broken: Utterance not reported, detected intent is reported wrong.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7790] opened 2021-05-13 17:10 UTC
## Repro
* View language analytics in appinsights
* Variation: LUIS or Orchestrator

## Results
1. Utternace is not showing up in 'text' field
2. Detected intent is reported wrongly (the wrong one is showing)

## Visual
- Observe: Conversation is detecting fruits and veggies; however appinsights shows only fruites
- Observe: utterance in text is not showing.

![image](https://user-images.githubusercontent.com/8867670/118160580-55917700-b3d3-11eb-88ed-48a4d883a773.png)

**Comment by scheyal** [comment] 2021-05-13 17:12
## version

Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by sgellock** [comment] 2021-05-14 15:24
Shiproom - let' repro to verify if we have a regression

**Comment by peterswimm** [comment] 2021-05-14 19:53
tested with a new bot and wasn't able to generate app insights records at all, once deployed to a web app it seems to work as intended.

**Comment by darrenj** [comment] 2021-05-17 08:42
I have just reproed on:
![image](https://user-images.githubusercontent.com/33519520/118459363-99e28700-b6f3-11eb-8ae9-8abfe10544b3.png)

See `LuisResult` entry does not have utterance
![image](https://user-images.githubusercontent.com/33519520/118459324-8df6c500-b6f3-11eb-9f63-1a8891238fc4.png)

Noe that `BotMessageRecieved` does:
![image](https://user-images.githubusercontent.com/33519520/118459538-be3e6380-b6f3-11eb-8e71-c0193c4b7086.png)

As per documentation `LuisResult` should have `question`:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0#custom-dimensions-luis

This is a regression.

**Comment by darrenj** [comment] 2021-05-17 08:45
> tested with a new bot and wasn't able to generate app insights records at all from composer web chat, once deployed to a web app it seems to work as intended.

I suspect your local problem was that you need to manually updating Bot settings (advanced JSON view) to put the connection string in? When testing locally, resources from your publishprofile aren't used :-(

**Comment by cwhitten** [comment] 2021-05-17 13:10
Do we know of a version of the SDK where this behaved as expected? We should also check with the service to see if there has been a change to PII collection

**Comment by sgellock** [comment] 2021-05-17 15:10
Shiproom - @scheyal assuming this is a dotnet SDK bot?

**Comment by taicchoumsft** [comment] 2021-05-17 19:54
Hi @darrenj , the `question` property is gated behind the `logPersonalInformation` telemetry property, the source is [here](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L571).  After enabling it, I get this: 
![image](https://user-images.githubusercontent.com/61705609/118546804-4ed56d80-b70d-11eb-9c07-5229f81dd078.png)

Please note that there appears to be a change to **where** this property is set.  

As of today, the `logPersonalInformation` property should be set in `=settings.telemetry.logPersonalInformation` in Composer.  It is changing to `=settings.runtimeSettings.telemetry.logPersonalInformation` per [this](https://github.com/microsoft/botbuilder-dotnet/commit/3181dd34ceb68878d9ffea42626ebb839a58482b) change made 10 days ago.  I will try to find out which version of the SDK this went into, and when Composer will take this change.

I'm trying to repro @scheyal's issue that started this thread.  There is a difference between the custom LUIS properties and the ones that the other recognizers use, I'll try to look for a common ground so we can refine his query - it currently won't work for LUIS.

**Comment by darrenj** [comment] 2021-05-18 08:14
Thanks Tai - agree that the multiple intent part is a new requirement so don't need to worry about that at this time.

Hopefully the latest build of Composer will take this change, will confirm in shiproom

**Comment by sgellock** [comment] 2021-05-18 15:07
Shiproom - requires 4.13.2 of dotnet SDK

**Comment by sgellock** [comment] 2021-05-18 16:38
Shiproom - Per @taicchoumsft's analysis, we have a fix merged into the 4.13 branch of the .NET SDK.  This will be addressed by publishing 4.13.2 and updating the NBTs to use the latest SDK bits.

**Comment by sgellock** [comment] 2021-05-19 14:46
Shiproom - 4.13.2 was published yesterday.

**Closed by sgellock** 2021-05-19 14:46 UTC
Labels: Build Bugbash, P0, ShipRoom-Approved, Type: Bug
