### ISSUE TITLE
Error starting bot after upgrading to release 1.1.0

### ISSUE THREAD

**Issue by timoconnellaus** [microsoft/BotFramework-Composer#4010] opened 2020-09-03 00:38 UTC
## Describe the bug

After starting the bot I get the following error in the bot framework composer interface

![image](https://user-images.githubusercontent.com/3151605/92054607-74198a00-edd1-11ea-8330-f39a998e8bd3.png)

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.ConfigureServices(IServiceCollection services) in C:\Users\User\AppData\Roaming\BotFrameworkComposer\hostedBots\30826.684404823012\runtime\azurewebapp\Startup.cs:line 146 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services) at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider() at Microsoft.Extensions.Hosting.HostBuilder.Build() at Microsoft.BotFramework.Composer.WebAppTemplates.Program.Main(String[] args) in C:\Users\User\AppData\Roaming\BotFrameworkComposer\hostedBots\30826.684404823012\runtime\azurewebapp\Program.cs:line 16

## Version

Release 1.1.0
Windows installation using the msi

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment] 2020-09-03 03:06
Can you provide more detail for your bot settings ?

**Comment by timoconnellaus** [comment] 2020-09-03 04:15
Thanks @hibrenda 

![image](https://user-images.githubusercontent.com/3151605/92070571-bce03b80-edef-11ea-84f0-ea22106030a3.png)

Note that:
- We're not using LUIS
- The knowledgebaseid for qna maker is set using a separate property, not stored in settings

**Comment by luhan2017** [comment] 2020-09-03 07:45
@timoconnellaus , thanks for reporting this, we've found the root cause on this, removed 1.1.0 version, and will publish a new release soon.
You can either wait for a few hours for another update or you can mitigate the issue by pasting those settings in you settings page,

"cosmosDb": {
	"authKey": "",
	"collectionId": "botstate-collection",
	"cosmosDBEndpoint": "",
	"databaseId": "botstate-db"
}, "applicationInsights": {
	"InstrumentationKey": ""
}, "blobStorage": {
	"connectionString": "",
	"container": "transcripts"
}

**Comment by hibrenda** [comment] 2020-09-03 11:04
https://github.com/microsoft/BotFramework-Composer/pull/4015

**Comment by GeoffCoxMSFT** [comment] 2020-09-09 18:14
v1.1.1 has been released so this should be fixed.

**Closed by GeoffCoxMSFT** 2020-09-09 18:14 UTC
Labels: Type: Bug
