### ISSUE TITLE
Update install not start

### ISSUE THREAD

**Issue by volkanbt06** [microsoft/BotFramework-Composer#9649] opened 2023-09-29 06:54 UTC
Hello,

This last update does not start on my set-up. I'm getting the following error:

"Couldn't complete the update: Error: Cannot download "https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/download/v2.1.3-nightly.364675.1a93f21/electron.exe", status 404:"

**Comment by dmvtech** [comment] 2023-09-29 19:15
Closing as duplicate of: 
https://github.com/microsoft/BotFramework-Composer/issues/9228

You can download the nightly from here:
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21/electron.exe

**Closed by dmvtech** 2023-09-29 19:15 UTC
Labels: Type: Bug, customer-reported, Bot Services, Needs-triage
