### ISSUE TITLE
Add publishing profile panels do not remember state

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6172] opened 2021-03-04 00:54 UTC
## Describe the bug
When I work my way through the Add publishing profile "wizard", bot name and publishing targets selection on the first screen are lost if I nav to the Configure resoruc3s screen, then click the Back button.

## Version
1.3.x R12 Bug Bash

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot project that doesn't not have an existing publishing profile
2. Nav to the Bot mgmt and config page
3. Scroll down to the Publish profiles section
4. click etc Add new link to invoke the Add a publishing profile UX
5. On the first panel provide a name and select a publishing target.
6. click the Next: Configure resources button
7. once on the Configure resources panel, click the Back button to return to the Add a publishing profile panel.

## Expected behavior
I would expect to see the values I added on this screen to be displayed.  

The values I entered are lost and the name and publishing target values are empty.

**Comment by benbrown** [comment] 2021-03-04 15:57
Dupe of #6086

thanks for the report @sgellock.

**Closed by benbrown** 2021-03-04 15:57 UTC
Labels: Needs-triage, R12 Bugbash, Team: Runtime & Publishing, Type: Bug
