### ISSUE TITLE
Value set form disappeared

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2819] opened 2020-04-29 04:49 UTC
## Describe the bug
Value set form disappeared, is this a bug or by design?
![image](https://user-images.githubusercontent.com/44257569/80561575-834d8d00-8a17-11ea-82ec-93c45b74d51d.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment] 2020-04-29 14:53
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2825

**Comment by a-b-r-o-w-n** [comment] 2020-04-29 20:18
Re-opening because this property has been removed from some inputs and shows up when it shouldn't.

cc @alanlong9278 @cwhitten

**Comment by cwhitten** [comment] 2020-04-29 20:21
Can we just hide it in from the ChoiceInput form?

**Comment by a-b-r-o-w-n** [comment] 2020-04-29 20:25
This could be due to an error in the schema. @chrimc62 is checking on that.

**Comment by a-b-r-o-w-n** [comment] 2020-04-29 21:42
@vishwacsena has confirmed that this is a bug in the schema. I'll close this now and we'll update the schema when fixed

**Closed** 2020-04-29 21:43 UTC
Labels: Type: Bug, skill-reported
