### ISSUE TITLE
start New bot from scratch, missing, Example list missing from desktop Composer GUI

### ISSUE THREAD

**Issue by powertrio77** [microsoft/BotFramework-Composer#7823] opened 2021-05-14 00:50 UTC
## Describe the bug
I remember clicking the C# tab in the start/home window of Composer, and now I cannot view/select Bot from scratch. Also the "Example List" pane on the right is missing. I have uninstalled, ran updates, reinstalled to a local folder (not AppData) c:\mydot\Bot FrameWork Composer\.

Originally Bot Framework composer installed here:
C:\Users\mrich\AppData\Local\Programs and I had the option to create bot from scratch and Example List appeared on right.
I'm not sure when I created this user mrich.  I have only 3 accounts on this PC and none are mrich. 2 using an outlook.com email address and I recognize the usernames and 3rd is hotmail.com username. mrich is close to  my first and last name, but I don't know why it's who I'm logged in as, per "C:\Users\mrich\AppData\Local\Programs" install path.

## Version
Version:  1.4.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
no browser, desktop app install

## OS
Windows 10 20H2 19042.xxx

## To Reproduce
open Bot Framework Composer desktop app, look for Example List on right and observe it's missing.
Click Home in Bot Framework Composer desktop app, click New, and observe the only option is C# and Blank Bot, Basic Conversational bot, QnA Maker bot are only 3 choices. Observe there is no option to click "Bot from scratch." But I did see a few days ago, when I started learning Bot Framework Composer. The last thing I remember doing, was seeing two tab headings in Home page of Bot Framework Composer. C# and I think other was Js. I clicked this C# tab during one tutorial. This is last thing I remember doing outside of tutorial. But I have uninstalled 3 times, and reinstalled.

## Expected behavior
tried installing to:
c:\Programs\Bot Framework Composer\   (that is the path in the screen shot by Microsoft)
c:\mydot\Bot Framework Composer\
problem remains

## Screenshots
![botframe2](https://user-images.githubusercontent.com/42945038/118204404-bfd20800-b423-11eb-8ce7-ca28c0cb3733.png)

screen shot of what I am expecting to see.
![botframe1](https://user-images.githubusercontent.com/42945038/118204432-cf515100-b423-11eb-9a4d-91425ab7a5d9.png)

**Comment by sgellock** [comment] 2021-05-14 15:10
Shiproom - moving our of R13

**Comment by ninggao** [comment] 2021-05-17 17:35
@darrenj  Could you please take a look at this one?

**Comment by sgellock** [comment] 2021-05-17 19:59
Shiproom - this is by design.  we are not including samples in the home page of composer 2.0.  these samples are migrated to the new adaptive RT and will be, at least for R13, found in the boatbuilder-samples repository.

**Comment by powertrio77** [comment] 2021-05-18 04:14
ok, thanks.

**Comment by ninggao** [comment] 2021-05-18 16:22
@powertrio77 would you like to close this issue, or do you have other questions?

**Comment by srinaath** [comment] 2021-05-18 16:55
@powertrio77 Once you turn on the flag for the new adaptive runtime in Composer settings you lose the ability to choose from these preexisting templates. This experience is expected.

**Comment by powertrio77** [comment] 2021-05-18 18:15
close. thanks

**Closed** 2021-05-19 18:30 UTC
Labels: Bot Services, Build Bugbash, Type: Bug, customer-replied-to, customer-reported
