### ISSUE TITLE
Wrong node selected when adding a new action.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4609] opened 2020-11-01 23:16 UTC
## Describe the bug
The wrong node is selected when adding a new action. I added a `SetProperty` action in the flow below but it then selected the node beneath the new one.
 
![add-selects-wrong-node](https://user-images.githubusercontent.com/698939/97818061-0664cf80-1c55-11eb-956e-3622ea850259.gif)

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.178300.83c0804

**Comment by cwhitten** [comment] 2020-11-03 00:46
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/4616

**Closed by cwhitten** 2020-11-03 00:46 UTC
Labels: Needs-triage, Type: Bug
