### ISSUE TITLE
Get Error When Logging Into Azure Through Bot Framework Composer

### ISSUE THREAD

**Issue by shesob** [microsoft/BotFramework-Composer#8848] opened 2021-12-10 20:04 UTC
## Describe the bug
I have been to log into Azure from Bot Framework Composer until today.  As of today, I get this message when required to log into Azure: 

"Unfortunately, this application does not currently support your work or school’s regional cloud environment. Alternatively, you could use a Microsoft personal account. Don’t have one? Create a Microsoft personal account for free" 

## Version

I'm using Bot Framework Composer v2.1.1

## Browser

Using Chrome browser

## OS

Using Windows 10 Home

## To Reproduce

1. Open Bot Framework Composer
2. Click on the profile icon on the right and click on 'Sign in to your Azure account'
3. Microsoft Sign In popup is displayed
4. Enter Email and click 'Next'
5. Error message is displayed: "Unfortunately, this application does not currently support your work or school’s regional cloud environment. Alternatively, you could use a Microsoft personal account. Don’t have one? Create a Microsoft personal account for free" 

## Expected behavior
Should ask for password, then after correct password is entered,  show log in successful.
## Screenshots

![image](https://user-images.githubusercontent.com/95938652/145634639-74df0968-7e00-4d5c-8e1c-81fce4ded2d8.png)

## Additional context

I have not changed any settings on both Azure or Bot composer.  I was able to log in successfully from Bot Composer and publish bots successfully the day before

**Comment by gabog** [comment] 2021-12-13 19:24
Hi @shesob, there were issues iwht AAD auth a few days ago, can you please retry and let us know if the problem persists?

**Comment by Gupta-Keshav-001378461** [comment] 2021-12-16 13:21
Hi @gabog I am facing the same problem again today.  can someone look at it.

**Comment by shesob** [comment] 2021-12-16 15:27
@gabog It was working again and since I saw that it wasn't working again for someone else, I checked it and it's giving me that same error again

**Comment by anishprasad01** [comment] 2021-12-20 18:49
@shesob, @Gupta-Keshav-001378461

There were further issues with AAD auth last week that appear to have been resolved. Since we are unable to reproduce this login error, could you please try one more time?

**Comment by shesob** [comment] 2021-12-20 18:54
@anishprasad01 
All looks to be working again...thx

**Comment by anishprasad01** [comment] 2021-12-20 18:58
Excellent. In that case, I'm going to go ahead and close this, but feel free to reopen if this issue pops up again.

**Closed by anishprasad01** 2021-12-20 18:58 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to, Needs-triage
