### ISSUE TITLE
Bot changes do not get saved

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3074] opened 2020-05-15 11:22 UTC
Nothing gets saved anymore.
- Fresh install of Composer
- Create a new Echo bot (I have custom location)
- Change text in the Send A response Component in Greeting Trigger
- Add a send response component with some text
- Re-open bot
- Changes are gone

## Version

6cd92ee2

**Comment by cwhitten** [comment] 2020-05-15 17:47
@cxbuilders we cannot reproduce this.

**Comment by cxbuilders** [comment] 2020-05-17 10:16
@cwhitten Stange, just tested with 31ff30ba and all is ok. CLosing this now.

**Comment by cxbuilders** [comment] 2020-05-17 10:57
@cwhitten It is an intermittent problem, just had it again. Will try to see if I can pinpoint it when it happens next time. Will update once I have more info

**Comment by hibrenda** [comment] 2020-05-19 01:53
addressed in https://github.com/microsoft/BotFramework-Composer/pull/3117. If you hit again, feel free to reopen.

**Closed by hibrenda** 2020-05-19 01:53 UTC
Labels: Needs-triage, Type: Bug
