### ISSUE TITLE
Configure resources panel of the Creating a publishing profile flow shows loading spinner 

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6171] opened 2021-03-04 00:47 UTC
## Describe the bug
When create a publish profile for a bot project that doesn't yet have one, the Configure resources panel shows a loading spinner indefinitely.

## Version
1.3.x for R12 bug bash

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [X ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot project that does not have a publishing profile.  
2. Nav to bot mgmt and config page
3. Click the Add new link of the Publish profiles section, to add a new profile
4. provide reasonable a Name, and select a publishing target of Azure functions, click Next:  Configure resources
5. get to the second panel (the configure resources) panel
6. I get a loading spinner.  the "Next:Review" button is disabled

## Expected behavior
The "Create new Azure resources" option is selected by default.
When this is the case, I wouldn't expect to see a loading spinner.

## Screenshots
<img width="981" alt="Screen_Shot_2021-03-03_at_4_40_12_PM" src="https://user-images.githubusercontent.com/733559/109893093-e4e61580-7c3f-11eb-97ab-e3430cfcfb58.png">

**Comment by mewa1024** [comment] 2021-03-04 02:24
I'm also running into this spinner when I click "Edit" next an existing publishing profile:
![image](https://user-images.githubusercontent.com/39317542/109901214-86279880-7c4d-11eb-9e0a-4d788c8b1c07.png)

This is on
Version:  1.3.1-nightly.219396.61c944a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

This did not happen for me on the previous nightly.

**Comment by benbrown** [comment] 2021-03-04 15:58
@sgellock @mewa1024 did you ever see the login prompt?

**Comment by sgellock** [comment] 2021-03-04 16:03
No.  never prompted to login.

**Comment by luhan2017** [comment] 2021-03-05 03:09
@sgellock @mewa1024 could you please help get more info by the following steps?
1. Open commnd line tool and Go to the composer exe folder, usually located here:
    C:\Users{YourUserName}\AppData\Local\Programs\Bot Framework Composer
2. run set debug=composer*
3. start Bot Framework Composer from the command line
4. do the reproduced steps again. 
5. Check the command line tool log and paste them here.

**Comment by cosmicshuai** [comment] 2021-03-05 07:38
I took some screenshots from the terminal output and electron dev tools.
<img width="1440" alt="Screen Shot 2021-03-05 at 3 31 38 PM" src="https://user-images.githubusercontent.com/17074777/110082657-9c0d9880-7dc8-11eb-8368-336115b3e390.png">
<img width="892" alt="Screen Shot 2021-03-05 at 3 35 47 PM" src="https://user-images.githubusercontent.com/17074777/110082663-9e6ff280-7dc8-11eb-887d-cc600ba9251f.png">

**Comment by cosmicshuai** [comment] 2021-03-05 07:50
The previous release, 5fd80ed version. The publish works. Here are some screenshots:
<img width="1432" alt="Screen Shot 2021-03-05 at 3 48 19 PM" src="https://user-images.githubusercontent.com/17074777/110083963-52be4880-7dca-11eb-8dad-680b51545fd9.png">
<img width="895" alt="Screen Shot 2021-03-05 at 3 49 46 PM" src="https://user-images.githubusercontent.com/17074777/110084033-6ec1ea00-7dca-11eb-9e73-6169b420d414.png">

**Comment by yeze322** [comment] 2021-03-05 09:23
It seems to be a pipeline issue @tonyanziano do you know what's the env difference between two releases on 61c944a?
![image](https://user-images.githubusercontent.com/8528761/110094873-47254e80-7dd7-11eb-8966-8eca90d87e78.png)

In 219396, getAuth returns 304 with an empty token, it might be related to oneauth-mac which is in the private registry

**Comment by boydc2014** [comment] 2021-03-05 09:39
> It seems to be a pipeline issue @tonyanziano do you know what's the env difference between two releases on [61c944a](https://github.com/microsoft/BotFramework-Composer/commit/61c944aba7cfe4f0b95120c5c2291b82468d3dc7)?
> ![image](https://user-images.githubusercontent.com/8528761/110094873-47254e80-7dd7-11eb-8966-8eca90d87e78.png)
> 
> In 219396, getAuth returns 304 with an empty token, it might be related to oneauth-mac which is installed from private registry.

By looking at the pipeline, the first one (219395 the working one) came from Composer-Nightly-All-Platform. The second one (219396 the not working one) came from Composer-Orchestrator-Nightly-All-Platform https://fuselabs.visualstudio.com/Composer/_build/results?buildId=219396&view=results, which is unexpected to published to Github.

**Comment by luhan2017** [comment] 2021-03-09 02:55
Close this issue since we already fixed the pipeline. Please reopen if needed.

**Closed by luhan2017** 2021-03-09 02:55 UTC
Labels: P0, R12 Bugbash, Team: Runtime & Publishing, Type: Bug
