### ISSUE TITLE
Adding Skill to Bot Composer is increasing the Bot Size and making it slow

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7872] opened 2021-05-20 17:20 UTC
## Describe the bug

After adding another Bot as Skill, the size of Bot has become larger  and became slow, is there a way to increase the performance and reduce size

## Browser

- [ ] Chrome

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Add another Bot using the manifest as skill ( the other bot is really small only two dialogues)
2.Creates a model folder (screen shots given below)
3. onnx files get formed
4. Suddenly the bot which has to be deployed  in scale of 100 mb becomes 10 times heavy 1 gb + 
5. takes time to publish and more importantly slow in execution as well

## Screenshots

![image](https://user-images.githubusercontent.com/26645750/119021608-265ca600-b98f-11eb-99bc-06bda5ecc00c.png)

![image](https://user-images.githubusercontent.com/26645750/119021730-4b511900-b98f-11eb-8fa2-d314cfe4e8f0.png)

**Comment by ninggao** [comment] 2021-05-21 18:21
@cwhitten  Could you please route it to anyone who can help the customer?

**Comment by srinaath** [comment] 2021-05-21 18:26
@aparnaji When you add a skill, the Root bot to which you added gets trained with the LU from the skill by adding trigger to the root bot which in turn will call the skill. You would have received a prompt to use "Orchestrator" recognizer when adding the skill. The model.onnx is the Orchestrator recognizer. 

@taicchoumsft Correct me if im wrong. This is the base footprint of this model file (.onnx) right?

**Comment by taicchoumsft** [comment] 2021-05-21 19:39
Yes @srinaath , you are right, the onnx models are part of Orchestrator.  @aparnaji , you can revert back to using LUIS by switching the recognizer in that dialog back to `Default Recognizer`.  

However, we would urge you to try Orchestrator a bit longer.  Yes, there is a cost to using Orchestrator - deployments are slower.  But the recognition performance and inference speed should be better than previous options.  

If you are finding that inference speed has actually fallen, can you help us understand how you're deploying to Azure? (What size VM are you deploying on, 32-bit vs 64-bit, VM or WebApp/Functions, how much slower is it compared to LUIS etc. )

Thanks @aparnaji .

**Comment by hcyang** [comment] 2021-05-21 19:56
@aparnaji, Orchestrator is the STOA Transformer-based NLU technology, which is much superior than the existing/legacy LUIS technology, so I would not recommend you reverting back to using LUIS. Other than that, LUIS is a web service, so there is a fixed network latency for making a prediction, while Orchestrator is a library (plus downloaded ONNX models), thus no network latency.

We know there is an Composer bot deployment issue uploading the ONNX models to an Azure VM and we have a task (https://github.com/microsoft/BotFramework-Composer/issues/6773) for addressing that. Essentially the ONNX models should be downloaded/deployed directly to Azure directly as that is lightening fast between Azure data centers, while uploading an ONNX model to Azure can take some time using an ISP (internet service provide)'s asymmetric upload/download broadband service.

**Comment by aparnaji** [comment] 2021-05-22 17:26
Thanks all for detailed updates on ONNX models , Will observe further .  Some information on deployment, I deployed as webapp , P1V2 as app service plan ( I used Basic plan and as this is slow moved to bit higher plan)
also I had an additional issue with multilingual model "
Failed to find or load Model with path C:\home\site\wwwroot\model\pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual"

**Comment by hcyang** [comment] 2021-05-22 18:32
Hi @aparnaji, our engineers are aware of and fully understand the issue and have filed a bug to fix it. It should be a simple fix. Thanks for reporting it.

**Comment by srinaath** [comment] 2021-05-25 17:53
Closing this ticket. #7892 #6773  are tracked for R14 and would address the root cause of this issue.

**Closed by srinaath** 2021-05-25 17:53 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported
