### ISSUE TITLE
Cant create new bots, Error calling npm to fetch template.

### ISSUE THREAD

**Issue by EnzoBasile** [microsoft/BotFramework-Composer#9775] opened 2024-10-08 12:23 UTC
When creating a new bot, I receive the next error:
`Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\RY36863\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@*`

At first the software was not detecting nodejs, so after running again the installation the installation error was not prompted again. Now I am facing some error with the npm and can not figure out why.

## Version
Release: 2.1.2
SDK 4.12.0

## Browser
- [ ] Electron distribution
- [ x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [ x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Create New'
2. Click on 'Empty Bot'
3. Click on 'create', using the default options: Name "empty", Runtime type "Azure web App", Location "anywhere"
4. Note the windowd of "downloading template"
5. See error

## Expected behavior
Bot created

## Screenshots

![image](https://github.com/user-attachments/assets/d606a2c5-7612-4b81-a81a-a187b185ccad)

**Comment by dmvtech** [comment] 2024-12-23 20:38
Please run the following commands and report what is returned:

- `npm -v`
- `node -v`

Also, if you try and run the command on its own, does it work?
`npm install -g --prefix %userprofile%\AppData\Roaming\BotFrameworkComposer.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@*`

**Comment by dmvtech** [comment] 2024-12-31 00:19
Closing as duplicate of:
https://github.com/microsoft/BotFramework-Composer/issues/9769

Please monitor and comment there.

**Closed by dmvtech** 2024-12-31 00:19 UTC
Labels: Type: Bug, Needs-triage
