### ISSUE TITLE
Can't import intent utterances into the root .lu file (works everywhere else)

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5756] opened 2021-02-10 20:59 UTC
## Describe the bug
When I try importing LU utterances from another file into my root .lu file I get an error.

LU
```
# Help
- [Help](common.en-us.lu#Help)

# Logout
- [Logout](common.en-us.lu#Logout)
```

Error:
`
[ERROR] Loop detected for reference '[Help](C:\Users\lamil\Source\repos\microsoft\botframework-components\skills\declarative\calendarSkill\common.en-us.lu#Help)' as C:/Users/lamil/Source/repos/microsoft/botframework-components/skills/declarative/calendarSkill/language-understanding/en-us/calendarskill.en-us.lu -> C:/Users/lamil/Source/repos/microsoft/botframework-components/skills/declarative/calendarSkill/language-understanding/en-us/calendarskill.en-us.lu
`

The referenced intents are in another file, and work elsewhere in the project, so I'm not sure what is causing this looping error. I also tried moving the common.en-us.lu file outside of the project and providing the literal path but got this same error.

## Version
![image](https://user-images.githubusercontent.com/27976702/107571494-d2783f00-6b9f-11eb-9710-2bdc4f3cec69.png)

**Comment by lauren-mills** [comment] 2021-02-10 21:29
Also, I noticed that any imports from the root dialog also get pulled in when I reference the utterances from an intent in another file.

So, if I have this in root LU:
```
[Common](common.en-us)

# MyIntent
- test
- test 1
- test 2
```

Then reference MyIntent in another file like this:
```
# Test
- [MyIntent](root.en-us.lu#MyIntent)
```

The generated .lu for file 2 will also include everything from common.lu, which is not expected.

**Comment by srinaath** [comment] 2021-02-11 18:29
@lauren-mills  This is because of the bf-lu upgrade we made in the last nightly. To temporarily unblock you can shift to an earlier nightly. The issue is related to 

#5763

**Comment by srinaath** [comment] 2021-02-18 04:56
[https://microsoft-my.sharepoint-df.com/:u:/p/srravich/Ec1MCSCAzP1DhuUHr1SdaGkBvNFRHwRtHgtyWNBqCO0TsQ?e=Bp2upM](https://microsoft-my.sharepoint-df.com/:u:/p/srravich/Ec1MCSCAzP1DhuUHr1SdaGkBvNFRHwRtHgtyWNBqCO0TsQ?e=Bp2upM)

@boydc2014 the bot with the repro

**Comment by feich-ms** [comment] 2021-02-18 09:03
It seems a bug of importing. I will take a look.

**Comment by feich-ms** [comment] 2021-02-19 13:41
The importing dup contents issue in comment https://github.com/microsoft/BotFramework-Composer/issues/5756#issuecomment-777048352 will be fixed from bf-cli here https://github.com/microsoft/botframework-cli/pull/1124

**Comment by srinaath** [comment] 2021-02-26 19:58
@feich-ms Does the latest bf-lu incorporate this fix in bf-cli for us to leverage on Composer?

**Comment by feich-ms** [comment] 2021-03-01 03:06
@srinaath, yes, the fix was cherry-picked to https://www.npmjs.com/package/@microsoft/bf-lu/v/4.12.0-rc1. Composer can update from rc0 to rc1 to consume this fix.

**Comment by lei9444** [comment] 2021-07-15 07:28
The @microsoft/bf-lu has upgraded to 4.15.0-dev.20210702.cbf708d now, so close it

**Closed by lei9444** 2021-07-15 07:28 UTC
Labels: Team: Authoring, Type: Bug
