### ISSUE TITLE
USER scope variable values do not transfer to skill when SSO is configured

### ISSUE THREAD

**Issue by ramfattah** [microsoft/BotFramework-Composer#9533] opened 2023-03-08 00:07 UTC
Transferring data from root bot to skill bot using "user" scope variable does not seem to work when SSO is configured. 

Example tutorial to Transfer data between Root bot and Skill Bot in Bot Composer:
https://www.youtube.com/watch?v=_I7fhwJO7nU&ab_channel=LearnMicrosoftAI

Looks like issue occurs when using "user" scope instead of "dialog":
![MicrosoftTeams-image](https://user-images.githubusercontent.com/38049078/223584071-1ae0a5d3-c68c-4100-a859-0126329f87c2.png)

Single sign on for skills documentation:
https://learn.microsoft.com/en-us/composer/how-to-single-sign-on-skill

**Comment by ramfattah** [comment] 2023-03-08 00:08
Investigating further on this.

**Comment by ramfattah** [comment] 2023-03-08 04:36
Investigating further on this.

**Comment by ramfattah** [comment] 2023-03-13 21:13
I'm able to reproduce this issue. 

Example Composer setup of transferring data to skill:
![image](https://user-images.githubusercontent.com/38049078/224832177-6eed313a-742c-4505-9ebd-5b0ba4deffde.png)

See the Activity `value` property; when SSO OAuth is NOT configured, it's showing the appropriate user scope variable data (999):

```json 
{

“lgType”: “Activity”,

“text”: {

"type": "event",

"id": "d6ef52c0-c1c5-11ed-9543-6de6bb2c76c8",

"serviceUrl": "http://127.0.0.1:3981/api/skills",

"channelId": "emulator",

"from": {

  "id": "2969b251-0239-4ba5-8893-b411488fc245",

  "name": "User",

  "role": "user"

},

"conversation": {

  "id": "48a6a729-691e-4e84-adc1-e5cb4c5e3393"

},

"recipient": {

  "id": "d405c760-c1c5-11ed-9b3a-8d75c85f18b5",

  "name": "Bot",

  "role": "skill"

},

"locale": "en-US",

"value": "999",

"name": "startSkill",

"relatesTo": {

  "activityId": "d6ef52c0-c1c5-11ed-9543-6de6bb2c76c8",

  "conversation": {

    "id": "d4183df0-c1c5-11ed-9543-6de6bb2c76c8|livechat"

  },

  "channelId": "emulator",

  "locale": "en-US",

  "serviceUrl": "http://localhost:61197"

},

"callerId": "urn:botframework:aadappid:57501............................d73c"
}

} 
```

#

After SSO is configured, See the Activity `value` property. ("value": "999" does not show):
```json
{

“lgType”: “Activity”,

“text”: {

"type": "invoke",

"timestamp": "2023-03-13T10:33:30.0144756-07:00",

"serviceUrl": "http://127.0.0.1:3981/api/skills",

"channelId": "emulator",

"from": {

  "id": "e8046f07-d69e-4a7c-8072-fff5acf0c36f",

  "name": "User"

},

"conversation": {

  "id": "a98aa330-5a84-4e4b-a709-11b9dc289f24"

},

"recipient": {

  "id": "0eee4dd0-c1c5-11ed-b0ce-7fc2b507b10b",

  "name": "Bot",

  "role": "skill"

},

"locale": "en-US",

"text": "",

"attachments": [],

"entities": [],

"value": {

  "id": "2855bf...............b4c934",

  "connectionName": "<MyOAuthConnectionName>",

  "token": "eyJ0eXAiOiJKV1QiLCJhbGciO.................j4dSuCgGimnDyN1BXLvWtZg4WrltejhCqw"

},

"name": "signin/tokenExchange",

"relatesTo": {

  "conversation": {

    "id": "0efb9440-c1c5-11ed-b481-cd85d765d611|livechat"

  },

  "channelId": "emulator",

  "locale": "en-US",

  "serviceUrl": "http://127.0.0.1:3981/api/skills"

},

"callerId": "urn:botframework:aadappid:5750185.........................73c"
}

}
```

**Comment by ramfattah** [comment] 2023-03-13 21:40
Hi @ceciliaavila, 

It appears this issue is reproducible. Assigning this to you for now.

Please let me know if you have any questions.
Thanks.

**Comment by ceciliaavila** [comment] 2023-03-15 12:02
Hi @ramfattah, we added this one to our backlog. We'll let you know as soon as we have new information.
Thanks!

**Comment by sw-joelmut** [comment] 2023-03-20 17:38
Hi @ramfattah, we were able to reproduce the issue by following the provided steps.
Analyzing the behavior of the bots (root/skill), we can see that SSO is working as intended.
When transferring data, the skill receives the Activity from the root bot, but after the OAuth login step is executed, this Activity is no longer available as it's replaced with the [invoke activity](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Components.TokenExchangeSkillHandler/TokenExchangeSkillHandler.cs#L138) the root bot sends to exchange the token.

A workaround for this behavior could be creating a property to store the Activity before the OAuth login step happens, and then use this property to access the data.
![imagen](https://user-images.githubusercontent.com/62260472/226422098-dea1df2c-e0f2-42fc-919b-29b4a7381ecd.png)

The following image shows how the host and skill behave.
![imagen](https://user-images.githubusercontent.com/62260472/226422134-4f92c857-44cd-45a3-b747-40ca3b4c1a76.png)

**Comment by ramfattah** [comment] 2023-03-27 17:59
Hey @sw-joelmut, 

Thanks for sharing this information.

Indeed I'm able to see the Value in the skill before OAuth.

In regards to the workaround, I tried to create a property `user.myValue` to store the Activity value before OAuth. But it seems the property does not contain the activity value anymore after OAuth step. 
![image](https://user-images.githubusercontent.com/38049078/227651757-3363db5f-5863-4dca-8049-5d6e93bdeb1f.png)

Additionally, all my other "user" memory scope properties within the skill dialog are also erased after OAuth.
Example:
![image](https://user-images.githubusercontent.com/38049078/228026491-45ca3908-2385-4de9-8385-77dadf22aeef.png)
![image](https://user-images.githubusercontent.com/38049078/228026623-a820bd6b-6c53-4cd0-a1e0-c649fad7f732.png)

**Comment by sw-joelmut** [comment] 2023-03-28 18:38
We were able to reproduce the issue where the `user` scope variable loses the state after the OAuth step when using Emulator. Web Chat works as expected.
We will investigate why the scope variable is behaving this way, and let you know when we have some information.
![image](https://user-images.githubusercontent.com/62260472/228331775-6d720df8-9d7a-4280-8daa-9865a25cd4d1.png)

**Comment by ceciliaavila** [comment] 2023-03-31 19:23
Hi @ramfattah, we found the cause of the issue. The user scope is not saved in the state until there's an _endOfTurn_ in the dialog.
As the root bot interrupts the dialog flow to send the _token exchange_ activity, the skill saves its state later than it should, causing the issue.
We are working on a fix, forcing the saving of the state in the _SetProperty_ action.
Please, let us know if you have any questions.

**Comment by ramfattah** [comment] 2023-03-31 20:02
Thank you for the update @ceciliaavila.

**Closed** 2023-04-20 21:49 UTC
Labels: Type: Bug, customer-reported, Bot Services
