### ISSUE TITLE
Code editor not opening in Bot Composer

### ISSUE THREAD

**Issue by achint740** [microsoft/BotFramework-Composer#7833] opened 2021-05-14 16:43 UTC
When I add a trigger, Send a Response and go to the properties pane on the right and Click on Go to Code Editor,
it pops up : Something went wrong.....
![image](https://user-images.githubusercontent.com/42889869/118302174-88398d80-b501-11eb-9be7-eb8cb24da3fd.png)

**Comment by achint740** [comment] 2021-05-15 15:54
Error Detailed Screenshot 
![image](https://user-images.githubusercontent.com/42889869/118370115-dc0cab00-b5c3-11eb-8778-3626d755a3d8.png)

**Comment by zhixzhan** [comment] 2021-05-17 03:21
@achint740 Can you stable reproduce this error, or if you restart Composer still see this?

**Comment by achint740** [comment] 2021-05-17 05:00
@zhixzhan this error pops up even after restarting.
I have tried re-installing the Composer many a times as well.

**Reproduce the error**
1. Open any Bot.
2.  Go to a Dialog.
3.  Add "Send a Response field".
4.  Go to properties pane on the right. 
5. Switch to Code editor. This error pops up.

**Comment by zhixzhan** [comment] 2021-05-17 10:32
@achint740 can you share the bot? I did not see  this on latest build with empty bot example.

**Comment by achint740** [comment] 2021-05-17 11:53
@zhixzhan Here is the bot. I have attached the zip file.
Reproduce the error : 
1. Go to Greeting Dialog
2. Go to the empty trigger below the Welcome User trigger.
3. Select it and go to properties pane on the right.
4. Click on "Switch to Code Editor".
5. Error pops up, click on OK and the code editor goes to a locked "Loading State".

Reproduce the error (Way 2)
1. Go to Greetings Dialogue.
2. Click on "Show Code" in the top right.
3. Error pops up, click on OK and the editor goes to a locked "Loading State".

[BotSample_first.zip](https://github.com/microsoft/BotFramework-Composer/files/6493536/BotSample_first.zip)
![image](https://user-images.githubusercontent.com/42889869/118484171-8c012600-b734-11eb-85e6-c7d628f8ce5f.png)
![image](https://user-images.githubusercontent.com/42889869/118484085-7429a200-b734-11eb-97c4-4760def4efdb.png)

**Comment by ninggao** [comment] 2021-05-17 18:13
@zhixzhan I have assigned this issue to you. Please keep helping the customer on this issue.

**Comment by zhixzhan** [comment] 2021-05-18 01:02
@ninggao Sure, I can follow on this.

**Comment by zhixzhan** [comment] 2021-05-18 01:19
@achint740 Which Composer version are you using? I have try your bot on Composer v1.4.1 it works as expected.

![image](https://user-images.githubusercontent.com/49866537/118575885-02943700-b7ba-11eb-99ba-e8d01e497d9b.png)

**Comment by achint740** [comment] 2021-05-18 08:01
@zhixzhan I am using Bot version 1.4.1 only
![image](https://user-images.githubusercontent.com/42889869/118613810-ba3a4080-b7dc-11eb-9295-4afb7ebd45c9.png)

I have opened the same on Composer v 2.0, even after converting it shows the same!
![image](https://user-images.githubusercontent.com/42889869/118614390-506e6680-b7dd-11eb-8fb6-a7db6a4f59ef.png)

**Comment by zhixzhan** [comment] 2021-05-18 08:18
@achint740 Can this error reproduce on a new created bot ?  Are your using nodejs v14+ ？

**Comment by achint740** [comment] 2021-05-18 09:01
Yes, this error reproduces on every bot I create.

Node Version : 
![image](https://user-images.githubusercontent.com/42889869/118623198-a0512b80-b7e5-11eb-8840-8edb803961c9.png)

**Comment by zhixzhan** [comment] 2021-05-18 09:19
@achint740 Did you try add some other filed,  delete an existed filed, or add a trigger to see if it's LG only issue or all bot resources are not be able to write.
And if it is possible, can you record a video, it would be very helpful for us to debug it.

**Comment by achint740** [comment] 2021-05-18 10:19
@zhixzhan Here is the video. Might be a bit blur.

https://user-images.githubusercontent.com/42889869/118634763-879a4300-b7f0-11eb-8a3f-5fb89c1725e2.mp4

Also, I tried creating the Ask a Response trigger and the same issue pops up there.

![image](https://user-images.githubusercontent.com/42889869/118634857-9e409a00-b7f0-11eb-8f7d-75e4f4a12cdd.png)

**Comment by srinaath** [comment] 2021-05-18 16:45
@achint740 It looks you are running Composer inside a virtual machine. Could you see if you are able to repro it on a non VM instance. We have tried to repro this error and are unable to.

**Comment by achint740** [comment] 2021-05-18 16:52
@srinaath Yes I am running it on a Virtual Machine since I have to work on that only for my work. 
I tried it on a non-VM machine. No error there.
But the whole bunch of my work is on my VM only.

**Comment by srinaath** [comment] 2021-05-19 16:31
@achint740 Could you paste a snapshot of the Chrome Developer Tools, networks tab and console tab view for us to see what if any network calls are failing.

![Screen Shot 2021-05-19 at 9 26 15 AM](https://user-images.githubusercontent.com/13004779/118849218-5d926080-b884-11eb-8571-5a0460bca7e4.png)

@hatpick also identified that this PR https://github.com/microsoft/BotFramework-Composer/pull/5547 to download monaco and fabric assets would allow offline usage of the assets.  @jwiley84 also something to consider in investigating this ticket.

**Comment by achint740** [comment] 2021-05-19 18:03
Console 
![image](https://user-images.githubusercontent.com/42889869/118861559-43936500-b8fa-11eb-8ad1-bed2f59803ad.png)

Network 
![image](https://user-images.githubusercontent.com/42889869/118861664-632a8d80-b8fa-11eb-8786-659caae0cc85.png)

@srinaath

**Comment by srinaath** [comment] 2021-05-19 18:10
@hatpick We can definitely confirm your investigation. https://github.com/microsoft/BotFramework-Composer/pull/5547/files#diff-96bd06513353b0cd4b08269cfe491f21242a411b7189a5017e2735c68021c1a1R8. The network call fails at loading monaco.

**Comment by zhixzhan** [comment] 2021-05-20 01:48
@srinaath Are you saying this error is caused by some resource of Monaco editor didn't load, or network issue in VM ?  I tried offline open Composer, when I click a trigger, it popup error immediately, seems different from this case.
![image](https://user-images.githubusercontent.com/49866537/118905861-276de300-b94f-11eb-8872-d5ae8f2546ea.png)

Could this caused by some file system write issue in VM? In @achint740 's video, when delete a trigger will also meet this error, even Monaco editor is not opened

**Comment by boydc2014** [comment] 2021-05-20 02:13
> @srinaath Are you saying this error is caused by some resource of Monaco editor didn't load, or network issue in VM ? I tried offline open Composer, when I click a trigger, it popup error immediately, seems different from this case.
> ![image](https://user-images.githubusercontent.com/49866537/118905861-276de300-b94f-11eb-8872-d5ae8f2546ea.png)
> 
> Could this caused by some file system write issue in VM? In @achint740 's video, when delete a trigger will also meet this error, even Monaco editor is not opened

FS is less likely to have issues, and even when it have issues, it's an issue in persistence layer and the error message should be clear. 

I guess it's still related to manaco editor, and probably the firewall\NSG in VM blocks the manaco editor download. 

How about we create a customized build including @liweitian's previous fix and ask customer to try again?

**Comment by zhixzhan** [comment] 2021-05-20 04:09
I created a build task on the Monaco fix branch.
https://fuselabs.visualstudio.com/Composer/_build/results?buildId=246786&view=results

**Comment by zhixzhan** [comment] 2021-05-20 05:28
@achint740 Here I uploaded the above fixed build, can you try it? 
https://github.com/zhixzhan/BotFramework-Composer-1/releases/tag/v2.0.0

**Comment by achint740** [comment] 2021-05-20 06:26
@zhixzhan thankyou so much for your co operation.
I installed the fixed build. It's working all fine. No error.
The code editor is opening as well :)
![image](https://user-images.githubusercontent.com/42889869/118929430-20040500-b962-11eb-81dc-870aaf6ba4ff.png)
![image](https://user-images.githubusercontent.com/42889869/118929468-301be480-b962-11eb-84ed-7e5f4fcd8a2e.png)

Thanks to @srinaath @boydc2014 and @ninggao and all others for helping out

**Comment by srinaath** [comment] 2021-05-21 15:45
We will look to incorporate this PR in our next release. @liweitian  can we make sure this PR gets merged. Thanks. Closing the ticket now

**Closed** 2021-05-21 15:46 UTC
Labels: Bot Services, Support, customer-replied-to, customer-reported
