### ISSUE TITLE
Cannot publish Bot to Azure

### ISSUE THREAD

**Issue by fathorMB** [microsoft/BotFramework-Composer#2387] opened 2020-03-26 16:38 UTC
## Describe the bug

We're trying to deploy out bot made with the Composer App with the publish workflow provided in the application. Our bot is also using LUIS services.

We're experiencing issues when launching the publish script and looks like it has to do with the proper LUIS resource configuration. We already did publish this specific bot in the past using the same process.

The problem began when updating to the last stable of the composer.

## Version

4.7.0-preview-191208-1

## Browser
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Follow the publish procedure provided in the composer app.
This is the error i get.

## Screenshots

![image](https://user-images.githubusercontent.com/13238241/77671804-65a88600-6f88-11ea-994e-662eb56aafef.png)

**Comment by zidaneymar** [comment] 2020-03-27 12:05
@fathorMB Hi, did you meet the same error like this:
![image](https://user-images.githubusercontent.com/9328933/77754323-120c6a00-7066-11ea-90d8-2bf5c0ca89ca.png)

@hibrenda  This is caused by empty model error in luis build. Will be fixed in #2402

**Comment by fathorMB** [comment] 2020-03-27 13:01
@zidaneymar Yes, that's an error we get before the lubuild succeeded message. All this happens before the 401 error.

**Comment by cwhitten** [comment] 2020-03-30 19:53
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2402

**Closed by cwhitten** 2020-03-30 19:53 UTC
Labels: R9, Type: Bug
