### ISSUE TITLE
Be able to run multiple instances of Composer...

### ISSUE THREAD

**Issue by hristp** [microsoft/BotFramework-Composer#3211] opened 2020-05-28 18:28 UTC
... Or have some way to easily flip between 2 bots.

For example, I've done the weather bot tutorial and want to create my own bot with a similar structure.  I know the concepts but I'm not comfortable yet with all the properties I need to set, so I want to be continuously looking at a working for as a reference.

It would be great if I can have multiple instances of Composer/multiple bot tabs/whatever other solution, so that I can easily flip between them, to verify my syntax.

**Comment by hibrenda** [comment] 2020-05-29 09:48
https://github.com/microsoft/BotFramework-Composer/issues/3091

**Comment by cwhitten** [comment] 2020-05-31 20:23
Closing as dupe of https://github.com/microsoft/BotFramework-Composer/issues/3091

**Closed by cwhitten** 2020-05-31 20:23 UTC
Labels: Type: Enhancement
