### ISSUE TITLE
Bot Responses Overview includes comments

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4822] opened 2020-11-16 08:18 UTC
In the overview of the bot responses comments (prefixed with '>>') are included by the preceding entry;

![image](https://user-images.githubusercontent.com/49873947/99228164-8ad65700-27ec-11eb-8523-d117a1d8773b.png)

![image](https://user-images.githubusercontent.com/49873947/99228253-a3df0800-27ec-11eb-9425-48c42970db23.png)

**Comment by cwhitten** [comment] 2020-11-16 18:22
@zhixzhan can you look at this?

**Comment by zhixzhan** [comment] 2020-11-17 03:27
Sure, thre current LG template parsing policy is take everting above next `#templateName` as previous template's body. I can discuss with @boydc2014 and @Danieladu to see how to improve it.

**Comment by hcyang** [comment] 2020-11-30 19:41
@boydc2014, can you take a look and comment?

**Comment by Danieladu** [comment] 2020-12-01 01:49
The comments can be defined everywhere, it is hard to decide which template the comments belong to. 
For example: 
```
# t1
- hi


> comment1
- t2
- hi
```

```
# t1
- hi

> comment1

- t2
- hi
```

```
# t1
- hi
> comment1

- t2
- hi
```

```
# t1
> comment1
- hi

- t2
- hi
```

The current policy is to treat the template name as the start of the template, and all the contents before the next template as the "whole" body of the current template. 
We suggest you put the comments under the template name, that may help.

**Comment by hcyang** [comment] 2020-12-01 02:13
@cxbuilders, please try @Danieladu's suggestion. If no objection, this issue can be closed.

**Comment by cxbuilders** [comment] 2020-12-01 07:04
@hcyang but they are comments.. one would expect those to be only visible in the code view and just completely ignored in the tabular view??

**Comment by hcyang** [comment] 2020-12-01 07:31
Hi @cwhitten, @Danieladu, @zhixzhan, and @boydc2014,

Please address @cxbuilders' concern and lead to a conclusion, either create a work item stripping the comments or treat lg comments as designed (per @Danieladu's workaround suggestion).

https://github.com/microsoft/BotFramework-Composer/issues/4996

**Comment by taicchoumsft** [comment] 2020-12-15 19:24
@boydc2014 , looks like this issue has been open for awhile, is there a response for this?

**Comment by boydc2014** [comment] 2020-12-16 04:04
Hi, @hcyang @taicchoumsft, sorry for the late response. 

@cxbuilders As @Danieladu explained above, the current parser is treating all the content before the next template as it's body, just for the simplicity. Which ends up you see the comments right before the next template is "classified" to the template above. The fix can be updating the parser to give the comments a dedicated position. 

That is technical doable, but we are not sure at this moment we want to do that change in parser, because we are not sure about this should be fixed in the parser side, or in the table view side. For example, the reason a traditional programming language don't have this problem is not because their parser is stronger, it is because, they don't provide this table view.  So, if we feels like this table view of comments is confusing, probably we should fix the table view, instead of making the parser more complicated. 

The reason we didn't strip all the comments lines in the tabular view is because the original design is to make it editable. If we strip all comments and allow editing, then we have to merge the comments back to the content. This can be pretty hard because we allow comments inside the body, which might get updated and we will loose the anchor for merging.

At this moment, I will suggest you put the comments inside the template. And our design team are revisiting at the design side, what features and UX we want to provide at the tabular view, as part of the overall review of this page's experience. I think we will wait until the comes out, to make technical changes if necessary. 

cc @hcyang, @vivekkshankar, @GeoffCoxMSFT, @cwhitten.

**Comment by chrimc62** [comment] 2021-01-06 03:22
Comments are an important part of the LU file format and definitely need to be preserved in the file.  I suspect they are also useful in the table view.  From a parser standpoint, I believe the issue is that comments are treated as trailing and that is almost never what you want.  In the below, I think comments immediately preceding a template should be part of the template, i.e. 1 below should be with foo and 2 with blah.  The main question is what to do with the floating comment ??? in between.  I would lean towards treating it as its own body.  If we do change the parser behavior I know some other things will need to change as well like the form generator merging.

> 1. foo prompt
# foo
- something
- else
> 1. TODO: - and more

> ????. Some section

> 2. blah prompt
# blah

**Comment by Virtual-Josh** [comment] 2021-02-08 19:37
closing due to inactivity

**Closed by Virtual-Josh** 2021-02-08 19:37 UTC
Labels: Backlog, Bot Services, Type: Bug, customer-replied-to, customer-reported
