### ISSUE TITLE
Access token expiry error message

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#8367] opened 2021-07-12 22:27 UTC
## Describe the bug

When switching to the "create" tab, I receive an error like

```
If this problem persists, please file an issue on GitHub
Details
The access token expiry UTC time '7/12/2021 9:05:06 PM' is earlier than current UTC time '7/12/2021 10:25:43 PM'.
```

## Version

Bugbash nightly

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot in Composer
2. Login (I think this is required)
3. Navigate away from the "Create" tab
4. Navigate back to the "Create" tab
5. Observe error

## Expected behavior

Don't get an error

## Screenshots

![image](https://user-images.githubusercontent.com/1139814/125363551-aebf4d80-e325-11eb-971d-8929449c10e3.png)

**Comment by mewa1024** [comment] 2021-07-12 22:31
I also got this error right after creating a new bot with the Empty bot template.

**Comment by benbrown** [comment] 2021-07-13 16:38
@clearab @mewa1024 did this happen after several hours of use?

**Comment by mewa1024** [comment] 2021-07-13 16:41
I updated to the nightly at the start of the bug bash and then saw the error within the first hour of use. I can't remember if I closed it before updating.

**Comment by benbrown** [comment] 2021-07-13 16:42
> I updated to the nightly at the start of the bug bash and then saw the error within the first hour of use. I can't remember if I closed it before updating.

INTERESTING, so this didn't happen after using the new auth system? Perhaps there was an older token from prior use in your app cache.

**Comment by mewa1024** [comment] 2021-07-13 17:01
Oh, it might have. I think the first thing I did when I restarted was create a new Enterprise Assistant bot and set up LUIS and QnA.

**Comment by clearab** [comment] 2021-07-13 17:58
For me it was a few hours I think, but I'm not sure. I was bouncing around between a lot of things before I first noticed it.

**Comment by benbrown** [comment] 2021-07-13 21:30
This was caused by a background API call firing. When the token was invalid, it would pop up this error. However, it should not be firing the api call in the background - only when called into action by a user.  The attached PR will reduce the calls to this API and prevent the error from appearing mysteriously.

**Closed** 2021-07-14 16:46 UTC
Labels: P0, R14 Bugbash, Type: Bug
