### ISSUE TITLE
_interruption intent not automatically added to the LUIS app on turning on "Allow interruption" for the text prompt

### ISSUE THREAD

**Issue by ridasaleem0** [microsoft/BotFramework-Composer#8823] opened 2021-12-01 09:43 UTC
I am having trouble while working with interruptions in my composer bot, turning on the "Allow interruption" for the text prompt doesn't actually allow global intents to be detected within the child dialog.
When I go and check my LUIS app for that dialog, there is no _interruption intent generated, I am not sure what's the reason?

**Comment by ridasaleem0** [comment] 2021-12-01 09:45
@cwhitten

**Comment by ridasaleem0** [comment] 2021-12-02 07:49
@stevkan still stuck, any leads?

**Comment by dmvtech** [comment] 2021-12-06 19:05
Hi @ridasaleem0 I'm not sure either. Are you able to share a simple reproduction in a github repository (doesn't have to be your actual LU/LG, just anything that reproduces the issue)? You can add conditions in certain locations to help things. But I'm not sure what is going on with your scenario without seeing more specifics.

**Comment by dmvtech** [comment] 2021-12-16 23:39
hi @ridasaleem0 Is this still an issue for you? Are you able to share a repro or share any simple steps to reproduce the behavior?

**Comment by dmvtech** [comment] 2021-12-18 00:28
Closing due to lack of reply. Please comment or reopen if assistance is still needed.

**Closed by dmvtech** 2021-12-18 00:28 UTC
Labels: customer-reported, Bot Services, customer-replied-to

**Comment by 2015manna** [comment] 2022-08-09 07:41
Hi @ridasaleem0 , I am new to bot composer. I don't need the _interruption to be generated but I couldn't find the "Allow Interruption" setting. Can you please guide me where to find this setting and stop the generation of _interruption intent ?
