### ISSUE TITLE
Migration from Composer 1.4 to Composer 2.0

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7444] opened 2021-04-28 05:59 UTC
## Describe the bug

Tested the flow of migrating Composer 1.4 to Composer 2 and opening a 1.4 bot and converting it.

Three issues but not sure if they are specific to the migration flow:
- after installing the update Composer did not restart automatically
- in "Create a bot project", the Name is prefilled as undefined and Runtime Type is empty (already reported in #7373)
- when converting one of the projects, got an error "Command failed: dotnet build filename.csproj"
- in the flow for adding a LUIS resource choosing an existing LUIS resource opens UI asking for ARM tokens instead of opening the Azure sign in flow 
- with a bot with ejected runtime, it seems like the first time I tried to convert the bot, it just copied it and didn't convert it
- for the bot with the ejected runtime, the modal did not warn me that any custom actions would be deactivated (is that because we can detect that it had no custom actions?) 

## Version

build created for testing this flow: [https://fuselabs.visualstudio.com/Composer/_build/results?buildId=240184&view=results](url)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Installed build listed above and follow instructions here: [https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/EYasxKrkpXlHs4fRPrlMmE4BsGmKiX4aij11YLNy0QLNcA?e=w3AI7s](url)
2. When 1.4 opened, saw the "Composer 2.0 is now available!" and clicked "Update and restart"
3. When the update was complete, got the modal "Update is complete. Composer will restart" and clicked Okay.
4. Composer closed but never restarted. 
5. Opening Composer manually opens 2.0
4. Opened an existing ToDoBotwithLUIS bot, saw the modal to convert and pressed "Convert".
5. In "Create a bot project", the name was prefilled as "undefined" and Runtime type was empty:
![image](https://user-images.githubusercontent.com/39317542/116350968-aab07480-a7a7-11eb-9791-928ebfebd0de.png)

6. named bot and clicked Okay.
7. Progress indicators started. After the message "Building runtime" got this error:
![image](https://user-images.githubusercontent.com/39317542/116351067-d7fd2280-a7a7-11eb-973b-a651fab80fc4.png)

8. Clicked OK and clicked Open to see if the bot was created anyway. It didn't appear in the MRU or the Open bot menu (looking for a folder or bot called ToDoBotWithLuisSampe_0_adaptive):
![image](https://user-images.githubusercontent.com/39317542/116351679-e8fa6380-a7a8-11eb-9699-9aa2e5f9397b.png)

9. Closed and reopened Composer and it did appear in the MRU:
![image](https://user-images.githubusercontent.com/39317542/116351236-28748000-a7a8-11eb-999d-71d12c46cd54.png)

10. Opened the bot and it seemed fine, but could not add LUIS resource through UI because I hit this screen:
![image](https://user-images.githubusercontent.com/39317542/116351367-6671a400-a7a8-11eb-9f30-1b1d153e6be9.png)

11. Copied the key manually and then everything was fine.

I did the same flow with the AskingQuestions sample bot and everything worked fine.

I did the same step son a ToDoBotwithLUIS sample with ejected runtime and got this at step 7:

"EEISDIR illegal operation on a directory open '/Users/melaniewang/bots/ToDoBotWithLuisSample_0427_ejected_adaptive/ ToDoBotWithLuisSample_0427_ejected_adaptive'
![image](https://user-images.githubusercontent.com/39317542/116352201-a6855680-a7a9-11eb-8151-e0348e9ce566.png)

then closed and reopened Composer, and the converted bot appeared in the MRU, but clicking on I got the modal that it was an older format and needed to be converted:
![image](https://user-images.githubusercontent.com/39317542/116353454-a38b6580-a7ab-11eb-8081-de920f807879.png)
![image](https://user-images.githubusercontent.com/39317542/116353467-aab27380-a7ab-11eb-9e9f-3121e7e8b969.png)

But it looked like it had already been converted?
![image](https://user-images.githubusercontent.com/39317542/116353571-db92a880-a7ab-11eb-9d9e-7c3a29c2edec.png)

converted it again with a new name, got the "dotnet build error" again:
![image](https://user-images.githubusercontent.com/39317542/116353668-0d0b7400-a7ac-11eb-81c3-080d5ee0627f.png)

Closed and reopened Composer again, the second converted bot opened fine.

**Comment by srinaath** [comment] 2021-04-28 22:08
Adding another issue seen on the runtime migration branch. The window.isElectron variable is not set due to preload.js script not loading (closely related [fix: refactor way we get COMPOSER\_VERSION by a-b-r-o-w-n · Pull Request #7326 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/7326)

Any features that need to be enabled specifically in the Electron context are not working on the branch. For ex settings to fetch the latest nightly

![](https://user-images.githubusercontent.com/13004779/116478695-55ba4000-a833-11eb-801c-892b04afc3d3.png)

**Comment by cwhitten** [comment] 2021-04-28 22:09
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/7373, please communicate on that ticket

**Closed** 2021-04-28 22:09 UTC
Labels: P0, R13 Bugbash, Type: Bug
