### ISSUE TITLE
How to get the image url of attached image in Bot Framework Composer?

### ISSUE THREAD

**Issue by BhogiSupriya** [microsoft/BotFramework-Composer#9564] opened 2023-04-23 16:37 UTC
I am trying to use the prompt for a file/attachment to upload an image but after uploading an image it's throwing the exception 'Object reference not set to an instance of an object.'
please refer below images

![image](https://user-images.githubusercontent.com/131548272/233852482-b22848ac-a31a-41b4-a49a-6f408d2d20ef.png)

![image](https://user-images.githubusercontent.com/131548272/233852524-559b723b-a812-4537-b529-fb7e278e534b.png)

**Comment by anishprasad01** [comment] 2023-04-24 16:57
Duplicate of https://github.com/microsoft/BotFramework-Composer/issues/9563

**Closed by anishprasad01** 2023-04-24 16:57 UTC
Labels: Needs-triage, feature-request
