### ISSUE TITLE
Form dialogs: restarting a bot with minimal or no changes takes over 1 minute

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4887] opened 2020-11-19 01:35 UTC
## Describe the bug

Starting a bot from Composer that has a form dialog takes over 1 min, even when there are no changes.

## Version

main branch, November 18

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Turn on the form dialog UI by going to Settings > App settings > Preview features and selecting "Form dialogs."
2. Create a form by clicking on the table-looking icon in the side nav, pressing the + button in the Schema pane, and adding a name. Add properties (or you can import a sample form schema form here: [https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas](url)
3. Generate the dialog by pressing the "Generate dialog" button.
4. Start bot.
5. Restart bot (even without making changes).

The message said "Publishing" for around a minute, then switched to reloading, but there were no changes to .lu files and no new models were uploaded to luis.ai (as far as I could tell from luis.ai).

## Expected behavior

I would expect the time to restart would be much shorter when there are no changes to the property schema or language model.

## Screenshots

Screen right after pressing "Restart bot":
![Screenshot (695)](https://user-images.githubusercontent.com/39317542/99609258-603ef680-29c4-11eb-8ee0-792bd81cf9d6.png)

Screen a minute later after message changed to "Test in Emulator":
![Screenshot (696)](https://user-images.githubusercontent.com/39317542/99609293-72b93000-29c4-11eb-9c78-6d10bf7d4986.png)

**Comment by GeoffCoxMSFT** [comment] 2020-12-02 21:45
@cwhitten - Does the LU build run every publish?  (We suspect this is the cause of the long publish time).  Who on runtime/publishing should this go to? (I don't think this is a form-dialog specific issue).

**Comment by cwhitten** [comment] 2020-12-08 21:48
@GeoffCoxMSFT it shouldn't republish LUIS models if there are no changes. cc @boydc2014 @zhixzhan

**Comment by GeoffCoxMSFT** [comment] 2020-12-08 22:43
I created a bot (form dialogs) and published it.  Took ~2:30 to publish and have running.  Then stopped it and updated only the top level dialog to start the child dialog right after the Greeting action.  Published again and it too ~2:20 to publish and have running again.

**Comment by chrimc62** [comment] 2020-12-09 01:11
This is caused by down sampling being run on every publish which causes the model to be different.  Downsampling is also dropping utterances.  Once we stop down sampling this should be fixed.

**Comment by cwhitten** [comment] 2021-02-11 23:36
This was addressed before release. Closing.

**Closed by cwhitten** 2021-02-11 23:36 UTC
Labels: Area: Form Dialogs, Team: Runtime & Publishing, Type: Bug
