### ISSUE TITLE
Does Composer support Adaptive Card Templating?

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/BotFramework-Composer#5662] opened 2021-01-29 23:36 UTC
Or I can only use lg templates to form the Adaptive Cards json?

**Comment by jwiley84** [comment] 2021-02-01 17:07
Closing as a duplicate of https://stackoverflow.com/questions/65962556/does-adaptive-cards-templating-work-in-composer

**Closed by jwiley84** 2021-02-01 17:07 UTC
Labels: Bot Services, Needs-triage, customer-reported
