### ISSUE TITLE
WeatherBot : After deployment, shows "Invalid URI: The hostname could not be parsed"

### ISSUE THREAD

**Issue by deenaMaistering** [microsoft/BotFramework-Composer#2032] opened 2020-02-20 12:29 UTC
After deploying the weather bot as a web app, it is not recognizing the intents (which is using LUIS recognizer) and shows "Invalid URI: The hostname could not be parsed". The same works fine when I try it in the composer before deployment.
![Screenshot (43)](https://user-images.githubusercontent.com/55096753/74933135-60946c00-5409-11ea-97e5-cb51f782e4d9.jpg)

**Comment by luhan2017** [comment] 2020-02-21 02:45
@deenaMaistering ， did you use our deployment script to deploy? there is a logic to generate the hostname in the deployment script, it will be missed if we don't use the script to deploy.

**Comment by hibrenda** [comment] 2020-02-21 05:32
https://github.com/microsoft/BotFramework-Composer/issues/2001 @deenaMaistering  should I close this one ?

**Closed** 2020-02-23 20:45 UTC

**Comment by ismendes** [comment] 2020-03-10 23:09
I'm using the composer but I'm not using it to deploy in our environment. What should I change in my deploy script to fix this error?

**Comment by jst84** [comment] 2020-03-16 17:22
Hi! the problem is the bot's appsettings.json. In particular, the LUIS url that the bot have to call. Publish process via cli change this appsettings.
If you want to do the manual process, you have to set this keys. Here an example of working appsettings:
``
{
  "bot": "ComposerDialogs",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "",
    "cosmosDBEndpoint": "",
    "databaseId": ""
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": ""
  }, 
  "qna": {
    "knowledgebaseid": "",
    "endpointkey": "",
    "hostname": ""
  },
  "MicrosoftAppId": "",  
  "MicrosoftAppPassword": "", 
  "luis": {
    "endpoint": "", //luisurl
    "endpointKey": "", //luiskey
    "Main_en-us_lu": "" //luisappid
  }
}
``
If you want to try, you can publish bot by follow the instruction and then see the appsettings.json.
NB. the deployment process set MicrosoftAppId & MicrosoftAppPassword in the azure appservice settings.

**Comment by RussHelfand** [comment] 2020-03-17 18:38
Hi @js84, I work with @ismedes. Thank you for your answer (above). It solved a problem that we've been struggling with for several days. We now have a system where we can edit with Composer, then have Visual Studio notice the changes to the files so we can check them into our private Git repository (via ADO), and the publish them via Azure pipelines' continuous deployment. Works like a charm... now that we have the 3 new settings that you pointed out (above) for our luis configuration! Again, thanks.
