### ISSUE TITLE
Resource Group Name Validation Not Needed When Creating Publish Profiles.

### ISSUE THREAD

**Issue by daronyondem** [microsoft/BotFramework-Composer#5414] opened 2020-12-29 12:20 UTC
The deployment wizard warns the user that the resource group exists. However, the existence of it is not a problem at all.

![image](https://user-images.githubusercontent.com/2984187/103283016-7d65dc80-49e8-11eb-8888-837edb8b95b9.png)

When the user fills in the `HostName` first and selects the subscription next, the wizard validates the input, and the deployment can proceed with no issues. 

I suggest the validation be removed.

![image](https://user-images.githubusercontent.com/2984187/103283133-c6b62c00-49e8-11eb-98f8-2408795e40f1.png)

This will help with the confusion of having three different field descriptions as well. From what I can tell, **Resource Group Name** is the correct one.

![image](https://user-images.githubusercontent.com/2984187/103283200-f402da00-49e8-11eb-9425-4818e96f313a.png)

This is on Bot Framework Composer v1.3.0. I hope it helps. Thanks.

**Comment by gabog** [comment] 2021-01-04 19:54
Thanks @daronyondem, @luhan2017 will look at the PR and merge it if it gets accepted.

**Comment by VanyLaw** [comment] 2021-01-05 09:56
Thanks @daronyondem. For you first scenario, currently, we need to deploy resources in a new resource group. Because we use the `HostName` to create different resources name. Like if you input `test` in HostName, we will use it as resource group name, and use it as webapp service name, and if you need luis or other resources, we will use it `test-luis`, `test-luis-authoring` as those resource name, so we add a validation there, to check if the resoruce group is existed or the name is the same as webapp service.

But as you said, it's a little bit confused, so we will have a discussion about how to improve this.

**Comment by daronyondem** [comment] 2021-01-05 10:01
Hi, @VanyLaw Are you sure you **need to** deploy resoıurces in a new resource group? I successfully deployed to existing resource groups multiple times as long as the other resources you are provisioning, such as webapp, etc do not conflict. I'm not against the check for the other resources. I just don't see value in checking the existence of the resource group, because as of right now the app is able to deploy to an existing resource group as well. I hope this makes sense.

**Comment by VanyLaw** [comment] 2021-01-05 10:07
@daronyondem Sure, I will change the resource group checking.

**Comment by daronyondem** [comment] 2021-01-29 10:27
Hi guys,

I had the same PR here https://github.com/microsoft/BotFramework-Composer/pull/5420/files. Instead of merging that you preferred submitting the same under a different name. Intended or not, such behavior is hostile and discouraging to future open source contributors. I hope this feedback helps you increase your inclusiveness to outside contributors.

I'm happy the original issue is not resolved. Thanks for your efforts.

**Comment by luhan2017** [comment] 2021-02-01 05:57
@daronyondem that must be some misunderstanding here, PR #5446 is closed just because we found it is duplicated with your PR. we want to merge your PR instead of creating a new one.  I approved your PR and thought it will be merged. But it seems it is not merged yet, so the problem is still there. would you mind to reopen your PR and I will merge it as soon as possible.

**Comment by daronyondem** [comment] 2021-02-01 10:16
Hi @luhan2017 please proceed with your pull request instead. I have deleted my fork as part of my monthly clean up. It has been waiting since December 30th. Sorry.

**Comment by luhan2017** [comment] 2021-02-02 06:09
@daronyondem Sure, I will make sure the issue will be fixed soon. Sorry again for the misunderstanding. We are more than happy to see the PRs from the community. Hope you don't mind :)

**Closed** 2021-02-09 06:01 UTC
Labels: Bot Services, customer-replied-to, customer-reported
