### ISSUE TITLE
orchestrator package does not installed correctly after bot migration

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7667] opened 2021-05-06 08:35 UTC
## Describe the bug

dotnet build error 

## Version

Latest electron nightly

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Migrate old empty bot to new bot
2. Install orchestrator package successfully ?
![image](https://user-images.githubusercontent.com/43408889/117262357-bbd24300-ae83-11eb-8d3b-c3aeeaf8e576.png)
But not showed up in installed page
![image](https://user-images.githubusercontent.com/43408889/117264533-e32a0f80-ae85-11eb-8f94-a7bb64912b62.png)
3. switch recognizer to orchestrator 
4. Start bot see error
![image](https://user-images.githubusercontent.com/43408889/117262451-d99fa800-ae83-11eb-9acd-4589c347b4ac.png)

5. deep dive into the erros, start bot error introduced by another task occupied
![image](https://user-images.githubusercontent.com/43408889/117275915-1e7e0b80-ae91-11eb-9999-efdeff21d719.png)

* Kill this process, start bot  can pass. (Everytime I click "install orchestrator" package in package model with nuget feed will generate this zombie process ? and then lead to the bot build error ?) But if I switch to the daily feeds, looks like package installed correctly. 
![image](https://user-images.githubusercontent.com/43408889/117264970-5a5fa380-ae86-11eb-9c76-9f390e907837.png)
Bot can run but test in emulator will hit following error .
![image](https://user-images.githubusercontent.com/43408889/117266979-5f255700-ae88-11eb-9bf1-9318bc644c84.png)

* If I created the new empty bot with this electron nightly, install orchestrator and run bot can worked fine.
* After migration , root bot can work correctly with luis recognizer. 

## Expected behavior

* If orchestrator package installed failed, need to show error to user
* orchestrator package should be installed to my legacy bot 

@taicchoumsft need your suggestion . anything wrong with my old bot ?

**Comment by boydc2014** [comment] 2021-05-06 10:35
I can't repro this with my previous created empty bot, can you attach your bot?

**Comment by hibrenda** [comment] 2021-05-06 11:18
[rootbot-oldbot.zip](https://github.com/microsoft/BotFramework-Composer/files/6433986/rootbot-oldbot.zip)

**Comment by benbrown** [comment] 2021-05-06 16:12
Dupe of #7670

**Closed by benbrown** 2021-05-06 16:12 UTC
Labels: P0, Type: Bug
