### ISSUE TITLE
Cannot sign-in / publish to Bot Composer

### ISSUE THREAD

**Issue by maydaystella** [microsoft/BotFramework-Composer#8817] opened 2021-11-25 08:30 UTC
## Describe the bug

 I have signed in so many times but ended up having error "Sign in failed: failed to fetch" after updating to 2.1.1

## Version

 2.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Sign in to BOT composer
2. Click on Publish
3. "Okay" cannot be clicked even if successful login

## Expected behavior

 "Published successfully"

## Screenshots

![image](https://user-images.githubusercontent.com/93115365/143406291-1eb22b5e-29fe-4514-b260-0f84260a1227.png)

**Comment by anishprasad01** [comment] 2021-11-25 17:17
Hi @maydaystella,

I'd like to get a bit more information from you so that we can try to solve your issue.

- The name of your bot implies this is a corporate Azure account. Is this correct?
- Are you having any issues with Active Directory, or reaching other services?
- Does your Azure account have a subscription?
- Are you able to create Azure resources within the Azure portal itself or though the Azure CLI?
- Are you only having this issue on Composer 2.1.1? Does downgrading fix the issue?
- Have you attempted any standard troubleshooting steps like reinstalling Composer and/or rebooting your machine?

**Comment by maydaystella** [comment] 2021-11-26 00:33
Hi @anishprasad01 

The name of your bot implies this is a corporate Azure account. Is this correct? Correct
Are you having any issues with Active Directory, or reaching other services? None
Does your Azure account have a subscription? Yes
Are you able to create Azure resources within the Azure portal itself or though the Azure CLI? Not sure. I am not an IT/SysAdmin of our company
Are you only having this issue on Composer 2.1.1? When I had it yesterday at Ver 2.1, it is already like that that's why I tried to update because it keeps on pushing me to update to ver 2.1.1. Usually the first thing that triggers is "update bot or Import as new"
Does downgrading fix the issue? Im not sure
Have you attempted any standard troubleshooting steps like reinstalling Composer and/or rebooting your machine? I rebooted my laptop but still the same

**Comment by anishprasad01** [comment] 2021-11-26 01:07
I assume you've been able to publish bots before? The error message `No Azure Directories were found` implies an access issue, though we can't rule out that there's a bug somewhere. I am able to create resources and publish bots to Azure, so thus far I haven't been able to reproduce this bug.

Let's try a few things. Start from the top, and keep going if it doesn't work:

- Reinstall Composer 2.1.1
- Uninstall Composer 2.1.1 and try Composer 2.0.0
- Check to see if you are part of an Azure Directory. You can do this by [logging in to Azure](https://portal.azure.com), clicking on your account name in the top right, and then clicking on `Switch Directories`. You should see at least one directory in this menu. The current one will be marked as such.

You can find Composer releases and installers [here](https://github.com/microsoft/BotFramework-Composer/releases).

Once we know the results of these tests, we can try to hone in on what the problem is.

**Comment by maydaystella** [comment] 2021-11-26 02:21
Hi @anishprasad01 

I uninstalled and reinstalled composer 2.1.1 and I was able to successfully publish. However, I have to sign in again before I can publish. That means I have to sign in upon opening the app and sign in again before publishing.

Checked also and I am a member of Azure Directory

**Comment by anishprasad01** [comment] 2021-11-26 16:16
I too have to sign-in again every time I publish, so I'll need to double check to see if that's expected behavior and under what conditions, if any.

The more promising thing is that you're able to publish now.

**Comment by anishprasad01** [comment] 2021-11-30 19:02
@maydaystella,

I checked with the team, and they confirmed that having to sign-in again to publish is intended behavior due to the need to refresh access tokens. This being the case, there is no solution or workaround available. I am going to go ahead and close this issue, but should you have any new problem, please feel free to file a new issue.

**Closed by anishprasad01** 2021-11-30 19:02 UTC
Labels: Type: Bug, customer-reported, Bot Services, customer-replied-to
