### ISSUE TITLE
POST 500 directline.conversations.:conversationId.activities

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1965] opened 2020-02-06 19:07 UTC
## Describe the bug

Whenever I start a bot where LUIS is used (so not an echo bot) even if I don't change anything the emulator outputs **POST 500 directline.conversations.:conversationId.activities** as soon as I hit the endpoint in the emulator. Have tried several LUIS keys all with the same result. The LUIS apps get created correctly by Composer and the model is fine, but I cannot chat with the bot. If I remove the LUIS intent triggers from the bot in Composer, it works fine.

![image](https://user-images.githubusercontent.com/29750798/73969679-29f42700-491c-11ea-8a75-504c61804164.png)

## Version

test

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-02-24 14:15
I have the same issue

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-02-24 14:17
![image](https://user-images.githubusercontent.com/60220228/75159634-94350600-5729-11ea-99d6-16d31a78943a.png)

**Comment by boydc2014** [comment] 2020-03-17 00:51
Hi @stephanbisser  @SiarheiKuchukBelitsoft  we have some changes recently, can you try the latest master and make sure you create a new bot (otherwise you are still using the old runtime bits), see if it still an issue?

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-03-17 08:03
Hello

@boydc2014 . My issue has been resolved by adding postfix to bot URL in bot emulator /api/messages. I with I wouldn't do prefixes but I understand why it should be so.

**Comment by stephanbisser** [comment] 2020-03-18 16:11
@boydc2014 works now thanks!

**Closed** 2020-03-21 22:05 UTC
Labels: Needs investigation

**Comment by Vrushil12** [comment] 2020-03-25 18:11
Hey @SiarheiKuchukBelitsoft, Actually I am facing same issue. So can you help me with adding postfix to the bot URL in bot emulator /api/messages??
Thank you in advance!!

**Comment by SiarheiKuchukBelitsoft** [comment] 2020-03-26 06:45
@Vrushil12  
Upon connection Bot Emulator will ask for URL.
Specify http://127.0.0.1:3978/api/messages 
(localhost or http://127.0.0.1:3978 won't work)

**Comment by sposaro** [comment] 2020-03-30 18:34
I'm also hitting this issue in 4.1.8 framework + Luis (the 127.0.0.1 did not help).
It didn't seem to start happening until I added back in the ConverstationState to my bot.

**Comment by rehakara** [comment] 2020-04-02 14:16
Version 4.8.1 and I'm using ConversationState+UserState in my bot. Having the same 500 issue. Is there any update about this issue?

**Comment by cwhitten** [comment] 2020-04-02 15:34
hello @sposaro & @rehakara 

can your attach your bot assets assets, or a smallest representation that reproduces the issue? I'm unable to reproduce by using both user & conversation state in my bot.

**Comment by Arjun-Jakka-Sridhar** [comment] 2020-10-07 21:59
![image](https://user-images.githubusercontent.com/72132528/95392387-4666ba00-0916-11eb-844d-576bd7057b5c.png)



Can somebody please tell me why I am getting POST 500 and how to resolve it?

Thank You

**Comment by divyesh-inferenz-ai** [comment] 2021-01-21 10:41
@SiarheiKuchukBelitsoft your solution does not resolve this issue.

@Arjun-Jakka-Sridhar I am facing the same issues
can anyone have any solution regarding this issue? please help.

Thank you in advance.

**Comment by rvinothrajendran** [comment] 2021-01-22 07:51
@divyesh-inferenz-ai  ref here : https://github.com/Microsoft/botframework-sdk/issues/4184
maybe it will help

**Comment by divyesh-inferenz-ai** [comment] 2021-01-25 07:57
Can you suggest how to integrate any bot framwork chatbot with existing
android application?

Thanks & Regards,
Divyesh.

**Comment by parsalotfy** [comment] 2021-05-10 13:34
same issue [here](https://github.com/microsoft/botframework-sdk/issues/6285)

**Comment by anjaligarg29** [comment] 2023-09-07 11:14
[16:38:50]POST500directline/conversations/<conversationId>/activities getting same error what should i do
