### ISSUE TITLE
Sharing LUIS resource

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/BotFramework-Composer#6312] opened 2021-03-08 15:27 UTC
Hi,

We are developing a bot with multiple skills, we are close to reaching the limit of 10 LUIS resources per subscription per region, since we don't have a lot of LUIS conversation apps in total it would be great if we can have all of them in a single LUIS resource, is that possible? I tried to host all of them together by replacing the LUIS section in the publish profile of the skills with the one from the main bot, the publish works fine, and in the LUIS portal I can see all the LUIS apps but on the webchat the bot many times shows a 403 error. What is odd is that sometimes the 403 error is thrown by a different skill when I publish something new but most of the times it's the same skill. 
My  question is if it's possible to share a LUIS resource with multiple bots/skills from the same subscription and how?

Thanks.

**Comment by anusharavindrar** [comment] 2021-03-10 23:35
@pedro-ramirez-suarez, can you attach a screenshot of the 403 error you are getting on webchat? Also, have you tried testing on any other channel to see if you get a 403 there as well?

**Comment by pedro-ramirez-suarez** [comment] 2021-03-16 00:51
I apologize for the late response, I needed to revert my changes to share the LUIS resource for deployment and then put the changes back, here is a screenshot. I use direct line as well, we use that to interact with a custom Twilio function and we get the same 403 error. As I said, everything works if the each one of the skills use a separated LUIS resource, is just when I try to reuse it.

![image](https://user-images.githubusercontent.com/1943439/111239500-8a8d7300-85b6-11eb-88d4-e766636df6c7.png)

**Comment by feich-ms** [comment] 2021-03-19 01:59
Hi @luhan2017 do you have any insights about this issue? A luis resource can definitely host multiple applications, so I think the problem may locate in luis configurations or runtime?

**Comment by luhan2017** [comment] 2021-03-30 01:24
@pedro-ramirez-suarez Sorry that I am not quite understand the issue, there is limit on luis resource count per region per subscription. But within one bot, we only use one resource, under this resource, we created several applications, do you mean, you also have the application number limitation in your subscription?

**Comment by pedro-ramirez-suarez** [comment] 2021-03-31 15:45
Hi @luhan2017 ,

I don't have any limitation in terms of number of applications. The problem that I have is that at runtime, the skills throw a 403 error when trying to access a shared LUIS resource.
Now, how did I created and configured that shared LUIS resource? We have a main bot and multiple skills, we used composer to create the resources needed for each one of them, since we are already reaching the limit of 10 authoring resources per region per subscription and also since we want to reduce costs we were thinking on using a single LUIS resource for the main bot and the skills (since we don't have a lot of LUIS apps in total). I replaced the LUIS section in the publish profile of each one of the skills, when I publish the bot (from composer) I get no errors and in the LUIS portal I can see the applications from all the skills and the main bot in the same authoring resource, but when the bot is executed I get the 403 error in the skills but not in the mainbot. 
Hope that this clarifies a little bit the issue that I am having.

**Comment by lauren-mills** [comment] 2021-04-12 16:46
Hi @pedro-ramirez-suarez, yes this is possible. What you are likely running into is that when you change the LUIS endpoint key to be a different prediction resource, right now there is a bug in composer where it does not do the prediction resource assignment automatically when it publishes. So, when you hit the 403, the problem is that you are using an endpoint key that has not been assigned to the model.

You can test if this is the issue but opening the model that throws the 403 in the luis.ai portal, and going to the Manage > Azure resources view and checking if the right prediction resource is assigned there. 

I believe this issue is being looked at for either this or the upcoming release. @Dewain27 can you please confirm?

**Comment by pedro-ramirez-suarez** [comment] 2021-04-12 20:09
Hello @lauren-mills ,

Yeah!, that's the problem, no prediction resource is assigned to the LUIS apps that are not working:

![image](https://user-images.githubusercontent.com/1943439/114455111-36af8300-9b90-11eb-8d92-bd7f0ddf7214.png)

**Comment by lauren-mills** [comment] 2021-04-12 20:40
Great to know that was the issue! To fix for now, you will need to assign the prediction resource for your models either in the LUIS portal here or via the Az CLI if you have a lot of models to update. Here's the command if you chose the latter option:

```
az account get-access-token --output json

bf luis:application:assignazureaccount `
    --accountName <luisAccountName> `
    --resourceGroup <resourceGroup> `
    --armToken <az access token> `
    --azureSubscriptionId <az account id> `
    --appId <luis app id>`
    --endpoint <luis endpoint> `
    --subscriptionKey <luis authoring key>
```

**Comment by pedro-ramirez-suarez** [comment] 2021-04-12 20:48
Thanks a lot @lauren-mills.

**Closed** 2021-04-19 16:39 UTC
Labels: Bot Services, customer-replied-to, customer-reported
