### ISSUE TITLE
"" is not a valid LUIS app id after updating to V1.3.0

### ISSUE THREAD

**Issue by ysnoek2** [microsoft/BotFramework-Composer#5448] opened 2021-01-05 15:02 UTC
## Describe the bug

After updating to version 1.3.0 i'm getting te error "" is not a valid LUIS app id in the emulator.

![image](https://user-images.githubusercontent.com/76207835/103661581-2bd0cb00-4f6f-11eb-83c5-72d9fe8b2bfe.png)

I can still publish to azure with no problems.

## Version

V1.3.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on start bot
2. Enter any utterance into the emulator

## Expected behavior

Start dialog connected to the LUIS utterance

**Comment by gabog** [comment] 2021-01-06 19:18
@dmvtech, can you also consider #5451 when looking at this one?

Thanks

**Comment by dmvtech** [comment] 2021-01-07 00:23
Yes @gabog Currently investigating. Also #5008

**Comment by dmvtech** [comment] 2021-01-20 01:06
Hi @ysnoek2 Is your bot only running locally in Composer or published to Azure? Are there any similarities to your setup and what is described in #5451

**Comment by ysnoek2** [comment] 2021-01-20 09:47
Hi @dmvtech, my bot is also published to Azure and working perfectly in Teams. I checked #5451 and the emulator version is the same (4.11.0), i do not use qnamaker but i use Luis. The luis settings in the generated folder are correct and so are the one in recognizer

**Comment by dmvtech** [comment] 2021-01-21 18:47
Hi @ysnoek2 Are you able to share your bot (perhaps in a repository of your own. with personal/sensitive info removed)?

**Comment by dmvtech** [comment] 2021-01-29 17:37
Hi @ysnoek2 I'm not able to reproduce this issue, are you able to share a bot that reproduces the issue so I can test?

**Comment by dmvtech** [comment] 2021-02-01 22:24
Closing due to inactivity. If you are still having this issue, please comment and I will reopen.

**Comment by ysnoek2** [comment] 2021-02-02 10:46
Hi @dmvtech, excuse the late reply. I have put the bot in a repository and invited you to see it

**Comment by dmvtech** [comment] 2021-02-10 01:30
Thank you. I'm not able to reproduce this with your bot.

![image](https://user-images.githubusercontent.com/43397658/107450950-254beb00-6afb-11eb-9721-b7b174cdeb5a.png)

@ysnoek2 Assuming everything is still in development and no other changes made to the model; if you remove applications (any named `IsaBot-master(composer)-__________`) from LUIS :
![image](https://user-images.githubusercontent.com/43397658/107451509-48c36580-6afc-11eb-973e-66b895c0d635.png)

 and then re-run the bot, does it work then?

@luhan2017 Any other ideas?

**Comment by ysnoek2** [comment] 2021-02-10 08:15
@dmvtech what message do you get when sending "hi" to the bot? Or when clicking on the "help" button?

**Comment by ysnoek2** [comment] 2021-02-10 08:46
@dmvtech I checked and I don't have any with "master" 
![image](https://user-images.githubusercontent.com/76207835/107485957-c2069b00-6b84-11eb-8438-37c85613a4d8.png)

**Comment by dmvtech** [comment] 2021-02-11 16:33
Sorry, ignore the master part. I think that is because of how i got the repo and opened it.

I am getting the following:
![image](https://user-images.githubusercontent.com/43397658/107666222-225c1200-6c43-11eb-89fd-30d12559a2c5.png)

Are you running Emulator against the locally running bot or against the one deployed in Azure? If the former; in Composer, if you have the LUIS Authoring key and LUIS region set, but leave the endpoint key blank, does it work?

**Comment by ysnoek2** [comment] 2021-02-15 08:14
@dmvtech I tried it with leaving the endpoint key blank and it is still giving me "" is not a valid LUIS application id

**Comment by dmvtech** [comment] 2021-02-18 17:20
@ysnoek2 Can you confirm both the region and environment values are correct? It _**seems**_ as though this is a configuration only issue, we just have to try and narrow down where exactly that issue is.

**Comment by ysnoek2** [comment] 2021-02-22 08:44
@dmvtech I tried turning the custom runtime off and got this error, maybe this gives more information? Btw all configuration values are correct (the same as my publish file)

Start bot failed

Unhandled exception. System.ArgumentException: skill.allowedCallers has to be defined, e.g. ['*'] or ['callerAppId'] 
at Microsoft.BotFramework.Composer.WebAppTemplates.Authorization.AllowedCallersClaimsValidator..ctor(BotSkillConfiguration settings) 
in C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Authorization\AllowedCallersClaimsValidator.cs:line 30 
at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.<>c__DisplayClass13_0.<ConfigureServices>b__1(IServiceProvider sp) in 
C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Startup.cs:line 134 at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, 
ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) 
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) at 
Microsoft.BotFramework.Composer.WebAppTemplates.Startup.GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s, 
TelemetryInitializerMiddleware telemetryInitializerMiddleware) in C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Startup.cs:line 96 at 
Microsoft.BotFramework.Composer.WebAppTemplates.Startup.<>c__DisplayClass13_0.<ConfigureServices>b__4(IServiceProvider s) in 
C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Startup.cs:line 189 at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) at 
Microsoft.Bot.Builder.Integration.AspNet.Core.ApplicationBuilderExtensions.UseNamedPipes(IApplicationBuilder applicationBuilder, String pipeName, String audience) at 
Microsoft.BotFramework.Composer.WebAppTemplates.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in 
C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Startup.cs:line 211 at
 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at 
 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at
 Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder) at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder) at 
 Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app) at 
 Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app) at 
 Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder) at
 Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app) at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) at 
 Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token) at 
 Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token) at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host) at 
 Microsoft.BotFramework.Composer.WebAppTemplates.Program.Main(String[] args) in C:\Users\snoekya\AppData\Roaming\BotFrameworkComposer\hostedBots\13807.631303033973\runtime\azurewebapp\Program.cs:line 16

**Comment by luhan2017** [comment] 2021-02-23 03:34
@ysnoek2 it seems that your are using the latest version runtime with an old version of appsettings?  In the latest version we need the following configuration to run the bot. 
```
  "skillConfiguration": {
    "isSkill": true,
    "allowedCallers": []
  },
```

**Comment by ysnoek2** [comment] 2021-02-25 08:18
@luhan2017 I do have this setting already set:
![image](https://user-images.githubusercontent.com/76207835/109123626-5a3a7d80-774a-11eb-95df-2d526c6d7e97.png)

**Comment by ysnoek2** [comment] 2021-02-25 10:02
@luhan2017  changing it to ["*"] removed the error but still: "" is not a valid LUIS application id

**Comment by luhan2017** [comment] 2021-03-01 04:23
I think that is because your runtime doesn't load the luis settings correctly, could you double check if you set your luis.environment in your appsettings?

**Comment by ysnoek2** [comment] 2021-03-01 07:58
@luhan2017 It is set in my appsettings
![image](https://user-images.githubusercontent.com/76207835/109467809-05f60d00-7a6c-11eb-966a-dce3c42f6380.png)

**Comment by luhan2017** [comment] 2021-03-01 09:48
@ysnoek2 you need to add "environment": "composer" under the luis settings. It is a default setting when you create a new bot in composer. If you don't have this settings, composer will not load your luis settings correctly.

**Comment by ysnoek2** [comment] 2021-03-01 11:05
@luhan2017 Looking at my appsettings file, it seems Luis (and other settings) are set multiple times. Is there an example file for these settings? I could only find one from last year.

**Comment by ysnoek2** [comment] 2021-03-01 12:50
@luhan2017 I created a new bot and copied those appsettings, changed the settings and that fixed the issue! (: 
I think with the new version it took the old settings plus the new ones and it created a bit of a mess but it is now working as it should! Thank you for the help!

**Comment by dmvtech** [comment] 2021-03-02 16:56
Closing as resolved. Thank you @ysnoek2 for the update.

**Closed by dmvtech** 2021-03-02 16:56 UTC
Labels: Bot Services, Type: Bug, customer-replied-to, customer-reported
