### ISSUE TITLE
Open a project via Power Virtual Agents doesn't use the right locale

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Composer#6036] opened 2021-02-28 21:02 UTC
## Describe the bug
Projects opened via Power Virtual Agents always use the `en-us` locale, where PVA supports more locales. Currently you have to add a new language, which is confusing for first time PVA/Composer users.

## Version
4.11.0 (nightly from a few days ago, build SHA not visible on about page)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Power Virtual Agents, create a new project with Dutch language.
2. Go to topics, open in Bot Framework (Preview)
3. Create a simple dialog
4. Publish project to Power Virtual Agents
5. See error

## Expected behavior

Since PVA only supports one language per project, I would expect PVA to handoff this locale to BF Composer when creating the project.

**Comment by iMicknl** [comment] 2021-03-01 09:37
As an addition, this also happens when you update / overwrite your local version. It will always fall back to en-us. This also means that you lose all your bot responses...

**Comment by cwhitten** [comment] 2021-03-01 18:59
Hi @iMicknl - this is a known issue and will be addressed soon. PVA is not sending the configured bot local to Composer, so Composer doesn't know which language to use. Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/5728

**Closed by cwhitten** 2021-03-01 18:59 UTC
Labels: Needs-triage, Type: Bug

**Comment by iMicknl** [comment] 2021-03-01 19:50
Thanks @cwhitten! I couldn’t find the other issue.
